### ISSUE TITLE
Parse error with shift operator in static field

### ISSUE THREAD

**Issue by doflah** [groovy/groovy-eclipse#1001]
```
class Abcde {
    public static double foo = 2 << 16 - 1
}
```

This code snippet results in the error "Shift distance must be an integral type but 15.0 (java.lang.double) was supplied. Removing the static modifier or putting parenthesis around the shift operation makes the error go away.

**Comment by eric-milles** [comment]
It looks like the operator precedence of `=` is 15, `<<` is 6 and `-` is 5.  http://docs.groovy-lang.org/latest/html/documentation/#_operator_precedence

So this should be parsed and evaluated as `foo = (2 << (16 - 1))`.

Looks like the AST for this is:
```
FieldNode(name: "foo", initialValue: BinaryExpression(
  operator: "<<" ,
  lhs: ConstantExpression(2),
  rhs: BinaryExpression(
    operator: "-",
    lhs: ConstantExpression(16),
    rhs: ConstantExpression(1),
  )
))
```

Which matches expectations.

**Comment by eric-milles** [comment]
This is called on the initial value expression and the target type is double (the field type).  Under the covers, the right side of the leftShift (<<) is transformed to double when it is transformed.  The left side of the leftShift is not yet transformed.

`Expression transformed = ExpressionUtils.transformInlineConstants(initialValueExpression, fieldNode.getType());`

I suppose in this case, `ExpressionUtils` should not be changing the type on the right side of any shift operation.

**Comment by eric-milles** [comment]
https://issues.apache.org/jira/browse/GROOVY-9336

**Comment by doflah** [comment]
Ah, good point about the operators, I got my precedence backwards (inheriting someone else's code).  The bug still stands though, since it compiles in older versions of groovy.  Thanks for the quick response!
