### ISSUE TITLE
Can't install on 2019-09 R (4.13.0)

### ISSUE THREAD

**Issue by milindrao** [groovy/groovy-eclipse#1003]
I get an error 
"Installing Software has encountered a problem.  
An error occurred while collecting items to be installed."

No repository found containing: osgi.bundle,org.eclipse.jdt.groovy.core,3.6.0.v201912121707-e1909

Eclipse IDE for Enterprise Java Developers.
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 1.8.0_221

**Comment by eric-milles** [comment]
What update site url were you using?  I'm guessing you caught the update site during a deployment.
