### ISSUE TITLE
Maven compiler always compiles whole module

### ISSUE THREAD

**Issue by heikobornholdt** [groovy/groovy-eclipse#1005]
I have created a Maven module following the instructions on https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin.

I have noticed that every time I run `mvn compile`, the whole module is recompiled. No matter if the files have changed since the last run or not.

In order to reproduce the problem better, I created a minimal working example (https://github.com/heikobornholdt/groovy-eclipse-compiler-problem)

Every time you run `mvn compile` you will get the message:
```
[DEBUG] Stale source detected: /Users/heiko/groovy-eclipse-compiler-problem/src/main/java/Java.java
[INFO] Changes detected - recompiling the module!
```

**Comment by eric-milles** [comment]
I believe it has to do with the argument passed to the `StaleSourceScanner`:
```java
    private File[] recalculateStaleFiles(CompilerConfiguration config) throws CompilerException {
        ...
        long staleMillis = 0; // Can we do better than using 0?
        ...
        Set<File> staleSources = computeStaleSources(config, new StaleSourceScanner(staleMillis, includes, config.getExcludes()));
        config.setSourceFiles(staleSources);
        return staleSources.toArray(new File[staleSources.size()]);
    }
```

**Comment by eric-milles** [comment]
https://bintray.com/groovy/maven/groovy-eclipse-compiler/3.6.0-03
