### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by wangliang1983** [groovy/groovy-eclipse#1006]
error message is：
No repository found at https://dist.springsource.org/snapshot/GRECLIPSE/e4.13.

how can i do to fix it????thx

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/71183352-7638ba00-223d-11ea-94bf-639168d209c9.png)

Looks fine to me.  You may have caught it during a deployment.  Try restarting your eclipse and check again.

**Comment by cosmotron** [comment]
I just tried to install Groovy via the Marketplace on Eclipse 2019.09 and am hitting a similar issue. 

It detects the list of packages fine, but when you try to proceed to actually installing them, you get this error:
<img width="447" alt="Screen Shot 2019-12-19 at 5 38 50 PM" src="https://user-images.githubusercontent.com/146394/71215687-74471900-2286-11ea-9a0e-97090c72ed48.png">

**Comment by eric-milles** [comment]
See also #119 and #821 

dist.springsource.org is mapped to an Amazon S3 (storage) domain.  There is something in the certificate(s) that causes troubles for some.  Pivotal has looked at the before and I'm not sure where it sits.
