### ISSUE TITLE
Can't compile Java 13 and Groovy 2.5.8

### ISSUE THREAD

**Issue by MilleR98** [groovy/groovy-eclipse#1021]
Java 12 works fine, but when switching to 13 version it shows me next errors

![image](https://user-images.githubusercontent.com/20678586/72519469-13e4d080-3860-11ea-83a0-bdb90eb54335.png)

**POM.xml:**

> <properties>
    <java.version>13</java.version>

    <maven.compiler.source>${java.version}</maven.compiler.source>

    <maven.compiler.target>${java.version}</maven.compiler.target>

    <javax.version>1.5.4</javax.version>

    <groovy.version>2.5.8</groovy.version>

    <lombok.version>1.18.10</lombok.version>

....

> <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
          <source>{java.version}</source>
          <target>{java.version}</target>
          <verbose>true</verbose>
          <fork>true</fork>
          <compilerArguments>
            <javaAgentClass>lombok.launch.Agent</javaAgentClass>
          </compilerArguments>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>3.6.0-03</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>${groovy.version}-01</version>
          </dependency>
          <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.10</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

**Comment by timyates** [comment]
https://github.com/groovy/groovy-eclipse/issues/963

**Comment by MilleR98** [comment]
> #963

**Comment by eric-milles** [comment]
For Java 13 support, the minimum groovy-eclipse-batch version is 2.5.8-03.
