### ISSUE TITLE
Release URLs invalid

### ISSUE THREAD

**Issue by Exupery** [groovy/groovy-eclipse#1023]
The update site links listed on [Releases](https://github.com/groovy/groovy-eclipse/wiki#releases) don't appear valid. e.g. https://dist.springsource.org/release/GRECLIPSE/e4.14 returns a 404 with a "The specified key does not exist" error message (same behavior when requesting via http instead of https as linked, mildly related: the cert doesn't appear valid).

**Comment by eric-milles** [comment]
The URL refers to an eclipse update site.  Eclipse knows what to do with it.  If you want to manually verify, you can fetch this https://dist.springsource.org/release/GRECLIPSE/e4.14/compositeContent.xml

**Comment by Exupery** [comment]
Apologies my original comment wasn't clearer. The URLs listed do not work from Eclipse (attempting to use one there was how/where I encountered a problem, I only used curl on the URL after to get the response code as I thought it would be helpful when reporting the issue).

Using the URLs as-is (i.e. https) results in a cert error:
```
Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/e4.14/content.xml.
Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/e4.14/content.xml.
Certificate for <dist.springsource.org> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]
```

Attempting to workaround this by using http results in no error but then it shows no available software (i.e. simply displays "There are no categorized items"). Hide items already installed is **not** checked (shouldn't matter since this isn't installed yet anyway) - toggling any of the available checkboxes do not result in any available software. This was tested on two different machines using two different versions of Eclipse (2019-03 and 2019-12) and multiple update site URLs each.

**Comment by eric-milles** [comment]
Duplicate of #119, #821 and #1006 (for reference).  Sorry for the trouble; this is out of my control.  You must get Pivotal to make some changes to their Amazon S3 services.

You can use the direct update site link (no redirect involved) and it should work properly.  https://dist.springsource.org/release/GRECLIPSE/3.6.0/e4.14

**Comment by Exupery** [comment]
> You can use the direct update site link (no redirect involved) and it should work properly. https://dist.springsource.org/release/GRECLIPSE/3.6.0/e4.14

Thanks, using that (or, more accurately, that but with http instead of https) worked.

Though seems the releases page should be updated to provide links that work (if the underlying problem is a redirect that's outside of your control).

**Comment by eric-milles** [comment]
Release notes has these site URLs as well as site archives for download.  The main page has the redirect URLs so they don't need to change with every release.  The redirect URLs do work under most circumstances.
