### ISSUE TITLE
Type annotation on a method return type considered a method annotation

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1038]
Consider this:

```groovy
import org.eclipse.jdt.annotation.NonNull
class Foo {
  @NonNull String foo() { 'foo' } 
}
```

where `NonNull` has `@Target({ TYPE_USE })`.
Greclipse shows the following error:

    Annotation @org.eclipse.jdt.annotation.NonNull is not allowed on element METHOD

I don't know if it's a Greclipse bug or rather a Groovy compiler bug...
I'm using Groovy 2.5 compiler.

**Comment by eric-milles** [comment]
I think this is the [JSR 308](https://jcp.org/en/jsr/detail?id=308) stuff which was added in Groovy 3.

![image](https://user-images.githubusercontent.com/18193802/74958089-10e47f00-53ce-11ea-972f-af7db1aa6475.png)

**Comment by mauromol** [comment]
Perhaps Groovy 3 does not have this problem (I've not tested), but I'm not sure my use case is related to JSR-308, which AFAIK is about annotations on generic type arguments.

**Comment by eric-milles** [comment]
It sounds like you are asking about the support for `java.lang.annotation.ElementType.TYPE_USE` specifically.  I have working examples of `@NonNull` (org.eclipse.jdt.annotation:1.1.x) where the target is `{ FIELD, METHOD, PARAMETER, LOCAL_VARIABLE }`.  `TYPE_USE` and `TYPE_PARAMETER` were added in Java 8.

Here is an excerpt from the Javadoc (just for reference):
```
 * <p>The constant {@link #TYPE_USE} corresponds to the 15 type contexts in JLS
 * 4.11, as well as to two declaration contexts: type declarations (including
 * annotation type declarations) and type parameter declarations.
 *
 * <p>For example, an annotation whose type is meta-annotated with
 * {@code @Target(ElementType.TYPE_USE)} may be written on the type of a field
 * (or within the type of the field, if it is a nested, parameterized, or array
 * type), and may also appear as a modifier for, say, a class declaration.
 *
 * <p>The {@code TYPE_USE} constant includes type declarations and type
 * parameter declarations as a convenience for designers of type checkers which
 * give semantics to annotation types. For example, if the annotation type
 * {@code NonNull} is meta-annotated with
 * {@code @Target(ElementType.TYPE_USE)}, then {@code @NonNull}
 * {@code class C {...}} could be treated by a type checker as indicating that
 * all variables of class {@code C} are non-null, while still allowing
 * variables of other classes to be non-null or not non-null based on whether
 * {@code @NonNull} appears at the variable's declaration.
```

https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.11

**Comment by eric-milles** [comment]
Groovy 2.5 did add some support for the two new targets.  org.codehaus.groovy.vmplugin.v8.Java8:
```java
    @Override @SuppressWarnings("incomplete-switch")
    protected int getElementCode(ElementType value) {
        switch (value) {
            case TYPE_PARAMETER:
                return AnnotationNode.TYPE_PARAMETER_TARGET;
            case TYPE_USE:
                return AnnotationNode.TYPE_USE_TARGET;
        }
        return super.getElementCode(value);
    }
```

**Comment by eric-milles** [comment]
org.codehaus.groovy.classgen.ExtendedVerifier is where annotation targets are checked.  I do not see any type use or type parameter checks in Groovy 2.5.  I'm betting there were parser changes required to support the new annotation targets and Groovy 2.5 just has the minimum support to allow loading of classes that use the new target values.
