### ISSUE TITLE
Enabling annotation based null analysis on the project brings a wrong compiler error in editor for a Java class

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1039]
It's hard to summarize the problem in a title, but I was able to extract a reproducible test case.
Consider the attached project (create a new workspace, "Import Existing Project Into Workspace", from the attached archive).
[TestGroovyNull.zip](https://github.com/groovy/groovy-eclipse/files/4235040/TestGroovyNull.zip)

Look at the Java class named `JavaExt1`.
In the Project Explorer all classes seem to compile fine. But if you open the editor on `JavaExt1` you'll see this error on line 10:

    The method getFoo() is undefined for the type GroovyExt2

If you then go to `TestGroovyNull` project settings and uncheck Java Compiler | Errors/Warnings | Enable annotation-based null analysis, the above error goes away.
It's not clear to me whether the code is actually compiled or not, and hence it could be run.

Please note that the error also goes away if you keep annotation-based null analysis enabled but remove method `test.GroovyExt2.foobar()`... really obscure to me why.

This is a bit annoying because it's forcing me to disable annotation-based null analysis on a real project for now.

**Comment by eric-milles** [comment]
Okay, here's the lowdown.  The null analysis triggers some extra processing on your `foobar()` method.  And this causes the usual flow of initializing fields and then methods to be bypassed.  With only methods initialized, the `LazilyResolvedMethodBinding` for `getFoo()` fails to find the field needed to determine its return type, so it is marked as failed and removed from the type binding's methods array.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric,
I find the latest build available in the snapshot repository to be 3.7.0.v2020022123:45-e1912, which I think doesn't contain this fix.

**Comment by eric-milles** [comment]
Yes, this is the latest snapshot.  The changes to SourceTypeBinding shold be in there.

**Comment by mauromol** [comment]
Ok, I'll test that version, I thought the build date (2020-02-21) indicated that the artifact was made before your above commit (which was on 2020-02-22), but perhaps it's just a time zone offset issue.

**Comment by mauromol** [comment]
Tested with 3.7.0.v202002212345-e1912, it works both on this use case and on the project where I found it, thanks Eric! 👍
