### ISSUE TITLE
Groovy JDK classes  not supported by default

### ISSUE THREAD

**Issue by joergEisen** [groovy/groovy-eclipse#1046]
I use the configuration:
- Windows 10
- a fresh installed Eclipse Version: 2019-12 (4.14.0) running on Java 12 JDK
- Groovy Development Tools 3.7.0.SNAPSHOT
- Groovy Compiler Version 3.0.1

A simple Groovy script, created in a new Groovy Project:
```
def d = new Date();
println d + 1
```
results in:
`caught: groovy.lang.MissingMethodException: No signature of method: java.util.Date.plus() is applicable for argument types: (Integer) values: [1]
Possible solutions: parse(java.lang.String), is(java.lang.Object), split(groovy.lang.Closure), use([Ljava.lang.Object;), wait(), clone()`

When I switch to Groovy **Compiler Version 2.4.1.8,** the Groovy script is running **correctly** and shows the expected result! 

After the compiler switch, the Eclipse windows are destroyed  (errors like "Failed to create the parts controls", "Invalid registry object", read crosses) but I can reopen them.

The same problem happens for Java8 or Eclipse 4.8.0 or Compiler Level 2.5.9.

I guess this as a bug. I would expect that the plugin supports the Groovy JDK classes by default. 

Thank You!

**Comment by eric-milles** [comment]
This is because Groovy 2.5 broke up the groovy-all jar into multiple jars.  If you want to use the DGM "plus(Date, int)", you need to add groovy-dateutil library to your project or to your `~/.groovy/lib/` directory.

**Comment by eric-milles** [comment]
The "Invalid Registry Object" is a known issue.  I have a workaround: https://github.com/groovy/groovy-eclipse/issues/981#issuecomment-572131744 and I have a fix that is yet to be merged: https://git.eclipse.org/r/#/c/155098/

**Comment by joergEisen** [comment]
Thanks for the fast answer :-)
For me it was quite frustrating that I was not able to simply run such an easy Groovy snipplet. It would be nice if there would be the same default-support for the Groovy libraries as in the GroovyConsole application.

**Comment by eric-milles** [comment]
I think the maintainers of Groovy are trying to push a switch to DateTime from Date.  The extension methods for DateTime are present out of the box.
