### ISSUE TITLE
Groovy launches do not include libraries from classpath containers

### ISSUE THREAD

**Issue by Mrodent** [groovy/groovy-eclipse#1050]
Specs: Linux Mint 18.3, Java 11, Groovy 2.5.x, Eclipse 2019-12

The problem I've got is with a file like this in a Groovy Project, having installed the right Groovy-Eclipse snapshot build: 

```
package test

import java.sql.*
import groovy.sql.Sql

println  "hello world"
```

Regardless of whether I have a directory lib under ~/.groovy, this runs without complaints at the CLI.

Conversely, in Eclipse, even if I create that directory ~/.groovy/lib, and put  the right .jar there (groovy-sql-2.5.9.jar in this case), I always get the following error if I try to run the above as a Groovy script: 

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/media/chris/W10 D drive/My Documents/software projects/EclipseWorkspace_NEW/GroovyExp/src/test/test.groovy: 4: unable to resolve class groovy.sql.Sql
 @ line 4, column 1.
   import groovy.sql.Sql
   ^

1 error
```
I have in fact discovered the place to reconfigure/update the "Groovy library containers": under  Window --> Prefs --> Groovy --> Compiler --> Update all Groovy library containers.  Clicking on that, doing a rebuild, closing and re-opening Eclipse: at the moment it just doesn't want to know.

**Comment by eric-milles** [comment]
Can you expand your Groovy Libraries container in your project and take a screenshot?

**Comment by Mrodent** [comment]
Here it is:

![Eclise 2019-12 - Screenshot from 2020-03-02 18-46-09](https://user-images.githubusercontent.com/7956369/75707096-37e85e00-5cb6-11ea-9320-c1bd9554efcf.png)

groovy-sql-2.5.9.jar present but obviously not "seen" for some reason.

**Comment by eric-milles** [comment]
Can you delete the script launch configuration (`Run menu > Run Configurations... > Groovy Script > <your script>`) and try running again?  If it still fails, can you show the launch configuration command line arguments?

The first time you run a script, the launch options are saved.  Changing the project classpath will only affect future launches.

**Comment by Mrodent** [comment]
Thanks.  Yes, still fails.

Program arguments: --classpath "${workspace_loc:GroovyExp}/src:${workspace_loc:GroovyExp}/bin" --main groovy.ui.GroovyMain --encoding UTF-8 "${workspace_loc:GroovyExp/src/test/test.groovy}"

VM arguments: -Dgroovy.home="${groovy_home}" -Djava.system.class.loader=groovy.lang.GroovyClassLoader

**Comment by eric-milles** [comment]
So the groovy-sql jar is not added to the classpath argument.  You can add it manually while I look into a fix.

**Comment by Mrodent** [comment]
Thanks... confirm that works (manual editing of the program arguments)...

**Comment by Mrodent** [comment]
Since last night I have done quite a bit of experimenting with different versions of Eclipse.  I find that there is at least one problem with Eclipse from 2019-09 onwards: the first manifestation of this is that there is a "grey bar" which appears in most (all?) editors when I try typing: it completely obscures what I'm trying to type. I'm planning to see whether anyone else has experienced this, and raise an issue if necessary.

But, regarding Groovy-Eclipse, I also find that, using 2019-06 flavour "Java" for example (i.e. rather than flavour "EE") - which I've gone back to - , when I create a Groovy project, creating "module-info.java" is the default setting. If I uncheck this when creating the project I can run a Groovy file (even including `import groovy.sql.Sql`) without any difficulty whatsoever, and run the script.

However, if I fail to uncheck this box, then I have problems when trying to run such a script... and, EVEN IF I THEN DELETE module-info.java, these problems do not go away!  This "fatal" error is:

```
Error occurred during initialization of VM
java.lang.Error: groovy.lang.GroovyClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.5/ClassLoader.java:1989)
	at java.lang.System.initPhase3(java.base@11.0.5/System.java:2069)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyClassLoader
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.5/BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.5/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java.base@11.0.5/ClassLoader.java:521)
	at java.lang.Class.forName0(java.base@11.0.5/Native Method)
	at java.lang.Class.forName(java.base@11.0.5/Class.java:398)
	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.5/ClassLoader.java:1975)
	at java.lang.System.initPhase3(java.base@11.0.5/System.java:2069)
```

NB in BOTH cases (successful script run and unsuccessful script run) I get this error when I run (or try to run) the script: 

```
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "groovy.lang.GroovyClassLoader"). To use archived non-system classes, this property must be not be set
```

This appears NOT to be a fatal problem as such.  But it may be of interest to you...?

As for Eclipse versions later than 2019-06 (-09 and -12 currently), I don't know whether unchecking create module-info.java when creating a Groovy project solves the various problems I've been having.  You might want to investigate that: at the moment I've got investigation fatigue and won't be moving to Eclipse 2019-09 or -12 at least until I've found a solution to the "grey bar" thing.

Obviously I have no understanding whatsoever about why creating module-info.java has such a problematic effect.

**Comment by eric-milles** [comment]
When you add module-info.java to your project (manually or automatically), it converts the project to a "modular" project.  This has implications for classpath vs modulepath.  Groovy and Groovy-Eclipse have only basic support for the JPMS (module system) and the modulepath.

I am looking into better warnings and the possibility of quick fix proposals to help coerce the project to a better state for running groovy scripts.  Your feedback has been very helpful in exposing this usability concern.

Sorry for the numerous issues.  I spend all my development time in a Java 8 world and haven't had much time to try Java 9+ beyond the basics.

**Comment by eric-milles** [comment]
Script launch should include extra classpath entries now.  If there are other specific launch errors, please open a new issue.
