### ISSUE TITLE
Completely uninstall groovy-eclipse and all features to do fresh install?

### ISSUE THREAD

**Issue by Mrodent** [groovy/groovy-eclipse#1052]
Me again, sorry.

I'm having another problem with groovy-eclipse. I'm pretty sure this is nothing to do with the previous two issues I have raised in the past days.

I found that the groovy-eclipse module had just gone "weird" in Eclipse 2019-06 (i.e. the "real" Eclipse tool which I'm using): in the context menu for all the .groovy files in my Groovy Projects I no longer get a choice of "Groovy script or Groovy console", but instead "Run on server" or "PHPUnit test".  I also got a problem/error for the project saying "The project cannot be built until build path errors are resolved".

So I thought the simplest thing was simply to uninstall Groovy-Eclipse completely and reinstall.

After uninstalling the softwared, restarting Eclipse and checking that it was not in the list of installed software, I again chose the right snapshot link and tried to install.  
Unfortunately I got this: 
"our original request has been modified.
  "Groovy-Eclipse M2E integration" is already installed, so an update will be performed instead.
  "Groovy Compiler 2.5" is already installed, so an update will be performed instead.
  "Eclipse Groovy Development Tools" is already installed, so an update will be performed instead."
- after this attempt to reinstall the "weirdness" is the same: the right-click/context menu is still giving me options of "Run on server" or "PHPUnit test".
- just to check, however, I when the Run configuration: trying to run it I got

```
"OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "groovy.lang.GroovyClassLoader"). To use archived non-system classes, this property must be not be set
Error occurred during initialization of VM
java.lang.Error: groovy.lang.GroovyClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.5/ClassLoader.java:1989)
	at java.lang.System.initPhase3(java.base@11.0.5/System.java:2069)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyClassLoader
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.5/BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.5/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java.base@11.0.5/ClassLoader.java:521)
	at java.lang.Class.forName0(java.base@11.0.5/Native Method)
	at java.lang.Class.forName(java.base@11.0.5/Class.java:398)
	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.5/ClassLoader.java:1975)
	at java.lang.System.initPhase3(java.base@11.0.5/System.java:2069)"
```
And in fact this issue appears to have affected my Eclipse setup systemically: Project Explorer no longer displays properly.  

I need to expunge all trace of Groovy-Eclipse from my Eclipse setup... but I can't work out how to do that.

**Comment by Mrodent** [comment]
I've now decided to migrate everything to the new Eclipse 2019-12 installation. At least Groovy-Eclipse is working (with the caveats about module-info.java and manually configuring the classpath as discussed).  BUT...

Can you please explain, for future reference, how to completely remove all traces of the Groovy-Eclipse module from Eclipse. Obviously just removing the item from the "installed software" leaves things behind.

**Comment by eric-milles** [comment]
Your best bet is to go to Help > About Eclipse Platform > Installation Details > Installation History.  You should be able to select an entry from the Previous Configurations list and click Revert.  After restarting, you can go back and remove unused installation snapshots.  Groovy-Eclipse includes a patch bundle, so I'm not too sure how well eclipse handles going back to the unpatched bundle...

**Comment by Mrodent** [comment]
OK thanks
