### ISSUE TITLE
Build Path > Add Libraries... > Groovy Runtime Libraries fails with duplicate entry error

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#1064]
![image](https://user-images.githubusercontent.com/18193802/77251238-4a9de500-6c1b-11ea-800e-c7daeeb3c091.png)

![image](https://user-images.githubusercontent.com/18193802/77251244-4eca0280-6c1b-11ea-8ca6-4c55185cb620.png)

**Comment by Parmeshg1** [comment]
Hello Eric, I am getting the exact same error . Did you manage to resolve it ? . 
Thanks
Parmesh

**Comment by Parmeshg1** [comment]
Hi Eric
  I was using Eclipse Version: 2019-09 and had installed Groovy using the Help->Install new Software .  Once i created a Groovy project and then a Groovy Class i got the same error as you.  Just as option i downloaded Eclipse Oxygen.3a Release (4.7.3a), but this time i installed Groovy using the Help->Marketplace . I am now able to create a project and class without any issues . 
Parmesh

**Comment by eric-milles** [comment]
@Parmeshg1 Fix is testing right now.  Should be available before the end of the day.
