### ISSUE TITLE
Groovy Script option

### ISSUE THREAD

**Issue by mictadlo** [groovy/groovy-eclipse#1070]
Hi after,
I created a Groovy project and I would like to create a Groovy Script file. However the only choices are Groovy DSL Descriptor, Groovy Test and Groovy Type. Would it be possible to add a Groovy Script option?

Thank you in advance,

Michal

**Comment by eric-milles** [comment]
Groovy Type gives 6 options within: Class, Trait, Script, Interface, Annotation and Enumeration.

![image](https://user-images.githubusercontent.com/18193802/77831893-e3db6880-70ff-11ea-86d4-041b0b4315b7.png)
