### ISSUE TITLE
Importing Groovy project from github 

### ISSUE THREAD

**Issue by mictadlo** [groovy/groovy-eclipse#1071]
Hi all,
I used Eclipse's import option in order to clone this [this](https://github.com/GMOD/Apollo) project. However, after the below steps I got 3009  errors and 99 warnings.

**Step 1**
![step1](https://user-images.githubusercontent.com/588297/78016278-eeab2d00-738d-11ea-921e-895e050d8239.png)

**Step 2**
![step2](https://user-images.githubusercontent.com/588297/78016284-efdc5a00-738d-11ea-947b-e9122c96175a.png)

**Step 3**
![step3](https://user-images.githubusercontent.com/588297/78016286-f074f080-738d-11ea-953c-2441d5169562.png)

**Step 4**
![step4](https://user-images.githubusercontent.com/588297/78016288-f10d8700-738d-11ea-8c1b-f24cff07d8cf.png)

**Step 5**
![step5](https://user-images.githubusercontent.com/588297/78016290-f10d8700-738d-11ea-94d9-72bb5ad50509.png)

**Step 6**
![step6](https://user-images.githubusercontent.com/588297/78016292-f1a61d80-738d-11ea-91fb-34ee66336234.png)

**Step 7**
![step7](https://user-images.githubusercontent.com/588297/78016295-f23eb400-738d-11ea-8a40-ea4e1f9e17db.png)

What did I do wrong?

Thank you in advance,

Michal

**Comment by eric-milles** [comment]
Not sure.  Looks like it's a Gradle project.  Do you have Gradle tools installed?  Please follow up with that project with any issues importing into your workspace.

**Comment by mictadlo** [comment]
Hi @nathandunn ,
I tried to import Apollo into groovy-eclipse as describe in my previous post. However, I got 3009 errors and 99 warnings. I installed the Groovy/Java environment in the following way:

**OpenJDK**
```
> sudo add-apt-repository ppa:openjdk-r/ppa
> sudo apt update
> sudo apt install openjdk-13-jdk
```

**Node**
```
> nvm install --lts
Installing latest LTS version.
Downloading and installing node v12.16.1...
Downloading https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz...
> ln -s /home/ubuntu/.nvm/versions/node/v12.16.1/bin/node /home/ubuntu/.nvm/versions/node/v12.16.1/bin/node.js
```
**Apollo dependecies**
```
> sdk install grails 2.5.5
> sdk install gradle 2.11
> sdk install groovy
```

What did I miss?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
I would use (in order of preference):

- Intellij (ultimate if you can afford it, this is the only one I use)

- If you are using Eclipse, I would recommend the Groovy / Grails Tool Suite (https://marketplace.eclipse.org/content/groovygrails-tool-suite-ggts-eclipse <https://marketplace.eclipse.org/content/groovygrails-tool-suite-ggts-eclipse>) 

- Netbeans (I haven’t used it in awhile)


You may have to tell the project it is “grails”, though so it detects it correctly. 

Also, you’ll want openjdk-8.  Grails doesn’t care, but GWT (which at some point I will get rid of) does.    

If you run through all of this and still get errors, let me know (and share the errors). 

Nathan

**Comment by mictadlo** [comment]
Hi @nathandunn ,
Unfortunately,  Intellij ultimate is too expensive. However, I tried Netbeans but I ran into 2 problems. The first [problem](https://stackoverflow.com/a/60985576/977828) could have been solved by downgrading to OpenJDK8. However, the second problem according to the [Netbeans developer](https://issues.apache.org/jira/browse/NETBEANS-4113?focusedCommentId=17075014&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17075014) appears to be related to:

> ... that [Apollo] project has really poor Gradle support. Created 4 years ago. I think the author saw more in Docker than providing a good build file. If you check the build.grade you see that there is no plugin applied just a bunch of code.  That's why you can't actually do anything meaningful with the project in NetBeans.

Next, I will try Groovy / Grails Tool Suite but its development has stopped in 2012. Therefore, I still would prefer Netbeans. 

Do you think it would be possible to update your project to be able to import to Netbeans and helped other contributer to setup a free IDE.

Thank you in advance,

Michal
