### ISSUE TITLE
Extend type inferencing of dynamic field or property assigned in constructor or initialization method

### ISSUE THREAD

**Issue by monrealis** [groovy/groovy-eclipse#1080]
It seems that the correct type is inferred only in the simple way where assignment is made at the location of declaration. Maybe it can be improved?

![image](https://user-images.githubusercontent.com/2280367/79042127-c3320900-7bfd-11ea-9cd8-5ff5a9d1bd3b.png)

It does not work, for example, when `def` variable is assigned in Spock's `setup()`.

Related article from 2009: http://contraptionsforprogramming.blogspot.com/2009/11/how-type-inferencing-for-groovy-in.html

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/79143361-b8ed4780-7d82-11ea-9d94-ec787dabb7aa.png)

**Comment by eric-milles** [comment]
This is testable for assignment in constructor or initializer block.  If that looks good, an additional change will be made to support post-construct and other well-known initializer methods (like Spock's `setup`).

**Comment by monrealis** [comment]
Thanks. Since there is no 100% guarantee that the value will not be overwritten with the value of another type from anywhere, it would make sense to look for the assignment anywhere.

**Comment by eric-milles** [comment]
Did you have a chance to test what was implemented?  This is not one of those 100% enhancements.  Only common cases are going to be properly supported.  See also #1056 (odd switch case structures will not infer properly).

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/79591928-d67e2200-809e-11ea-8339-29eb94b30e03.png)
