### ISSUE TITLE
Groovy files throwing ClassNotFoundException

### ISSUE THREAD

**Issue by LogeshLohit** [groovy/groovy-eclipse#1081]
I have updated my STS to v4 few days ago,since then I unable to run my application which has groovy files.

I have installed Groovy Development plugin and tried to build the project using the maven command "clean install".

Maven build has been successfully executed, but when I started my project it throws that the Groovy class has not found exception.

I tried cleaning the project many times, but getting the same ClassNotFoundException for the Groovy classes.

My STS v4 installation details:

enter image description here

Java Build path details: enter image description here
![Installation details](https://user-images.githubusercontent.com/25660705/79040611-4310a100-7c07-11ea-8ce8-fd80733c3f3d.png)

Error Details, while I am running the project:

![Error details](https://user-images.githubusercontent.com/25660705/79040613-47d55500-7c07-11ea-80a5-b4b3ec3482df.png)

That parser class is the groovy class which throws ClassNotFoundException. Moreover, in the project explorer some strange icon is shown next to those kind of groovy files.
![File Icon](https://user-images.githubusercontent.com/25660705/79040624-5885cb00-7c07-11ea-8cad-29d2df2c2a54.png)

I am also attaching the maven build details, 
![Gmaven gen](https://user-images.githubusercontent.com/25660705/79040631-63406000-7c07-11ea-9954-465e576acb4c.png)
![Gmaven build](https://user-images.githubusercontent.com/25660705/79040633-676c7d80-7c07-11ea-998b-d35d59babda7.png)

these build information shows that those groovy files are compiled successfully, but still it throws ClassNotFoundException while starting the application.

NOTE: I gave clean - build, "clean compile" and updated maven project more than 15 times. Yet no luck.

**Comment by LogeshLohit** [comment]
Yes. The issue is with the compiler mismatch. My groovy jar has v2.4.9  and groovy compiler plugin has v2.4.19, when I updated the jar it worked fine.
Thank you!

**Comment by eric-milles** [comment]
One small follow-up: The reason your groovy source icons are showing the little circle-slash in the lower right is because they are not in a source folder or they match a script filter.  I can help resolve this if you were to give a little more detail on the structure of your project within eclipse.

**Comment by LogeshLohit** [comment]
Hi Eric, Sure. Those groovy files are placed at src/main/groovy. while java files are at src/main/java and the resource files are at src/main/resources.

Even after "clean compile" - that little circle slash - is still there!
Anyway the application  is running now without any problem. but I wish to know how to remove that circle next to the file.

**Comment by eric-milles** [comment]
Could you post a screenshot of your project with only root (project node) expanded in Package/Project Explorer?  That would help me see the defined source folders.  Also, can you check if Window > Preferences > Groovy > Compiler > Script Folders is showing any configured elements.  And the same for _Project_ > Properties > Groovy Compiler > Script Folders.
