### ISSUE TITLE
try-with-resources not recognized by groovy30 compiler

### ISSUE THREAD

**Issue by limpus2** [groovy/groovy-eclipse#1082]
The following snippet works perfectly in **groovyConsole 3.0.2**:
``` groovy
def inFile = new File('.bashrc')
// show WAIT_CURSOR
try (InputStream is = inFile.newInputStream()) {
    println is.text
} catch (Exception x) {
    return
} finally {
    // restore default cursor
}
```
but **org.codehaus.groovy30.feature 3.8.0.v202004111558-e2003** in **Eclipse 2020-03 (4.15.0)** says:
Description | Resource | Path | Location | Type
----------- | -------- | ---- | -------- | ----
Groovy:expecting '{', found '(' | Importer.groovy | /Importer/src/main/groovy/ | line 302 | Java Problem

**Comment by eric-milles** [comment]
> The new Parrot Parser is disabled by default in Groovy 3. To enable it, add `-Dgroovy.antlr4=true` to your eclipse.ini file after the -vmargs line or add a compiler config script to your project with `configuration.pluginFactory = ParserPluginFactory.antlr4()`. Please note that parser recovery is not implemented for the Parrot Parser, so your editing experience may be sub-par in this mode.

https://github.com/groovy/groovy-eclipse/wiki/3.7.0-Release-Notes#support-for-new-versions-of-groovy
