### ISSUE TITLE
Provide workaround for null annotation processing on return types (to avoid compiler errors)

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1085]
In #1038 we determined that annotation on return types is not supported by the Groovy parser for Groovy <3.0.
So, consider the attached project, which uses Groovy 2.5 compiler: 
[TestGroovyNull_2.zip](https://github.com/groovy/groovy-eclipse/files/4476501/TestGroovyNull_2.zip)

In this project, I enabled null annotation processing, set up a folder to contain external annotations and defined a `@NonNull` external annotation on `Object.toString()`.
When I try to override this method in my Groovy `Test61` class, I get a compiler error because when I override `toString()`, the return type should be marked as `@NonNull` as well: but I can't do it!
Compiling this code with and external compiler (and/or Gradle) works fine, indeed, but the Eclipse compiler complains, unless I disable null annotation analysis completely (for both Java and Groovy sources) or lower the error severity.

What is the expected behaviour?
Maybe a warning could be given (so saying something like "it should be `@NonNull` but you can't express it with this version of the Groovy compiler"). Otherwise, I would even prefer no error/warning at all, being conscious that null annotation analysis isn't available for Groovy sources. The code seems to run fine, even from within Eclipse, but having a constant red error mark in both the editor and the navigator views is an actual problem.

**Comment by eric-milles** [comment]
If you set this preference to enabled, the overriding method will inherit the annotation:
![image](https://user-images.githubusercontent.com/18193802/79289297-7b75e080-7e8e-11ea-8e9d-71cf3cb84c10.png)

    org.eclipse.jdt.core.compiler.annotation.inheritNullAnnotations=enabled

**Comment by mauromol** [comment]
Hi Eric,
this indeed is a possibility, I forgot about that option. When I set up null analysis on my projects, I documented myself a bit about that option and read some of the discussion around it. For reference:

https://wiki.eclipse.org/JDT_Core/Null_Analysis/Null_Contracts#Null_Contract_Inheritance

In short, that option is disabled by default because it's recommended to have annotations repeated on overriding classes for clarity, otherwise without an IDE it would be hard to determine which null constraint (if any) applies to a given overriding method return type or input parameter.

So, why I think this is an option to avoid the Groovy compiler error, I still think the Greclipse compiler should in some way deal with it being unchecked in some way, especially because annotation inheritance is disabled by default. Perhaps the Greclipse compiler may force the inheritance (i.e.: on Groovy sources, null annotations are implicitly inherited by default, even if that option is unchecked, at least when Groovy 2.5 compiler is in use). Otherwise, an even better solution IMHO would be this: the error you now get when the "inherit" option is unchecked is changed into a WARNING in Groovy <3.0 code; the warning message explains that the null annotation is lost with the current compiler settings because of a limitation of Groovy <3.0 parser/compiler, and suggests to either enable the null annotation inheritance option or to switch to Groovy compiler >=3.0...

I don't know about the feasibility of both solutions... What do you think?
