### ISSUE TITLE
Property reference in with { } closure not renamed

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1091]
Consider this:

```groovy
package test62

class GBean {
	String fooBar
	String bar
}
```

and this:

```groovy
package test62
class Test62 {
	void doSomething() {
		def g = new GBean()
		g.with { 
			fooBar = 'foo'
			bar = 'bar'
		}
	}
}
```

Now go to `GBean`, highlight `GBean.fooBar`, hit Alt+Shift+R and rename `fooBar` to `foo`: the reference in `Test62.doSomething()` is not renamed.
The strange thing is that if you do the opposite (source is `foo`, rename to `fooBar`), it works correctly.

Another strange behaviour (but I think it's for the same reason): if you issue Alt+Shift+R from `Test62` instead of `GBean` and you try to rename `fooBar` to `foo`, after the operation is finished the editor replaces `foo` with `fooBar`.

**Comment by eric-milles** [comment]
ready to test

You may need to rebuild the Java index before trying again.

**Comment by mauromol** [comment]
Tested with Greclipse 3.8.0.v202004230438-e1912: even if I rebuilt the index, it didn't work at first unless `Test62` applied `@CompileStatic`. After several attempts and a "Search for references", it seems now to work reliably, even if `Test62` does not apply `@CompileStatic`.
