### ISSUE TITLE
Cannot run program "java"

### ISSUE THREAD

**Issue by ouryperd** [groovy/groovy-eclipse#1094]
I am on 2.9.2, can't upgrade for work reasons. Using Groovy 2.4.13. Linux.

I have a simple script. On the line:

`println "java -version".execute().err.text`

I get:

`Caught: java.io.IOException: Cannot run program "java": error=2, No such file or directory`

The java SDK is (AdoptOpenJDK)(build 1.8.0_242-b08) installed with sdkman.

Are there any gonfigurations I must do ?

**Comment by eric-milles** [comment]
Availability of a process is up to the OS.  Usually this means setting PATH environment variable or providing absolute path to executable.

**Comment by ouryperd** [comment]
Doing it in the command-line works, it's definitely Eclipse related:

```
groovy:000> println "java -version".execute().err.text
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

===> null
groovy:000> 
```
Java home is set in the OS.

**Comment by eric-milles** [comment]
When you start the groovy shell, the environment is enhanced to make java available.  In your plain shell/terminal, can you just type "java -version"?  What is the output of "which java"?

**Comment by ouryperd** [comment]
user@tintin:~$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

user@tintin:~$ which java
/home/user/.sdkman/candidates/java/current/bin/java

user@tintin:~$ echo $JAVA_HOME
/home/user/.sdkman/candidates/java/current

user@tintin:~$ echo $GROOVY_HOME
/home/user/.sdkman/candidates/groovy/current
