### ISSUE TITLE
"Eclipse JDT Core patch for Groovy" shown twice when checking for updates

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1097]
Is there a particular reason for which recently the "Eclipse JDT Core patch for Groovy" bundle is shown twice when I do a "check for updates"?

Also, is it really wanted/necessary for this to show as a top level selectable element there? Couldn't it just become a transitive dependency transparently brought in by one of the other main bundles ("Eclipse Groovy Development Tools" and/or "Groovy Compiler")? After all, I don't think it's something the user would want "on its own" or rather something he/she could exclude if the main bundles are checked, right?

Screenshot of the first step, taken one Linux system:
![immagine](https://user-images.githubusercontent.com/1742494/80072879-25b4ce80-8547-11ea-87f0-39f52ef7113c.png)

Screenshot of the second step, taken on another Windows system:
![immagine](https://user-images.githubusercontent.com/1742494/80073174-9f4cbc80-8547-11ea-8fe6-dea7d8599c26.png)

Both systems use Eclipse 2019-12.

**Comment by eric-milles** [comment]
As seen in your last screenshot, Eclipse JDT Core patch for Groovy is a transitive dependency of Eclipse Groovy Development Tools.  The patch would show twice if you selected it as a top-level item at some point in time.  The update site offers only 4 features by default:
* Eclipse Groovy Development Tools
* Groovy-Eclipse M2E integration
* Groovy Compler 2.5
* Groovy Compiler 3.0

**Comment by mauromol** [comment]
Hmm... I'm still perplexed. The "showing twice" problem only started relatively recently, maybe with 2019-12... I always selected it as a top-level in the past, both on first install and on upgrade, but did not encounter this.
Also, I still believe it should not be shown at all, since it's somewhat a "service" package (an "implementation detail"), I don't know if it's possible or not.
I see now that the update site is not showing the patch bundle unless you uncheck the option to group items by category: this is good.
Anyway, I will see what happens when I will switch to an updated Eclipse version.
