### ISSUE TITLE
StackOverflowError when placing a "static" keyword

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1099]
Consider this class:

```groovy
package test64

import groovy.transform.CompileDynamic
import groovy.transform.CompileStatic

@CompileStatic
class Test64 {

	@CompileDynamic
	static enum ShippingAddressSynchType {
		ACCOUNTING {
			@Override
			void synch(Test64 customer) {
				truncate('foo', 2)
			}
		};

		void synch(Test64 customer) { }

		private String truncate(String input, int maxLength) {
			if(!input)
				return input
			if(input.length() > maxLength)
				input = input[0..maxLength - 1]
			return input
		}
	}
}
```

Now change the `truncate(...)` declaration by adding the `static` keyword and hit Ctrl+S: 

```groovy
private static String truncate(String input, int maxLength) {
```

BOOM!
You have to close the IDE, possibly kill it.

**Comment by mauromol** [comment]
See also what happens with Groovy without the `static` keyword:
https://issues.apache.org/jira/browse/GROOVY-9523
https://issues.apache.org/jira/browse/GROOVY-9524

Adding `static` seems to work fine with Groovy itself, but because of this Greclipse issue it crashes my IDE.

**Comment by eric-milles** [comment]
Quick observation, you can write `truncate` like this.  Not important, just a suggestion.

    private static String truncate(String input, int maxLength) {
      if (input && input.length() > maxLength)
        input = input[0..<maxLength]
      return input
    }

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Works with 3.8.0.v202004242058-e1912, thank you!
