### ISSUE TITLE
Unrecognized method call with @CompileDynamic

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1100]
Consider this Groovy class:

```groovy
package test65

import groovy.transform.CompileDynamic
import groovy.transform.CompileStatic

@CompileStatic
class Test65 {

	@CompileDynamic
	static enum ShippingAddressSynchType {
		ACCOUNTING {
			@Override
			void synch(Test65 customer) {
				foo('foo')
			}
			
			private foo(String foo) { }
		};

		void synch(Test65 customer) { }

		private String truncate(String input, int maxLength) {
			if(!input)
				return input
			if(input.length() > maxLength)
				input = input[0..maxLength - 1]
			return input
		}
	}
}
```

The call to `foo(String)` is underlined and navigation to it does not work. If you remove `@CompileDynamic` both syntax highlighting and navigation work fine.

**Comment by eric-milles** [comment]
ready to test

Do these enum constant inner classes support fields and types as well?  Only methods are visited for type info.

**Comment by mauromol** [comment]
Works with 3.8.0.v202004242058-e1912.

Yes, of course, just like any top-level enum, a nested enum may itself also contain fields and inner/nested classes. I use them regularly, although usually in Java code, as enums declared in Groovy have always been problematic...
