### ISSUE TITLE
Wrong navigation for constructor call

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1103]
Consider the project attached to #1090 and its `MyBean` class, but use this test class instead:

```groovy
package test61

import java.util.function.BiConsumer

import org.hibernate.Session
import org.hibernate.SessionFactory
import org.hibernate.criterion.DetachedCriteria
import org.hibernate.criterion.Order

class Test66 {

	SessionFactory shopSessionFactory
	
	void foo() {
		def b = new MyBean(shopSessionFactory, bar('a', 'b', 'c'), [Order.asc('foo'), Order.asc('bar')], ['a', 'b'], 
			{} as BiConsumer<Session, ? super List>)
	}

	DetachedCriteria bar(String a, String b, String d) {
		
	}
}
```

If you click on `MyBean` word inside the `foo()` method and hit F3, you're brought to `test61.MyBean.MyBean(SessionFactory, DetachedCriteria, Order...)` constructor, while you should be brought to `test61.MyBean.MyBean(SessionFactory, DetachedCriteria, List<Order>, Map<String, ? extends Iterable<String>>, BiConsumer<Session, ? super T>)`.

Call Hierarchy and Search for References for the latter constructor, though, are correct, so it seems to be just an issue with navigation.

**Comment by eric-milles** [comment]
`['a', 'b']` is not a Map literal.  This call is not an exact match for a declared constructor.

**Comment by mauromol** [comment]
Right, sorry, when I extracted the use case from the real case I wrote the constructor call wrong. You should change it like this:

```groovy
package test61

import java.util.function.BiConsumer

import org.hibernate.Session
import org.hibernate.SessionFactory
import org.hibernate.criterion.DetachedCriteria
import org.hibernate.criterion.Order

class Test66 {

	SessionFactory shopSessionFactory
	
	void foo() {
		def b = new MyBean(shopSessionFactory, bar('a', 'b', 'c'), [Order.asc('foo'), Order.asc('bar')], [a: ['a'], b: ['b']], {} as BiConsumer<Session, ? super List>)
	}

	DetachedCriteria bar(String a, String b, String d) {
		
	}
}
```

The same problem with navigation occurs.

**Comment by eric-milles** [comment]
Getting tripped up on `Map<String, ? extends Iterable<String>>`.  Testing fix now.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Sorry, I missed this. Works fine in 3.8.0.v202004282258-e1912.
