### ISSUE TITLE
Severe regression: wrong delegation in with { } and @CompileStatic

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1106]
Consider this:

```groovy
package test67;
class Bean2 {
  String foo
}
```

This:

```groovy
package test67;

import groovy.transform.CompileStatic

@CompileStatic
class Bean {
  String foo = 'bean'
  
  void doSomething(Bean2 b) {
    b.with {
      foo = 'bean2'
    }
  }
}
```

And this:

```
package test67;

public class Test67 {

	public static void main(String[] args) {
		Bean b = new Bean();
		Bean2 b2 = new Bean2();
		b.doSomething(b2);
		System.out.println(b.getFoo());
		System.out.println(b2.getFoo());
	}

}
```

Run `Test67` in Eclipse (Run As -> Java Application).
Expected output:

    bean
    bean2

Actual output:

    bean2
    null

This is certainly a regression because an application of mine started to fail today.
Running this same example with Gradle/Groovy 2.5.11 (no Greclipse involved) brings the correct result.

Removing `@CompileStatic` from `Bean` brings the correct result.

**Comment by eric-milles** [comment]
I am getting the expected result for this and some common variations like Groovy Script.  Did I miss a critical detail?

![image](https://user-images.githubusercontent.com/18193802/80603743-72d8ea80-89f6-11ea-87c5-dfdfb9ca3abf.png)

**Comment by mauromol** [comment]
So, does it print `outer / inner` to you? Are you running this script from within Eclipse (with Run As -> Java Application)?

What happens if put the cursor over `foo` in row "foo = 'inner'" and hit F3? 
In my case, I am brought to `One1106.foo`, while I should be brought to `Two1106.foo`. This is coherent with what I see at runtime, when running from the IDE. And it is wrong.

When I run this with Gradle, all works fine.

**Comment by eric-milles** [comment]
It prints "outer inner", not "inner null".  I am seeing this:
![image](https://user-images.githubusercontent.com/18193802/80608150-fd701880-89fb-11ea-962c-8a18c43b0101.png)

If your class is tagged with `@CompileStatic` the editor is using the compiler metadata that SC/STC populate.  So if your hover is linking to the outer class field, then at runtime you should get the same result.

One possible difference is that I use the "indy" versions of the core and test libraries.  What groovy library does your project include?

**Comment by mauromol** [comment]
Oh, well, I just found the root cause...
You may remember that I had to recreate my workspace from scratch because of the broken Call Hierarchy problem.
After I rebuilt the workspace, I didn't notice that the workspace Groovy compiler level was set to 2.4, while my project has 2.5.11 on its buildpath (even the test project). After switching the workspace compiler level to 2.5, the "Run As" behaviour and the navigation behaviour are correct again.

I'm just a bit perplexed on why this happens at runtime. I may understand some weird behaviour of the IDE when using a mismatching workspace compiler level, but at runtime the application classpath must contain the Groovy JARs I supply (indeed, I'm using Gradle/Buildship to supply all JARs, including Groovy, I'm not using Greclipse's own Groovy classpath container)... So, how could this faulty behaviour manifest at runtime? Probably because the mismatching compiler  produced the wrong bytecode at build time and then this wrong bytecode got executed?

I see that Greclipse is bundling Groovy 2.4.19 when using 2.4 compiler level. So I guess this severe bug is still present in that Groovy version...

**Comment by eric-milles** [comment]
When you compile in the IDE, it mainly uses the groovy jar that is embedded in the compiler plug-in.  Auto-detection of the invoke-dynamic is based on the library your project includes, which is why I asked about that.  When you compile through Gradle, it uses the groovy jar that is specified in your dependencies or that the groovy gradle plug-in links to (not sure which one).

You can set the option "groovy.compiler.level=25" in \<project\>/.settings/org.eclipse.jdt.groovy.core.prefs to generate a warning if workspace compiler does not match expected version.  This is set in the UI under _project properties > Groovy Compiler > Groovy compiler level for this project_.

**Comment by eric-milles** [comment]
I tested with Groovy 2.4 and it worked for me.  I did not try Groovy 2.4 compiler and Groovy 2.5 runtime.  Although when I build the tooling, I am always using Groovy 2.4 compiler and runtime is switched between 2.4, 2.5 and 3.0.  So it is possible to use this configuration, but it becomes harder to guarantee that issues such as this won't crop up.

Once the @CS has been compiled, the choices of method calls or field writes is frozen, except in some rare cases where dynamic property selection is compiled in.  So the choice of runtime library matters much less.

**Comment by mauromol** [comment]
Yes, the warning was present but I did not see it. Indeed, its a "red mark" in the Project Explorer, but it does not make the build fail. I think it should make the build fail, because some unexpected and subtle errors like this can occur. I would have noticed it immediately, if my build were failing.
