### ISSUE TITLE
Groovy 2.4 Maven support?

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#111]
I have Groovy 2.4 working happily in Eclipse, but the latest version of the `groovy-eclipse-batch` plugin available is 2.3.7, and the Spock compiler is extremely picky about the Groovy version (I can't use `1.0-groovy-2.3` with `groovy-all:2.4`). Is there a timeline for getting the Eclipse compiler artifact pushed out into batch? This is essentially a blocker for using 2.4 with CLI/CI builds.

**Comment by kdvolder** [comment]
I have just built and staged 

  - groovy-eclipse-compiler 2.9.2-01
  - groovy-eclipse-batch 2.4.3-01

These are available from codehaus staging repo:
https://nexus.codehaus.org/content/groups/staging/

I'll leave it there for a couple of days so if someone (chrylis?) could test them out a little before I press the button to promote them to maven central that would be great.

Thanks,

Kris

**Comment by chrylis** [comment]
What do you need, just running some builds and seeing that they work okay?

**Comment by chrylis** [comment]
Cautiously optimistic. Rolled over our main build, and Jenkins was able to build, deploy, and run Geb-Spock tests without any handholding.

**Comment by kdvolder** [comment]
> What do you need, just running some builds and seeing that they work okay?

Whatever you can do to give it smoke test. I run some very basic tests as part of the build but it contains only 'toy' program code. So anything using this to build something 'real' would be great.

**Comment by chrylis** [comment]
Okay, well, that was a headless build of an 11-module Maven project with mixed Java and Groovy, building into a Spring Boot packaged jar. Everything seems to be working fine.

**Comment by kdvolder** [comment]
Thanks for testing.

I've released the artefacts to maven central. They should show up there in a day or so.
