### ISSUE TITLE
Can't install Groovy on Eclipse 4.2 Juno

### ISSUE THREAD

**Issue by bressan3** [groovy/groovy-eclipse#1112]
I've been getting the following error message whenever trying to install Groovy through the Eclipse Marketplace:

![Screen Shot 2020-05-12 at 1 35 57 PM](https://user-images.githubusercontent.com/13811157/81721010-915acf00-9455-11ea-9577-083b064c6a73.png)

I also tried to install it using the update site provided in the wiki (https://dist.springsource.org/release/GRECLIPSE/e4.2) and have been getting the following error:

![Screen Shot 2020-05-12 at 1 37 50 PM](https://user-images.githubusercontent.com/13811157/81721138-c830e500-9455-11ea-8e5a-f6244f5453f3.png)

Seems to me that the update sites provided in the wiki are all down. I was able to install groovy yesterday on a different Eclipse version (neon) and had no issues whatsoever.

**Comment by eric-milles** [comment]
Can you try the "http" variant of the update site?  Older eclipse releases may not be able to handle TLS.  If this works, I can update the marketplace entry.

If this doesn't work, you can download the update site archive from: https://dist.springsource.org/release/GRECLIPSE/2.9.2/e4.2/org.codehaus.groovy-2.9.2.xx-201801081821-e42-RELEASE-updatesite.zip

(see https://github.com/groovy/groovy-eclipse/wiki/2.9.2-Release-Notes#update-sites for additional versions)

**Comment by bressan3** [comment]
Using the update site .zip archive instead of the update site itself did it. Thank you!
