### ISSUE TITLE
Groovy Geb Jars to Eclipse

### ISSUE THREAD

**Issue by ofeliiaB** [groovy/groovy-eclipse#1119]
Hi, 

I need to use groovy script to open a new browser tab and redirect to the link
```
import geb.Browser

def myBrowser = new Browser()
def targetUrl = "http://google.com/"
myBrowser.go(targetUrl)
```
the script will be something like this. I have imported geb jar files downloaded from this link https://jar-download.com/artifacts/org.gebish/geb-core/2.0/source-code . I added them via Add External Jars button.
The Compiler builds the project but the Run throws an exception unable to resolve class geb.Browser . I checked that the added libraries went to Referenced Libraries of the Project and the Classes in the jars say that "Source Not Found". 
What should I do to fix this? Or is there a way to write the same script without the Geb package? 

P.s. I am getting the same error for Groovy Json Parser jars

**Comment by eric-milles** [comment]
Can you include the small project that you are using to develop and run this script?  I need to see how you have linked in the external libraries to understand how the launch config is working.

Also, you can use `@Grab` to bring in dependencies for a Groocy script:
```groovy
@Grab('org.gebish:geb-core:2.0')
import geb.Browser

new Browser().go('http://google.com/')
```

This might be a simpler way to go if your intention is to run scripts.

**Comment by ofeliiaB** [comment]
Thanks for the response !

My actual goal is to use the script in a Flowable project (its a special workflow engine). But I cant get it running even in a simple Groovy project in Eclipse. This is the Groovy project [https://github.com/ofeliiaB/groovy_geb_browser_test.git](https://github.com/ofeliiaB/groovy_geb_browser_test.git) .

The error it throws is ` unable to resolve class geb.Browser`

The actual Flowable project is here [https://github.com/ofeliiaB/flowable_open_tab_groovy.git](https://github.com/ofeliiaB/flowable_open_tab_groovy.git) with the script in src/main/resources/diagrams/OpenTabWf.bpmn . But I am gonna deal with this later...

**Comment by eric-milles** [comment]
One problem straight away is that you have specified Groovy 3 as the target compiler but you are importing Groovy 3, Groovy 2.5 and Groovy 2.4 libraries.  If you use the Groovy Libraries container, you can save yourself some work.  It provides Groovy and Ivy jars plus anything you put into your _C:\Users\\\<username\>\\.groovy\lib_ directory.  You could add the Geb jars there and you wouldn't need to add them as external libraries through eclipse.

**Comment by eric-milles** [comment]
When I fix up the libs issues, the Run As > Groovy Script works fine -- it finds geb.Browser, but dos not fund the Selenium web driver.

![image](https://user-images.githubusercontent.com/18193802/83534059-fa15f400-a4b5-11ea-867a-698709689e49.png)

You may also want to change your script name from "main" to something else to avoid the comoiler warning "method has a constructor name".
