### ISSUE TITLE
Support asynchronous computation of content assist proposals

### ISSUE THREAD

**Issue by CrushaKRool** [groovy/groovy-eclipse#1123]
Eclipse introduced [a flag in 4.14](https://www.eclipse.org/eclipse/news/4.14/jdt.php#completion-ext-flag-uithread) that lets code completion providers indicate whether they require to run in the UI thread or can be computed in the background, to provide a more fluent user experience when hitting the content assist key.

However, it seems like the Groovy Eclipse proposals are currently preventing this feature from being used in the IDE.
![GroovyEclipseCodeCompletion](https://user-images.githubusercontent.com/7923164/83662123-6896a700-a5c7-11ea-8370-2bbe8493cfd3.png)

Perhaps it wouldn't take much to make the computation from this plugin async-compatible as well?

**Comment by eric-milles** [comment]
ready to test

**Comment by CrushaKRool** [comment]
Looks good to me. No longer prevents that option from being enabled in the settings and couldn't notice any obvious issues when opening Content Assist.
