### ISSUE TITLE
Link to install instructions is dead

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#113]

**Comment by kdvolder** [comment]
Which link? Please be precise. Where is the link?

**Comment by shafel** [comment]
I think this one http://groovy.codehaus.org/Eclipse+Plugin

**Comment by kdvolder** [comment]
Where did the link come from, the pages on codehaus are probably gone for good and are not coming back. All codehaus Groovy stuff is moving to apache. To fix the link it has to be fixed at its source. For groovy eclipse plugin it is best to point people to groovy-eclipse github project and/or its wiki on github.

**Comment by ttf** [comment]
The Link is mentioned in this projects [Readme.md](https://github.com/groovy/groovy-eclipse/blob/master/README.md) and on [the official ide support page](http://groovy-lang.org/ides.html)

**Comment by chrylis** [comment]
Sorry, should have been more specific. I meant the links from within this repository.

**Comment by kdvolder** [comment]
Thanks, indeed the readme probably needs a bit of work on broken links. Probably best to wait a little though and see what happens with Groovy moving to appache. When the dust settles on that we can pick good new places to point to.
