### ISSUE TITLE
e44: JDT watch won't apply when building a custom product

### ISSUE THREAD

**Issue by sterns** [groovy/groovy-eclipse#114]
We include groov-eclipse in our IDE for scripting and deploy our own product using PDE build. When adding Groovy to the target, the build won't deploy the product, as P2 is not able to serve groovy-eclipse dependencies on JDT. Eclipse 4.4 ships with JDT version 3.10.0 to 3.10.1, while groovy-eclipse JDT feature patch is specified for versino 2.9.2. 
JDT 2.9.2 was part of with Eclipse 4.3.

**Comment by kdvolder** [comment]
Are you using the right update site? At first sight the e44 version of greclipse is compatible eclipse 44 JDT. Try this update site:

http://dist.springsource.org/snapshot/GRECLIPSE/e4.4/

**Comment by sterns** [comment]
Yes, I mirrored the e4.4 update site, using repo2runnable, using it as target for the PDE. When I tried included Greclipse feature into the product and ran the PDE build, I got an error message telling that JDT version '3.9.2.v20140221-1700' was not available. 
I checked the version and found that Eclipse 4.4 comes with JDT 3.10.0 (4.4.0 and 4.4.1) / 3.10.1 (4.4.2). Looking for the dependency to the former minor release version of JDT, I found that the Groovy feature patch plugin specifies the 3.9.2 as target feature version for the patch feature.

**Comment by kdvolder** [comment]
Okay, I just pushed a fix for that. I found the stray version reference. It is odd this doesn't cause our e44 based builds to fail.

Now we have to wait for a successful snapshot build [*] and then hopefully you can try if it works.

[*]: https://build.spring.io/browse/GRECLIPSE-E44TP-241

**Comment by sterns** [comment]
Thanks for the quick response (both comment and code fix). Seems the build failed for some reason, which gives me some time to adapt our target from 4.4.1 to 4.4.2. ;) I'll keep an eye on the builds and take the next valid build result to give feedback.
Though I'm currently in doubt whether PDE build can handle feature patches in a target platform at all.
