### ISSUE TITLE
Unable to Install Snapshot Builds from Update Site

### ISSUE THREAD

**Issue by ssadedin** [groovy/groovy-eclipse#1150]
I'm finding I can't install snapshot builds from the update site.

Steps:

- uninstall all groovy-eclipse plugins and update sites
- add update site for snapshot build 4.16:

![image](https://user-images.githubusercontent.com/138868/89092329-1cfc5000-d3f4-11ea-9a6b-c23f03a0e947.png)

- select groovy-eclipse artifacts and install
- receive error:

![image](https://user-images.githubusercontent.com/138868/89092322-01914500-d3f4-11ea-9319-67545a5f9437.png)

This seems to happen for any version I try and regardless of whether I have previously installed groovy-eclipse or not.

I would love to be able to try out snapshot builds to help troubleshoot, test and bug-fix - happy to use a manual process or workaround, but would be ideal if this worked.

**Comment by eric-milles** [comment]
Could you restart and try again?  I think you caught the update site being updated by the latest snapshot build.

**Comment by ssadedin** [comment]
You are right!  sorry for the noise - it now updated fine.
