### ISSUE TITLE
General error during conversion -  Transform org.codehaus.groovy.macro.transform.MacroTransformation cannot be run

### ISSUE THREAD

**Issue by brian-vtti** [groovy/groovy-eclipse#1164]
I'm getting the following error in all my Groovy files - classes and scripts:
Groovy:General error during conversion: Transform org.codehaus.groovy.macro.transform.MacroTransformation cannot be 
 run

I have started with a clean install of Eclipse 2020-09:
Eclipse IDE for Enterprise Java Developers (includes Incubating components)
Version: 2020-09 (4.17.0)
Build id: 20200910-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 14.0.2

I have installed the following version of the Groovy-Eclipse plugin:

Eclipse JDT Core patch for Groovy 3.9.0.v202009212057-e2009 org.codehaus.groovy.jdt.patch.feature.group Pivotal Software, Inc.
Groovy Compiler 2.5 3.9.0.v202009212057-e2009 org.codehaus.groovy25.feature.feature.group Pivotal Software, Inc.
Groovy Compiler 3.0 3.9.0.v202009212057-e2009 org.codehaus.groovy30.feature.feature.group Pivotal Software, Inc.
Groovy-Eclipse M2E integration 3.9.0.v202009212057-e2009 org.codehaus.groovy.m2eclipse.feature.feature.group Pivotal Software, Inc.

I created a new Groovy project and a new Groovy script within that project.
I add the following line of code to the script:
println "Hello world from Groovy ${GroovySystem.version}"

I see an error indication on the line:
Multiple markers at this line
	- Groovy:General error during conversion: Transform org.codehaus.groovy.macro.transform.MacroTransformation 
	 cannot be run
	- Groovy:General error during conversion: Transform org.codehaus.groovy.macro.transform.MacroTransformation 
	 cannot be run
	- implements groovy.lang.Script.run

I see this error in every Groovy file I have opened.  The preceding simple script will actually run and produce the expected output but other Groovy code I have will not.  I get an error similar to the following in Groovy classes:

java.lang.Error: Unresolved compilation problem: 
	Groovy:General error during conversion: Transform org.codehaus.groovy.macro.transform.MacroTransformation cannot be run

	at edu.vt.vtti.ResourceTracker.ResourceTracker.<init>(ResourceTracker.groovy:16)
	at RT_test.run(RT test.groovy:4)

when I try to run a Groovy script that uses a Groovy class.

**Comment by brian-vtti** [comment]
I should have added that I am using the following version of the Groovy-Eclipse plugin:

  Eclipse JDT Core patch for Groovy	3.9.0.v202009212057-e2009	org.codehaus.groovy.jdt.patch.feature.group	Pivotal Software, Inc.
  Groovy Compiler 2.5	3.9.0.v202009212057-e2009	org.codehaus.groovy25.feature.feature.group	Pivotal Software, Inc.
  Groovy Compiler 3.0	3.9.0.v202009212057-e2009	org.codehaus.groovy30.feature.feature.group	Pivotal Software, Inc.
  Groovy-Eclipse M2E integration	3.9.0.v202009212057-e2009	org.codehaus.groovy.m2eclipse.feature.feature.group	Pivotal Software, Inc.

**Comment by eric-milles** [comment]
The macro transform is part of the groovy-macro library.  Does this library appear in your project's classpath?  If so, what version is it?  And which version of the groovy compiler is active in your workspace (you can check this at _Window > Preferences > Groovy > Compiler_).

**Comment by brian-vtti** [comment]
Hi Eric,
  According to Eclipse, the groovy-macro library is in my project's classpath - groovy-macro-3.0.3.jar.
It is in a .groovy folder in my Windows user home directory.  I haven't changed anything from the way Eclipse set up the Groovy project.
The active Groovy compiler version in Eclipse is 3.0.5.  Is that a mismatch between versions ( 3.0.3 vs 3.0.5)?
I checked and the latest version of Groovy available to download is 3.0.4 from http://groovy-lang.org/.

Thanks,
Brian

**Comment by eric-milles** [comment]
If you don't want to include the jars that are in your `~/.groovy/lib` directory, you can right-click on the Groovy Libraries container and choose Properties.  If you do want them included, it is probably best to add them one at a time.

**Comment by eric-milles** [comment]
You may also disable specific global AST transforms using a compiler config script:
```groovy
configuration.disabledGlobalASTTransformations = [
  'groovy.grape.GrabAnnotationTransformation',
  'org.codehaus.groovy.ast.builder.AstBuilderTransformation',
  'org.codehaus.groovy.macro.transform.MacroTransformation'
] as Set
```

**Comment by brian-vtti** [comment]
Thanks for your responses, Eric.  I unchecked the option to include all jar files from the ~/.groovy/lib folder and that cleared the error from my simple test project.  I opened another older, slightly more complicated project and still saw the error but was able to clear it by editing the Java Build Path - Groovy libraries option for the project and changing the option for "include jars from the ~/.groovy/lib on the classpath" to "use the workspace settings".  I think I understand now what you meant in your reply - I should only include jars from my Groovy install (~/.groovy/lib) if I need them and they aren't included in the Groovy-Eclipse provided jar files.  Is my understanding correct?   It's interesting that I haven't had this problem before - I've been using the Groovy-Eclipse for years.  It makes me wonder if the option to " include all jar files from the ~/.groovy/lib folder" being checked by default is better than it not being checked by default.  I guess you're damned if you do, damned if you don't :)

Brian

**Comment by eric-milles** [comment]
The `~/.groovy/lib` directory is part of the global distribution/configuration mechanism.  If you want to use it for other purposes, but not for your eclipse projects, you can set a workspace setting so you don't need to change individual projects.  I think it was supported long ago so there would be a consistent experience between the IDE and the command-line tools.

If you run into problems with any global AST transforms again, you can look in the Groovy Event Console and the Event Log for any output from the compiler.  And you can disable transforms on an individual basis as I mentioned above.  If you want to make use of extra groovy libraries (groovy-macro, etc.) I do recommend that you try to get the latest version if you can.
