### ISSUE TITLE
GroovyEclipse incompatible with Eclipse 4.5 JDT version 

### ISSUE THREAD

**Issue by mjmeijer** [groovy/groovy-eclipse#118]
When using GroovyEclipse 2.9.1 an Error occurs in the Eclipse log when changing Java compiler settings:
`!ENTRY org.eclipse.jdt.ui 4 10001 2015-05-05 17:32:17.087`
`!MESSAGE preference option missing: org.eclipse.jdt.core/org.eclipse.jdt.core.compiler.problem.unusedExceptionParameter (org.eclipse.jdt.internal.ui.preferences.ProblemSeveritiesConfigurationBlock)`

Eclipse 4.5 contains newer JDT/Core version that i messed up by GroovyEclipse patch
See alse:
466380: StandInException in OptionsConfigurationBlock.testIfOptionsComplete (853)
https://bugs.eclipse.org/bugs/show_bug.cgi?id=466380

**Comment by aclement** [comment]
JDT Core patch upgraded. 

Update site: http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/

Now installs ok.  Doesn't quite pass all of its regression tests unfortunately, but let's see how things go.

**Comment by facundofarias** [comment]
Perfect! Thanks a lot :+1:
