### ISSUE TITLE
Groovy 2.4 no longer available in 4.0.0

### ISSUE THREAD

**Issue by hansi-b** [groovy/groovy-eclipse#1183]
After updating from 3.9.x to 4.0.0, I no longer have the 2.4 Groovy compiler available in the Eclipse preferences

* with plug-in version 3.9
![w_groovy24](https://user-images.githubusercontent.com/9629717/96254103-073f0580-0fb5-11eb-8fa4-abda49006a38.png)

* with plug-in version 4.0
![wo_groovy24](https://user-images.githubusercontent.com/9629717/96254087-00b08e00-0fb5-11eb-9174-a3784edb56f2.png)

There seems to be no option to add a 2.4 compiler:
![update_options](https://user-images.githubusercontent.com/9629717/96254052-f2627200-0fb4-11eb-9497-cee9b1ba1ff9.png)

As a workaround, I got the 2.4 compiler back by reverting to plug-in version 3.9. (Unfortunately, we are stuck with 2.4 for a few choice projects ...)

**Comment by eric-milles** [comment]
It was an intentional change: https://github.com/groovy/groovy-eclipse/commit/454c669ab9649be2a87f449f7b9ea2eb29f7999e

**Comment by l3ender** [comment]
How do I install a previous version of the plugin (< 4.0) if I need to use Groovy 2.4? I am using Eclipse 4.17 (2020-09) but I only see version 4.0 of the Groovy development tools when trying to install. I have unchecked "show only the latest versions of available software".

![image](https://user-images.githubusercontent.com/2243641/103425770-48898f00-4b7a-11eb-9972-3bc90fdfca48.png)

**Comment by eric-milles** [comment]
There are update site links and archives at the bottom of each release notes wiki page.  Here is the last that supports Groovy 2.4 directly: https://github.com/groovy/groovy-eclipse/wiki/3.9.0-Release-Notes#update-sites

Note: You can use a different compiler version to build a project that uses Groovy 2.4 at runtime.  This project uses the Groovy 2.5 compiler to build for Groovy 2.5, 3.0 and 4.0 support.  And previously it used the Groovy 2.4 compiler to build for Groovy 2.4, 2.5 and 3.0 support.

**Comment by rbioteau** [comment]
@eric-milles Hi,
 I'm in the situation where my runtime uses groovy 2.4.x and migrating would be a huge pain. I also can't be stuck on an old eclipse version. 
I'm curious about your statement on using a groovy 2.5 compiler with groovy-eclipse and keeping a groovy 2.4.x version at runtime. Are you suggesting that it will work ? I'm afraid of the discrepancies between what will be supported by the editor and at runtime.
Any help on this will be much appreciated !

**Comment by eric-milles** [comment]
@rbioteau When you run Eclipse with Groovy 2.5 compiler but your project has a different Groovy dependency, you should not see any content assist proposals from 2.5.  The project's classpath is respected.  A similar situation exists for running Eclipse with Java 11 but targeting Java 8 for a project.

Groovy-Eclipse itself builds Groovy 2.5, 3.0 and 4.0 projects all using the 2.5 compiler.  Previously it built Groovy versions 1.8-2.4 using the 2.1 compiler.
