### ISSUE TITLE
Method reference support

### ISSUE THREAD

**Issue by radist-nt** [groovy/groovy-eclipse#1185]
According to the documentation, [method reference operator|https://docs.groovy-lang.org/next/html/documentation/#method-reference-operator} is supported in Groovy3+.

But, eclipse shows error on method reference usage.
```
assert 6G == [1G, 2G, 3G].stream().reduce(0G, BigInteger::add)
```
Groovy event trace console (same messages repeated several times):
```
      Compiler : 15:42:55 D:\Work\workspace\groovy-maven-sample\src\main\java\script.groovy: 1: expecting ')', found ':' @ line 1, column 58.
   tream().reduce(0G, BigInteger::add)
                                 ^
      Compiler : 15:42:55 D:\Work\workspace\groovy-maven-sample\src\main\java\script.groovy: 1: expecting EOF, found ')' @ line 1, column 62.
   m().reduce(0G, BigInteger::add)
```

Current workaround is usage of method pointer operator (.&) instead. But it's not the same actually: method pointer returns Closure which has to be casted to required functional interface, but method reference returns functional interface.

Installed version is ![img](https://user-images.githubusercontent.com/15953267/97005374-05da8380-1547-11eb-8a73-ff05a3c7a1f1.png)

**Comment by eric-milles** [comment]
Method references are indeed supported in Groovy 3+ when the Parrot Parser is enabled.  As per this link (https://github.com/groovy/groovy-eclipse/wiki/3.9.0-Release-Notes#support-for-new-versions-of-groovy) the Parrot Parser is not enabled by default in the Groovy Development Tools pending completion of #1011.
