### ISSUE TITLE
Zipped repos for restricted environments?

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#1188]
Hi Eric, hope you're good 👍 

A client wants to install groovy-eclipse but he gets a certificate error during the install (PKIX Path Building Failed). Are there zipped versions of the groovy-eclipse release repos somewhere so he can try these?

Thanks,
Felix

**Comment by eric-milles** [comment]
Yes, indeed.  The release notes each have a section at the end for specific update site links and update site archives: https://github.com/groovy/groovy-eclipse/wiki/3.9.0-Release-Notes#update-sites

**Comment by felixdo** [comment]
Ok thank you. Maybe a 2 column table would be better here, for easier association between update site and zipped version.
