### ISSUE TITLE
p2.index not (always) published?

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1193]
I'm routinely running into the useless p2 error about "No repository found containing", and in trying to debug it it seems that the GRECLIPSE update sites aren't publishing a `p2.index`, where my other update sites do. Is this typical?

**Comment by eric-milles** [comment]
I'm guessing that you are referencing one of the snapshot update sites.  There are frequent builds, which result in replacing the contents of the site.  This is compounded by the fact that eclipse caches the metadata of an update site for as long as it is running.  So if you check for updates it may be reading from that cached metadata which is out of date if a new snapshot has been built.

As far as `p2.index` goes, you can have a look at the update site archives linked on any of the release notes wikis.  They contain all the same files that the online update site does.

**Comment by chrylis** [comment]
Correct; specfically, snapshots for 4.17 (though they say they've finally fixed the formatter bugs after 12 years in 4.18...). Oddly enough, _both_ restarting Eclipse _and_ manually blowing away the p2 cache wasn't enough to clear the stale entries, but after about three restarts it looks like it finally picked it up.
