### ISSUE TITLE
Can't download artifacts

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1207]
I'm getting 403s when trying to download the latest updates (e.g., `https://dist.springsource.org/snapshot/GRECLIPSE/e4.17/plugins/org.codehaus.groovy.eclipse_4.0.0.v202012021929-e2009.jar`). Is this related to the Spring repo permissions changes?

**Comment by eric-milles** [comment]
Three groovy releases dropped today.  There have been a lot of snapshot builds queued up.

**Comment by chrylis** [comment]
Does that mean that the repo is returning a 403 but in reality it's a Not Found?

**Comment by eric-milles** [comment]
Did you try restarting eclipse and checking for updates today?
