### ISSUE TITLE
Looking for groovy.text and groovy.text.markup

### ISSUE THREAD

**Issue by Pace17881** [groovy/groovy-eclipse#1208]
Hi,

I am using the following update url in my eclipse rcp project: https://dist.springsource.org/release/GRECLIPSE/e4.16

I want to use classes like:

- BaseTemplate
- MarkupTemplateEngine
- TemplateConfiguration
- Template

But it seems that the packages groovy.text and groovy.text.markup are not available.

What could be the solution for my problem?

Thanks for any answers

Sebastian

**Comment by eric-milles** [comment]
https://github.com/groovy/groovy-eclipse/wiki/Catalog-of-Features#classpath-container describes the container's function.  `groovy.text` is not part of the core groovy library that is included for Groovy 2.5+.  For that you will need to add the extra groovy modules.

**Comment by Pace17881** [comment]
I followed the steps from the guide and added the groovy libraries container. But where I can get the "extra groovy modules"? And how to add them to the container?

**Comment by eric-milles** [comment]
It would be helpful to know a little more about what type of project you have setup -- maybe a quick screenshot of it.  If you have Gradle, Maven or Ivy you would add dependencies according to how those tools work.  If you are just trying to experiment, you can use `@Grab` annotation to have Groovy download dependencies for a script.  Or you can download the [Groovy binary distribution](https://dl.bintray.com/groovy/maven/apache-groovy-binary-3.0.7.zip) and add jars to the `.groovy/lib` directory in your home directory.

**Comment by Pace17881** [comment]
![grafik](https://user-images.githubusercontent.com/24521835/101238397-40a40f80-36e0-11eb-8516-dc601c94c8fe.png)

This product is based on Eclipse RCP Framework. It consists of many plugins (own and third party). Currently the target is java 1.8. To build the application we use Maven with Tycho(nearly pomless) extension. Some plugins have the groovy nature enabled.

I hope this helps a little bit.

Thanks
Sebastian

**Comment by eric-milles** [comment]
I think the simplest route that will be compatible with both Eclipse IDE and Maven/Tycho is:
1. remove the _Groovy Libraries_ container from your project(s) classpath
1. add `https://dist.springsource.org/release/GRECLIPSE/3.9.0/e4.16` to your target platform definition(s) and select the _Groovy Development Tools_ feature only (includes _Groovy Compiler 2.4_)
1. add `org.codehaus.groovy;bundle-version="2.4.20"` to the `Require-Bundle` section of your plug-in(s) `MANIFEST.MF` file

Groovy 2.4 bundle embeds the `groovy-all.jar` which contains packages `groovy.text`, etc.  Starting in Groovy 2.5 there is no groovy-all artifact.  You can have a look here to see an example of a plug-in project that has a dependency on Groovy classes and enables Groovy compilation for Eclipse export and Maven/Tycho: https://github.com/groovy/groovy-eclipse/tree/master/ide/org.codehaus.groovy.eclipse.astviews

**Comment by Pace17881** [comment]
Hi,

Thanks for this.

But using an older compiler than 2.5 is not possible because of exisiting code uses 2.5 features :(
Are there other solutions?

**Comment by eric-milles** [comment]
Guess I was a little unclear that you already had Groovy in your main or test sources.  Are you trying to use the template stuff for testing?  If you don't need OSGi bundles as part of your application, you fall back to adding the necessary libs to your project classpath.  This would be similar to how I see JUnit in your screenshot and how I assume Spock is referenced as well.

You can still reference the groovy-eclipse projects for how to integrate Groovy with main and test sources in a fully OSGi-compliant way that works for IDE and Maven/Tycho.  The only difference would be that groovy-eclipse is both a consumer and *supplier* of Groovy bundle(s).

**Comment by Pace17881** [comment]
Sry. I cannot understand what I should do.

I don't use the example repo for testing. I have a repo consisting of many eclipse rcp plugins. We use groovy to generate html files to show some data to the user in our ui. We use Spock to test this plugin and all other plugins in our workspace.

So unfortunately I cannot use Groovy 2.4.

If I add only https://dist.springsource.org/release/GRECLIPSE/e4.16 to my target file it will not work because of missing groovy.text namespace.

**Comment by eric-milles** [comment]
If you need more classes than the org.codehaus.groovy bundle provides, you need to import more bundles or jars.  You can get them from Apache Groovy download page or Maven Central or Bintray or wherever.

**Comment by Pace17881** [comment]
Okay. I added the [groovy-templates jar](https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-templates/2.5.13) from maven repository to a pom file as dependency. Thank you for your help and patience.
