### ISSUE TITLE
Detect CompileStatic when added dynamically

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1215]
I'm not sure whether this is simple or herculean, but I have a custom ASTT (in `SEMANTIC_ANALYSIS`) that tags `@CompileStatic` in addition to its other responsibilities. Eclipse currently ignores the directive, since it's not physically present in the class file. I _believe_ that using it in an annotation collector would work, but it would be pleasant if Groovy-Eclipse could detect it and apply it to the editor.

**Comment by eric-milles** [comment]
A working example would be very helpful.  I'm not sure what is meant by "Eclipse currently ignores the directive".  The compiler handles static type checking and the Eclipse editor gives you a view of the metadata that is stored within the AST as well as any errors that are emitted.

If you are not sure if static type checking or static compilation is applied, you can check `ASTTransformationVisitor` which is responsible for detecting local transform annotations and adding the necessary phase operations.  It also runs in `SEMANTIC_ANALYSIS`, so your transform may have run after.
