### ISSUE TITLE
Formatting spock test damages the file

### ISSUE THREAD

**Issue by monrealis** [groovy/groovy-eclipse#1219]
Reformatting this file

```groovy
import spock.lang.Specification

class MySpec extends Specification {
    def "test"() {
        expect:
        [] == [] 
        toString()
    }
}
```

results in this
```groovy
import spock.lang.Specification

class MySpec extends Specification {
    def "test"() {
        expect:
        []== []toString()
    }
}
```
Notice the space at the end of line 6
![image](https://user-images.githubusercontent.com/2280367/104637006-df8f3480-56ac-11eb-9ce8-5254867b77e9.png)

Groovy Plugin Version: Eclipse Groovy Development Tools	4.0.0.v202012170419-e2012
Eclipse version: Version: 2020-12 (4.18.0) Build id: 20201210-1552

**Comment by eric-milles** [comment]
There is code in the formatter to compact list literals, including trailing whitespace.  This is what is affecting your test spec.

**Comment by eric-milles** [comment]
ready to test
