### ISSUE TITLE
editor has spurious "abstract method" error on trait methods

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#122]
I have a `trait Auditable` with a method `void publish()` that is "implemented" by an abstract class. The concrete subclass has an error marker saying

> Can't have an abstract method in a non-abstract class: [...] or the method 'void publish()' must be implemented.

 This looks to be a bug with the Eclipse index where it confuses the fact that traits look like Java interfaces (no implementation) with their having the code added at compile-time. The classes actually compile fine, and I don't get an adornment in Package Explorer.

**Comment by levsa** [comment]
I have the same problem. No errors in Package Explorer, or among in the "Problems" views, but an error is shown in the editor.

![image](https://cloud.githubusercontent.com/assets/310653/18871594/5d1192b8-84b6-11e6-8379-d95eb8cbb827.png)

![image](https://cloud.githubusercontent.com/assets/310653/18871604/6a085164-84b6-11e6-81ad-de6eae62a74c.png)
