### ISSUE TITLE
Formatter ignores indent for if, for, while expressions

### ISSUE THREAD

**Issue by rabits** [groovy/groovy-eclipse#1221]
Hello folks,

I use groovy-eclipse through spotless and during scan found it don't like the multiline expression blocks:
* Example-orig.groovy
   ```
   def   call() {
     if( true
         && true
         && false) {
       println('test')
     }
   }
   ```
* Example-processed.groovy
   ```
   def   call() {
     if( true
     && true
     && false) {
       println('test')
     }
   }
   ```
So the expression for some reason gets the same indent as "if".

Also I noticed that by default it's not removing duplicated spaces (`def   call`) and I found no params to control that.

**Comment by eric-milles** [comment]
fix building now; can you file a separate issue for the spaces concern

**Comment by rabits** [comment]
Oh sure, sorry about mixing this up. Created a separated one: https://github.com/groovy/groovy-eclipse/issues/1225

Thank you for working on that)

**Comment by eric-milles** [comment]
Can you give the changes a try?

**Comment by rabits** [comment]
Oh, so I'm using maven & spotless with 4.17.0 for greclipse and not quite sure how to run the changes... If you can give me a clue - I will be glad to test the changes)

**Comment by eric-milles** [comment]
How is the groovy formatter included?

**Comment by rabits** [comment]
I think this could help: https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#groovy

**Comment by eric-milles** [comment]
It looks like you would create a local install of spotless-eclipse-groovy.  The most recent targets Groovy-Eclipse 3.9.0.  Snapshot builds are at 4.1.0 currently.

**Comment by rabits** [comment]
Ok, thank you - will check how to do that)

**Comment by rabits** [comment]
So, I actually started with spotless, found _ext/eclipse-groovy and probably the file that is links the groovy-eclipse version: https://github.com/diffplug/spotless/blob/main/_ext/eclipse-groovy/gradle.properties#L6 , so I tried to compile 4.1.0-SNAPSHOT as you recommended, but `mvn clean package` on the current groovy-eclipse master failed with error about "Could not find specification for custom execution environment profile 'JavaSE-15 in the target platform'"...

I tried to figure out what's happening in the repo and it's quite confusing, I did not found some build docs - so unfortunately I'm stuck here...
