### ISSUE TITLE
groovy-macro is loaded in version 2.5.8 and you are trying to load version 2.5.12

### ISSUE THREAD

**Issue by Pirlock** [groovy/groovy-eclipse#1222]
Hi,

I am using Eclipse 4.13, version 4.0.0 of the plugin with Groovy compiler 2.5 and Spock 2.0-M2.

We are using Gradle to manage our dependencies. Recently we have updated our Groovy libraries to 2.5.12 and since then when executing Spock tests we are getting the following error:

groovy-macro is loaded in version 2.5.8 and you are trying to load version 2.5.12

Seems that Spock is fetching transitively version 2.5.8. I was thinking of avoiding Spock from fetching 2.5.8, but just modifying manually the classpath of the project executing the Spock test and making sure that all the Groovy libraries are version 2.5.12 doesn't seem to help as I am getting the same error.

**Comment by eric-milles** [comment]
Can you include your build.gradle (or a link to your project) and maybe a screenshot of the project with the gradle classpath container expanded?  It should be quite easy to fix this, but I need some more detail to give proper help.
