### ISSUE TITLE
groovy-eclipse-compiler no longer published to mvnrepository.com

### ISSUE THREAD

**Issue by BartRobeyns** [groovy/groovy-eclipse#1223]
Hello,

The last version of the groovy-eclipse-compiler in [https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-eclipse-compiler](https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-eclipse-compiler) is 3.6.0-03, while the git-repo suggests that 3.9 and 4.0 have been released.
Is it possible to make the latest version of groovy-eclipse-compiler again available in mvnrepository.com?
Or is there a reason not to?

Thank you,

Bart

**Comment by eric-milles** [comment]
There have been no new versions of `groovy-eclipse-compiler` since 3.6.0-03.  This maven plugin adapts between `maven-compiler-plugin` and `groovy-eclipse-batch`.  All the significant changes are found in the batch compiler.

**Comment by walery** [comment]
But there are release notes for [3.7.0], [3.8.0], [3.9.0] and [4.0.0]. Those versions are missing on mvn central, right?

  [3.7.0]: https://github.com/groovy/groovy-eclipse/wiki/3.7.0-Release-Notes
  [3.8.0]: https://github.com/groovy/groovy-eclipse/wiki/3.8.0-Release-Notes
  [3.9.0]: https://github.com/groovy/groovy-eclipse/wiki/3.9.0-Release-Notes
  [4.0.0]: https://github.com/groovy/groovy-eclipse/wiki/4.0.0-Release-Notes

**Comment by eric-milles** [comment]
`groovy-eclipse-compiler` history: https://github.com/groovy/groovy-eclipse/commits/master/extras/groovy-eclipse-compiler
`groovy-eclipse-batch` releases: https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-eclipse-batch
