### ISSUE TITLE
Groovy compiler preference not persisted

### ISSUE THREAD

**Issue by javiermv** [groovy/groovy-eclipse#1224]
With Groovy-Eclipse 4.0.0, switching from default compiler version 2.5.14 to 3.0.7 works after restarting but the preference is not persisted. Shutting down and reopening eclipse resets the groovy compiler version back to 2.5.14.

**Comment by eric-milles** [comment]
If you start eclipse with the "-console" command line switch, do you see "Starting Groovy-Eclipse compiler resolver. Specified compiler level: ..." in the console?

**Comment by javiermv** [comment]
Yep: osgi> Starting Groovy-Eclipse compiler resolver. Specified compiler level: 2.5

**Comment by eric-milles** [comment]
Okay, so the compiler chooser is running.  The version to activate is given by the system property `groovy.compiler.level` or the instance preference of the same name in the namespace `org.codehaus.groovy.eclipse.compilerResolver`.  This is usually found in the configuration directory of your eclipse.exe.  I don't have an example on hand at the moment.

**Comment by javiermv** [comment]
In workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings there is a file named org.codehaus.groovy.eclipse.compilerResolver.prefs, with content groovy.compiler.level=25
I have no groovy.compiler.level system property. Manually changing 25 to 30 fixed the issue for me.
Thanks!

**Comment by eric-milles** [comment]
When you click the button to choose another compiler version, that value should be changed.  Is it getting changed or does it stay at the same value?

**Comment by javiermv** [comment]
Short answer: it stays the same.
Long answer follows.
After clicking on "Switch to 2.4.20" and restarting eclipse, the console outputs:
`osgi> Starting Groovy-Eclipse compiler resolver. Specified compiler level: 2.4
1803 org.codehaus.groovy_3.0.7.v202012311456-e2012-RELEASE STARTING
1800 org.codehaus.groovy_2.5.14.v202012311456-e2012-RELEASE STARTING
1804 org.codehaus.groovy_2.4.20.v202009301344-e2009-RELEASE STARTING
Stopped bundle version 3.0.7.v202012311456-e2012-RELEASE
Stopped bundle version 2.5.14.v202012311456-e2012-RELEASE
Skipped bundle version 2.4.20.v202009301344-e2009-RELEASE`.
Then, opened groovy editors display the error msg "No editor descriptor for id org.codehaus.groovy.eclipse.editor.GroovyEditor" and selecting Window > Preferences shows no Groovy options at all. 
The content of org.codehaus.groovy.eclipse.compilerResolver.prefs is still `groovy.compiler.level=25`.

Shuting down and restarting Eclipse prints 
`osgi> Starting Groovy-Eclipse compiler resolver. Specified compiler level: 2.5`
to the console, editors work again and so does Windows > Preferences > Groovy.

Clicking now on "Switch to 3.0.7" and restarting eclipse, the console outputs:
`osgi> Starting Groovy-Eclipse compiler resolver. Specified compiler level: 3.0`.
The content of compilerResolver.prefs is still `groovy.compiler.level=25` but everything works fine until eclipse is shut down. Then, again, the console outputs: 
`osgi> Starting Groovy-Eclipse compiler resolver. Specified compiler level: 2.5`
which is ok this time since the preference was not persisted.

I can get along with modifying the file manually but I'd be happy to try whatever you think may be of any help.
Thanks for caring.

**Comment by eric-milles** [comment]
Is there any reason eclipse cannot modify the file `<workspace>/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.codehaus.groovy.eclipse.compilerResolver.prefs`?  When you click the button to activate a different groovy compiler, the preference is written and then eclipse restarts.  Do you see the file modification timestamp changing?

Version switch is here: https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy.eclipse.compilerResolver/src/org/codehaus/groovy/eclipse/chooser/CompilerChooser.java#L151

It is only called by this: https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.core/src/org/codehaus/groovy/eclipse/core/compiler/CompilerUtils.java#L86  It writes a log entry in case of error.  Do you see any errors in the _Error Log_ view?

**Comment by javiermv** [comment]
It seems eclipse can modify the file. I did this:
1- Modified some random file to force _Save Resource_ confirmation dialog.
2- Clicked on _Switch to 3.0.17_ and confirm compiler switching dialog.
3- Since there's a dirty editor, the eclipse _Save Resource_ dialog pauses eclipse's restart.
4- In this moment (after compiler switching confirmation but before restart proceeds) `groovy.compiler.level` is **properly** set to 30.
5- Upon restart, the console displays `osgi> Starting Groovy-Eclipse compiler resolver. Specified compiler level: 3.0`.
6- Version 3.0 of the compiler works perfectly well **but** now `groovy.compiler.level` is back at 25 in `org.codehaus.groovy.eclipse.compilerResolver.prefs`. Dunno why. :o)

Now that you mention it, there are several almost identical error entries in the _Error Log_ view:
Message: _FrameworkEvent ERROR_
Exception Stack Trace: `org.osgi.framework.BundleException: Could not resolve module: org.codehaus.groovy.eclipse.compilerResolver [766]`
`  Another singleton bundle selected: osgi.identity; type="osgi.bundle"; version:Version="4.0.0.v202012311456-e2012-RELEASE"; osgi.identity="org.codehaus.groovy.eclipse.compilerResolver"; singleton:="true"`
Same error for several bundles with id org.eclipse.jdt.groovy.* and org.codehaus.groovy.*.

**Comment by eric-milles** [comment]
Would it be possible to try with a fresh install of eclipse?  Or at least uninstall GDT, purge Installation History and manually remove all GDT bundles from plugins directory?

**Comment by javiermv** [comment]
Sure. Same behavior.
Installed fresh _Eclipse IDE for Java Developers_ 2020-12, linux x64; not the installer.
Installed _Groovy-Eclipse 4.0.0_ 2020-12.
Chose _Switch to 3.0.7_ and restart... same problem.
Before restart `groovy.compiler.level` is set to 30 in `org.codehaus.groovy.eclipse.compilerResolver.prefs`, only to be reset back to 25 after restart. But, this time, there are no error messages in the _Error Log_ view.

**Comment by eric-milles** [comment]
I tried a fresh install of Eclipse IDE for Java Developers plus Groovy Development Tools -- I'm on WIndows, so I can't really account for what Linux might be doing.  The switching and preference update is working as expected.  Is it possible you have some file synching software?  When the value reverts to 25, do you see the timestamp of the prefs file advance or go back to before the timestamp of the 30 update?

**Comment by javiermv** [comment]
Found it! It was Eclipse's Preference synching. Sorry.
I've disabled _Preference Recorder_ and solved the problem.
Thanks!
