### ISSUE TITLE
Switch maven instructions to Maven Central

### ISSUE THREAD

**Issue by TobiX** [groovy/groovy-eclipse#1228]
On https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin and https://github.com/groovy/groovy-eclipse/wiki#maven-artifacts, there are still links to the Bintray repository for the Maven complier plugins. Since BinTray will be[ shut down in May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), it would be a good idea to switch to Maven Central URLs (AFAICS, the artifacts are already published there).

I would suggest shields.io for the badges:
- ![Maven Central](https://img.shields.io/maven-central/v/org.codehaus.groovy/groovy-eclipse-compiler)
- ![Maven Central](https://img.shields.io/maven-central/v/org.codehaus.groovy/groovy-eclipse-batch)

And search.maven.org for the links:
- https://search.maven.org/artifact/org.codehaus.groovy/groovy-eclipse-compiler
- https://search.maven.org/artifact/org.codehaus.groovy/groovy-eclipse-batch

**Comment by eric-milles** [comment]
all set
