### ISSUE TITLE
Load Last-Used Compiler Version on Startup

### ISSUE THREAD

**Issue by hankolerd** [groovy/groovy-eclipse#1229]
Using the 4.0.0 release in Eclipse 4.18, every time I start Eclipse it defaults back to the 4.0.0 compiler. I would like to see the ability for the plugin to remember the last used version on the workspace, and always start with that version. This way I can use different workspaces for different projects or branches that require specific versions of Groovy, without having to always double-start the workspace to get the correct compiler version selected, i.e.:
1. Start Eclipse and select a workspace
2. Go to *Preferences->Groovy->Compiler* and select *"Switch to ..."* action and restart the workspace again

**Comment by eric-milles** [comment]
Can you try this: https://github.com/groovy/groovy-eclipse/issues/1224#issuecomment-773018528

**Comment by hankolerd** [comment]
> Can you try this: [#1224 (comment)](https://github.com/groovy/groovy-eclipse/issues/1224#issuecomment-773018528)

Oh my - yes that was it. Sorry for the duplicate bug, I searched but guessed I missed it. Thanks!

**Comment by hankolerd** [comment]
Actually @eric-milles, I may have spoken too soon. I found that compiler level still gets reset to 4.0 each time even without Preference Recording enabled.

I see my workspace has:
`.metadata/org.eclipse.core.runtime/.settings/org.codehaus.groovy.eclipse.compilerResolver.prefs`:
```properties
eclipse.preferences.version=1
groovy.compiler.level=24
```

After manually changing this file to have `groovy.compiler.level=25` then workspace starts with 2.5 as expected. But for some reason when using the Groovy Preferences to switch to a different compiler, it does not appear to update this preference file on disk.

If I create a fresh workspace, it looks the preference file gets set to 25 correctly when switching the compiler level through Preferences, so not sure if a permission issue or what exactly is going on.

**Comment by hankolerd** [comment]
I spoke too soon again - even with `groovy.compiler.level=25` in the preference file, even still most times the workspace will start with 4.0 as the default. It seems only way to be sure is just to check preference on each workspace startup and use the Switch To Compiler action in the Preferences page.
