### ISSUE TITLE
Compile error - No such class: jdk.Profile+Annotation

### ISSUE THREAD

**Issue by walery** [groovy/groovy-eclipse#1231]
A few days ago, I had faced an issue that only appears under JDK >=11 but not under JDK 8.
The error was:

`Groovy: compiler error: exception in phase 'canonicalization' in source unit '/private/tmp/j11i/groovy-eclipse-compiler-jdk11-issue/src/main/java/compilerissue/Foo.groovy' No such class: jdk.Profile+Annotation -- JDTClassNode.getTypeClass() cannot locate it using transform loader`

I was not able to nail down the issue itself. To share the problem, I've isolated and shrunk the project as much as I could. A full example with one small class and one pom.xml is in this repo:

https://github.com/walery/groovy-eclipse-compiler-jdk11-issue

The main purpose is to share the problem with you. I've fixed it by switching to gmavenplus plugin.

**Comment by walery** [comment]
BTW: This issue was the reason why I asked in https://github.com/groovy/groovy-eclipse/issues/1223#issuecomment-789687228 about a newer version of the compiler.

**Comment by eric-milles** [comment]
If I indicate the compiler release, it compiles successfully:
```xml
  <properties>
    <maven.compiler.fork>true</maven.compiler.fork>
    <maven.compiler.release>11</maven.compiler.release>
  </properties>
```

Also, there is a newer batch compiler artifact (3.0.7-02) than the one you are using (3.0.7-01).

**Comment by eric-milles** [comment]
In this case, there is an AST transform that is calling `ClassNode#getTypeClass`, which is an unsafe call to make (citations from Groovy JIRA required).  Within Groovy-Eclipse, we create `JDTClassNode` instances for the Java references that exist between sources and classes or other sources.  `JDTClassNode` does not have a `Class` by default, but tries to accommodate the needs of the compiler and its AST transformations by using `Class#forName` to try and get one from the current context.

```java
    @Override
    public Class getTypeClass() {
        if (hasClass()) return clazz;
        throw new MissingClassException(this, "-- JDTClassNode.getTypeClass() cannot locate it using transform loader");
    }

    @Override
    public boolean hasClass() {
        if (clazz == null && !unfindable) {
            // Some AST transforms are written such that they refer to typeClass on a ClassNode.
            // This is not available within Eclipse. However, we can support it in a rudimentary
            // fashion by attempting a class load using the transform loader (if it's available).
            ClassLoader transformLoader = resolver.compilationUnit.getTransformLoader();
            if (transformLoader != null) {
                try {
                    clazz = Class.forName(getName(), false, transformLoader);
                } catch (ReflectiveOperationException | LinkageError e) {
                    unfindable = true;
                }
            }
        }
        return (clazz != null);
    }
```

![image](https://user-images.githubusercontent.com/18193802/109983057-199daf80-7cc8-11eb-8310-2b70d9c695cf.png)
