### ISSUE TITLE
Project with Groovy 2.4 dependency cannot be built by the Groovy 2.5 compiler

### ISSUE THREAD

**Issue by agabrys** [groovy/groovy-eclipse#1235]
Hello,
The plugin doesn't support Groovy 2.4 since the [4.0.0](https://github.com/groovy/groovy-eclipse/wiki/4.0.0-Release-Notes) version. I read in the #1183 issue that the content assist should work correctly even when the configured Groovy dependency and compiler versions are not the same ([see the comment](https://github.com/groovy/groovy-eclipse/issues/1183#issuecomment-763700330)):
> [...] When you run Eclipse with Groovy 2.5 compiler but your project has a different Groovy dependency, you should not see any content assist proposals from 2.5. The project's classpath is respected. [...]

Unfortunately, some issues popup when I imported the project.

The first issue sounds like a regression of the #893:

![build-error](https://user-images.githubusercontent.com/10604335/111811792-b753ca00-88d7-11eb-91aa-b765726aab37.png)

> The project was not built since its build path is incomplete. Cannot find the class file for groovy.transform.Generated. Fix the build path then try building this project
> The type groovy.transform.Generated cannot be resolved. It is indirectly referenced from required .class files

The fix was based on removing `@groovy.transform.Generated` from the code. Some time later `@groovy.transform.Generated` was added only for compiler 2.5+ and now it is always added. Is it possible to keep the `if-else` statement? 2.4 Groovy is unfortunately still used by some quite very popular tools (e.g. Jenkins). Maybe it is possible to detect Groovy library available on the classpath?

The second issue is very weird:
![compiler-mismatch](https://user-images.githubusercontent.com/10604335/111814619-fa636c80-88da-11eb-9533-a37c08ce001b.png)

It presents the same information twice:
> Groovy: compiler mismatch: project level is 2.5, workspace level is 4.0

I disabled the mechanism which compares compilers:
![verification-disabled](https://user-images.githubusercontent.com/10604335/111814846-40203500-88db-11eb-8f37-6973c9cce7af.png)

I also set the project level to 2.5:
![project-compiler](https://user-images.githubusercontent.com/10604335/111814911-55955f00-88db-11eb-91b9-1976be9b43e1.png)

So I don't know why it shows these errors.

Environment:
* Eclipse 2021-03 (4.19.0), 20210312-0638
* Groovy Development Tools: 4.1.0.v202103180358-e2103 (today's snapshot)

Let me know if you need any additional details or if I should split this issue to more.

Cheers
Adam Gabryś

**Comment by eric-milles** [comment]
All of these things could be fixed.  The free options are to use the 3.9.0 release or to define a `groovy.transform.Generated` annotation or fork the 3_9_maintenance branch and combine the missing JDT patches from master.  I can discuss separately contracted work to provide Groovy 2.4 (or older) support for recent eclipse releases.

**Comment by agabrys** [comment]
Thank you for the hits. I chose option no. 2. It doesn't force to stick to the older versions of the Groovy plugin and Eclipse IDE.

I added the `groovy.transform.Generated` annotation (`src/main/groovy/groovy/transform/Generated`):
```groovy
package groovy.transform

import java.lang.annotation.ElementType
import java.lang.annotation.Retention
import java.lang.annotation.RetentionPolicy
import java.lang.annotation.Target

@Target([ElementType.METHOD, ElementType.CONSTRUCTOR, ElementType.TYPE, ElementType.FIELD])
@Retention(RetentionPolicy.RUNTIME)
@interface Generated {
	// empty
}
```
and next added it to the SCM system global ignore list - Git in my case.

`~/.gitignore`:
```
**/groovy/transform/Generated.groovy
```

`~/.gitconfig`
```
[core]
	excludesFile = <path-to-home-dir>/.gitignore
```

References:
* [StackOverflow - Global Git ignore](https://stackoverflow.com/a/7335487/4944847)
* [Groovy 3.0.7 - [Java] Annotation Type Generated](https://docs.groovy-lang.org/3.0.7/html/gapi/groovy/transform/Generated.html)

**Comment by fco271292** [comment]
I use the following versions:

- Eclipse IDE 2021‑03
- https://dist.springsource.org/release/GRECLIPSE/e4.17 and e4.18, e4.19, but no load compiler groovy 2.4
- Windows 10
- Groovy 2.4.21 
- Java JDK 1.8.291

But I get the error
**The project was not built since its build path is incomplete. Cannot find the class file for groovy.transform.Generated. 
**

Because unsupported groovy 2.4?, and how the solve the problem?

Thanks in advance

**Comment by eric-milles** [comment]
You must use the update site that matches your Eclipse.  2021-03 is 4.19, so you should be using https://dist.springsource.org/release/GRECLIPSE/e4.19 or https://dist.springsource.org/snapshot/GRECLIPSE/e4.19

If you want to use a Groovy 2.4 compiler, the last release that supported that was 3.9.0 and that means 4.17 is the latest release of the IDE you could use: https://dist.springsource.org/release/GRECLIPSE/3.9.0/e4.17

**Comment by davidmichaelkarr** [comment]
For the record, I note that adding "groovy/transform/Generated.groovy" as described above does result in no red marks in the project. I'm not wild about this solution, but it looks like my only reasonable choice at this point.
