### ISSUE TITLE
Updating eclipse causes blank groovy editors 

### ISSUE THREAD

**Issue by gregbujak** [groovy/groovy-eclipse#1238]
After an update to eclipse when attempting to open groovy files using the groovy editor produces a blank editor. This is the second time an update has broken this. 

Reinstalling eclipse and adding the same groovy eclipse plugin version fixed the problem. A later update triggered it again. 

<img width="1310" alt="Screen Shot 2021-03-31 at 1 39 43 PM" src="https://user-images.githubusercontent.com/6308373/113208519-be0f0500-9226-11eb-8062-18f4a3812817.png">

MacOSX: 10.15.7

Spring Tool Suite 4:
Version: 4.10.0.RELEASE
Build Id: 202103111225

Groovy-Eclipse M2E integration	4.1.0.v202103301644-e2012	org.codehaus.groovy.m2eclipse.feature.feature.group	Pivotal Software, Inc.

**Comment by eric-milles** [comment]
What got updated exactly?  I don't know too much about STS.  Groovy Development Tools patch a bundle from Java Development Tools.  Not sure if this is what was updated or if something else was going on.

**Comment by eric-milles** [comment]
Do you still have the failing install for examination?

**Comment by gregbujak** [comment]
Yes, how would you like it?

**Comment by eric-milles** [comment]
If you start with the "-console" option is there anything displayed in there when you start or open the editor (that's blank)?  Is there anything in the Error Log view that could be helpful?

**Comment by gregbujak** [comment]
Unfortunately no. Eventually the  filename _location/*.groovy_ file gets flushed to console but other then that there is nothing helpful. Nothing in the error logs.

**Comment by eric-milles** [comment]
Under the Help > About ... > Installation Details > Plug-ins, what version is shown for `org.eclipse.jdt.core` and `org.eclipse.jdt.groovy.core`?

**Comment by gregbujak** [comment]
Eclipse.org	Java Development Tools Core	3.25.0.v20210223-0522	org.eclipse.jdt.core
	Pivotal Software, Inc.	Groovy-Eclipse integration	4.1.0.v202103301644-e2012	org.eclipse.jdt.groovy.core

**Comment by eric-milles** [comment]
Not sure why STS is using "v20210223-0522"; the release qualifier for JDT was "v20210303-1800".  This latter version is what is designated for the patch and so it must have been unapplied by the update.

**Comment by gregbujak** [comment]
Interesting;
Eclipse.org	Eclipse Java Development Tools	3.18.700.v20210303-1800	org.eclipse.jdt

while _.core_ is behind, cant seem to force an update. 
(But I wonder if that matters. This is the second time that this has happened. Sometime in Feb is when it was fixed by downloading STS and starting over. )

**Comment by eric-milles** [comment]
GDT indicates that it patches the `org.eclipse.jdt` feature: https://github.com/groovy/groovy-eclipse/blob/master/jdt-patch/e419/Feature-org.codehaus.groovy.jdt.patch/feature.xml#L21

The `org.eclipse.jdt.core_3.25.0.v20210223-0522` plugin is part of that feature group.  If STS includes the feature `org.eclipse.jdt_v20210303-1800`, then I am unsure why an update is breaking the patching of `org.eclipse.jdt.core`.

**Comment by chrylis** [comment]
Heads-up that I just repro'd this on my installation, Linux GTK on my end (so it looks like it's a problem with the Java core, not a problem with an interaction with SWT). Updated with a different set of versions that P2 approved, and the only error report I get is a launch-console message

```
(Spring Tool Suite 4:2609): Gtk-CRITICAL **: 21:54:55.008: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

Versions involved:
```
Eclipse.org	Eclipse Java Development Tools	3.18.800.v20210611-1600	org.eclipse.jdt
Pivotal Software, Inc.	Groovy-Eclipse integration	4.2.0.v202106171918-e2103	org.eclipse.jdt.groovy.core
```
