### ISSUE TITLE
@Grab Annotations in eclipse not working - Old GRECLIPSE-1052 ?

### ISSUE THREAD

**Issue by h4gbard** [groovy/groovy-eclipse#124]
I just installed Eclipse Mars Release (4.5.0) and Groovy Eclipse 2.9.2 snapshot builds for Eclipse 4.5.

Using @Grap Annotations in eclipse shows errors in the editor: Groovy:No suitable ClassLoader found for grab.
Also errors for imported classes are shown:  Groovy:unable to resolve class...

Similar as described here.
http://groovy-eclipse-plugin.42567.n3.nabble.com/Grab-annotation-not-working-in-editor-td2990348.html

I couldn't find the old GRECLIPSE-1052 bug because codehaus terminated all services and there are no redirects set up.
Can/will this be fixed anytime?

**Comment by aclement** [comment]
i'm afraid there is no-one working on groovy-eclipse at the moment.
