### ISSUE TITLE
3.0.8 support?

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1250]
The docs indicate that April 19th's nightly should have added support for 3.0.8, but using the snapshot repo for 4.19 (STS 4.10), I'm seeing 4.2.0.v202104192043-e2103 and 3.0.7 as the latest available. Is this the snapshot that should supply 3.0.8?

**Comment by eric-milles** [comment]
Sorry, there were a couple build timeouts.  A new build should begin shortly and it publishes at the end.
