### ISSUE TITLE
Parsing Groovy Sources Takes Forever

### ISSUE THREAD

**Issue by JAPRESSLEY** [groovy/groovy-eclipse#1251]
Hi,

I am using the latest version of eclipse and the latest version of the plugin. I have a bunch of groovy scripts which use @Grab notation. I have configured the files to be scripts under the script folder support so the script is not compiled and just copied to the output folder. Whenever I make a change to one of these scripts it seems to get stuck for hours on "Parsing Groovy Sources". All of the jar dependencies are available in ~/.groovy/grapes and if I monitor this folder there is some files which appear every now and then but disappear almost instantly. I think the issue lies in the @grab notation as if I remove these from the scripts it compiles alot faster. I am actually using maven inside eclipse so the dependencies are available from maven but when I deploy the script it runs standalone and downloads the dependencies using the @Grab. It would be good for an option to turn off @grab resolving in eclipse so I can use my maven dependencies in eclipse and my tests which run the script via groovyshell can execute via the @Grabs

**Comment by eric-milles** [comment]
To disable the Grab transformation, you can load a compiler config script for your project like this:
```groovy
configuration.disabledGlobalASTTransformations = ['groovy.grape.GrabAnnotationTransformation']
```

Save this to `config.groovy` in the root of your project and then right-click on your project and choose _Properties_.

![image](https://user-images.githubusercontent.com/18193802/115722964-1bd5cf00-a345-11eb-84e5-6e9159ffa5c3.png)

**Comment by JAPRESSLEY** [comment]
@eric-milles That seems to help a bit but I am still seeing a long time "parsing groovy sources" and I am seeing the ivy resolver still being called
![image](https://user-images.githubusercontent.com/40691111/115727525-93265580-a37b-11eb-829a-b0a24de2ebe9.png)

![image](https://user-images.githubusercontent.com/40691111/115727288-5c503f80-a37b-11eb-8bc4-a472d0232fb6.png)


Do I need to restart eclipse?

**Comment by eric-milles** [comment]
You can introduce an error into your config script and see if the editor stops short.  This would show if the config is being used.

**Comment by eric-milles** [comment]
If you could supply a small sample project so that I could investigate, that would be helpful.
