### ISSUE TITLE
When using .stream().reduce(identity, accumulator), when providing a lamda or method reference operator for accumulator the editor parser raises a syntax error.

### ISSUE THREAD

**Issue by Spitfire1900** [groovy/groovy-eclipse#1252]
Using Eclipse 2021-3 w/ AdoptOpenJDK 8 with   
```
Eclipse Groovy Development Tools      4.2.0.v202104222128-e2103
Groovy Compiler 3.0                   4.2.0.v202104222128-e2103
```
and groovy-3.0.8 jar with the Project and Workspace compiler set to 3.0 

The following 4 lines will all print '6' under `./gradlew run`
```groovy
println Arrays.asList(1, 2, 3).stream().reduce(0, {x, y -> Integer.sum(x, y)})
println([1, 2, 3].stream().reduce(0, { x, y -> Integer.sum(x, y) }))
println([1, 2, 3].stream().reduce(0, (x, y) -> Integer.sum(x, y) ))
println([1, 2, 3].stream().reduce(0, Integer::sum ))
```

However only the first two lines do not throw a syntax error within the Eclipse editor.

Line 3 throws the following errors:
```
println([1, 2, 3].stream().reduce(0, (x, y) -> Integer.sum(x, y) ))
                                       ^    
                                        \_Groovy:expecting ')', found ','
                                            ^
                                            \_Groovy:expecting ')', found ',' 
```

Line 4 throws the following error:
```
println([1, 2, 3].stream().reduce(0, Integer::sum ))
                                            ^    
                                            \_Groovy:expecting ')', found ','
```

**Comment by eric-milles** [comment]
The new antlr4-based parser is not enabled by default until proper error recovery can be implemented to support editing source files.  If you wish to use it, you can [enable it](https://github.com/groovy/groovy-eclipse/wiki/4.0.0-Release-Notes#support-for-new-versions-of-groovy).

#1101

**Comment by Spitfire1900** [comment]
Thanks @eric-milles . It's not clear to what "parser recovery is not implemented" means here. Does this mean that it will only alert on the first error?

Best reference I have for this nomenclature is https://www.tutorialspoint.com/compiler_design/compiler_design_error_recovery.htm
