### ISSUE TITLE
Regression in IDE handling of generics with STC

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1254]
I'm not certain how to communicate a clear repro, so I'll do my best and will try to provide whatever additional information may be helpful.

I have built some processing pipelines using Vavr's functional types and extension methods (written in Java, consumed from Groovy), which naturally make moderate to heavy use of generics to track the types of the contents. I had a pipeline that (1) worked last week in Eclipse and (2) still works with 3.0.8 from the command line but that (3) recently started giving me IDE errors (both in the editor and in the Problems view).

The signature of the extension method being called is

```
public static <E, A, R extends JsonApiResource<A>>
Either<JsonApiErrorResponse<E>, JsonApiDataItemResponse<A, R>>
mapToJsonApiItemResponse(
        Either<JsonApiErrorResponse<E>, R> self
)
```
and I am invoking it as an extension method by calling `(eitherExpression).mapToJsonApiItemResponse()`. I'm getting this error in Eclipse only:

```
Groovy:[Static type checking] - Cannot call <E,A,R extends com.example.jsonapi.representation.resource.JsonApiResource<A>> io.vavr.control.Either#mapToJsonApiItemResponse() with arguments []
```

**Comment by eric-milles** [comment]
I'll need to know what kind of `Either` is produced, that is what are the type arguments supplied for `L` and `R`.  And what the relationship (type hierarchy) is for `JsonApiResource`, `JsonApiErrorResponse` and `JsonApiDataItemResponse`.

The error message (maybe poorly) indicates that the receiver (aka `eitherExpression`) is not satisfying the requirements of `Either<JsonApiErrorResponse<E>, R> self`.

**Comment by eric-milles** [comment]
Can you retest with the latest snapshot distribution?  I have just completed a large update for return type generics inference.
