### ISSUE TITLE
Add autocomplete support for "def" keyword

### ISSUE THREAD

**Issue by moriline** [groovy/groovy-eclipse#1255]
Please add autocomplete support for "def" keyword. Because "def" keyword is exists, but work with code with current realisation is bad. Just place this peace of code in the file **ide/org.codehaus.groovy.quickfix/templates/groovy-templates.xml**:
```xml
<template name="def"
	description="definition of new variable (Groovy)"
	id="org.eclipse.jdt.ui.templates.def"
	autoinsert="true"
	context="groovy"
	enabled="true"
>def ${word_selection}${name} = ${value}${cursor}</template>

<template name="deff"
	description="definition of new function (Groovy)"
	id="org.eclipse.jdt.ui.templates.deff"
	autoinsert="true"
	context="groovy"
	enabled="true"
>def ${word_selection}${name}(${args}) {
	${cursor}
}</template>
```

**Comment by eric-milles** [comment]
If you'd like the template for a new function, you can always add it under _Window > Preferences > Groovy > Editor > Templates_.  I don't recommend "def" for use as a return type.
