### ISSUE TITLE
Reformatting unnecessarily removes space after []

### ISSUE THREAD

**Issue by monrealis** [groovy/groovy-eclipse#1258]
```groovy
import spock.lang.Specification

class MySpec extends Specification {
    def "test"() {
        expect:
        [] == []
    }
}
```
gets reformatted as

```groovy
import spock.lang.Specification

class MySpec extends Specification {
    def "test"() {
        expect:
        []== []
    }
}
```
There's no reason why space after first `[]` should disappear.
Eclipse Groovy Plugin Version: 4.0.0.v202012170419-e2012
Eclipse version: Version: 2020-12 (4.18.0), Build id: 20201210-1552

May be related: https://github.com/groovy/groovy-eclipse/issues/1219

**Comment by eric-milles** [comment]
Can you try with the latest snapshot distribution?  I am not able to recreate.
