### ISSUE TITLE
Groovy-eclipse sees Traits as interfaces and urges to implement its methods

### ISSUE THREAD

**Issue by injecteer** [groovy/groovy-eclipse#1267]
I have a super-class implementing 2 traits:
```
class CRUDController<T extends MongoEntity> implements ControllerTrait, I18nTrait {...}
```
and it's sub-class:
```
class ScreenController extends CRUDController<Screen> {...}
```

The Eclipse of `Version: 2021-03 (4.19.0)` with `Eclipse Groovy Development Tools 4.2.0.v202106101948-e2103` complains in a sub-class about not implemented methods and as quick fixes suggests to either make the class abstract or implement the methods:

![image](https://user-images.githubusercontent.com/32952/121752410-5a4f6500-cb10-11eb-9aae-f2c2af03a543.png)

The traits must supported also in sub-classes as they are compiled by Groovy compiler (ver. 3) just fine.

**Comment by eric-milles** [comment]
Can you provide a simple and complete example?  Traits are supported, although there are some rough edges since they cannot be fully represented in the Java model.

**Comment by injecteer** [comment]
[repro.zip](https://github.com/groovy/groovy-eclipse/files/6642967/repro.zip)

the class SubClass.groovy demonstrates the behaviour

**Comment by eric-milles** [comment]
I think this error is in the editor only.  Can you confirm that it does not show up in the Problems view and you can compile and test your project successfully?

**Comment by injecteer** [comment]
Yes, it's in editor only, the errors do not appear in "Problems"

**Comment by eric-milles** [comment]
ready to test

**Comment by injecteer** [comment]
Looks much better thanks. 

The other problem is, that in Editor for classes with `@TypeChecked` the trait methods are marked with "not found"

![image](https://user-images.githubusercontent.com/32952/121924456-32dce000-cd3c-11eb-9c66-faedf7217852.png)

**Comment by eric-milles** [comment]
Can you update your sample project to demonstrate?

**Comment by injecteer** [comment]
here you go:

![image](https://user-images.githubusercontent.com/32952/122027929-cf9a8e80-cdcb-11eb-894f-480e8d6b4ec5.png)
[repro.zip](https://github.com/groovy/groovy-eclipse/files/6654423/repro.zip)

**Comment by eric-milles** [comment]
ready to test

**Comment by injecteer** [comment]
I don't get any new snapshots from https://dist.springsource.org/snapshot/GRECLIPSE/e4.19 now

**Comment by eric-milles** [comment]
You may need to restart eclipse for it to reload the update site metadata.

**Comment by injecteer** [comment]
it took a while to upgrade eclipse and reinstall Groovy feature 4.19 -> 4.20, but now I don't get any warnings about traits.
Well done!

**Comment by eric-milles** [comment]
Cheers.  And thanks for filing an issue.
