### ISSUE TITLE
Add support for Groovy compiler configuration scripts

### ISSUE THREAD

**Issue by tkent** [groovy/groovy-eclipse#127]
It would be great if groovy-eclipse supported the groovy 2.1+ [custom compiler configuration feature](https://issues.apache.org/jira/browse/GROOVY-5503).

With Gradle we can specify a configuration file which [makes all groovy classes use the CompileStatic AST](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.GroovyCompileOptions.html#org.gradle.api.tasks.compile.GroovyCompileOptions:configurationScript) by default, but there seems to be no way to get Eclipse to do the same. Having the ability to instruct Eclipse in the same way, IMO, would be huge win.

**Comment by micklev** [comment]
agree, it's unproductive to mark all 100500 classes as @CompileStatic

**Comment by tstibbs** [comment]
This would be really useful both as part of the maven compiler plugin and as part of the eclipse plugin.

**Comment by eric-milles** [comment]
It is in my plan for Groovy-Eclipse 3.0

**Comment by tkent** [comment]
@eric-milles 

Awesome to see this added, thanks!

**Comment by skwirking** [comment]
is there some documentation on how we might use this new feature?

**Comment by eric-milles** [comment]
https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-2.9.2-Release-Notes#support-for-compiler-configuration

**Comment by skwirking** [comment]
Great, thank you @eric-milles. :)
