### ISSUE TITLE
cannot find Maven artifacts for versions >3.0.8

### ISSUE THREAD

**Issue by ispringer** [groovy/groovy-eclipse#1280]
Where can I download Maven artifacts for newer versions of the batch compiler? Maven central only has version 3.0.8 and earlier. I think the newer versions used to be in jfrog/bincenter, but that was recently shut down. I'm interested in downloading the 4.2.0 jars. Thanks!

https://search.maven.org/artifact/org.codehaus.groovy/groovy-eclipse-batch

**Comment by eric-milles** [comment]
I have created the artifacts but have not published them.  I am working through post-bintray deployment.

**Comment by eric-milles** [comment]
To clear up any confusion regarding the versioning of the maven artifacts, the versions are not aligned with that of the main release.   `groovy-eclipse-compiler` the maven compiler adapter has its own semantic versioning and is currently at 3.7.0 with a 3.7.1 in the works to fix a very minor issue with forked execution and `java.home` system property use.  `groovy-eclipse-batch` the compiler itself is versioned to indicate the Groovy release that it patches/targets.  So 3.0.8-01 is linked to Groovy 3.0.8.  There is not a newer non-alpha Groovy release, so the unpublished batch compiler artifact that I have is 3.0.8-02.  It is built against Eclipse 4.20 where 3.0.8-01 was built against 4.19.  This is further described here: https://github.com/groovy/groovy-eclipse/wiki/Building-Maven-Batch-Compiler#version-numbers

**Comment by jan-krakora** [comment]
So for compile against Java 16 we have to wait for 3.0.8-02, right?

**Comment by eric-milles** [comment]
You can build and install the artifacts locally.  I can walk you through this if the instructions are not clear.  Or I could send you the artifacts; github won't let me attach a zip in the comments.

**Comment by karthikdivi** [comment]
@eric-milles can we get ETA for `3.0.8-02`? till then is there any way that you can share the artifacts?

**Comment by cameronbraid** [comment]
Any progress on this ?

**Comment by eric-milles** [comment]
https://groovy.jfrog.io/ui/native/plugins-release-local/org/codehaus/groovy/groovy-eclipse-batch

https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin#how-to-use-the-compiler-plugin---setting-up-the-pom
