### ISSUE TITLE
Type inferencing error (only in Eclipse, not in groovyc)

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1281]
Consider this:

```groovy
package test70

import groovy.transform.CompileStatic

@CompileStatic
class Test70 {

	void foo() {
		Object v1 = 'a'
		Object v2 = 'b'
		[v1, v2].each {
			v ->
			if(v instanceof Map) {
				v.entrySet().each { e ->
					def s = e.value
					if(s instanceof String)
					e.value = s.toUpperCase()
				}
			}
		}
	}
}
```

An error is given on both occurrences of `e.value`, because `e` is evaluated as `Object` instead of `Map.Entry`.
This used to work until some version of the Greclipse plugin (now I'm on 4.3.0.v202107132103-e2009).
If I compile this with Gradle/Groovy, the JAR is built successfully.

If I remove `@CompileStatic`, I get underlining for `v.entrySet()` and again on both occurrences of `e.value`.

If I try to give `e` a type in the closure:

```groovy
				v.entrySet().each { Entry e ->
					def s = e.value
					if(s instanceof String)
					e.value = s.toUpperCase()
				}
```

I see this:
- with `@CompileStatic` an additional error is given on `Entry`, saying it's expecting `Object`.
- without `@CompileStatic`, instead, the underlining for `e.value` is fixed, so the situation improves.

![image](https://user-images.githubusercontent.com/18193802/126511507-12c5dd37-a9bc-4d95-94fe-a41e8027761f.png)

**Comment by eric-milles** [comment]
It is this change where the raw type `Map` is causing the return type of `v.entrySet()` to be changed to `Set`.
https://github.com/groovy/groovy-eclipse/blob/74e24d8fd5aa45e3ec694fab2b42aec48b6d851c/base/org.codehaus.groovy30/src/org/codehaus/groovy/transform/stc/StaticTypeCheckingVisitor.java#L5740

As a workaround, you can add a cast: `((Map<?,?>)v).entrySet()` and you may also need to add a cast to `v1` or `v2` to stop the flow type of `String`.

This will be an issue for groovyc as well wherever [GROOVY-10049](https://issues.apache.org/jira/browse/GROOVY-10049] is addressed.

**Comment by eric-milles** [comment]
Here are forms that should work the same;  `v.entrySet().each { e ->` can be expressed as `v.each { e ->` or `for (e in v) {`:
```groovy
@groovy.transform.TypeChecked
void test() {
  Object v1 = 'a'
  Object v2 = 'b'
  [v1, v2].each { v ->
    if (v instanceof Map) {
      v.each { e ->
        def s = e.value
        if (s instanceof String)
          e.value = s.toUpperCase()
      }
    }
  }
}
```

STC should infer `Entry` for `e` through DGM `static <K, V> Map<K, V> each(Map<K, V> self, @ClosureParams(MapEntryOrKeyValue.class) Closure closure)` for the first.

`for (e in v) {` and `for (Map.Entry e in v) {` both fail with similar errors but `for (e in (Map)v) {` does work.  I'll have to investigate this later.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Version 4.3.0.v202107240018-e2009 fixes the problem for me, thank you!

**Comment by mauromol** [comment]
Still, if I remove `@CompileStatic`, I get two underlinings that shouldn't be there IMHO:

![immagine](https://user-images.githubusercontent.com/1742494/126876038-b123a2b1-7c5b-428b-baae-5cfebd1d8d01.png)

Should I open a new issue for this?

**Comment by eric-milles** [comment]
In this specific case, it can be determined that the only possible type for "v" is String.  So an "instanceof Map" check presents an inconvertible type and so Map is ignored.  You can add a typecast to the list: `[(Object)v1, v2]` or to the declaration `Object v1 = (Object)'a'` if you wish.

**Comment by mauromol** [comment]
Still, it's unexpected that static type inference and dynamic type inference behave in different ways in this example...
