### ISSUE TITLE
Incorrect SIG_ARRAY_LENGTH=255 at org.codehaus.groovy.classgen.asm.CallSiteWriter

### ISSUE THREAD

**Issue by emrekultursay** [groovy/groovy-eclipse#1285]
`SIG_ARRAY_LENGTH` should have been `250` instead of `255` at https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy25/src/org/codehaus/groovy/classgen/asm/CallSiteWriter.java

```
    private static final int SIG_ARRAY_LENGTH = 255;
```

Because, the maximum is determined by the maximum number of arguments that can be passed to `ArrayUtil.createArray()`, which is 250 as can be seen here: http://docs.groovy-lang.org/docs/groovy-2.4.0/html/api/org/codehaus/groovy/runtime/ArrayUtil.html

Currently, any value less than 250 works, over 255 throws `IllegalArgumentException`, but value between 250-255 continues to fall through and fail in a way that is very difficult to debug (which is what the CL that introduced SIG_ARRAY_LENGTH wanted to avoid).

**Comment by eric-milles** [comment]
https://issues.apache.org/jira/browse/GROOVY-10183
