### ISSUE TITLE
has Groovy 2.5 compiler support been dropped in the latest version?

### ISSUE THREAD

**Issue by jeacott1** [groovy/groovy-eclipse#1287]
has Groovy 2.5 compiler support been dropped in the latest version?
I cannot find anywhere to install the 2.5 compiler anymore.

**Comment by eric-milles** [comment]
Groovy Compiler 2.5 is included with the Groovy Development Tools Feature.  Groovy Compiler 3.0 and 4.0 are additional / optional.
