### ISSUE TITLE
GDT could not support java lambda forEach of list syntax?

### ISSUE THREAD

**Issue by river2017** [groovy/groovy-eclipse#1290]
Hello,
       I pust some code snippet of groovy into GDT( The Groovy Development Tools ) to test java lambda function,but GDT can not compile it. 
I need some help.

`
public class Test1 {
    public static void main(String[] args) {
        List<String> list = new ArrayList<>();
        list.add("123456");
        list.forEach(t->{System.out.println("r="+t)})
    }
}
`

The error msg is ：
`
Multiple markers at this line (  list.forEach(t->{System.out.println("r="+t)}) )
	- Groovy:expecting '}', found '->' @ line 7, 
	 column 23

`

**Comment by eric-milles** [comment]
You need to enable the newer parser for now (#1011): https://github.com/groovy/groovy-eclipse/wiki/4.2.0-Release-Notes#support-for-new-versions-of-groovy

**Comment by eric-milles** [comment]
You could also write your test this way:
```groovy
class Test {
  static main(args) {
    List<String> list = ['123456']
    list.forEach { println "r=$it" }
  }
}
```

**Comment by river2017** [comment]
Great! thank u!
