### ISSUE TITLE
Is the underline appearing normal?

### ISSUE THREAD

**Issue by chazhongbao** [groovy/groovy-eclipse#1293]
![image](https://user-images.githubusercontent.com/43258262/130030795-4090f1a1-ca8e-42df-aa6e-099fbd5d1e56.png)

eclipse Version: 2021-06 (4.20.0)

**Comment by eric-milles** [comment]
The underline is an indication of "unknown" or dynamic resolution.

![image](https://user-images.githubusercontent.com/18193802/130091955-cdc587ca-3b61-412a-88f4-868925fbca38.png)

![image](https://user-images.githubusercontent.com/18193802/130091973-a3ada2e0-86b3-427c-9b8f-000778ae6763.png)

**Comment by c384795430** [comment]
But in eclipse, it does not automatically prompt, which is a pity.Idea can do this.

**Comment by eric-milles** [comment]
@c384795430 What kind of prompting are you expecting in this case?  Groovy is a dynamically-typed language and so this feature of the editor lets you know when you are relying on dynamic/runtime resolution.
