### ISSUE TITLE
Java 8 lambda style doesn't work

### ISSUE THREAD

**Issue by ivan-vanek** [groovy/groovy-eclipse#1294]
When I want use Java 8 lambda style Groovy script then plugin show error 
```
Multiple markers at this line
	- Groovy:expecting EOF, found '->'
	- Groovy:expecting ')', found '->'
```
code (example from https://groovy-lang.org/releasenotes/groovy-3.0.html)
```
(1..10).forEach(e -> { println e })
```
I have setup Groovy compiler 3.0.8 version
![obrazek](https://user-images.githubusercontent.com/66460094/130802034-555c5a49-d73a-4093-9d1b-9f3465a74696.png)

**Comment by eric-milles** [comment]
#1290 #1107 #1011
