### ISSUE TITLE
Any plan to be compatible with BETA version of JDT with Java 17 support ?

### ISSUE THREAD

**Issue by gjevardat** [groovy/groovy-eclipse#1298]
Hello,
Using 4.3.-SNAPSHOT version of the plugin makes it incompatible with the JDT Java 17 support  BETA version plugins (4 in total)
I was just curious if there is any easy possibility to change it.
Thanks

**Comment by eric-milles** [comment]
Eclipse 2021-12 (4.22) will have milestone 1 released on October 8th.  That should have Java 17 support included.  It may be possible to set up a compatible patch using the Java 17 beta update site -- I have stopped creating official builds like that since the quarterly release cadence was adopted.
