### ISSUE TITLE
Import maven project in workspace: 'configure->convert to groovy project' not available

### ISSUE THREAD

**Issue by nuytsm** [groovy/groovy-eclipse#130]
When I import a multi-module maven project from svn, I should be able to convert it to the groovy nature. This option is not available.

When I do this with a project that was created in the same eclipse workspace (create it, delete it, reimport it), it does work. So there must be some info missing if the project wasn't initiated on the same workspace?

See also: 
http://stackoverflow.com/questions/31782335/eclipse-mars-m2e-groovy-eclipse-compiler-no-source-folders?noredirect=1#comment51614821_31782335

**Comment by eric-milles** [comment]
Can you provide an example project to import that exhibits this problem?

**Comment by eric-milles** [comment]
You shouldn't need to convert an imported project to groovy if the pom uses the groovy-eclipse-compiler. The groovy nature and source folders should be added when you run a Maven update.
