### ISSUE TITLE
GROOVY-10124: "refers to the missing type" error in Greclipse (not Groovy)

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1300]
Consider the attached project.
If you run `./gradlew jar` it will compile fine.
However, if you open it in Greclipse and open the class `test.test.TestGreclipseError`, you'll see an error:

```
The method getResult() from the type BaseResponse<Result> refers to the missing type Result
```

Of course, the mentioned type is not missing.

This is quite annoying because Eclipse seems not to perform a clean build for this. I suspect the problem lies in `test.api.io.BaseResponse<T>`, which has a field `result` of the generic type `T`.

If the fix is hard, a suggestion for a workaround would be much appreciated.

[TestGroovyGradle.zip](https://github.com/groovy/groovy-eclipse/files/7253750/TestGroovyGradle.zip)

Tested with Greclipse 4.3.0.v202109281919-e2009.

**Comment by eric-milles** [comment]
I believe this is related to [GROOVY-10124](https://issues.apache.org/jira/browse/GROOVY-10124).  Groovy and Java have different scope rules for the header of a class (annotations, generics, extends, implements).

Adding a qualifier to the inner class type argument will fix resolution for JDT.
```groovy
class Response extends WithResultOperationResponse<Response.Result> {
//                                                 ^^^^^^^^^
	static class Result ...
}
```

**Comment by mauromol** [comment]
Good catch... using `Response.Result` in the class declaration "extends" clause seems to fix #1301 as well...

Can anything be done on Greclipse side as a workaround until Groovy bug is fixed?

**Comment by eric-milles** [comment]
If GROOVY-10124 was fixed, you would get an error in the groovy source as well.  This could be done in greclipse ahead of groovy proper.  I am unsure of doing that as pure groovy can still work as before.

**Comment by mauromol** [comment]
Having an error in the Groovy source is fine for me, at least you know what you should fix. 

I understand your concern of doing that in Greclipse before it's done in Groovy, but if the current behaviour prevents correct compilation under Eclipse, I think that having an error in the IDE even if it would be legitimate with plain groovyc is better than having an incomprehensible build error in the IDE anywhere else in the code...

**Comment by eric-milles** [comment]
I will put out 4.3.0 release tomorrow.  Then I will take a look at fixing the scope issue so you get a helpful error for 4.4.0.

**Comment by eric-milles** [comment]
```groovy
package p
class Outer extends X<Inner> {
  static class Inner {}
}
```
I have a bit of code worked up for #256 / GROOVY-8063 that represents the example above as the following in the Java model:
```java
package p;
import java.lang.*;
import java.util.*;
import java.io.*;
import java.net.*;
import groovy.lang.*;
import groovy.util.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import p.Outer.*;
public class Outer extends X<Inner> {
  public static class Inner {
    ...
  }
  ...
}
```

The extra on-demand import at the end is enough help JDT find the inner class reference.  This should deliver a more seamless experience in the IDE.

**Comment by eric-milles** [comment]
This solution will only help top-level types.  If you make this kind of reference, it will still fail:
```groovy
class Outer {
  @Tag(Deeper.VALUE)
  class Inner {
    static class Deeper {
      public final VALUE = ...
    }
  }
}
```
