### ISSUE TITLE
Maven dependencies not able to download in Eclipse

### ISSUE THREAD

**Issue by vishnuprakash9845** [groovy/groovy-eclipse#1322]
**So in the pom.xml tried to download the Java Client dependency, but getting the below error**

Eclipse Version: 2020-09 (4.17.0)
Build Id: 20200910-1200

_Description Resource Path Location Type
Error while downloading 'https://maven.apache.org/xsd/maven-4.0.0.xsd' to /Users/muniswamyv/.lemminx/cache/https/maven.apache.org/xsd/maven-4.0.0.xsd. pom.xml /appiumFramwork line 1 Language Servers
Description Resource Path Location Type
Error while downloading 'https://maven.apache.org/xsd/maven-4.0.0.xsd' to /Users/vishnu/.lemminx/cache/https/maven.apache.org/xsd/maven-4.0.0.xsd. pom.xml /appiumFramwork line 1 Language Servers
Description Resource Path Location Type
Missing artifact io.appium:java-client:jar:7.6.0 pom.xml /appiumFramwork line 1 Maven Dependency Problem
Description Resource Path Location Type
Missing artifact io.appium:java-client:jar:7.6.0 pom.xml /appiumFramwork line 1 Maven Dependency Problem_

![image](https://user-images.githubusercontent.com/24207575/146875303-33797682-9ff4-44f6-b96c-15fc4e619717.png)

Can anyone help me on this issue please

**Comment by eric-milles** [comment]
Looks like that dependency is indeed available from Maven Central.  You can try deleting all your problem markers and updating the maven project (Alt+F5).  If it still fails, you need to open a bug with m2e (https://www.eclipse.org/m2e/).
