### ISSUE TITLE
Editor reports errors in compliant Groovy 3.0.0 code

### ISSUE THREAD

**Issue by finianoboyle** [groovy/groovy-eclipse#1323]
Using:
* groovy-eclipse 4.21
* Eclipse 2021-12 (4.22.0) Build id 20211202-1639
* Ubuntu 20.04
* Java 1.8.0_201

There an anomaly in the compiler used by the plugin to parse Groovy code within the editor. Having selected `Window > Preferences > Groovy > Compiler` and confirmed `using Groovy compiler 4.0.0-rc-1` and that `Enable checking for mismatches between the project and workspace Groovy compiler levels` is checked, there are code errors identified against syntax that was introduced in Groovy 3.0.0 - this is how two examples from the [documentation for Groovy 4.0.0-rc-1](http://docs.groovy-lang.org/docs/groovy-4.0.0-rc-1/html/documentation/) are reported:

Groovy 3.0.0 Elvis assignment operator raises compilation error `Groovy:unexpected token: ?`:

```
import groovy.transform.ToString

@ToString
class Element {
  String name
  int atomicNumber
}

def he = new Element(name: 'Helium')
he.with {
  name = name ?: 'Hydrogen'
  atomicNumber ?= 2       // Raises compilation error "Groovy:unexpected token: ?"
}
assert he.toString() == 'Element(Helium, 2)'
```

Groovy 3.0.0 - safe indexing operator raises compilation errors `Groovy:expecting ':', found 'array'` and `Groovy:unexpected token: array`

```
String[] array = ['a', 'b']
		assert 'b' == array?[1]
		array?[1] = 'c'         // Raises compilation errors "Groovy:expecting ':', found 'array'"
													  // and "Groovy:unexpected token: array"
		assert 'c' == array?[1]
```

Using the Ubuntu command line and the version of Groovy 4.0.0-rc-1 installed within Ubuntu, `groovyc test.groovy` compiles both of these without any errors.

It seems as though, despite selecting the 4.0.0-rc-1 compiler that the plugin is using version 2.5.15 to parse the Groovy code in the editor.

**Comment by eric-milles** [comment]
#1011 #1107 #1185 #1211 #1290 #1294 #1310

https://github.com/groovy/groovy-eclipse/wiki/4.3.0-Release-Notes#support-for-new-versions-of-groovy

> The new antlr4-based Parrot Parser is disabled by default. To enable it, add `-Dgroovy.antlr4=true` to your *eclipse.ini* file after the `-vmargs` line or add a compiler config script to your project with `configuration.pluginFactory = org.codehaus.groovy.control.ParserPluginFactory.antlr4()`

**Comment by finianoboyle** [comment]
Thank you for explaining that and for responding so quickly. It has resolved the issue.
