### ISSUE TITLE
Update wiki Lombok integration instructions

### ISSUE THREAD

**Issue by alexandre-senecal** [groovy/groovy-eclipse#1329]
Could you please update the wiki section on Lombok
https://stackoverflow.com/questions/8524891/maven-groovy-and-java-lombok/9948860#9948860
to include the following clarification regarding outlining Lombok as a dependency when configuring the maven-compiler-plugin.

See https://stackoverflow.com/questions/8524891/maven-groovy-and-java-lombok/9948860#9948860

It appears to have stumped many of us.
Thanks

**Comment by eric-milles** [comment]
The referenced SO answer is quite old.  What is missing from the document exactly?  The very first statement in the Project Lombok section is that you need to add to build and compiler dependencies section: https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin#project-lombok

There is an example project provided here as well (with some fill-in-the-blanks): https://github.com/groovy/groovy-eclipse/tree/master/extras/groovy-eclipse-compiler-tests/src/it/apt-lombok

**Comment by alexandre-senecal** [comment]
Hello Eric, thanks for the response. The example section is exactly what I was looking for!

I guess the confusing part for me in the wiki is the "The lombok jar needs to be added to both the build and compile dependencies sections". I'm not very familiar with this nomenclature, build vs compile dependencies. It wasn't immediately clear that lombok needed to be listed as a dependency to the maven-compiler-plugin in the build section. Maybe it's just a 
 terminology thing but I believe a link to the example from the wiki would be very helpful.

Thanks again
