### ISSUE TITLE
Error when passing class parameter to annotation with bound

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1330]
I'm wrangling some Jackson deserialization and am attempting to annotate my POGO with

```
@JsonTypeResolver(CustomTypeResolverBuilder)
```

In Eclipse (but only Eclipse), I get this error message:

```
Type mismatch: cannot convert from Class<CustomTypeResolverBuilder> to Class<? extends TypeResolverBuilder<?>>
```

groovyc works fine. The error persists in Eclipse regardless of whether I apply `@CompileStatic`. This is a particular problem because while most other spurious errors will go away if I close the class, delete the marker, and build from the CLI, this one keeps recurring spontaneously whenever the entire compilation unit is touched.

GRECLIPSE version: 4.5.0.v202201031939-e2112

**Comment by eric-milles** [comment]
Could you provide some more detail about where this annotation is used and what `CustomTypeResolverBuilder` looks like?  Is it possible to produce a small project that demonstrates this issue?

**Comment by eric-milles** [comment]
There are some complicated generics at play here:
```groovy
Class<? extends TypeResolverBuilder<?>> // for JsonTypeResolver#value

interface TypeResolverBuilder<T extends TypeResolverBuilder<T>>

// one example of a TypeResolverBuilder implementation:

static class ObjectMapper.DefaultTypeResolverBuilder extends StdTypeResolverBuilder implements Serializable

class StdTypeResolverBuilder implements TypeResolverBuilder<StdTypeResolverBuilder>
```

**Comment by chrylis** [comment]
Aha, I have been able to make the compiler happy: I'm not certain why I was getting the error I was (the error message per se was incorrect, and groovyc was happy), but I had forgotten to include the type parameter on `implements TypeResolverBuilder<CustomTypeResolverBuilder>`. Eclipse (and groovyc) did not emit raw-type warnings, and apparently somewhere along the line groovy-eclipse decided that the generic bounds didn't match somehow.

**Comment by eric-milles** [comment]
There were some changes in 2021 for self-referential type parameters such as this.  I'm not sure how much of that made it back to Greclipse's Groovy 2.5.

**Comment by chrylis** [comment]
This was in the latest 3.0 nightly, but as 4.0 is coming out it may be moot in a month.
