### ISSUE TITLE
Fix broken reference in Oomph setup

### ISSUE THREAD

**Issue by merks** [groovy/groovy-eclipse#1334]
The [setup archiver job](https://ci.eclipse.org/oomph/job/setup-archiver/) notices [errors in groovy-eclipse.setup](https://github.com/groovy/groovy-eclipse/blob/c3c00a58b297e3dbe779b43ee317d3d40185b613/groovy-eclipse.setup#L365) as reported like this:
```
FAILED to load https://raw.githubusercontent.com/groovy/groovy-eclipse/master/groovy-eclipse.setup
  ERROR: Unresolved reference '//@setupTasks.21/@workingSets.3'. (https://raw.githubusercontent.com/groovy/groovy-eclipse/master/groovy-eclipse.setup, 365, 67) 365 365 67
```
No doubt you've been textually editing which has broken the positional cross reference `excludedWorkingSet="//@setupTasks.21/@workingSets.3"`.  I've attached below a fixed version where I've assigned an ID to the working sets task such that references to other working sets are based on that ID, `excludedWorkingSet="//'working.sets.Groovy-Eclipse'/@workingSets[name='Tests']"`, rather than being positional so that this problem doesn't happen again in the future.

[groovy-eclipse.setup.txt](https://github.com/groovy/groovy-eclipse/files/7868411/groovy-eclipse.setup.txt)

**Comment by eric-milles** [comment]
Thanks for the tip on how to replace the relative reference(s).  I updated the setup script and it appears to have fixed the build.  Can you confirm?

**Comment by merks** [comment]
Yes, the problem is solved.  Thanks. 🥇
