### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by psadi** [groovy/groovy-eclipse#1338]
```
Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/e4.22/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Im getting this error, Is there a way to install manually ?

**Comment by eric-milles** [comment]
You can get the update site archive from the link at the bottom of the release notes: https://github.com/groovy/groovy-eclipse/wiki/4.4.0-Release-Notes#update-sites

**Comment by addy3494** [comment]
is it possible to install manually ? im new to eclipse. Please do share the instructions if yes.
