### ISSUE TITLE
help migrating from IDEA to groovy-eclipse

### ISSUE THREAD

**Issue by amiracam** [groovy/groovy-eclipse#1350]
hi, sorry if not appropriate.

I'm exploring migrating several production projects to groovy-eclipse, however I use the combination of
1. groovy 3.8
2. Jav1 1.8.312
3. gradle 6.x

the combinations of installed groovy-ecllipse releases including snapshots seem to come along with Groovy 2.5 and I don't understand how that's configured with Eclipse.
in the case of IDEA , it was driven by build.gradle 

but I don't understand the setup from Eclipse perspective for that i.e. a groovy specific gradle setup.
obviously I"m used to IDEA , is there perhaps a demo groovy gradle project for Eclipse that can be cloned or followed.

thanks 

-Charles

**Comment by eric-milles** [comment]
Hello and thanks for your interest.  Groovy 2.5 is the default compiler that comes installed.  Groovy 3 and 4 compilers can also be installed and switched between.

In a typical Gradle project, you would find this in your _build.gradle_:
```groovy
plugins {
  id 'groovy'
  id 'eclipse'
}
```
Then you can run `gradle eclipse` or `gradlew eclipse` to produce the necessary project files for eclipse.  I think this also happens as part of _File > Import... > Gradle > Existing Gradle Project_ -- please consult Eclipse Buildship (Gradle integration) for more details.

After importing the project, you should see source folders and be able to add sources in a typical manner.  Dependencies are added through the normal Gradle mechanisms and will show up under the _Project and External Dependencies_ node.
![image](https://user-images.githubusercontent.com/18193802/158077008-668f9c3f-9d61-4a41-b29c-a27f49da63fe.png)
