### ISSUE TITLE
Compiler creates different byte code on Linux vs Windows/MacOS

### ISSUE THREAD

**Issue by kriegaex** [groovy/groovy-eclipse#1353]
@eric-milles, we started talking about this problem on StackOverflow [here](https://stackoverflow.com/a/61071840/1082681). Please re-read your own and my comments to which lately you did not react anymore, even though I created a reproducer for you on GitHub as part of my bigger Spock playground project with a dedicated [branch `groovy-properties-emilles`](https://github.com/kriegaex/GebSpockSamples/tree/groovy-properties-emilles), only running the problematic test on GitHub. Sorry, I have to rely on GitHub CI, because locally I neither have Linux (where the problem occurs) nor MacOS.

Now I think I pinpointed the problem to the GrEclipse compiler, because it creates different byte code for the class under test on Linux than on the other two platforms. In the Spock test, I just see the result. It is not part of the problem.

Please first look at directory [_geb-spock-samples/src/test/groovy/de/scrum_master/stackoverflow/q61065342_](https://github.com/kriegaex/GebSpockSamples/tree/groovy-properties-emilles/geb-spock-samples/src/test/groovy/de/scrum_master/stackoverflow/q61065342). There you find:
  * 3 groovy classes which I am going to talk about more later,
  * Text files _deps-linux.txt_ vs. _deps-windows.txt_, which show exactly identical Maven dependency trees for the module on both platforms. I extracted those from a previous GitHub build result in which I had added `mvn dependency:tree` to the build plan. So dependency management is not the problem here.
  * Text files _ex-linux.txt_, _ex-macos.txt_, _ex-windows.txt_ which, if you diff e.g. Windows to Linux, show that the call stack leading to the problem in the Spock test on Linux really does look different there compared to the two identical ones on Windows/MacOS.

First I thought this might be some Spock quirk, but then I had the idea to attach the `target` directory for that Maven module as a ZIP file to the GitHub build, so I can download and compare the class files. You can do so yourself by downloading the build attachments for [this build run](https://github.com/kriegaex/GebSpockSamples/actions/runs/2010479402). Scroll down to "Artifacts" and fetch the Linux and the Windows versions. Then unpack them and do a directory tree diff, focusing on _*.class_ files. The result looks like this for me, using Total Commander's diff tool:

![image](https://user-images.githubusercontent.com/1537384/159146311-6991a395-87c4-434e-a8b5-2866adad3283.png)

That was unexpected: The exact same GrEclipse compiler version produces different class files for 3 classes in my project, depending on which platform it runs on. Focusing on `UnderTest`, which is the one of those 3 classes actually used by `SetGroovyPropertyTest`, here is the source code:

```groovy
package de.scrum_master.stackoverflow.q61065342

class UnderTest {
  void call(Collaborator collaborator, String value) {
    collaborator.x = value
  }
}
```

`Collaborator` looks like this:

```groovy
package de.scrum_master.stackoverflow.q61065342

class Collaborator {
  String x
}
```

Simple enough, I think. FYI, the Spock 1.3 test asserting on `setX` to be called looks like this:

```groovy
package de.scrum_master.stackoverflow.q61065342

import spock.lang.Specification

class SetGroovyPropertyTest extends Specification {
  void 'expect setX'() {
    setup:
    def collaborator = Mock(Collaborator)

    when:
    new UnderTest().call(collaborator, 'test')

    then:
    // Both of these seem to be called sometimes on Groovy 2.5, maybe depending on the OS platform,
    // test order or whatever
    1 * collaborator.setX('test')
    //1 * collaborator.setProperty('x', 'test')
  }
```

But we do not even have to run the Spock test in order to spot the difference. When opening the class files for `UnderTest` from the downloaded _target_ directories, we see that on Windows and MacOS it looks like this when decompiled (using Fernflower, which is embedded in IntelliJ IDEA Ultimate):

```groovy
package de.scrum_master.stackoverflow.q61065342;

import groovy.lang.GroovyObject;
import groovy.lang.MetaClass;
import groovy.transform.Generated;
import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
import org.codehaus.groovy.runtime.callsite.CallSite;

public class UnderTest implements GroovyObject {
  @Generated
  public UnderTest() {
    CallSite[] var1 = $getCallSiteArray();
    super();
    MetaClass var2 = this.$getStaticMetaClass();
    this.metaClass = var2;
  }

  public void call(Collaborator collaborator, String value) {
    CallSite[] var3 = $getCallSiteArray();
    // This is the expected Groovy code found on Windows and MacOS
    ScriptBytecodeAdapter.setGroovyObjectProperty(value, UnderTest.class, collaborator, (String)"x");
  }
}
```

Now if we look at the Linux version, we find:

```groovy
package de.scrum_master.stackoverflow.q61065342;

import groovy.lang.GroovyObject;
import groovy.lang.MetaClass;
import groovy.transform.Generated;
import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
import org.codehaus.groovy.runtime.callsite.CallSite;

public class UnderTest implements GroovyObject {
  @Generated
  public UnderTest() {
    CallSite[] var1 = $getCallSiteArray();
    super();
    MetaClass var2 = this.$getStaticMetaClass();
    this.metaClass = var2;
  }

  public void call(Collaborator collaborator, String value) {
    CallSite[] var3 = $getCallSiteArray();
    // This is the unexpected Groovy code found on Linux
    ScriptBytecodeAdapter.setProperty(value, (Class)null, collaborator, (String)"x");
  }
}
```

Spot the difference?

```groovy
    // This is the expected Groovy code found on Windows and MacOS
    ScriptBytecodeAdapter.setGroovyObjectProperty(value, UnderTest.class, collaborator, (String)"x");
```

versus

```groovy
    // This is the unexpected Groovy code found on Linux
    ScriptBytecodeAdapter.setProperty(value, (Class)null, collaborator, (String)"x");
```

So now the question is why GrEclipse creates different byte code on different platforms and whether this is an actual GrEclipse problem as such or maybe the result of certain Groovy calls, i.e. in that case Groovy 2.5.x itself (tested on several versions up to 2.5.16)  is the root cause.

I hope that my initial analysis is deserving of an answer this time.

**Comment by kriegaex** [comment]
FYI, I also compared the decompiled classes for the other two files from the diff screenshot above, and the differences are similar:

---

`PersonBuilder` on Windows/MacOS:

```groovy
  public PersonBuilder withAge(int age) {
    CallSite[] var2 = $getCallSiteArray();
    ScriptBytecodeAdapter.setGroovyObjectProperty(age, PersonBuilder.class, this.person, (String)"age");
    return this;
  }

  public PersonBuilder withName(String name) {
    CallSite[] var2 = $getCallSiteArray();
    ScriptBytecodeAdapter.setGroovyObjectProperty(name, PersonBuilder.class, this.person, (String)"name");
    return this;
  }

  public PersonBuilder withHair(String hair) {
    CallSite[] var2 = $getCallSiteArray();
    ScriptBytecodeAdapter.setGroovyObjectProperty(hair, PersonBuilder.class, this.person, (String)"hair");
    return this;
  }
```

`PersonBuilder` on Linux:

```groovy
  public PersonBuilder withAge(int age) {
    CallSite[] var2 = $getCallSiteArray();
    ScriptBytecodeAdapter.setProperty(age, (Class)null, this.person, (String)"age");
    return this;
  }

  public PersonBuilder withName(String name) {
    CallSite[] var2 = $getCallSiteArray();
    ScriptBytecodeAdapter.setProperty(name, (Class)null, this.person, (String)"name");
    return this;
  }

  public PersonBuilder withHair(String hair) {
    CallSite[] var2 = $getCallSiteArray();
    ScriptBytecodeAdapter.setProperty(hair, (Class)null, this.person, (String)"hair");
    return this;
  }
```

---

`SetupOnceExtension` on Windows/MacOS:

```groovy
  public void visitFeatureAnnotation(SetupOnce annotation, FeatureInfo feature) {
    CallSite[] var3 = $getCallSiteArray();
    if (!DefaultTypeTransformation.booleanUnbox(this.interceptor)) {
      Object var4 = var3[0].callConstructor(SetupOnceMethodInterceptor.class);
      this.interceptor = (SetupOnceMethodInterceptor)ScriptBytecodeAdapter.castToType(var4, SetupOnceMethodInterceptor.class);
      var3[1].call(var3[2].callGetProperty(feature), this.interceptor);
    }

    boolean var5 = false;
    var3[3].call(var3[4].callGroovyObjectGetProperty(this.interceptor), var3[5].callGetProperty(feature), var5);
  }
```

`SetupOnceExtension` on Linux:

```groovy
  public void visitFeatureAnnotation(SetupOnce annotation, FeatureInfo feature) {
    CallSite[] var3 = $getCallSiteArray();
    if (!DefaultTypeTransformation.booleanUnbox(this.interceptor)) {
      Object var4 = var3[0].callConstructor(SetupOnceMethodInterceptor.class);
      this.interceptor = (SetupOnceMethodInterceptor)ScriptBytecodeAdapter.castToType(var4, SetupOnceMethodInterceptor.class);
      var3[1].call(var3[2].callGetProperty(feature), this.interceptor);
    }

    boolean var5 = false;
    var3[3].call(var3[4].callGetProperty(this.interceptor), var3[5].callGetProperty(feature), var5);
  }
```

**Comment by eric-milles** [comment]
The decision between `setGroovyObjectProperty` and `setProperty` is made here in `AsmClassGenerator#visitPropertyExpression`: https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy25/src/org/codehaus/groovy/classgen/AsmClassGenerator.java#L1230

It depends on the type of your object expression -- "collaborator" in your first example -- which is determined by `TypeChooser` in the GROOVY-9195, GROOVY-9288 patch: https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy25/src/org/codehaus/groovy/classgen/AsmClassGenerator.java#L1300

`ClassNode#isDerivedFromGroovyObject` is pretty simple: https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy25/src/org/codehaus/groovy/ast/ClassNode.java#L1021

But if your input type is good -- came from `TypeChooser` -- there is one other item that may come into play.  If the type was determined to have an inconsistent hierarchy, then `getInterfaces()` will just return an empty array: https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy25/src/org/codehaus/groovy/ast/ClassNode.java#L432

You can remote debug your compiler process and check for the object expression type in `AsmClassGenerator#isGroovyObject` and if it is as you would expect, you can check the response from `ClassNode#isDerivedFromGroovyObject`.

**Comment by kriegaex** [comment]
Thanks for your insights, but actually I do not understand most of it. I am just a user raising a bug, and I prepared a reproducible example for you. Even if I knew how to remotely debug into a build process on GitHub (if that is even permitted, which I strongly doubt), I would not know what to look for and how to interpret the findings. Therefore, I am asking you as a committer to look into the issue.

For me the question boils down to the same question I raised before: Under which circumstances can it happen that it consistently works as expected in two OS platforms, but not in the other one (Linux), l of that consistently across JDK versions? I was naively thinking that Groovy compilation was platform-independent and deterministic. I still believe that it is deterministic, but definitely not OS-independent. If you answer this question, then I think you also know how to fix the problem.

**Comment by eric-milles** [comment]
One thing you can do to probe the state of the compiler without remote debugging is to use `ASTTest`, like this:
```groovy
class UnderTest {
  @groovy.transform.ASTTest(phase=org.codehaus.groovy.control.CompilePhase.CLASS_GENERATION, value={
    def expr = node.code.statements[0].expression
    def type = expr.leftExpression.objectExpression.type
    System.err.println(type.isDerivedFromGroovyObject())
  })
  void call(Collaborator collaborator, String value) {
    collaborator.x = value
  }
}
```

**Comment by kriegaex** [comment]
Actually, I am grateful on the one hand that you seem to intend to teach me something, but at the same time also confused because you are not investigating this on your own. Usually this kind of Q/A game in played if the creator of an issue does **not** provide a complete, reproducible example. Usually, maintainers complain about that. OTOH, they are very happy if they can work based on facts rather than on many iterations of Q/A. You however spend much more of your own and my time, playing Q/A ping-pong, than necessary. I think if you would have investigated this by yourself, you would have pinpointed the root cause after a few minutes, given your far superior knowledge of Groovy as a programming language and especially deep knowledge of the tool code bases (Groovy and GrEclipse) we are dealing with here. I cannot be more than some kind of remote-controlled puppet, executing your commands, always feeling inadequate while doing so.

Anyway, I gave it a spin in commit https://github.com/kriegaex/GebSpockSamples/commit/a679b0abac1d9ac136a9eddc0b270a308c7ad25e.  If you look at the [build logs](https://github.com/kriegaex/GebSpockSamples/actions/runs/2016888141), you see that each build (Windows, MacOS, Linux) prints exactly 258x (really!):

```text
CLASS_GENERATION: type.isDerivedFromGroovyObject() = true
```

Actually, I would have expected that on Linux, where the test fails, it would print `false`, but as a matter of fact it prints the same on all platforms. Go figure...

Is there anything else you wish me to do for you, or would it be OK if you would cast your expert gaze upon this problem?

**Comment by eric-milles** [comment]
Sorry if it seems like a lot of back-and-forth.  I'm trying to provide information that keeps the investigation moving forward.  Please understand that my time on this project as well as core Groovy is 100% unpaid and voluntary.

Sometimes issues like these come up and it requires a lot of time up front to pinpoint the root cause.  The reproducible example you have is not easy to work with -- typically it would be in the form of a small script or a few source files.  A large project that must be run on a remote system is cumbersome.

I appreciate the amount of information you have collected so far.  That has narrowed the issue down to method selection.  And if the `isDerivedFromGroovyObject()` info is an accurate picture of what `AsmClassGenerator` sees, the investigation can proceed into the `setGroovyObjectProperty` adapter.  If we are able to figure this one out, we will probably look back and think that the cause was so obvious.  But as you can see, it takes a lot to get there.

**Comment by kriegaex** [comment]
Did you even try to work with my example? If you, you did not mention it. I totally disagree that it is cumbersome to work with. You clone a relatively small repo, switch to the branch I created especially for you and run the same command you see in the GitHub workflow file. If you fork (one click), you can even commit and run builds on GitHub by yourself. If you happen to use Linux, maybe you can even reproduce it locally. Otherwise, then there is still GitHub. I am not a Linux user, I am working on Windows. Why do you care about the other tests in the repo? Just run the one that makes problems, ignore the others. The build is still fast enough. If it is too slow, you can delete all other tests in your fork, no problem.

As for you working for free, I was assuming so. I do the same in other OSS projects. But I know from my own experience than in 95% of all cases, I am faster and more time-efficient if I investigate problems by myself than by reading or writing lots of messages. I only do the latter if I have no direct access to the reproducer. But OK, if you disagree, I will of course collaborate further and do what is in my power to support your analysis.

**Comment by eric-milles** [comment]
> prints exactly 258x (really!)

There is a bug where `ASTTest` is run for each source unit in the compilation unit.  It has been fixed to only run for the enclosing source unit.  [GROOVY-9757](https://issues.apache.org/jira/browse/GROOVY-9757)

Yes, I have looked at your project and loaded it into Eclipse.  I have tried to see if `setHasInconsistentHierarchy(boolean)` is called during compilation or if `isDerivedFromGroovyObject()` is false for any circumstances.  I have provided details on where the choice between `setProperty` and `setGroovyObjectProperty` is made and I have inspected those paths for anything that looks like it might be subject to OS variation.

I don't see anything under `setGroovyObjectProperty` that looks like it could end up writing out a `setProperty` call, unless the array within `MethodCallerMultiAdapter` is different or if the `CallSiteWriter` has been altered.  The code does fallback to `setProperty` if `isThisOrSuperInStaticContext(objectExpression)` evaluates to true, but I think that is very unlikely for an object expression like "collaborator" which should be a simple `VariableExpression`.

**Comment by eric-milles** [comment]
The type of "collaborator" that is tested against `GroovyObject` comes from `TypeChooser`, which is not easy to get at through `ASTTest`.  But the logic we are looking at is:
```groovy
    private boolean isGroovyObject(Expression objectExpression) {
        /* GRECLIPSE edit -- GROOVY-9195, GROOVY-9288, et al.
        return ExpressionUtils.isThisExpression(objectExpression) || objectExpression.getType().isDerivedFromGroovyObject() && !(objectExpression instanceof ClassExpression);
        */
        if (ExpressionUtils.isThisExpression(objectExpression)) return true;
        if (objectExpression instanceof ClassExpression) return false;

        ClassNode objectExpressionType = controller.getTypeChooser().resolveType(objectExpression, controller.getClassNode());
        if (objectExpressionType.equals(ClassHelper.OBJECT_TYPE)) objectExpressionType = objectExpression.getType();
        return objectExpressionType.isDerivedFromGroovyObject();
        // GRECLIPSE end
    }
```

So if `objectExpression` is a `ClassExpression` then `setProperty` would be used.  I don't thick this is the case, but you can confirm by dumping `expr.leftExpression.objectExpression` in the ast test body.  The typical path through `StatementMetaTypeChooser` will return `objectExpressionType.originType` which is close to what I had you check in the ast test body.  You can change to dump that out as well.

```groovy
class UnderTest {
  @groovy.transform.ASTTest(phase=org.codehaus.groovy.control.CompilePhase.CLASS_GENERATION, value={
    def expr = node.code.statements[0].expression
    System.err.println(expr.leftExpression.objectExpression)
    System.err.println(expr.leftExpression.objectExpression.type)
    System.err.println(expr.leftExpression.objectExpression.originType)
    System.err.println(objectExpression.originType.isDerivedFromGroovyObject())
    System.err.println(objectExpression.getNodeMetaData()) // just for good measure
  })
  void call(Collaborator collaborator, String value) {
    collaborator.x = value
  }
}
```

**Comment by kriegaex** [comment]
Windows (passing):

```text
org.codehaus.groovy.ast.expr.VariableExpression@17442f[variable: collaborator type: de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator]
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
true
[:]
```

Linux (failing):

```text
org.codehaus.groovy.ast.expr.VariableExpression@17442f[variable: collaborator type: de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator]
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
true
[:]
```

Looks absolutely identical to me. See [build result](https://github.com/kriegaex/GebSpockSamples/actions/runs/2017508890).

**Comment by eric-milles** [comment]
Can you switch to `groovy-eclipse-batch` 2.5.16-01?  I don't think it will make a difference, but then it will match up with the code that I'm inspecting.

You can also change `CLASS_GENERATION` to `INSTRUCTION_SELECTION` to capture that state before `AsmClassGenerator` runs.

Also for sanity checking, you can print this out as well: `org.codehaus.groovy.classgen.AsmClassGenerator.@setGroovyObjectProperty.@methods*.name`

**Comment by kriegaex** [comment]
Which time zone are you in? I am in GMT+7, it is ~00.30 here. I might not respond anymore tonight, unless I read some more.

See [this build](https://github.com/kriegaex/GebSpockSamples/actions/runs/2017705169).

Windows (passing):

```text
>> INSTRUCTION_SELECTION ----------
[setGroovyObjectProperty, setGroovyObjectPropertySafe, setGroovyObjectPropertySpreadSafe]
org.codehaus.groovy.ast.expr.VariableExpression@29210815[variable: collaborator type: de.scrum_master.stackoverflow.q[61](https://github.com/kriegaex/GebSpockSamples/runs/5631756655?check_suite_focus=true#step:6:61)0[65](https://github.com/kriegaex/GebSpockSamples/runs/5631756655?check_suite_focus=true#step:6:65)342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator]
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
false
[:]
<< INSTRUCTION_SELECTION ----------
```

Linux (failing):

```text
[setGroovyObjectProperty, setGroovyObjectPropertySafe, setGroovyObjectPropertySpreadSafe]
org.codehaus.groovy.ast.expr.VariableExpression@4ea7068b[variable: collaborator type: de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator]
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
false
[:]
```

Lines number 2 look somewhat different. How relevant that is, I guess you know better than I.

**Comment by eric-milles** [comment]
Okay, so the integrity of `setGroovyObjectProperty` looks good.  So it must be skipping due to `isGroovyObject` returning false or `isThisOrSuperInStaticContext` returning true.

I am in US central time zone.  It is about lunch time for me.  Can you give me a few more minutes?  I have been reading through this stuff all morning trying to see where it might make a decision one way or another.

**Comment by kriegaex** [comment]
**Update:** The difference in line 2 was just a copy & paste artifact. I updated it. Now it looks the same again.

**Comment by eric-milles** [comment]
So in your log, the `isDerivedFromGroovyObject()` shows false the first time and true thereafter.  That is what we need to probe.

**Comment by kriegaex** [comment]
> I don't see anything under `setGroovyObjectProperty` that looks like it could end up writing out a `setProperty` call, unless the array within `MethodCallerMultiAdapter` is different or if the `CallSiteWriter` has been altered. The code does fallback to `setProperty` if `isThisOrSuperInStaticContext(objectExpression)` evaluates to true, but I think that is very unlikely for an object expression like "collaborator" which should be a simple `VariableExpression`.

Remember what Sherlock Holmes used to say about unlikely possibilities?

> "When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth."

😉

**Comment by eric-milles** [comment]
This is from your #118 run:
```
WARNING: All illegal access operations will be denied in a future release
>> INSTRUCTION_SELECTION ----------
[setGroovyObjectProperty, setGroovyObjectPropertySafe, setGroovyObjectPropertySpreadSafe]
org.codehaus.groovy.ast.expr.VariableExpression@4ea7068b[variable: collaborator type: de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator]
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
de.scrum_master.stackoverflow.q61065342.Collaborator -> de.scrum_master.stackoverflow.q61065342.Collaborator
false
[:]
<< INSTRUCTION_SELECTION ----------
```

**Comment by kriegaex** [comment]
> This is from your #118 run on linux:

Yes, exactly like I quoted it above. On Windows it is the same.

**Comment by eric-milles** [comment]
There is a small window of time where `Collaborator` is not returning any interfaces for some reason.

**Comment by kriegaex** [comment]
> Can you print `expr.leftExpression.objectExpresison.originType.interfaces.toString()`? You can drop most of the other stuff.

Windows (passing):

```text
2022-03-21T17:57:49.2350452Z >> INSTRUCTION_SELECTION ----------
2022-03-21T17:57:49.2350837Z []
2022-03-21T17:57:49.2351273Z << INSTRUCTION_SELECTION ----------
2022-03-21T17:57:49.2352108Z >> INSTRUCTION_SELECTION ----------
2022-03-21T17:57:49.2353690Z [groovy.lang.GroovyObject]
2022-03-21T17:57:49.2354187Z << INSTRUCTION_SELECTION ----------
2022-03-21T17:57:49.2354563Z >> INSTRUCTION_SELECTION ----------
2022-03-21T17:57:49.2354931Z [groovy.lang.GroovyObject]
2022-03-21T17:57:49.2355361Z << INSTRUCTION_SELECTION ----------
...
```

Linux (failing):

```text
2022-03-21T17:57:02.9528599Z >> INSTRUCTION_SELECTION ----------
2022-03-21T17:57:02.9528908Z []
2022-03-21T17:57:02.9529208Z << INSTRUCTION_SELECTION ----------
2022-03-21T17:57:02.9529485Z >> INSTRUCTION_SELECTION ----------
2022-03-21T17:57:02.9529730Z [groovy.lang.GroovyObject]
2022-03-21T17:57:02.9530027Z << INSTRUCTION_SELECTION ----------
2022-03-21T17:57:02.9530386Z >> INSTRUCTION_SELECTION ----------
2022-03-21T17:57:02.9530683Z [groovy.lang.GroovyObject]
2022-03-21T17:57:02.9531037Z << INSTRUCTION_SELECTION ----------
...
```

Looks the same again to me. Interesting is the `[]` the first of the 258 or so calls, but also identical.

**Comment by eric-milles** [comment]
It's the same, but it is timing based.  That could easily explain an OS difference.  If Linux could get to classgen before the thread had its interfaces reference updated, it could get a different answer for `isGroovyObject`.

**Comment by kriegaex** [comment]
I do not know anything about Groovy AST and do not even remember in which phase Spock does its thing. Do you think it might be that Spock is involved? But actually, not the Spock tests are any different, but the classes under test, so Spock should not be involved there. But I am a noob there, like I said.

**Comment by kriegaex** [comment]
> It's the same, but it is timing based. That could easily explain an OS difference. If Linux could get to classgen before the thread had its interfaces reference updated, it could get a different answer for `isGroovyObject`.

Ugh, this stuff is concurrent? That could caus all kinds of problems like race conditions.

**Comment by eric-milles** [comment]
I have enough to investigate to see why the interfaces are this way.

**Comment by eric-milles** [comment]
It is `Verifier` that adds `GroovyObject` if not present.  This happens at the start of the classgen compile phase.

**Comment by eric-milles** [comment]
The "classgen" steps -- `OptimizerVisitor`, `Veifier`, `LabelVerifier`, `InstanceOfVerifier`, `ClassCompletionVerifier`, 
`ExtendedVerifier` and `AsmClassGenerator` are run as a group on a single source unit.  So if `UnderTest` is processed before `Collaborator` the `GroovyObject` test will fail.

You can try modifying `Collaborator` like this to see if it comes down to order of operations:
```groovy
class Collaborator implements GroovyObject {
  String x
}
```

**Comment by kriegaex** [comment]
With `Collaborator implements GroovyObject`, the [build](https://github.com/kriegaex/GebSpockSamples/actions/runs/2019571978) passes on Linux, too. You seem to have identified the root cause of the problem correctly. Thanks for your endurance.

Having seen your commit on the main branch, a little question: I am currently using GrEclipse 3.7.1 and GrEclipse Batch 2.5.16-02 in this example project. Will this change be present in a future 2.5.16-02, too?

**Comment by kriegaex** [comment]
May I ask again after two days? I would like to contribute re-testing feedback in order to get this off the table. Of course, you do not need my thumbs-up in order to put that into the next release, but we both put a bit of work and time into this issue. Let's finish it in style, shall we?

**Comment by eric-milles** [comment]
Source control was migrated over the weekend, so that has been taking my time.  Also, I wanted to get the issue fixed as best I could in the core project: https://github.com/apache/groovy/pull/1706

You can build a batch compiler using these steps: https://github.com/groovy/groovy-eclipse/wiki/Building-Maven-Batch-Compiler

I can provide you with jars if I had a way to send them.  I'm not sure if I want to create snapshot jars on the artifactory.

**Comment by kriegaex** [comment]
I understand how much time an SCM migration can eat up. No problem, as long as you don't mind me pinging you if I get no response.

Concerning the snapshot, I thought that you somehow automatically deploy snapshots for testing like other important Apache OSS projects, say for example Maven Surefire. You do not need to send anything to me or make a big fuss to deploy something, if it is more than a matter of a shell command or mouse click.

Thanks also for pointing me to the upstream Groovy issue. Please do make sure that this will be back-ported to 2.5.x, because this is where I found it.

**Comment by eric-milles** [comment]
batch compiler 2.5.16-02 is now available

**Comment by kriegaex** [comment]
Thank you so much, I am going to test that in my project.

Where do I find the source repository, branch and tag for that release? I actually have no idea where the code is kept. Neither here nor in Groovy Core there seem to be any 2.5 maintenance branches or tags. I did find https://github.com/groovy/groovy-eclipse/tree/master/base/org.codehaus.groovy25 and saw the corresponding commit there, but no reference to `<artifactId>groovy-eclipse-batch</artifactId>` in any POM here. Somehow, it is hard to figure out for me how the components Groovy Core, Groovy Eclipse and Groovy Eclipse Batch Compiler are all connected.

**Comment by kriegaex** [comment]
The problem no longer occurs during my Linux CI builds → re-test successful. Thank you for releasing a bugfix version.

**Comment by eric-milles** [comment]
`groovy-eclipse-batch` is a fat jar that is assembled from `org.codehaus.groovy25`, `org.eclipse.jdt.core`, etc.  There is a description of the build setup here:  https://github.com/groovy/groovy-eclipse/wiki/Building-Maven-Batch-Compiler

**Comment by kriegaex** [comment]
Very instructive, thank you. I understand much better than before now. 👏

**Comment by tomaszburdka-oc** [comment]
I've opened new issue here: https://github.com/groovy/groovy-eclipse/issues/1553
