### ISSUE TITLE
Invalid warning about redundant specification of type arguments with anonymous inner classes

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1358]
Ensure the following option is set to warning or above:
Right click on project => Properties | Java Compiler | Errors/Warnings | Enable project specific settings | Redundant type arguments (1.7 or higher), under Generic types.

Consider this:

```groovy
package testdiamond

class TestDiamond {
	ArrayList<String> list = new ArrayList<String>() {
		
	}
}
```

Greclipse compiler shows a warning on `new ArrayList<String>` saying:

```
Redundant specification of type arguments <String>
```

However, if you change that line to:

```groovy
ArrayList<String> list = new ArrayList<>() {
```

this of course produces an error, because:

```
Cannot use diamond <> with anonymous inner classes
```

**Comment by eric-milles** [comment]
Can you retest with latest?  I think I have it setup right but no longer get the warning:
![image](https://user-images.githubusercontent.com/18193802/198832740-882502b7-bbd5-4774-9991-e9babca22676.png)

**Comment by mauromol** [comment]
Hmmm... it's strange. I don't get this error for the above simple case any more, but (at least in 4.8.0.v202210271251-e2206) I still get it on another project of mine... Trying to understand what's different...

**Comment by mauromol** [comment]
I was not able to reproduce with a simple test case. But there's a class in which I still have this problem, see here:

![immagine](https://user-images.githubusercontent.com/1742494/201631248-31014c63-7e28-4004-be5b-ba4015ea4526.png)

The original problem I see is the second red row on the right, but, as you can see, even the simple `ArrayList` extension produces the error. I don't know why this happens here but not on the simple test-case project. The option setting related to the redundant type argument warning is the same. Tried to add `@CompileStatic` to the simple test case but didn't help to reproduce... Any idea?

**Comment by mauromol** [comment]
Ok, I found the way to reproduce. The problem DOES NOT show up if the project uses a JavaSE-1.8 execution environment, but DOES show up if it uses a JavaSE-11 execution environment.
So, try to switch your project to Java 11 and see. I get it now even with the simple class above.
