### ISSUE TITLE
Compilation error in Greclipse (not with groovyc/Gradle)

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1360]
Using Greclipse 4.6.0.v202205032224-e2112, with Groovy 2.5 compiler (2.5.16 on build path).

Consider these Java classes/interfaces:

```java
package testgen;
public interface MyInterface {
}

package testgen;
public class MyClass<T> {
}

package testgen;
import java.util.List;
public class MyClassE<T extends MyInterface> extends MyClass<T> {
    MyClassE(){}
    MyClassE(List<T> list) {
    }
}
```

And these Groovy classes:

```groovy
package testgen
class MyBean implements MyInterface {
}
```

and:

```groovy
package testgen
import groovy.transform.CompileStatic

@CompileStatic
class GClass {
   
    MyClassE<MyBean> foo
    
    void bar() {
	foo = new MyClassE<>(new ArrayList<>())
    }
}
```

The assignment is marked with an error in Greclipse:

```
Groovy:[Static type checking] - Incompatible generic argument types. Cannot assign testgen.MyClassE<testgen.
 MyInterface> to: testgen.MyClassE<testgen.MyBean>
```

This error is not given when compiling with Gradle/groovyc.
Also, if I replace that assignment with:

```groovy
foo = new MyClassE<>()
```

no error is given by Greclipse as well. So it seems like the combination with the list is fooling Greclipse.

Workaround:
```groovy
foo = new MyClassE<MyBean>(new ArrayList<>())
```

**Comment by eric-milles** [comment]
This is related to the GROOVY-10086 JIRA ticket.  The target for `new ArrayList<>()` is `List<MyInterface>`.  The inference engine does not look beyond the immediate target and see an outer target `MyClassE<MyBean> foo = new MyClassE<>(new ArrayList<>())`.

You can do `foo = new MyClassE<MyBean>(new ArrayList<>())` or `foo = new MyClassE<>(new ArrayList<MyBean>())` or `new MyClassE<>([])` or probably `foo = new MyClassE<>(new ArrayList())`.

**Comment by mauromol** [comment]
I can hardly understand how GROOVY-10086 can be related to this problem, which seems to be fixed in 4.0. Here the compiler should not give an error, so groovyc 2.5 is correct indeed, while Greclipse is not. The generic type for `ArrayList<>` should be inferred to be `ArrayList<MyBean>`, with `MyBean` extending `MyInterface`. An equivalent Java class compiles fine with both Eclipse and Gradle/javac:

```
package testgen;

import java.util.ArrayList;

class JClass {
    
    private MyClassE<MyBean> foo;
    
    public void bar() {
	foo = new MyClassE<>(new ArrayList<>());
    }
}
```

**Comment by mauromol** [comment]
However, this is the opposite case: groovyc behaves correctly and compiles, ecj does not...
Do you mean that groovyc 4.0 also fails to compile the above code?

**Comment by eric-milles** [comment]
That's right, Groovy 4 will produce this same error.  This should probably be opened as a Groovy ticket and when fixed can be backported here as well.

**Comment by eric-milles** [comment]
https://issues.apache.org/jira/browse/GROOVY-10624
