### ISSUE TITLE
Eclipse does not see inherited trait properties

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1361]
In a scenario similar to #1113, Eclipse cannot find properties that are declared on a supertrait, causing inference failure and spurious compilation errors that go away with groovyc.

```
trait Super {
  String prop
}

trait Sub extends Super {
}

class Foo implements Sub {
  // Eclipse doesn't see `prop`
}
```

**Comment by eric-milles** [comment]
For my reference: https://docs.groovy-lang.org/latest/html/documentation/#_extending_traits
