### ISSUE TITLE
Probably missing support for Eclipse 4.24

### ISSUE THREAD

**Issue by 4javier** [groovy/groovy-eclipse#1375]
> java.lang.NoClassDefFoundError: org/codehaus/groovy/eclipse/refactoring/formatter/GroovyIndentationService

Trying to open .groovy file on 
```
SpringToolSuite
Version: 4.15.1.RELEASE
Build Id: 202206171354
```
based on 
```
Eclipse Platform
Version: 4.24.0.v20220607-0700
Build id: I20220607-0700
```
with
```
Eclipse Java Development Tools
Version: 3.18.1200.v20220607-0700
Build id: I20220607-0700
```
Usual missing patch?

**Comment by eric-milles** [comment]
Not sure what update site you are pulling from, but the Eclipse 4.24 site (https://dist.springsource.org/snapshot/GRECLIPSE/e4.24) patches JDT Core 3.18.1200.v20220607-0700.

**Comment by 4javier** [comment]
You're right. It looks like the patch is correctly applied.
![immagine](https://user-images.githubusercontent.com/459381/175351497-5bec91b7-3ad4-4fa4-9fe5-94613a1676b3.png)
And now that I think about it, I'm sure I had already rebooted IDE after last update. 
I don't know why all of sudden this problem arised, and now I'm blocked.
I use a couple of groovy files to setup DB by liquibase for some integration tests, and now it fails not founding them and printing that error when I try to open them with dedicated editor.
Obviously files are there.

**Comment by eric-milles** [comment]
Eclipse 4.24 is 2022-06.  You have 2022-03 (Eclipse 4.23) Groovy Development Tools.

**Comment by 4javier** [comment]
Ouch.
Totally missed that.
Sorry for wasting your time.
