### ISSUE TITLE
Type interferences seems still buggy

### ISSUE THREAD

**Issue by efc-mw** [groovy/groovy-eclipse#1384]
I verified the progress with Groovy 4.0.4 of my compile problem, the groovy editor still won't accept the following java functional syntax:
In java this is fine:
```
	public void works() {
		daoV_search_doc_key.selBy(s-> s.where(V_search_doc_keySql.ISDELETED, isEqualTo(0)));
	}

```
In Groovy, this is wrong:
```
	public void works() {
		daoV_search_doc_key.selBy(s-> s.where(V_search_doc_keySql.ISDELETED, isEqualTo(0)))
	}

```
A repo to reproduce:
https://github.com/EffectiveCompany/public_repo.git

**Comment by eric-milles** [comment]
In your example project, the Groovy code is still indicated as `@CompileStatic` which was not addressed by https://github.com/groovy/groovy-eclipse/issues/1364.  You will need to wait for [GROOVY-10646](https://issues.apache.org/jira/browse/GROOVY-10646) for type-checked code or switch to dynamic mode.
