### ISSUE TITLE
Compiler targetDirectory is not canonicalized

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1387]
I'm trying to obtain the target directory to write a resource (see post on users@), and while running in GRECLIPSE, the config's `targetDirectory` is set to a relative `target/test-classes`. When canonicalized or used to open a file, this produces `$ECLIPSE_HOME/target/test-classes` instead of the actual output directory. groovyc under Maven works as expected.

Related: #575

**Comment by eric-milles** [comment]
Is this when you build in the IDE or using the maven compiler adapter?

**Comment by chrylis** [comment]
This is when running from the regular IDE build (i.e., "clean project and start a build immediately").

**Comment by chrylis** [comment]
That looks like it should do it. Thanks so much, and I'll pick up the next snapshot!

**Comment by chrylis** [comment]
I updated to the latest snapshot, and it's working. Thanks again!
