### ISSUE TITLE
Question (maven): what is the thing with "The Groovy dependency version should match the compiler version"

### ISSUE THREAD

**Issue by cstamas** [groovy/groovy-eclipse#1388]
Context: using groovy-eclipse-compiler + groovy-eclipse-batch from Maven (for mixed compilation of Java and Groovy), no Eclipse IDE involved.

The documentation page [here](https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin) contains the sentence: "The Groovy dependency version should match the compiler version". 

I am curious:
* how "strict" this needs to be done, for example Groovy 4.0.5 vs groovy-eclipse-batch 4.0.4-01 is "okay" to be used together?
* what are the reasons to tie Groovy compiler and Groovy runtime so tightly?
* what is the timeframe to have "aligned" groovy-eclipse-batch after new Groovy release happens?

TIA

**Comment by DariusX** [comment]
Similar question, but for 2.5.x
groovy-all is at 2.5.18, but the only groovy-eclipse-batch I found is [2.5.14-02](https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-eclipse-batch/2.5.14-02)

**Comment by eric-milles** [comment]
2.5.18-01?  https://groovy.jfrog.io/ui/native/plugins-release-local/org/codehaus/groovy/groovy-eclipse-batch
