### ISSUE TITLE
targetDirectory is null in Eclipse

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1394]
I recently updated GRECLIPSE to take advantage of #1387, and it was working as expected. With the latest nightly, however, I'm getting an NPE because `source.AST.unit.config.targetDirectory` is returning null during CANONICALIZATION:

```
var outDir = source.AST.unit.config.targetDirectory
```
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "outDir" is null
```

The ASTT works correctly in groovyc. I don't know of any correct reason why `targetDirectory` would be null.

Eclipse: 4.15.3.202208110744
GRECLIPSE: 4.7.0.v202209210315-e2206

**Comment by eric-milles** [comment]
I'm not aware of the historical reasons for setting target directory on the `CompilerConfiguration`, but here are the limited cases in which it gets set:
```java
        if (requestor instanceof Compiler) {
            Compiler compiler = (Compiler) requestor;
            if (compiler.requestor instanceof AbstractImageBuilder) {
                AbstractImageBuilder builder = (AbstractImageBuilder) compiler.requestor;
                if (builder.notifier != null) {
                    compilationUnit.setProgressListener(newProgressListener(builder.notifier));
                }
                if (eclipseFile != null) {
                    SourceFile sourceFile = (SourceFile) builder.fromIFile(eclipseFile);
                    if (sourceFile != null) {
                        compilationUnit.getConfiguration().setTargetDirectory(sourceFile.getOutputLocation().toFile());
                    }
                }
            } else if (compiler.requestor instanceof BatchCompilerRequestor) {
                Main main = ReflectionUtils.getPrivateField(BatchCompilerRequestor.class, "compiler", compiler.requestor);
                if (main != null && main.destinationPath != null && main.destinationPath != Main.NONE) {
                    compilationUnit.getConfiguration().setTargetDirectory(main.destinationPath);
                }
            }
        }
```

There are many reasons why a source unit might get processed through at least the first few groovy compiler phases -- just opening a file in the editor triggers several compilation unit structure requests -- but you might want to assume in your transformation that if target directory is null that the project is not being built.

**Comment by chrylis** [comment]
Hmm. Seems counterintuitive, but if that's an Expected Behavior, I'll make accommodation. (FWIW, if you're saying it's unclear why you would want to set the target directory, my ASTT is responsible for writing out a resource file; the Java annotation processor uses `Filer#createResource`. Presumably similar functionality is desired generally.)
