### ISSUE TITLE
Problem with search path for type-checking extensions

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1397]
I'm actively working on a type-checking extension, which is in the `src/main/resources` of my project. My class has `@CompileStatic(extensions = 'my/extension.groovy')`. This works correctly in the Maven CLI build and in Eclipse if I run Maven through at least `process-resources`, but using a Eclipse clean causes 

```
Groovy:Static type checking extension 'my/extension.groovy' was not found on the classpath.
```

The problem appears to be a sequencing problem regarding resource access.

**Comment by eric-milles** [comment]
Can you share at least the structure of your project?  Does eclipse recognize `src/main/resources` as a source folder?  To get UI support, it needs to be a source folder and then you probably want a groovy script filter on it to prevent compilation.  Let me know if you need help understanding how to set up those two things.

**Comment by chrylis** [comment]
It does recognize the folder as a source folder. I am not sure about the "Groovy script filter"; I was unaware of the concept until now.

**Comment by eric-milles** [comment]
Eclipse does not have the distinction of source and resource directories like Maven does.  To have resources available through classpath, they must be source folders.  Any groovy source unit in a source folder will be compiled, unless it is matched by a script filter.  The m2e project configurator should probably apply a groovy script filter for any maven resource directory that is manifested as an eclipse source folder.

**Comment by eric-milles** [comment]
I've used gradle to write script filters (see below).  I think `maven-eclipse-plugin` can do a similar thing, if you are interested in automating configuration.
```gradle
        apply plugin: 'eclipse'
        project.tasks.eclipse.doLast {
            if (!file("${project.projectDir}/.classpath").exists()) return

            file("${project.projectDir}/.settings/org.eclipse.jdt.groovy.core.prefs").with { prefs ->
                if (!prefs.exists()) {
                    append('''\
                        eclipse.preferences.version=1
                        groovy.compiler.level=40
                        groovy.script.filters=**/*.gradle,n,**/script*.groovy,y,**/*resources/**/*.groovy,y,**/benchmarks/**/*.groovy,y
                        org.codehaus.groovy.eclipse.preferences.compiler.project=true
                        '''.stripIndent()
                    )
                }
            }
```

**Comment by eric-milles** [comment]
I could look into changing the m2e project configurator to add script filters for resource directories.  I'm not sure if m2e reapplies the configurator when you update a Maven project or if you would need to re-import the project.  Thoughts?
