### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1407]
I know this issue will be very generic, but...
I'm seeing a perceivable performance degradation in latest Greclipse when working on large Groovy sources (I'm using Greclipse 4.7.0.v202209190834-e2206).
Right now I'm working with a ~3000 rows JUnit test class and:

- any content assist request takes from 2 to 5 seconds and more; if I disable non-blocking completion, it will trigger the UI freeze monitor warning or even the popup dialog that says that the Groovy content failed because it took too much time to complete; enabling non-blocking completion improves the perception a bit, but it still takes a lot of time
- saving requires almost 10 seconds, probably due to formatting action on save

Yes, I don't have a bleeding edge system (it's a 4th generation Intel Core i5 processor with 16 GB of RAM), but still the difference compared to working with Java sources is huge.

**Comment by eric-milles** [comment]
Do you know about when this started showing up -- is it 4.6.0 vs 4.7.0?  Would you be able to load up a separate install with 4.8.0 snapshot so we can compare?

For content assist, GDT needs to run type inferencing up to the element you are completing on.  So it is usually the type inferencing time that is perceived.  But there are also several completion proposal processors.  You can get a sense of the type inferencing time by opening the file in the editor and seeing how long it takes for the syntax coloration to show up.

**Comment by mauromol** [comment]
4.6.0 vs 4.7.0, hard to say, honestly. I do not work with Groovy all days, or even with the same sources, what I can say is that in the past it was not so slow, even if it has always been heavier than plain Java .

WRT time it takes to open the file: when I hit Ctrl+Shift+T, type the test class name and hit enter to open it, it takes ~10 seconds for the UI to react in some way. After this ~10 seconds, the editor opens, then it takes less than a second to show syntax coloring, at least at the beginning of the file (which is the portion shown on editor opening).

Do you think 4.8.0 snapshot may show improvements in this area?

**Comment by mauromol** [comment]
Also, I do not see a perceivable difference of time it takes to show proposals if I try content assist at the beginning of the file (around line 40) or at the end of the file (around line 2800). So perhaps the culprit is not type inferencing?

**Comment by mauromol** [comment]
For comparing, these are the event logs with Greclipse 4.8.0.v202210122100-e2206:

Opening the file:
```
      Compiler : 15:36:26 Build Structure starting for ServiceOwnerTest.groovy
AST Transforms : 15:36:28 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to ServiceOwnerTest.groovy(type: it.dcssrl.shop.cart.model.ServiceOwnerTest) in 636ms
      Compiler : 15:36:28 Event complete: 2197ms: Build structure: ServiceOwnerTest.groovy : main
      Compiler : 15:36:29 Build Structure starting for ServiceOwnerTest.groovy
AST Transforms : 15:36:31 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to ServiceOwnerTest.groovy(type: it.dcssrl.shop.cart.model.ServiceOwnerTest) in 433ms
      Compiler : 15:36:31 Event complete: 2224ms: Build structure: ServiceOwnerTest.groovy : main
AST Transforms : 15:36:32 Global transform groovy.grape.GrabAnnotationTransformation applied to ServiceOwnerTest.groovy in 1ms
AST Transforms : 15:36:32 Global transform org.codehaus.groovy.ast.builder.AstBuilderTransformation applied to ServiceOwnerTest.groovy in 1ms
AST Transforms : 15:36:33 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to ServiceOwnerTest.groovy(type: it.dcssrl.shop.cart.model.ServiceOwnerTest) in 571ms
   Code select : 15:36:33 Code select on ServiceOwnerTest.groovy at [ 461,16 ]
   Code select : 15:36:33 Event complete: 1ms: Code select: ServiceOwnerTest.groovy
   Code select : 15:36:36 Code select on ServiceOwnerTest.groovy at [ 852,0 ]
   Code select : 15:36:36 Event complete: 17ms: Code select: ServiceOwnerTest.groovy
```

Save:
```
   Code select : 15:37:19 Code select on ServiceOwnerTest.groovy at [ 1333,0 ]
   Code select : 15:37:19 Event complete: 13ms: Code select: ServiceOwnerTest.groovy
 Clean imports : 15:37:21 ServiceOwnerTest.groovy
AST Transforms : 15:37:22 Global transform groovy.grape.GrabAnnotationTransformation applied to ServiceOwnerTest.groovy in 6ms
 Clean imports : 15:37:22 {MultiTextEdit} [0,0] [undefined]
 Clean imports : 15:37:22 Event complete: 1097ms: ServiceOwnerTest.groovy
   Code select : 15:37:30 Code select on ServiceOwnerTest.groovy at [ 1333,0 ]
   Code select : 15:37:30 Event complete: 7ms: Code select: ServiceOwnerTest.groovy
AST Transforms : 15:37:30 Global transform groovy.grape.GrabAnnotationTransformation applied to ServiceOwnerTest.groovy in 1ms
AST Transforms : 15:37:31 Global transform org.codehaus.groovy.ast.builder.AstBuilderTransformation applied to ServiceOwnerTest.groovy in 1ms
AST Transforms : 15:37:32 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to ServiceOwnerTest.groovy(type: it.dcssrl.shop.cart.model.ServiceOwnerTest) in 333ms
```

Code assist:
```
   Code select : 15:38:35 Code select on ServiceOwnerTest.groovy at [ 1317,0 ]
   Code select : 15:38:35 Event complete: 9ms: Code select: ServiceOwnerTest.groovy
Content assist : 15:38:37 Starting content assist for ServiceOwnerTest.groovy
      Compiler : 15:38:37 Build Structure starting for ServiceOwnerTest.groovy
      Compiler : 15:38:37 Build Structure starting for ServiceOwnerTest.groovy
      Compiler : 15:38:37 /home/mauro/svn/DCS-SHOP-devel/shop-commons/src/test/java/it/dcssrl/shop/cart/model/ServiceOwnerTest.groovy: 54: [Static type checking] - Cannot find matching method it.dcssrl.shop.cart.model.ServiceOwner$BasicServiceOwner#return(it.dcssrl.shop.cart.model.ServiceOwner$BasicServiceOwner). Please check if the declared type is correct and if the method exists.
 @ line 54, column 3.
   		result.
     ^
AST Transforms : 15:38:38 Global transform groovy.grape.GrabAnnotationTransformation applied to ServiceOwnerTest.groovy in 1ms
AST Transforms : 15:38:38 Global transform org.codehaus.groovy.ast.builder.AstBuilderTransformation applied to ServiceOwnerTest.groovy in 1ms
AST Transforms : 15:38:38 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to ServiceOwnerTest.groovy(type: it.dcssrl.shop.cart.model.ServiceOwnerTest) in 322ms
      Compiler : 15:38:38 Event complete: 1039ms: Build structure: ServiceOwnerTest.groovy : ForkJoinPool.commonPool-worker-2
      Compiler : 15:38:38 /home/mauro/svn/DCS-SHOP-devel/shop-commons/src/test/java/it/dcssrl/shop/cart/model/ServiceOwnerTest.groovy: 54: [Static type checking] - Cannot find matching method it.dcssrl.shop.cart.model.ServiceOwner$BasicServiceOwner#return(it.dcssrl.shop.cart.model.ServiceOwner$BasicServiceOwner). Please check if the declared type is correct and if the method exists.
 @ line 54, column 3.
   		result.
     ^
AST Transforms : 15:38:38 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to ServiceOwnerTest.groovy(type: it.dcssrl.shop.cart.model.ServiceOwnerTest) in 459ms
      Compiler : 15:38:38 Event complete: 1423ms: Build structure: ServiceOwnerTest.groovy : org.eclipse.jdt.internal.ui.text.JavaReconciler
   Code select : 15:38:38 Code select on ServiceOwnerTest.groovy at [ 1324,0 ]
   Code select : 15:38:39 Event complete: 134ms: Code select: ServiceOwnerTest.groovy
AST Transforms : 15:38:39 Global transform groovy.grape.GrabAnnotationTransformation applied to ServiceOwnerTest.groovy in 2ms
AST Transforms : 15:38:39 Global transform org.codehaus.groovy.ast.builder.AstBuilderTransformation applied to ServiceOwnerTest.groovy in 14ms
           DSL : 15:38:39 Getting DSL proposals for result.
           DSL : 15:38:39 Event complete: 1ms: DSL proposals
Content assist : 15:38:40 Event complete: 3075ms: Content assist for ServiceOwnerTest.groovy
```

**Comment by eric-milles** [comment]
This is a typical file (~800 lines) for me:
```
      Compiler : 12:29:07 Build Structure starting for GrapeIvy.groovy
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.AutoFinalASTTransformation applied to GrapeIvy.groovy(type: groovy.grape.GrapeIvy) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.EqualsAndHashCodeASTTransformation applied to GrapeIvy.groovy(type: groovy.grape.IvyGrabRecord) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(type: groovy.grape.GrapeIvy) in 39ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: processGrabArgs) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: getConfList) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: addURL) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(type: groovy.grape.IvyGrabRecord) in 2ms
      Compiler : 12:29:07 Event complete: 143ms: Build structure: GrapeIvy.groovy : main
      Compiler : 12:29:07 Build Structure starting for GrapeIvy.groovy
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.AutoFinalASTTransformation applied to GrapeIvy.groovy(type: groovy.grape.GrapeIvy) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.EqualsAndHashCodeASTTransformation applied to GrapeIvy.groovy(type: groovy.grape.IvyGrabRecord) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(type: groovy.grape.GrapeIvy) in 30ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: processGrabArgs) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: getConfList) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: addURL) in 0ms
AST Transforms : 12:29:07 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(type: groovy.grape.IvyGrabRecord) in 1ms
      Compiler : 12:29:07 Event complete: 126ms: Build structure: GrapeIvy.groovy : main
AST Transforms : 12:29:07 Global transform groovy.grape.GrabAnnotationTransformation applied to GrapeIvy.groovy in 0ms
AST Transforms : 12:29:08 Local transform org.codehaus.groovy.transform.AutoFinalASTTransformation applied to GrapeIvy.groovy(type: groovy.grape.GrapeIvy) in 0ms
AST Transforms : 12:29:08 Local transform org.codehaus.groovy.transform.EqualsAndHashCodeASTTransformation applied to GrapeIvy.groovy(type: groovy.grape.IvyGrabRecord) in 0ms
AST Transforms : 12:29:08 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(type: groovy.grape.GrapeIvy) in 31ms
AST Transforms : 12:29:08 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: processGrabArgs) in 0ms
AST Transforms : 12:29:08 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: getConfList) in 0ms
AST Transforms : 12:29:08 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(method: addURL) in 0ms
AST Transforms : 12:29:08 Local transform org.codehaus.groovy.transform.sc.StaticCompileTransformation applied to GrapeIvy.groovy(type: groovy.grape.IvyGrabRecord) in 1ms
```

A lot of it comes down to the complexity of the source -- yours is a junit, so I'm assuming its fairly flat -- the number of source references and the size of the project or project tree.  Can you share anything about your test source or the project structure?

**Comment by eric-milles** [comment]
Could you try capturing opening the file and content assist using jvisualvm or some other sampler?  It's hard to look into this one without a good lead.

**Comment by mauromol** [comment]
I can try something. Suggested filters to avoid sampling anything? org.codehaus.** and/or org.eclipse.**, or something more?

**Comment by eric-milles** [comment]
I think `org.apache.*`, `org.codehaus.*`, `org.eclipse.*` and `org.osgi.*` would cover nicely.

**Comment by mauromol** [comment]
It was rather challenging to produce these profiling snapshots, especially the save one which took ages after which often caused the IDE to freeze (and all the collected data to be lost...).
Anyway, I got it at last. I had to reduce the scope: I chose `org.codehaus.groovy.**` as "profile classes" and `org.eclipse.**` as "include outgoing calls" in Visual VM. Trying to include all the requested classes made Visual VM complain because too many classes would need to be instrumented.

I hope you can obtain useful information from these.
The open-type.nps file contains info when opening the mentioned test case class with Ctrl+Shift+T: collection starts from when I hit Ctrl+Shift+T up to the point I select the class and wait for the editor to appear and for syntax coloring to be completed.
The save.nps contains info when hitting Ctrl+S and collection was terminated when the IDE gave me back control of the blinking cursor in the editor.
cede-assist.nps file contains info collected just before invoking code assist: I have code assist auto activation enabled, so I quickly types a local parameter name followed by "." and waited for the completion proposals to finally show up in the code assist popup (I have async completion enabled).

[profiling.zip](https://github.com/groovy/groovy-eclipse/files/9864348/profiling.zip)

**Comment by eric-milles** [comment]
You can use the _Sampler_ instead of the _Profiler_ to identify hot spots.  It would be helpful if you could send the source file, even if you need to obscure all the names.

So it looks like reconcile is taking about 24 seconds.  Lots of time is spent visiting static method calls.  I'm guessing you have a lot of `assertEquals` and the like in the file.  I think I can see some savings under `StaticTypeCheckingVisitor#visitStaticMethodCallExpression` -- I'll just need to test that there is no functional difference.

Another thing you could do is disable static compilation for this class and compare the time to open.  It will still need to parse and resolve, but I think a lot of time is spent type-checking.

**Comment by mauromol** [comment]
Yes, I have a lot of `assertEquals`/`assertTrue` and alike, because this is a JUnit4 unit test. I may send you the unit test source, but will it be sufficient? Because without the classes under test it won't compile it. Do you need also those classes? (hoping they won't pull too many other ones)?

Removing `@CompileStatic` perhaps brings a little improvement in opening and code assist. Saving is still very slow.

**Comment by eric-milles** [comment]
For starters, just the test source would help me understand the structure that must be parsed and visited.

Could you get the latest snapshot and send capture for opening file with and without @CS?

**Comment by mauromol** [comment]
Here is the source. It apparently contains personal data, but they are all fictitious data.
[ServiceOwnerTest.groovy.zip](https://github.com/groovy/groovy-eclipse/files/9869760/ServiceOwnerTest.groovy.zip)

Do you need a profiler snapshot or a sampler snapshot? I usually find the sampler output too coarse-grained, but if you think it's enough I will use that instead.

**Comment by eric-milles** [comment]
If you can gather profiler without trouble, that would compare against what I have nicely.  I find the sampler data easier to capture and look for aggregated hot spots, so if you could get that too.  Just need for the open file case.

**Comment by eric-milles** [comment]
I can open the file in around 500ms with a very simplistic data model:

```groovy
enum FiscalSubjectType {
  LEGAL_PERSON, NATURAL_PERSON;
}
enum ServiceOwnerType {
  PRIVATE, FREELANCER, PRIVATE_COMPANY, INDIVIDUAL_COMPANY, NONPROFIT_ORGANIZATION, PUBLIC_ADMINISTRATION;
}
interface ContactableFiscalSubject {
}
interface FiscalSubject {
}
class ServiceOwner {
  String firstName, lastName, vatNumber
  String title, companyName, companyFiscalCode, personalFiscalCode, electronicInvoiceRecipientCode
  ContactDetails companyContactDetails, personalContactDetails
  boolean nonProfit, publicAdministration
  FiscalSubjectType fiscalSubjectType
  ServiceOwnerType serviceOwnerType

  static class BasicServiceOwner extends ServiceOwner {
  }
  static class ContactDetails {
    String streetName
    String postalCode
    String city
    String province
    String country
    String phone
    String mobile
    String fax
    String email
    String emailPEC
    boolean isEmpty() {
    }
    boolean matches(ContactDetails that) {
    }
  }
  ServiceOwner copyUpperCaseFrom(ContactableFiscalSubject that) {
  }
  ServiceOwner copyUpperCaseFrom(FiscalSubject that) {
  }
  ServiceOwner copyUpperCaseFrom(ServiceOwner that) {
  }
  boolean conflicts(ServiceOwner that) {
  }
  boolean matches(ServiceOwner that) {
  }
}
```

Not sure how deep your class model is.  Some of the resolve time is spent parsing those source units.  But I can say that the test file doesn't contain anything that out-of-the-ordinary.  The last change that I put in should help with the resolve time of the static method calls.  I'm curious to see how much that helped.

**Comment by mauromol** [comment]
The model is like the one you created, apart from the fact that it's in Java rather than in Groovy.
I'm profiling right now with Greclipse 4.8.0.v202210260251-e2206.

**Comment by mauromol** [comment]
[open-type-with-without-cs.zip](https://github.com/groovy/groovy-eclipse/files/9872189/open-type-with-without-cs.zip)

Here is the profiling snapshots with and without `@CompileStatic`. Later I will provider sampler snapshots, as well, I just can't right now.

> Thanks for the tip on your model being Java. I'll try that and see if it makes any difference.

Please also note that:
- the code is inside a much more complex project structure (a 9-project Gradle multiproject); I haven't tried yet to see whether extracting those classes would speed up things
- `ServiceOwner` is indeed an interface and hierarchically extends other (smaller) interfaces
- `ContactDetails` is itself an interface
- methods in `ServiceOwner` (like `copyUpperCaseFrom...`, `matches`, `conflicts`, ...) are indeed implemented as default methods

If you think it would be useful, I may try to extract these classes. Are method implementation useful for your analysis or not?

**Comment by mauromol** [comment]
Here are the sampler results.

[sampler.zip](https://github.com/groovy/groovy-eclipse/files/9872671/sampler.zip)

First I tried by including all classes except (substantially) the JDK ones. But honestly, I don't think the result is very useful.
Then I tried to profile only classes `org.codehaus.groovy.**` and `org.eclipse.jdt.**`. In this case hot spots seem to be more informative.
Again, I tried the open type action with and without `@CompileStatic` and waited until syntax coloring completed.

**Comment by eric-milles** [comment]
Even without static compilation, it is the static methods that are taking lots of time.  I have another small change that helps non-STC.

One thing you can do to improve method call inference is to have the arguments as local variables.  That is "assertTrue(o.personalContactDetails.matches(avvLuigiRosso.personalContactDetails))"  -->  "boolean matches = o.personalContactDetails.matches(avvLuigiRosso.personalContactDetails); assertTrue(matches)".

Or you can use Groovy `assert` which would cut way down on the resolve time: "assert o.personalContactDetails.matches(avvLuigiRosso.personalContactDetails)"

I'm not trying to change your test style; just trying to point out where there is time spent.  I may do the search-and-replace and post it back here so you can try it and see the difference.

**Comment by mauromol** [comment]
Fact is that Groovy `assert` won't nicely replace JUnit `assertEquals`... But what is so special about static methods? Is it the fact that they have overloadings or just their nature of being static methods? I would have guessed static methods resolution were less problematic than instance methods...

And what about the "save" case? Is it also affected by the problematic static method call inference?

**Comment by eric-milles** [comment]
The static methods are an issue for your test due to sheer volume.  I have lessened the types searched to find the method.  For example, `Assert#assertEquals` looked at `Assert` and `Object`.  Once found, there are 12 variants of `assertEquals` to choose from, so there is time spent selecting the best fit for the arguments.

In the save case, do you have Organize Imports enabled?

**Comment by mauromol** [comment]
> In the save case, do you have Organize Imports enabled? Update: Looks like you have format enabled on save.

Yes I have, as well as code format cleanup on save.

**Comment by eric-milles** [comment]
So the `assert` change makes a minor improvement: 733ms vs 577ms.  Here is is if you want to have a look. 
 [ServiceOwnerTest2.zip](https://github.com/groovy/groovy-eclipse/files/9873736/ServiceOwnerTest2.zip)

During save, the `ASTScanner` used a `java.util.Stack` which is based off the old `Vector` (both are synchronized).  I switched to an `ArrayDeque` so you should get a boost there.

**Comment by mauromol** [comment]
Seems like the new snapshot is not ready yet on the update site.

**Comment by eric-milles** [comment]
It is building now.  There is something wrong with one of the build agents.

**Comment by mauromol** [comment]
Tried it now. Although the save operation is still quite heavy, I must say that there's a perceivable improvement now. 

Do you think there's some room for improvement in the code assist case?

**Comment by eric-milles** [comment]
If you can send new captures, I can take a look.
