### ISSUE TITLE
Regression in array-like map access

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1411]
With  Greclipse 4.8.0.v202210192327-e2206	I see the following regression:

```groovy
package testmap
import groovy.transform.CompileStatic
@CompileStatic
class Foo {
	Map<String, Integer> map = new HashMap()
}
```

```groovy
package testmap
import groovy.transform.CompileStatic
@CompileStatic
class TestMap {
	void foo() {
		def foo = new Foo()
		def a = 'aaa'
		foo.map[a] = 1
	}
}
```

An error is given on `foo.map`: ` Cannot find matching method testmap.Foo#map(). Please check if the declared type is correct and if the method exists.`.

**Comment by eric-milles** [comment]
GROOVY-9771 revisit of "foo.map" in subscript expression is one half of the issue: https://github.com/apache/groovy/commit/9512b798abc11c3f7d762e3aae454f3d65e592ee

**Comment by eric-milles** [comment]
https://github.com/apache/groovy/commit/29c485893478da32166dc01058a0b14fb20c90ea

**Comment by mauromol** [comment]
With Greclipse 4.8.0.v202210232216-e2206 this seems to be fixed, thank you!
