### ISSUE TITLE
Regression: STC is losing generics information in inheritance

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1419]
I first ran into this with a trait that had a property of type `List<String>`, where GRECLIPSE was treating the property as type `List<E>` and producing errors, but I had trouble replicating it. However, this replicates what appears to be the same problem:

```
@Grab('com.google.guava:guava:29.0-jre')
import com.google.common.reflect.TypeToken

class Generics {
  private static final TypeToken<List<String>> LIST_STRING =
    new TypeToken<List<String>>() {}
    // ^ Type mismatch: cannot convert from new TypeToken<Object>(){} to TypeToken
}
```

This error is present in 4.8.0.v202211162249-e2206 (e4.24), and I think it was present in the nightly from Tuesday. It might be in Groovy itself, but groovyc 4.0.6 has no trouble with it.

**Comment by eric-milles** [comment]
I am not getting this error.

![image](https://user-images.githubusercontent.com/18193802/202910888-c4b8c311-5900-4a7e-99d8-baadd02528bc.png)

**Comment by eric-milles** [comment]
Related to #1358

**Comment by chrylis** [comment]
Thanks, this appears to solve the problem!
