### ISSUE TITLE
Update formatter to bring in line with Eclipse Mars SR1

### ISSUE THREAD

**Issue by philwebb** [groovy/groovy-eclipse#142]
The patched JDT version shipped with Groovy Eclipse contains formatter bugs that have been fixed with Mars SR1. Specifically https://bugs.eclipse.org/bugs/show_bug.cgi?id=472962 is causing problems for me.

**Comment by guillaumecle** [comment]
I am also facing a formatter [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=471145) fixed in Mars SR1 because of groovy-eclipse.

**Comment by philwebb** [comment]
@guillaumecle In the end I created a custom formatter plugin for Eclipse. You can get it [here](https://dl.bintray.com/philwebb/spring-eclipse-code-formatter/) if it helps. Code is [here](https://github.com/philwebb/spring-eclipse-code-formatter). Once installed you get a new 'Spring' formatter in the preferences page.

**Comment by guillaumecle** [comment]
Thank you. In fact I didn't need the groovy-eclipse plugin on my eclipse installation, it came as m2e connector but wasn't necessary.
