### ISSUE TITLE
Not compatible with eclipse 2022-12

### ISSUE THREAD

**Issue by OverDrone** [groovy/groovy-eclipse#1429]
Hello!
If you download latest [Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2022-12/r/eclipse-ide-enterprise-java-and-web-developers) and try to install this plugin via marketplace, error occurs saying some components can't be installed. If needed I can provide you more details, but as I understand it's reproducible in any environment. Had to downgrade to 2022-09, which is compatible with this plugin.

**Comment by eric-milles** [comment]
#1425
