### ISSUE TITLE
2022-12 (v 4.8.0) Eclipse (latest) is incompatible with latest Groovy Plugin

### ISSUE THREAD

**Issue by scottwdavidson** [groovy/groovy-eclipse#1431]
When I attempt to install latest Groovy Plugin, I get the following error ( using a brand new, 2022-12 latest, instance of Eclipse ): 

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Groovy Development Tools 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
  Software currently installed: Eclipse IDE for Java Developers 4.26.0.20221201-1200 (epp.package.java 4.26.0.20221201-1200)
  Software currently installed: Eclipse Java Development Tools 3.18.1400.v20221123-1800 (org.eclipse.jdt.feature.group 3.18.1400.v20221123-1800)
  Only one of the following can be installed at once: 
    Java Development Tools Core 3.32.0.v20221108-1853 (org.eclipse.jdt.core 3.32.0.v20221108-1853)
    Java Development Tools Core 3.32.0.v202212311456-e2212-RELEASE (org.eclipse.jdt.core 3.32.0.v202212311456-e2212-RELEASE)
  Cannot satisfy dependency:
    From: Eclipse IDE for Java Developers 4.26.0.20221201-1200 (epp.package.java 4.26.0.20221201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.epp.package.common.feature.feature.group [4.26.0.20221201-1200,4.26.0.20221201-1200]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Compilerless feature 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.compilerless.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]
  Cannot satisfy dependency:
    From: Eclipse Groovy Development Tools 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Headless feature 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.headless.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]
  Cannot satisfy dependency:
    From: Eclipse Packaging Project Common Feature 4.26.0.20221201-1200 (org.eclipse.epp.package.common.feature.feature.group 4.26.0.20221201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.32.0.v20221108-1853,3.32.0.v20221108-1853]
  Cannot satisfy dependency:
    From Patch: org.codehaus.groovy.jdt.patch.feature.group 4.8.0.v202212311456-e2212-RELEASE Eclipse Java Development Tools 3.18.1400.v20221123-1800 (org.eclipse.jdt.feature.group 3.18.1400.v20221123-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.32.0.v202212311456-e2212-RELEASE,3.32.0.v202212311456-e2212-RELEASE]
```

**Comment by eric-milles** [comment]
https://github.com/groovy/groovy-eclipse/wiki/4.8.0-Release-Notes

> :warning: It is not possible to install GDT into one of the Eclipse 4.26 [package releases](https://www.eclipse.org/downloads/packages/) (aka Eclipse IDE for Java Developers, etc.) due to a JDT version restriction in `org.eclipse.epp.package.common.feature`. GDT installs normally starting from the [Eclipse Platform Runtime](https://download.eclipse.org/eclipse/downloads/drops4/R-4.26-202211231800/#PlatformRuntime). More details can be found here: https://github.com/groovy/groovy-eclipse/issues/1425

**Comment by scottwdavidson** [comment]
Similar but different error using Eclipse Platform Runtime : 

Cannot complete the install because one or more required items could not be found.
  Software being installed: Eclipse Groovy Development Tools 4.8.0.v202212311458-e2209-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.8.0.v202212311458-e2209-RELEASE)
  Missing requirement: Eclipse JDT Core patch for Groovy 4.8.0.v202212311458-e2209-RELEASE (org.codehaus.groovy.jdt.patch.feature.group 4.8.0.v202212311458-e2209-RELEASE) requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.18.1300.v20220831-1800,3.18.1300.v20220831-1800]' but it could not be found
  Cannot satisfy dependency:
    From: Groovy-Eclipse Compilerless feature 4.8.0.v202212311458-e2209-RELEASE (org.codehaus.groovy.compilerless.feature.feature.group 4.8.0.v202212311458-e2209-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [4.8.0.v202212311458-e2209-RELEASE,4.8.0.v202212311458-e2209-RELEASE]
  Cannot satisfy dependency:
    From: Eclipse Groovy Development Tools 4.8.0.v202212311458-e2209-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.8.0.v202212311458-e2209-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [4.8.0.v202212311458-e2209-RELEASE,4.8.0.v202212311458-e2209-RELEASE]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Headless feature 4.8.0.v202212311458-e2209-RELEASE (org.codehaus.groovy.headless.feature.feature.group 4.8.0.v202212311458-e2209-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [4.8.0.v202212311458-e2209-RELEASE,4.8.0.v202212311458-e2209-RELEASE]
