### ISSUE TITLE
Installation fails for Eclipse 2022-12

### ISSUE THREAD

**Issue by fsilkswan** [groovy/groovy-eclipse#1437]
Downloaded a fresh package: eclipse-jee-2022-12-R-win32-x86_64.zip
Unpacked it to local folder and my first action was to install "Groovy Development Tools" via Marketplace.

Error details:
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Groovy Development Tools 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
  Software currently installed: Eclipse IDE for Enterprise Java and Web Developers 4.26.0.20221201-1200 (epp.package.jee 4.26.0.20221201-1200)
  Software currently installed: Eclipse Java Development Tools 3.18.1400.v20221123-1800 (org.eclipse.jdt.feature.group 3.18.1400.v20221123-1800)
  Only one of the following can be installed at once: 
    Java Development Tools Core 3.32.0.v20221108-1853 (org.eclipse.jdt.core 3.32.0.v20221108-1853)
    Java Development Tools Core 3.32.0.v202212311456-e2212-RELEASE (org.eclipse.jdt.core 3.32.0.v202212311456-e2212-RELEASE)
  Cannot satisfy dependency:
    From: Eclipse IDE for Enterprise Java and Web Developers 4.26.0.20221201-1200 (epp.package.jee 4.26.0.20221201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.epp.package.common.feature.feature.group [4.26.0.20221201-1200,4.26.0.20221201-1200]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Compilerless feature 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.compilerless.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]
  Cannot satisfy dependency:
    From: Eclipse Groovy Development Tools 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Headless feature 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.headless.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]
  Cannot satisfy dependency:
    From: Eclipse Packaging Project Common Feature 4.26.0.20221201-1200 (org.eclipse.epp.package.common.feature.feature.group 4.26.0.20221201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.32.0.v20221108-1853,3.32.0.v20221108-1853]
  Cannot satisfy dependency:
    From Patch: org.codehaus.groovy.jdt.patch.feature.group 4.8.0.v202212311456-e2212-RELEASE Eclipse Java Development Tools 3.18.1400.v20221123-1800 (org.eclipse.jdt.feature.group 3.18.1400.v20221123-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.32.0.v202212311456-e2212-RELEASE,3.32.0.v202212311456-e2212-RELEASE]

**Comment by fsilkswan** [comment]
Also tried to install manually using the release and the snapshot repository for e4.26 but with same result.

**Comment by eric-milles** [comment]
#1425
