### ISSUE TITLE
wiki docs: POM fragment missing groupId for maven-compiler-plugin

### ISSUE THREAD

**Issue by slotrans** [groovy/groovy-eclipse#1440]
screenshot of https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin as of this writing:

![Screenshot 2023-01-12 203503](https://user-images.githubusercontent.com/3879334/212231322-2cda141f-bd2d-4dd2-966e-02daa947f29d.png)
--
The example suggests:
```
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version><!-- 3.6.2 is the minimum -->
```
But this won't work. It also needs:
```
        <groupId>org.apache.maven.plugins</groupId>
```
I struggled with this for a while. Finally clicked when I found this other doc: https://maven.apache.org/plugins/maven-compiler-plugin/examples/compile-using-different-jdk.html

**Comment by eric-milles** [comment]
`org.apache.maven.plugins` is implicit if no `groupId` element is supplied.  I can add it in if that helps clarity.
