### ISSUE TITLE
The package javax.xml.stream is accessible from more than one module: <unnamed>, java.xml

### ISSUE THREAD

**Issue by EkaLinMan** [groovy/groovy-eclipse#1441]
The error happens when we execute the command `mvn clean install`
Failed to execute groovy-eclipse compiler as below image. (I removed the information about the codebase's detail) 
![image](https://user-images.githubusercontent.com/122604222/212289993-73e242d1-bcf8-488a-a70f-eba3dbd31ed0.png)

This is our maven-compiler-plugin's settings, and we use JDK17.
![image](https://user-images.githubusercontent.com/122604222/212296898-346ee4b8-64b5-4bb7-9d24-326236812d26.png)

We've already done some research:
https://stackoverflow.com/questions/55571046/eclipse-is-confused-by-imports-accessible-from-more-than-one-module
https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10
It seems caused by the package name **javax.xml** used by xml-apis library and "java.xml" module from the JRE System Library at the same time.

For now, we don't want to create module-info.java or exclude the library from the project to solve it.
Is there any setting of groovy-eclipse that help us to prevent this issue?

**Comment by eric-milles** [comment]
Can you say who (or what) is supplying the `javax.xml` module in your build?  If it is coming from the JDK, then why the reluctance to exclude `xml-apis` from whichever dependency supplies it?

I'm not too familiar with JPMS, but having a package split across two modules is a violation of the specification.  The eclipse compiler options are listed here if you want to try to suppress somehow: https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin

**Comment by EkaLinMan** [comment]
Thanks for your reply.

> Who (or what) is supplying the javax.xml module in your build? 
Yes, it is coming from the JDK
> Why the reluctance to exclude xml-apis from whichever dependency supplies it?
Now we are trying to upgrade Java from 11 to 17, our highest priority is to fix any error from Java's upgrade, the issue `he package javax.xml.stream is accessible from more than one module` seems coming from `groovy-eclipse-batch`'s upgrade, not from Java's upgrade. (It seems fine when we use Java 11 & groovy-eclipse-batch 2.5.6-01) So we prefer to turn off the module check if we can instead of changing our dependency structure. We're also afraid there are any issues if we exclude the `xml-apis` because it is also another third-library's compile or runtime dependency.
Or do you think the unnamed module is really always ignored (I'm not sure about that), so we totally don't need `xml-apis`?

> The eclipse compiler options are listed here if you want to try to suppress somehow: https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm
Thanks! I'll try these compiler options and report back if I have any new discoveries.

I also have another question: https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10/74890645#74890645
Is `org.eclipse.jdt.core.compiler.ignoreUnnamedModuleForSplitPackage=ENABLED` an available option in groovy-eclipse-batch?

**Comment by EkaLinMan** [comment]
Hi Eric, I've made some tests.

According to [this post](https://stackoverflow.com/a/53824670), I think `--limit-modules` is a good way to exclude `java.xml` from the set of observable modules.

I add `<compilerArgument>-J--limit-modules=java.compiler,java.desktop,java.logging,jdk.unsupported</compilerArgument> ` into the configuration
![image](https://user-images.githubusercontent.com/122604222/212631439-badaabd7-2434-421d-9a6e-1474ff64e136.png)

But there is still the error message: `The package javax.xml.stream is accessible from more than one module: <unnamed>, java.xml`, it's weird because there shouldn't be `java.xml` in the observable modules.

Do you have any suggestions? thanks!

**Comment by eric-milles** [comment]
A couple notes:
1. `groovy-eclipse-compiler` 3.8.0 is current; `groovy-eclipse-batch` 3.0.14-02 or 4.0.7-02 is current
1. Java 17 target is probably best expressed to maven as `<release>17</release>`
1. Groovy 4 is only major release to support 17 target
1. `xml-apis` artifact (that I inspected) does not contain `java.xml.stream` package.  Which specific dependency in your project contains classes in `java.xml.stream` package?
1. `-J` options are for the JVM that runs the forked compiler.  So that JVM will not use `java.xml` package but the compilation classpath/modulepath is unchanged.

> Is `org.eclipse.jdt.core.compiler.ignoreUnnamedModuleForSplitPackage=ENABLED` an available option in `groovy-eclipse-batch`?

You can use the `-properties` option to link to a file that includes any `org.eclipse.jdt.core.compiler.*` options you wish to set.

Again, I don't think the right road is suppression.  If you have a split package situation and your application process loads classes from both modules, you can get illegal access issues in Java 17 that do not trip under Java 11.  This all started in Java 16.

**Comment by EkaLinMan** [comment]
Hi @eric-milles 

We decide to follow your suggestion of excluding the xml-apis from our project to prevent the split package situation, thanks!

> 1. Java 17 target is probably best expressed to maven as <release>17</release>
```
<source>17</source>
<release>17</release>
```
Is this correct?

> 2. Which specific dependency in the project contains classes in `java.xml.stream` package?
Our `xml-apis` contains this package.
![image](https://user-images.githubusercontent.com/122604222/212877653-3fd7dffe-71bc-4322-a2ef-edae040b8b54.png)

> 3. -J options are for the JVM that runs the forked compiler. So that JVM will not use java.xml package but the compilation classpath/modulepath is unchanged.
Although we don't use this way now, I'm still curious what is the correct way to limit modules in the module path.

**Comment by EkaLinMan** [comment]
I'll report back when we finish excluding `xml-apis`, maybe not so quickly because there are still other tasks that need to be done.

**Comment by eric-milles** [comment]
When I used the Java Build Path UI to remove the `java.xml` module, Eclipse IDE produced this `.classpath' change:
```xml
<classpath>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11">
    <attributes>
      <attribute name="module" value="true" />
      <!-- the next line is the only change -->
      <attribute name="limit-modules" value="java.datatransfer,java.instrument,java.net.http,java.transaction.xa,jdk.compiler,jdk.httpserver,jdk.internal.ed,jdk.internal.le,jdk.internal.opt,jdk.jartool,jdk.jdi,jdk.management.agent,jdk.management.jfr,jdk.naming.ldap,jdk.net,jdk.scripting.nashorn,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported" />
    </attributes>
  </classpathentry>
  <classpathentry kind="con" path="GROOVY_DSL_SUPPORT" />
  <classpathentry kind="con" path="GROOVY_SUPPORT" />
  <classpathentry kind="output" path="bin" />
  <classpathentry kind="src" path="src" />
</classpath>
```

So you could connect the `limit-modules` attribute to the batch compiler option(s).
