### ISSUE TITLE
On STS/Eclipse (with java 17 support) m2e can't import maven project correctly if I configure maven compiler plugin with groovy eclipse compiler

### ISSUE THREAD

**Issue by ksanjeev9211** [groovy/groovy-eclipse#1444]
STS Version -4.17.1 (or any eclipse version supporting java 17)

-configure maven compiler plugin with Groovy Eclipse compiler in your pom with lombok support
-Import the maven project on STS/Eclipse
-STS starts popping up m2e lifecycle issue (compile and testCompile not covered)

when I remove the groovy eclipse compiler  from maven-compiler plugin, project is imported correctly, however, my groovy/spock testers are not compiled and I can't test them from my IDE. 

Maven build works fine.

**Comment by eric-milles** [comment]
What version of Groovy Development Tools so you have installed within STS?  It's possible you don't have any; Groovy m2eclipse is what fills in those lifecycle mappings.  Can you include a small sample project that has the import issue?

**Comment by ksanjeev9211** [comment]
I have the eclipse plugin, the latest one which is compatible with STS-4.17.1.RELEASE /(eclipse-4.26) .
The plugin I installed is 
https://dist.springsource.org/release/GRECLIPSE/e4.26

This has been an issue with any eclipse version having m2e plugin with Java 17 support.

Wondering if I would be able to upload a sample project from my work computer or not, however, will try something uploaded here from my personal computer to reproduce the issue.
I have been working on groovy, grails, Spock, GORM etc since 2008, never faced such issue on eclipse/GGTS/STS before. 

not sure if I am missing anything.

**Comment by ksanjeev9211** [comment]
Hi @eric-milles,
I am attaching  a sample project to reproduce the issue.
[grooovy-eclipse-compiler-sample.zip](https://github.com/groovy/groovy-eclipse/files/10531647/grooovy-eclipse-compiler-sample.zip)


Env:
STS-4.17.1.RELEASE with GRECLIPSE plugin (https://dist.springsource.org/release/GRECLIPSE/e4.26)
JDK -17
Spring boot version 3.0.2
Lombok -1.18.24: adding/removing lombok does not make any differnce though

while Installing GRECLIPSE i could not install the optional 'Groovy-Eclipse-M2E Integration'

![greclipse-install](https://user-images.githubusercontent.com/4118153/215373526-0f316845-4b0e-438a-af0f-42db1280d190.jpg)

when I import the project after adding the groovy eclipse compiler i get the maven lifecycle issue:

![maven-project-import](https://user-images.githubusercontent.com/4118153/215373598-0418adf9-a48c-4ea1-8771-085b6eeab4ac.jpg)

and after selecting the option not to execute the above the project structure on STS is :







![maven-project-structure](https://user-images.githubusercontent.com/4118153/215373710-aad54fa0-2a06-4c90-8990-a2dc45b1ae7b.jpg)

i.e. no .classpath is created for the project, also the .project having the incorrect project configuration

![project](https://user-images.githubusercontent.com/4118153/215375170-7a9ec6a6-bf86-41e3-a50f-6c04d81b7d2b.jpg)

**Comment by ksanjeev9211** [comment]
For the time being I haven;t added any groovy/spock testers in the above project, howver in my work project thare are many spock testers, in case required I could add them.
The maven build is fine, no issues.
The same project worked fine i.e.  imported correctly when there was no groovy-eclipse-compiler plugin configured.

**Comment by eric-milles** [comment]
You can install the latest snapshot, which includes compatibility with m2e 2.x: https://dist.springsource.org/snapshot/GRECLIPSE/e4.26

**Comment by eric-milles** [comment]
With Groovy-Eclipse M2E installed, the project imported with no additional prompts.  I did not have Lombok installed at the time, so no generation.  But I have used lombok from eclipse before, so I have little doubt that the project would be fine in the end.

![image](https://user-images.githubusercontent.com/18193802/215504560-38711fd3-1f8c-4dd7-94d1-7cf552eeb371.png)

**Comment by ksanjeev9211** [comment]
Great!
However, I am not able to install the  Groovy-Eclipse M2E if I install [https://dist.springsource.org/release/GRECLIPSE/e4.26](url)

I get the following error: 

`Cannot complete the install because one or more required items could not be found.
  Software being installed: Groovy-Eclipse M2E integration 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.m2eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
  Missing requirement: Groovy m2e integration 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.m2eclipse 4.8.0.v202212311456-e2212-RELEASE) requires 'osgi.bundle; org.eclipse.m2e.core [1.9.1,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Groovy-Eclipse M2E integration 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.m2eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.m2eclipse [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]`

What is the version of groovy eclipse plugin you have installed on your local STS?

**Comment by eric-milles** [comment]
I included the _snapshot_ update site link above.

**Comment by ksanjeev9211** [comment]
Awesome, it worked!!
Thanks a lot for fixing this issue in the latest snapshot version of the GRECLIPSE.

Wondering, if you can add a note regarding this on the wiki page of groovy eclipse plugin?
