### ISSUE TITLE
Groovy-Eclipse with M2E integration can't be installed in Eclipse 2022-12

### ISSUE THREAD

**Issue by ahiltenkamp** [groovy/groovy-eclipse#1445]
I can not install Groovy-Eclipse in a fresh installed version of Eclipse 2022-12
Maven integration is installed according to the Marketplace Client only the PDE feature is missing. 

I added  https://dist.springsource.org/release/GRECLIPSE/e4.26 to the available update sites 
but when trying to install it I get:

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: Groovy-Eclipse M2E integration 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.m2eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
>   Missing requirement: Groovy m2e integration 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.m2eclipse 4.8.0.v202212311456-e2212-RELEASE) requires 'osgi.bundle; org.eclipse.m2e.core [1.9.1,2.0.0)' but it could not be found
>   Cannot satisfy dependency:
>     From: Groovy-Eclipse M2E integration 4.8.0.v202212311456-e2212-RELEASE (org.codehaus.groovy.m2eclipse.feature.feature.group 4.8.0.v202212311456-e2212-RELEASE)
>     To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.m2eclipse [4.8.0.v202212311456-e2212-RELEASE,4.8.0.v202212311456-e2212-RELEASE]
> 

Of course because m2e comes with Version 2.1.x and Groovy-Eclipse M2E expects [1.9.1,2.0.0) - I can try to downgrade m2e but that's not what I want.

> Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.1.0.20221015-0744	org.eclipse.m2e.logback.feature
> Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.1.2.20221130-2239	org.eclipse.m2e.feature
> Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.1.2.20221130-2134	org.eclipse.m2e.pde.feature

**Comment by eric-milles** [comment]
Groovy-Eclipse M2E has been updated in 4.9.0 (https://dist.springsource.org/snapshot/GRECLIPSE/e4.26): https://github.com/groovy/groovy-eclipse/issues/1405

Groovy-Eclipse cannot be installed to a 2022-12 packaged release (you can start from [Platform Runtime](https://download.eclipse.org/eclipse/downloads/drops4/R-4.26-202211231800/#PlatformRuntime)): https://github.com/groovy/groovy-eclipse/issues/1425
