### ISSUE TITLE
Composite update site XML is invalid for e4.17

### ISSUE THREAD

**Issue by apeteri** [groovy/groovy-eclipse#1449]
Hi all,

We are using version 3.9.0 for Eclipse 4.17 (2020-09). It appears that the previous update site, `dist.springsource.org` is unreachable at the moment, so we wanted to switch over to the URL listed in the wiki: https://groovy.jfrog.io/ui/native/plugins-release/e4.17

This however leads to a `compositeArtifacts.xml` with malformed content (the commented portion should start with `<!--` instead of `<--`):

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<repository name="Groovy Development Tools for e4.17" type="org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository" version="1.0.0">
  <properties size="1">
    <property name="p2.timestamp" value="1672499771461"/>
  </properties>
  <children size="9">
    <child location="https://groovy.jfrog.io/artifactory/plugins-release-local/org/codehaus/groovy/groovy-eclipse-integration/4.8.0/e4.17"/>
    [...]
    <child location="https://groovy.jfrog.io/artifactory/plugins-release-local/org/codehaus/groovy/groovy-eclipse-integration/4.0.0/e4.17"/>
    <--
    <child location="https://groovy.jfrog.io/artifactory/plugins-release-local/org/codehaus/groovy/groovy-eclipse-integration/3.9.0/e4.17"/>
    -->
  </children>
</repository>
```

Regards,\
András

**Comment by eric-milles** [comment]
Should be fixed now.  Thanks for spotting this.

**Comment by eric-milles** [comment]
The site on the wiki is: https://groovy.jfrog.io/artifactory/plugins-release/e4.17
If you want 3.9.0 specifically, you can use: https://groovy.jfrog.io/artifactory/plugins-release-local/org/codehaus/groovy/groovy-eclipse-integration/3.9.0/e4.17

(or substitute a different release version)

And there are update site archives made available (links in the release notes) so you can keep a local copy if you'd like.

**Comment by apeteri** [comment]
Correct, I think I copied the URL from the browser after it redirected to the directory listing. Thank you!
