### ISSUE TITLE
DSLDs: Wrong ordering on enclosingCallName/enclosingCallDeclaringType pointcut binding

### ISSUE THREAD

**Issue by andvazqu** [groovy/groovy-eclipse#1451]
Hi! We're using DSLDs to add editor support to a  Groovy Builder, which looks like this:

![image](https://user-images.githubusercontent.com/48433864/218142499-62cd9aad-9e36-45e1-b01e-5260d0baa879.png)

Using the following contribution block:

`contribute(bind(enclosingCalls:enclosingCallName())) {log "enclosingCallName returns: " + enclosingCalls}`

According to the documentation, the enclosingCallName/enclosingCallDeclaringType pointcuts "return all enclosing method name/declaring types as an ordered set. The ordering is from the lexically closest call to the furthest."

However, when invoking code assist at "|" (line 6), we obtain: 
enclosingCallName returns: [ApplicationRecordData, elements, **smt**, **ARPackage**]
The expected behavior would be:
enclosingCallName returns: [**elements**, ApplicationRecordData, elements, **ARPackage**, **smt**]

The ArrayList in 
https://github.com/groovy/groovy-eclipse/blob/eef468afe38fbab749d7b104095945f20d9d4be9/ide/org.codehaus.groovy.eclipse.dsl/src/org/codehaus/groovy/eclipse/dsl/pointcuts/impl/EnclosingCallNamePointcut.java#L39
has the correct ordering. 

The problem comes when binding the return value to a named argument (e.g. to pass it to a locally defined pointcut) since on 
https://github.com/groovy/groovy-eclipse/blob/eef468afe38fbab749d7b104095945f20d9d4be9/ide/org.codehaus.groovy.eclipse.dsl/src/org/codehaus/groovy/eclipse/dsl/pointcuts/AbstractPointcut.java#L141
the ArrayList is put in a HashSet so duplicates disappear and the ordering gets messed up.

Then again on
https://github.com/groovy/groovy-eclipse/blob/eef468afe38fbab749d7b104095945f20d9d4be9/ide/org.codehaus.groovy.eclipse.dsl/src/org/codehaus/groovy/eclipse/dsl/pointcuts/BindingSet.java#L52
this is put in a HashSet, messing the ordering. 

Changing those two HashSets to LinkedHashSets fixes the ordering (although the duplicates issue remains). Changing to ArrayLists fixes the issue (although the ordering is from furthest to closest).

All the same applies to enclosingCallDeclaringType.

In our use-case, the contributions depend not only on the name/declaring type of the currentNode (e.g. "elements") but also its direct parent (e.g. "ApplicationRecordData), that's why we use the return value of enclosingCallName and the duplicates and correct ordering are important. Is there maybe some alternative way to obtain the name/declaring type of the direct parent? Thanks! :)

**Comment by eric-milles** [comment]
Inside the contribution, you can check `currentNode` and `enclosingNode`.  This works is the element matched is directly inside the block, like:
```groovy
foo {
  bar {
    baz
  }
}
```

When matching on "baz" with something like `contribute(currentIdentifier) { ... }` then `enclosingNode` should be the "bar" method call expression.  If you need more from the current scope, you'll need use pointcut bindings.
