### ISSUE TITLE
Error "interface GormEntity cannot be implemented twice with different arguments" when building Grails project that uses inheritance for Domain classes

### ISSUE THREAD

**Issue by mindcrime** [groovy/groovy-eclipse#1452]
Using the latest 4.8.0 version of the Groovy Development Tools package, I find the following problem in a Grails project I am working on. This happens where I have a base class in my "domain" folder, and another domain class which extends that class in turn. In this particular instance the base class is defined as abstract, but that doesn't seem to make any difference.

The Eclipse Groovy compiler complains about this scenario, giving me an error like:

Groovy:The interface GormEntity cannot be implemented more than once with different arguments: org.grails.datastore.gorm.GormEntity<org.fogbeam.quoddy.stream.BusinessEventSubscriptionItem> and org.grails.datastore.gorm.GormEntity<org.fogbeam.quoddy.stream.StreamItemBase>	BusinessEventSubscriptionItem.groovy	

Where org.fogbeam.quoddy.stream.StreamItemBase is the base class, and org.fogbeam.quoddy.stream.BusinessEventSubscriptionItem is the subclass.

Conversely building this same project using Gradle/Grails on the command line works fine, with no errors.  

If it helps, my Eclipse version is:

Version: 2022-03 (4.23.0)
Build id: 20220310-1457

Java version is:

openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)

And the Grails version is 5.2.5

When building on the command line, the Gradle version is alternately 7.4.2 or 7.2, depending on whether I'm using the "Wrapper" version in the project dir or the system install of Gradle.

**Comment by eric-milles** [comment]
Can you provide a simple example?  I think this is a legit error.

**Comment by mindcrime** [comment]
> Can you provide a simple example? I think this is a legit error.
> 
> Typically, I would expect a relationship like this to be declared in this way:
> 
> ```groovy
> abstract class A<T extends BaseItem> implements List<T> { ... }
> class C extends A<SubscriptionItem> { ... }
> ```

In this case, all the interface stuff is being done as "black magic" that Grails manages. All I have is a class sitting in the "domain" folder of the Grails project, which extends another class in that same folder. I don't fully understand how the Groovy Developer Tools integrate with that "Grails black magic" which is part of what makes this hard to understand.  

That said, the code in question does work if I build using the standard command line tools. It's only inside Eclipse using GDT that I see the error. 

To see it happen with the same code-base I'm using, you can clone this repo and import it into Eclipse with GDT and you should see the error in question where a couple of the Grails domain classes have an inheritance relationship. 

https://github.com/fogbeam/quoddy_g5/

Note that this code is Open Source but the repo is private since that's just a temporary transition repo for where we're upgrading to Grails 5.x. I added you with a READ role so you can access.

**Comment by eric-milles** [comment]
The `GormEntity` trait is injected by `org.grails.compiler.gorm.GormEntityTransformation`, which delegates to this method in `org.grails.datastore.mapping.reflect.AstUtils`.  No check is made if the class already implements the trait.  And I don't think Grails/GORM has any problem creating an entity class from an abstract class.
```groovy
    static void injectTrait(ClassNode classNode, Class traitClass) {
        ClassNode traitClassNode = ClassHelper.make(traitClass)
        boolean implementsTrait = false
        boolean traitNotLoaded = false
        try {
            implementsTrait = classNode.declaresInterface(traitClassNode)
        } catch (Throwable e) {
            // if we reach this point, the trait injector could not be loaded due to missing dependencies (for example missing servlet-api). This is ok, as we want to be able to compile against non-servlet environments.
            traitNotLoaded = true
        }
        if (!implementsTrait && !traitNotLoaded) {
            final GenericsType[] genericsTypes = traitClassNode.getGenericsTypes()
            final Map<String, ClassNode> parameterNameToParameterValue = new LinkedHashMap<String, ClassNode>()
            if(genericsTypes != null) {
                for(GenericsType gt : genericsTypes) {
                    parameterNameToParameterValue.put(gt.getName(), classNode)
                }
            }
            classNode.addInterface(replaceGenericsPlaceholders(traitClassNode, parameterNameToParameterValue, classNode))
        }
    }
```

You could ask the Grails team what they think of this scenario.  Advice online seems to suggest moving the base class out of the domain source folder or changing it to a trait.  This interface check is made by Groovy 4 (IIRC) so I wonder what they did for Groovy 4 compat.

**Comment by mindcrime** [comment]
OK, I'll check with the Grails folks and see if they have any input. I'm not opposed to re-structuring this code, if there's a better recommended practice anyway. 

I am still curious why this error shows up with Eclipse GDT, but not when building using the command line tools. But it's not a big issue. I actually just filter this error out in Eclipse anyway so it isn't a distraction in the "Problems" view.  

Anyway, if moving my base class out of the "domain" folder and into src/main/groovy or whatever will address this, then I'll probably just do that and call it good.  Thanks for the help!
