### ISSUE TITLE
Installation instructions on wiki have incorrect links for snapshot repos

### ISSUE THREAD

**Issue by mindcrime** [groovy/groovy-eclipse#1453]
The wiki page here:

https://github.com/groovy/groovy-eclipse/wiki

has this listing:

4.27 (2023-03) | https://groovy.jfrog.io/artifactory/plugins-shapshot/e4.27
4.26 (2022-12) | https://groovy.jfrog.io/artifactory/plugins-shapshot/e4.26
4.25 (2022-09) | https://groovy.jfrog.io/artifactory/plugins-shapshot/e4.25

note the typo "shapshot" instead of "snapshot" in each of these URLs.

**Comment by eric-milles** [comment]
Fixed. Thanks for spotting that.
