### ISSUE TITLE
Snapshot publication for 4.24?

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1459]
I note that with the migration to a new repository, snapshot builds targeting 4.24 were dropped. My team reverted to 4.24 after getting burned by some of the breaking changes, but I would like to continue running the GRECLIPSE snapshots for feedback and debugging. Would it be possible to re-enable 4.24 without too much trouble?

**Comment by eric-milles** [comment]
4.25+ use common tools -- Java 17, Maven 3.8, Tycho 2.7.5

You can build your own snapshot update site by downloading source and running `mvn -Pe4.24 package` from the root.
