### ISSUE TITLE
Grails 3.1.0.M2 and Eclipse Mars: Groovy:Could not find class for Transformation Processor org.grails.compiler.injection.test.TestForTransformation declared by grails.test.mixin.TestFor

### ISSUE THREAD

**Issue by tvinke** [groovy/groovy-eclipse#146]
Software
- Groovy Eclipse compiler (2.9.2.xx-201508121448-e45)
- Eclipse Mars (4.5.1 20150924-1200)
- Grails 3.1.0.M2 

Steps
- Generated a unit test in on the command-line in my project with `create-domain-class Sample` 
- This also generates a `SampleSpec` which looks like 

``` groovy
package test.Sample

import grails.test.mixin.TestFor
import spock.lang.Specification

/**
 * See the API for {@link grails.test.mixin.domain.DomainClassUnitTestMixin} for usage instructions
 */
@TestFor(Sample)
class Sample extends Specification 
```
- Refreshed the project in Eclipse. Now there's a red cross before the "package ..." line with an errror: `Groovy:Could not find class for Transformation Processor org.grails.compiler.injection.test.TestForTransformation declared by grails.test.mixin.TestFor`

**Comment by greggvarona** [comment]
I had the same error before and every time I try to execute a specification/test, I get a `java.lang.VerifyError`. In case you haven't found the solution yet, I fixed my problem by upgrading my JDK. Try upgrading to the latest JDK, and if that still doesn't work there might really be a problem with the groovy/grails classes.
