### ISSUE TITLE
Support for Java style lambda expression.

### ISSUE THREAD

**Issue by StellarH** [groovy/groovy-eclipse#1464]
Java style Lambda Expression is supported in groovy-3.0. But when I use it, groovy analyzer of this plugin reports an error. And it still can run generally.

**Comment by eric-milles** [comment]
This has been supported for a long time now.  It is not on by default until release 5.0.0.

> The new antlr4-based Parrot Parser is disabled by default. To enable it, add `-Dgroovy.antlr4=true` to your eclipse.ini file after the -vmargs line or add a compiler config script to your project with `configuration.pluginFactory = org.codehaus.groovy.control.ParserPluginFactory.antlr4()`. Please note that parser recovery is not implemented for the Parrot Parser, so your editing experience may be sub-par in this mode.
