### ISSUE TITLE
Maven central repo cannot obtain this dependency

### ISSUE THREAD

**Issue by wangshuai67** [groovy/groovy-eclipse#1480]
Hello, why am I unable to obtain this dependency in Maven Central Repo

**Comment by eric-milles** [comment]
I do not have the resources to meet the Maven Central requirements without additional support.  You can obtain `groovy-eclipse-batch` and `groovy-eclipse-compiler` from https://groovy.jfrog.io/artifactory/plugins-release-local/org/codehaus/groovy/
