### ISSUE TITLE
unable to unlock jenkins

### ISSUE THREAD

**Issue by MaheshwariVasam** [groovy/groovy-eclipse#1490]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/ubuntu/.jenkins/war/WEB-INF/lib/groovy-all-2.4.21.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-06-27 12:17:33.077+0000 [id=29]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
2023-06-27 12:17:33.099+0000 [id=22]    INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running

**Comment by eric-milles** [comment]
Illegal reflective access warnings do not block groovy from working.  There are fewer and fewer of these if you move from Groovy 2.4 to 3.5 or 3.0 or 4.0.
