### ISSUE TITLE
Tab/Space related preference should not be inherited from Java Editor.

### ISSUE THREAD

**Issue by sbernard31** [groovy/groovy-eclipse#1495]
I'm using Groovy Editor to format my JenkinsFile and I want 2 spaces indentations.
But I want to keep my 4 spaces indentation for my java files.
I think for now this is impossible because : 

![Capture d’écran de 2023-07-21 10-42-04](https://github.com/groovy/groovy-eclipse/assets/840294/489bd747-df26-4a71-8e62-a3ac9d9fb5c4)

**Comment by eric-milles** [comment]
Many preferences are shared with java tools, but the preferences are read from 3 places.  So you can override any setting that is shared with a groovy-specific value.  For example you can add a line to `workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.codehaus.groovy.eclipse.ui.prefs`

```properties
eclipse.preferences.version=1
...
org.eclipse.jdt.core.formatter.tabulation.size=8
```

**Comment by sbernard31** [comment]
Thx it seems to work. :pray: 

(Too bad there is no UI about it)
