### ISSUE TITLE
Is Groovy-Eclipse plugin causing problems with evaluating variables in the debugger?

### ISSUE THREAD

**Issue by davidmichaelkarr** [groovy/groovy-eclipse#1506]
I was noticing that while debugging Java applications in Eclipse, I found that the Debug Shell wasn't working at all, giving me unhelpful ClassNotFoundExceptions when I tried to evaluate anything.  I was somehow finally able to get it to hit a breakpoint where it was throwing the CNFE, and I found it was a Groovy class.  I created the following issue in eclipse.jdt.debug: https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/295 .

My groovy-eclipse version is 5.1.0.v202308151946-e2306 .

**Comment by eric-milles** [comment]
Yes. https://github.com/groovy/groovy-eclipse/wiki/5.0.0-Release-Notes#debug-support

As noted there, you can disable by adding "-Declipse.groovy.debug=false" to your _eclipse.ini_ file.  Also, this is only active for projects with the Groovy nature.

**Comment by davidmichaelkarr** [comment]
Ok.  I think this might have fixed it. I changed two things at the same time (also went back from Groovy 4 to Groovy 3), and it now works, but this seems more likely.
