### ISSUE TITLE
How can I install previous version (4.xx) of the development tools in Eclipse

### ISSUE THREAD

**Issue by sbayeta** [groovy/groovy-eclipse#1507]
Hi guys, I just searched for this in the issues but couldn't find anything. Is it possible to install previous versions? The marketplace only shows version 5, and that version doesn't include the 2.5x compiler, which I need in a project.
Could anyone please suggest a method for installing previous versions?
Thanks!
Santiago

**Comment by eric-milles** [comment]
There are links for past release updste sites at the end of the release notes.  https://github.com/groovy/groovy-eclipse/wiki/4.9.0-Release-Notes#update-sites

You can also add the [Groovy 2.5 compiler bundle](https://groovy.jfrog.io/artifactory/plugins-release/org/codehaus/groovy/groovy-eclipse-integration/4.9.0/e4.27/plugins/org.codehaus.groovy_2.5.22.v202303311542-e2303.jar) to the eclipse _dropins_ folder for release 5.0.0 -- I needed a compatibility bridge for the transition to Groovy 3.

**Comment by sbayeta** [comment]
Thanks for your reply!!
