### ISSUE TITLE
Trait properties and methods ignored

### ISSUE THREAD

**Issue by injecteer** [groovy/groovy-eclipse#1509]
Using 
`Eclipse Build id: 20230608-1333`
`Eclipse Groovy Development Tools    5.0.0.v202306301519-e2306`

For a class:
```
import grails.gorm.annotation.Entity
import grails.mongodb.MongoEntity

@Entity
class Game implements MongoEntity<Game> {}
```
where the `MongoEntity `defines the methods like:
```
@CompileStatic
trait MongoEntity<D> implements GormEntity<D>, DynamicAttributes {
    static MongoCollection<Document> getCollection() {
        currentMongoStaticApi().getCollection()
    }
}
```
If I use the class in the code:

![image](https://github.com/groovy/groovy-eclipse/assets/32952/7d338752-c299-41de-b904-982b24f1d863)

it compiles and runs just fine, but the trait methods are underlined as "unknown" and also not resolved in autocomplete.

**Comment by eric-milles** [comment]
caused by: 97a612e8ec129dbcc63b94c552767a74efb12dc0

![image](https://github.com/groovy/groovy-eclipse/assets/18193802/7922cb3b-d46d-42e6-928d-9970219d2f73)

**Comment by eric-milles** [comment]
![image](https://github.com/groovy/groovy-eclipse/assets/18193802/91a8a9ea-3558-4796-bff0-adff1557db1a)
