### ISSUE TITLE
Cannot complete the install because one or more required items could not be found.

### ISSUE THREAD

**Issue by COMMANDERWONG** [groovy/groovy-eclipse#1516]
Full error:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Eclipse Groovy Development Tools 5.2.0.v202310061521-e2312 (org.codehaus.groovy.eclipse.feature.feature.group 5.2.0.v202310061521-e2312)
  Missing requirement: Eclipse JDT Core patch for Groovy 5.2.0.v202310061521-e2312 (org.codehaus.groovy.jdt.patch.feature.group 5.2.0.v202310061521-e2312) requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.19.300.v20230927-1806,3.19.300.v20230927-1806]' but it could not be found
  Cannot satisfy dependency:
    From: Groovy-Eclipse Compilerless feature 5.2.0.v202310061521-e2312 (org.codehaus.groovy.compilerless.feature.feature.group 5.2.0.v202310061521-e2312)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [5.2.0.v202310061521-e2312,5.2.0.v202310061521-e2312]
  Cannot satisfy dependency:
    From: Eclipse Groovy Development Tools 5.2.0.v202310061521-e2312 (org.codehaus.groovy.eclipse.feature.feature.group 5.2.0.v202310061521-e2312)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [5.2.0.v202310061521-e2312,5.2.0.v202310061521-e2312]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Headless feature 5.2.0.v202310061521-e2312 (org.codehaus.groovy.headless.feature.feature.group 5.2.0.v202310061521-e2312)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [5.2.0.v202310061521-e2312,5.2.0.v202310061521-e2312]
 
Anyone knows what leads to this error? just trying to install groovy development tool on 2023-12 version of the IDE.

**Comment by eric-milles** [comment]
The 2023-12 snapshot targets [2023-12 M1](https://download.eclipse.org/eclipse/downloads/drops4/S-4.30M1-202309271800/).  If you use any other version, it is likely that the JDT patch will fail.

**Comment by eric-milles** [comment]
It looks like the marketplace integration is trying to install the 2023-12 (4.30) components regardless of the version of eclipse you have.

**Comment by eric-milles** [comment]
https://gitlab.eclipse.org/eclipsefdn/it/websites/marketplace.eclipse.org/-/issues/220
