### ISSUE TITLE
Please provide updatesite.zip files for e4.5

### ISSUE THREAD

**Issue by gufertum** [groovy/groovy-eclipse#152]
Without zipped updates sites, Installation in a corporate environment is just impossible.

**Comment by hebaceous** [comment]
Please

**Comment by vesko50** [comment]
Could you please provide zipped version

**Comment by dongshen** [comment]
where to get zipped version?

**Comment by vesko50** [comment]
i used link https://github.com/groovy/groovy-eclipse (download ZIP), but it did not work for me

**Comment by eric-milles** [comment]
You can get the update site zip for any build from the CI server: https://build.spring.io/browse/GRECLIPSE

Ex: https://build.spring.io/browse/GRECLIPSE-GE45-225/artifact
