### ISSUE TITLE
Go to Help > Install New Software... not works anymore with current Groovy Eclipse repositories

### ISSUE THREAD

**Issue by Zardoz89** [groovy/groovy-eclipse#1520]
Every https://groovy.jfrog.io/ui/native/plugins-release/e4.XX (for example https://groovy.jfrog.io/ui/native/plugins-release/e4.24 ) requeires JavaScript. If not, then returns an HTML page saying that JavaSCript it's required to browse that page. That results in Eclipse throwing errors triying to pares the sitte and unable to get the Groovy Eclipse plugins.

**This has the really nasty side effect that** the current way of installing Groovy Eclipse it's using the marketplace, and **don't allows to update Groovy Eclipse on users that can't update Eclipse to the last version** (Marktplace always tries to use the version for the last Eclipse ... currently 4.30)

The repository MUST not requiere JavaScript to allow to access to the content.

**Comment by Zardoz89** [comment]
Anyone cant verify this running curl https://groovy.jfrog.io/ui/native/plugins-release/e4.24 and how returns a page that uses VUE ☠️

**Comment by eric-milles** [comment]
The update site links are listed here:
https://github.com/groovy/groovy-eclipse/wiki#releases
https://github.com/groovy/groovy-eclipse/wiki#snapshots

When you try to view in a browser you will be redirected to the "native" pages.  They are not part of the update sites and are not meant for eclipse consumption.

**Comment by eric-milles** [comment]
The marketplace bug has been resolved as well: https://gitlab.eclipse.org/eclipsefdn/it/websites/marketplace.eclipse.org/-/issues/220

**Comment by Zardoz89** [comment]
@eric-milles **These links don't work**  
![imagen](https://github.com/groovy/groovy-eclipse/assets/888483/8bb44b15-8038-40ec-946a-47f8353d4d14)

I testes it with https://groovy.jfrog.io/ui/native/plugins-release/e4.27

**Comment by eric-milles** [comment]
That is not the correct update site.  You should be using: https://groovy.jfrog.io/artifactory/plugins-release/e4.27

**Comment by Zardoz89** [comment]
Thanks!
