### ISSUE TITLE
Eclipse doesn't see extension methods

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1529]
I have a multimodule Maven project where a dependency module defines some extension methods and then the main module uses them. After a reinstall upgrading to the latest, Eclipse does not appear to resolve the extension methods, and I am getting "Cannot find matching method" and downstream errors on apparently every use of my own extension methods.

In the past, doing a clean of the extension-method module and the main module would clear up extension-methods-not-found, but that's not working anymore. The CLI build works correctly.

GRECLIPSE 5.3.0.v202401011440-e2312
STS 4.21.0 (a recent clean-install upgrade from 4.16.0)
Eclipse Platform 4.30.0.v20231201-0512
M2E Maven Integration for Eclipse Core 2.4.200.20231119-0901

**Comment by eric-milles** [comment]
Can you show in the Package Explorer how the dependency module appears on the classpath of the main module?

**Comment by chrylis** [comment]
This is weird: It was persisting across global and selective cleans, restarts, and branch changes. Now, however, I closed the extension-module projects (leading to `!` markers) and reopened them... and it appears working and stable. I haven't been able to trigger the bug again. I'll keep watch for anything more specific. In the meantime, it appears it may have been some glitchy interaction between GRECLIPSE and m2e, but I can't figure out more.

![package-explorer-dependencies](https://github.com/groovy/groovy-eclipse/assets/2394512/a1bdddb0-15c7-4dd0-a3bc-15f2eca34a9d)
