### ISSUE TITLE
Why are patches carried forward with each GDT release?

### ISSUE THREAD

**Issue by andrew-tram** [groovy/groovy-eclipse#1535]
Why is the patch for `org.eclipse.jdt.core` carried forward with each GDT release rather than committing those changes into the Eclipse JDT Core project https://github.com/eclipse-jdt/eclipse.jdt.core ?

**Comment by eric-milles** [comment]
I have made several attempts to incorporate patches into the core project.  Long story short, they are not accepted without a strong test case that demonstrates value for a vanilla java project.
