### ISSUE TITLE
how to get groovy 2.4.15 compiler on the latest groovy eclipse plugin

### ISSUE THREAD

**Issue by ksanjeev9211** [groovy/groovy-eclipse#1536]
I have a legacy project based on java 8, groovy 2.4.15, and spock 1.4. 
Not able to compile the groovy classes on latest eclipse/STS with the groovy eclipse plugin 4.30,  as there is no groovy 2.4.15 compiler available. Any suggestion what shall I do get it working.

**Comment by eric-milles** [comment]
The last GDT to support Groovy 2.4 was [3.9.0](https://github.com/groovy/groovy-eclipse/releases/tag/v3.9.0).  You can still install it into any supported release of Eclipse: 4.9 - 4.17

If you want or need to use Eclipse 4.30 then you must use GDT [5.2.0](https://github.com/groovy/groovy-eclipse/releases/tag/v5.2.0).  You can still build a project that has Groovy 2.4 code in it with decent confidence.  There may be some STC differences but they should not be too hard to work out.  On the project's Groovy Compiler prefs page, you would change the drop-down from "2.4" to "I don't care" to suppress the compiler mismatch warning.

![image](https://github.com/groovy/groovy-eclipse/assets/18193802/bb544b9d-d3e7-415f-b20e-358d7a028091)

**Comment by ksanjeev9211** [comment]
Hi Eric, 
Thanks for your timely response and apologies for commenting here so late.
Probably I had tried similar thing before also and once again I tried following your advice, however, Spock is still not happy with this arrangement. I still get the following compilation error in my Test classes.

![image](https://github.com/groovy/groovy-eclipse/assets/4118153/01646f18-5a21-41c0-bf6f-1d9fd0da4cc0)

Despite selecting compiler version ass 'I don't care' for this project,  Spock still complains about the mismatch. 

Following is my Windows-> Preference-groovy-Compiler settings in STS/Eclipse:

![image](https://github.com/groovy/groovy-eclipse/assets/4118153/826f9aee-2722-47dd-93b1-2a38351a2e5b)

**Comment by ksanjeev9211** [comment]
If required,  to reproduce the issue,  I can upload a sample project from my personal laptop.

**Comment by eric-milles** [comment]
Yes, spock is a little more strict.  You could temporarily change the spock version that you use.  Or you can use an older eclipse version.  Adding back Groovy 2.4 and 2.5 compatibility to the latest eclipse would be quite costly.

**Comment by natalie9200** [comment]
I have a similar problem and I also wonder why the current plugin doesn't support Groovy 2.5 anymore. Groovy 2.5 is still officially supported and widely used.
One more reason why I hate Eclipse :-(

**Comment by eric-milles** [comment]
@natalie9200 You can still use [4.9.0](https://github.com/groovy/groovy-eclipse/wiki/4.9.0-Release-Notes) which support Eclipse from 4.9 through 4.27 for Groovy 2.5 development.  Groovy 2.5 has changed very little since this release.

As for why did GDT move to Groovy 3 as the minimum.  Since Eclipse 4.25+ requires Java 17 to build.  There was no easy path to add support for Eclipse 4.25+ and retain support for Groovy 2.5, which only supports Java up to 15.
