### ISSUE TITLE
Compiler uses different bytecode method after upgrading spring boot

### ISSUE THREAD

**Issue by tomaszburdka-oc** [groovy/groovy-eclipse#1553]
Hi, I have a problem, because after upgrading spring-boot version in my project I cannot run my app properly.
After spring-boot upgrade from 2.4.2 -> 2.7.18 below code stop working:

```
import com.mycompanyname.scheduler.config.EnableScheduler
import com.mycompanyname.textlocalization.job.*
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

@EnableScheduler(
    jobClasses = [
        DisputeReportJob,
        ModifiedSourceValuesReportJob,
        DeutschApprovalReportJob,
        ForAgencyReportJob,
        IncorrectStandardMessagesReportJob,
        NotUpdatedYetReportJob,
        ModifiedMessageDuplicatesReportJob,
    ],
    tablePrefix = "TL_QRTZ_",
    changeLogTablePrefix = "TL_",
    quartzProperties = [
        "org.quartz.jobStore.misfireThreshold=100",
    ]
)
```
I realized that compiler uses different method of ScritBytecodeAdapter.class. After change it uses:
```     
public static void setGroovyObjectProperty(Object messageArgument, Class senderClass, GroovyObject receiver, String messageName) throws Throwable {
        try {
            receiver.setProperty(messageName, messageArgument);
        } catch (GroovyRuntimeException var5) {
            throw unwrap(var5);
        }
    }
```
which provides to error and code is not working as expected. Code worked before upgrade (so in spring-boot 2.4.2). Compiler in old version used:
```   
public static void setProperty(Object messageArgument, Class senderClass, Object receiver, String messageName) throws Throwable {
        try {
            if (receiver == null) {
                receiver = NullObject.getNullObject();
            }

            InvokerHelper.setProperty(receiver, messageName, messageArgument);
        } catch (GroovyRuntimeException var5) {
            throw unwrap(var5);
        }
    }
```
Do you know if there is a way of configure compiler to use the different old method?

**Comment by eric-milles** [comment]
Which property reference in your example is getting this different treatment?  The selection between these two methods during classgen is usually based on whether or not the target object implements `GroovyObject`.  However a change in type inference could cause this as well.

Can you produce a small example that demos the issue?  One that could be switched back and forth between the different Spring Boot versions.  You can make a script that uses `@Grab` to import dependencies instead of a whole gradle/maven project.

**Comment by tomaszburdka-oc** [comment]
I had to upgrade groovy version from 2.5.14 to 3.0.19 (same as in spring-boot pom) and it solved the problem.
