### ISSUE TITLE
incremental compiler erroneously removes AST annotations from fields

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#156]
I'm writing an AST transformation that's similar to JPA's `@OneToOne` in that the annotation should be applied to matching fields on separate classes. In my transformation class, I look up the field on the "other" class that corresponds to the back reference and verify that it carries the annotation. This is failing in the incremental compiler only; in the incremental compiler, annotations corresponding to AST transformations are removed from fields, regardless of the retention policy of those annotations.

This bug does not appear to affect transformation annotations applied to types or methods, only fields.

**Comment by eric-milles** [comment]
Is this still an issue?  Could you provide a code example that I could test with?

**Comment by eric-milles** [comment]
I'm guessing this has to do with the phase the transformation runs in.  When editing a project with incremental compile enabled, the file is processed to different phases for different reasons.
