### ISSUE TITLE
Recent updates of groovy-eclipse are all failing with "Unexpected end of ZLIB input stream"

### ISSUE THREAD

**Issue by davidmichaelkarr** [groovy/groovy-eclipse#1581]
In the past few weeks, every time I've attempted to update the groovy-eclipse plugin in my 2024-03 Eclipse, it fails with this:

An error occurred while collecting items to be installed
session context was:(profile=C__Users_dk068x_eclipse_java-2024-03_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,org.codehaus.groovy,3.0.21.v202405141705-e2403.
Unexpected end of ZLIB input stream
Problems downloading artifact: osgi.bundle,org.codehaus.groovy,4.0.21.v202405141705-e2403.
Unexpected end of ZLIB input stream

**Comment by eric-milles** [comment]
I just uploaded a new 4.31 and 4.32 snapshot.  Can you restart eclipse and update?  If it still fails, can you try the non-aggregated site link: https://groovy.jfrog.io/artifactory/plugins-snapshot-local/e4.31

**Comment by eric-milles** [comment]
I was able to install from the snapshot site, so it is not an issue with the files.  Do you have a proxy or vpn enabled?  Are you able to try the update from another network just to check?

**Comment by davidmichaelkarr** [comment]
Yes, I'm on VPN with a proxy.  I tried disconnecting from VPN and disabling the proxy. That did slightly change the results, but the final result was the same. I wouldn't be at all surprised if my security-paranoid organization figured out how to block things in the Windows image we use. However, I'm not having problems with other plugins.

An error occurred while collecting items to be installed
session context was:(profile=C__Users_dk068x_eclipse_java-2024-03_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at https://groovy.jfrog.io/artifactory/plugins-snapshot/e4.31/plugins/org.codehaus.groovy_3.0.21.v202405181214-e2403.jar.
Connect to https://groovy.jfrog.io:443 [groovy.jfrog.io/34.123.170.31] failed: Read timed out
Unable to read repository at https://groovy.jfrog.io/artifactory/plugins-snapshot/e4.31/plugins/org.codehaus.groovy_4.0.21.v202405181214-e2403.jar.
Connection reset
