### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mustangxu** [groovy/groovy-eclipse#160]
Last commit was 3 months ago, no support for e4.5 Mars, no progress on the issues... Any alternatives to this plugin for developers on Eclipse platform?

**Comment by effrafax** [comment]
Yes, I think so. Pivotal dropped it's support for groovy and grails during this year and this project was mainly developed by Pivotal developers too. Seems they abandoned it, leaving it for the community.

**Comment by kenwdelong** [comment]
This is pretty nasty.  All of my projects are joint Java/Groovy and they all depend on this project.  What are the alternatives?

Pivotal certainly lost my business!

**Comment by PascalSchumacher** [comment]
@mustangxu You can use the plugin with Eclipse Mars if you install the latest snapshot as explained in https://github.com/groovy/groovy-eclipse/wiki I use it almost every day.

@kenwdelong I guess the best free option is Intellij community edition. Netbeans also offers support for Groovy, but I do not know how good it is.

**Comment by kenwdelong** [comment]
@PascalSchumacher  Thanks for the response.  The problem for me is not the IDE, but the Maven builds.  If I can't build the software it's a big problem.

I wonder if I can tell Maven to use groovyc for the entire project?  I'll have to do some more research.

**Comment by PascalSchumacher** [comment]
@kenwdelong I guess you could switch to https://github.com/groovy/GMavenPlus

**Comment by kenwdelong** [comment]
cool, thanks!
