### ISSUE TITLE
Add support for InvokeDynamic (indy)

### ISSUE THREAD

**Issue by kriegaex** [groovy/groovy-eclipse#161]
Hi.

This is more of a question referring to an old Codehaus [mailing list thread](http://groovy-eclipse-plugin.42567.n3.nabble.com/groovy-eclipse-compiler-for-Maven-and-Invoke-Dynamic-support-td4025232.html) (is there a new ML?) and to [this ticket](http://jira.codehaus.org/browse/GRECLIPSE-1582) which I can find nowhere else:

Is invokedynamic supported now?

Background: We currently use invokedynamic support via indy from GMavenPlus and additionally use the Eclipse compiler from IntelliJ IDEA because it is much faster and less problematic with recompilation compared to the standard Groovy compiler. In order for it to be in sync with what we do in Maven I would like to know if indy is now supported by Greclipse. We might then also switch to the Greclipse compiler plugin in Maven.

**Comment by aclement** [comment]
Hey. Unfortunately no. The groovy compiler is patched for inclusion in groovy-eclipse - patched to improve error reporting, have recoverable parsing, better incremental behaviour, etc.  We had to pick which version to patch and picked the non-indy one. If the indy one were patched in the same way then it could be used.  (Actually I might be using old information - back when I last looked at this they were separate jars: indy and non-indy. If it is all in one jar now then the patched groovy just needs to be brought up to the latest level and you could do it).

**Comment by eric-milles** [comment]
I think you could use the indy version of groovy-all in your pom and pass the indy argument to the compiler plugin. Although I have not tried this myself.
