### ISSUE TITLE
How to patch new JDT versions

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#165]
I would like to know what your technique is to patch new versions of JDT. Do you simply commit the whole JDT project and then search for //Groovy comments in the previous version?
I am asking because I'm interested to patch the jdt that comes with mars sr1 and also keep up to date with future jdt versions. I could do this in some spare time.

**Comment by aclement** [comment]
Hey. What I would typically do is grab the version of JDT I am interested in, have it in my workspace alongside the patched version of JDT from groovy-eclipse, then merge across all the JDT changes into the groovy-eclipse variant. This can take a little while - especially if it is a long time since it was done previously. However, it is usually straightforward unless something serious has changed in JDT that requirements the groovy-eclipse patch to be drastically refactored.  Searching for the comment tags left in around changes might get it done but I can't guarantee the tags are all correct (they should be but you never know where a rushed change didn't get tagged), hence the full diff process.

The tests will likely tell you if you messed up. I know we put up a wiki page on the process for upgrading the groovy version in groovy-eclipse ( https://github.com/groovy/groovy-eclipse/wiki/Updating-the-groovy-in-groovy-eclipse ) but never quite got around to the version for updating the jdt patch.

In an ideal world the patches would be better formatted so that a git merge could apply them to a new JDT level, rather than the manual process being necessary. Then updating to a new JDT could be pretty automatic.

**Comment by felixdo** [comment]
How about maintaining a clone of jdt and then continually rebasing the groovy patch(es) on top?

**Comment by aclement** [comment]
Sure thing, if i had the time I'd go down that route. I'd love to have the upgrading process more automated (so leave it to git in that case). Some of the existing patch will need massaging to try and ensure it reliably cleanly applies.

**Comment by felixdo** [comment]
For me it looks just like one giant patch :). But probably it is possible to split it up into distinct smaller meaningful chunks.

**Comment by felixdo** [comment]
Ok so I am experimenting with the rebase approach. You can find it here: https://github.com/felixdo/eclipse.jdt.core 

To update, I just git pull --rebase

I also managed to build the jdt plugin with the instructions provided here: https://wiki.eclipse.org/Platform-releng/Platform_Build#Building_Selected_Projects

Do you think we could try and go ahead with this approach? What's missing currently is to push the patched bundle into a feature patch and supply that patch on an update site. The groovy-eclipse build would then just use that update site. The advantage would also be that we wouldn't need to update groovy-eclipse whenever jdt changes I guess.

**Comment by felixdo** [comment]
I have one doubt about some code of jdt that the patch seems to have removed but without any comments. Could you look at

https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration.java#L162

vs 

https://github.com/groovy/groovy-eclipse/blob/master/jdt-patch/e46/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration.java#L161

A git blame shows that the jdt code that misses from the greclipse patch was committed in november so it _should_ really also be present in the patch?

**Comment by aclement** [comment]
Not sure. Recent patch jobs have been done in a rush, maybe it was missed. If no test case was hitting a problem then it may not have been noticed. The patched version of jdt is still not currently run against the JDT test suite (which it should be).  RE: your comment of Apr 22 - if you have it all ready to go, I'm probably happy to switch to using your up to date patch (if the update site is reliable).

**Comment by felixdo** [comment]
If we ever have to remove some jdt code it shouldn't be done without commenting. I would guess you think the same so probably just missed it.

Regarding the patch itself, my questions to eclipse-releng led to opening https://bugs.eclipse.org/bugs/show_bug.cgi?id=497840 which explains how they do their Java9 Beta Feature Patch for JDT, and it's a pita compared to how you build the patch (I'm not sure why they need tons of tricks where here it's straightforward..). So I am now experimenting with an intermediate solution: We pull in a fork of eclipse.jdt.core that contains the patch as a submodule to groovy-eclipse and build almost the same way as now, only that the submodule pom inherits from its eclipse parent so that it's being build the exact same way it's done for eclipse. I think I have it almost working but need some more testing and clean up. I'll tell you when I have something.

**Comment by felixdo** [comment]
Andy, I am on vacation now, so I won't work on this for a few weeks. If you want you can test the whole build by checking out the felix/bug165 branch together with the jdt fork submodule on my groovy-eclipse fork:

$git clone ... -b felix/bug165 --recursive

I have updated the e46 profile to use the new system, so this will build greclipse + the jdt.core 4.6 maintenance branch + the greclipse jdt patchset:

mvn -Pe46,build-individual-bundles -DskipTests=true clean verify

(the build-individual-bundles profile is coming from jdt). Note that when I build with tests, I have about 16 failures in the groovy-all suite and some failures in the jdt suite.

The result installs fine into neon, but I wouldn't go as far as saying it's ready to be merged, but I'm confident that we can use the new system to for the neon service release (IIRC that's in december?)

**Comment by eric-milles** [comment]
@felixdo Thanks for doing this.  I have been using your JDT Core patch and things are running quite smoothly.  I have a small patch for type inferencing errors found by the Greclipse unit tests.  Could you please apply it to your greclipse/e46 branch?  [felixdo-jdtcore.patch.txt](https://github.com/groovy/groovy-eclipse/files/498782/felixdo-jdtcore.patch.txt)

Also, Eclipse Neon SR1 is now out.  Could you rebase your branch to that point?

**Comment by felixdo** [comment]
Eric, I rebased the patch onto master and R4_6_maintenance branches and updated my groovy-eclipse branch for this bug to use R4_6_maintenance. Feel free to test if that builds, I didn't test it.
As for your patch, please rebase it onto that and format it so you get credit. (https://git-scm.com/docs/git-format-patch)

**Comment by eric-milles** [comment]
@felixdo I'm using eGit from within Eclipse.  Do you know how to do the formatting from there?  Or can I submit patches as they export eGit and you can post-process them?
