### ISSUE TITLE
Greclipse prevent the use of the new Mars.2 (or even Mars.1) JDT code

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#168]
After experiencing the problem described at:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488703
I determined that it's the Groovy Eclipse plugin fault. Substantially, it seems like it's carrying in some old JDT code that is being used instead of the one updated with Mars.1 and Mars.2.

I know this plugin is not maintained any more, but could at least a newer version be packaged, based on Mars.2 JDT? Thank you.

**Comment by aclement** [comment]
Would you be satisfied with a jump to Neon and skipping mars ?

**Comment by mauromol** [comment]
Of course, given the current situation any action would be appreciated.

IMHO, however, an updated Greclipse for Mars.2 would ensure to include all fixes (and especially regression fixes!) applied to JDT over the last 8 months of refinements over the Mars release and would be a good choice for however won't upgrade to Neon for whatever reason.
Also, Neon is not quite there until June (4 months)...

On the other hand, I was even wondering if not providing a Neon version of Greclipse at all would be paradoxically beneficial to Greclipse: maybe at last someone with the required skills and resources will take some action on this?

I really can't believe nobody in the world is caring about the future of Groovy support in Eclipse! Am I the only one who still uses it in Eclipse projects? :(

**Comment by aclement** [comment]
> On the other hand, I was even wondering if not providing a Neon version of Greclipse
> at all would be paradoxically beneficial to Greclipse: maybe at last someone 
> with the required skills and resources will take some action on this?

That is my other option. Do nothing.  I see from the github issues a few people do still seem to be using it.

**Comment by mauromol** [comment]
Well, if you decide to "do nothing" for Neon, please consider a Greclipse update based on Mars.2, so that we can at least "rest in piece" with a final Mars-compatible release of Greclipse... In this way, current Greclipse users like me will have the option to stick with a good Mars Eclipse IDE if they can't quickly switch away from Groovy in the near future...

**Comment by aclement** [comment]
Unfortunately I've moved on from Mars, bugs like this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=488795 make it rather useless to some of my team - the only proper ship vehicle for that fix is Neon (bizarrely). If I have bandwidth to do anything for greclipse, I'd do the Neon thing.  If there are specific fixes you need from mars, you could dig out the commits from JDT and apply them to the groovy jdt patch and submit a PR, that wouldn't seem too tricky. Much less effort than a full upgrade.

**Comment by aclement** [comment]
I saw you reference the formatter issue in particular so I had a look, it was a one line change so I just folded that into the JDT patch for e45. So todays update site actually includes that fix.

**Comment by mauromol** [comment]
Thank you very much Andy!

**Comment by aclement** [comment]
Just FYI, neon update site is up: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/
