### ISSUE TITLE
Problem installing on Mars.2

### ISSUE THREAD

**Issue by rsgratien** [groovy/groovy-eclipse#169]
Hello, I have this error trying to install Groovy-Eclipse in a fresh Eclipse installation (version Mars.2). It was working fine some days ago.

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/plugins/org.codehaus.groovy_2.3.10.xx-201601131831-e45.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/plugins/org.codehaus.groovy_2.3.10.xx-201601131831-e45.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/features/org.codehaus.groovy.compilerless.feature_2.9.2.xx-201601131831-e45.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/features/org.codehaus.groovy.compilerless.feature_2.9.2.xx-201601131831-e45.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/plugins/org.codehaus.groovy.eclipse_2.9.2.xx-201601131831-e45.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/plugins/org.codehaus.groovy.eclipse_2.9.2.xx-201601131831-e45.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/plugins/org.codehaus.groovy.eclipse.ant_2.9.2.xx-201601131831-e45.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/plugins/org.codehaus.groovy.eclipse.ant_2.9.2.xx-201601131831-e45.jar

**Comment by aclement** [comment]
I think this is me tinkering with trying to get something that will install on Neon. Let me repair that damage.

**Comment by aclement** [comment]
I kicked off a rebuild, seems to install ok now into Mars.

**Comment by rsgratien** [comment]
Hello,

Thanks for your prompt action.
I just re-tried and now I have another error message :-( (see below)
I know that I'm behind a proxy (here at work). Can this be the cause of my problem?

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.codehaus.groovy,2.3.10.xx-201603021634-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.compilerless.feature,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ant,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.astviews,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codeassist.completion,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codebrowsing,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.compilerResolver,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.core,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.dsl,2.9.2.xx-201603021634-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.eclipse.feature,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.quickfix,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.refactoring,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ui,2.9.2.xx-201603021634-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.headless.feature,2.9.2.xx-201603021634-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.jdt.patch,2.9.2.xx-201603021634-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy23.feature,2.9.2.xx-201603021634-e45
No repository found containing: osgi.bundle,org.eclipse.jdt.core,3.11.0.xx-201603021634-e45
No repository found containing: osgi.bundle,org.eclipse.jdt.groovy.core,2.9.2.xx-201603021634-e45

**Comment by aclement** [comment]
Hmm, I just downloaded a fresh mars.2 jee, and installed from the 45 update site ok. My colleagues tell me your error could be proxy related or repo caching related. Easiest way to ensure you aren't hitting the latter is just to restart eclipse.

**Comment by rsgratien** [comment]
Hello,

I tried an install from home (where I have no proxy) and it installs OK. The proxy I have at work must be the culprit. I'll address this internally within my company.

Thanks for your support.
