### ISSUE TITLE
eclipse 4.5.2 SubMonitor error 

### ISSUE THREAD

**Issue by wangshiyang** [groovy/groovy-eclipse#172]
`An internal error occurred during: "Initializing Java Tooling".
org.eclipse.core.runtime.SubMonitor.split(I)Lorg/eclipse/core/runtime/SubMonitor;`

use [http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/](url)

**Comment by ascrus** [comment]
I got the same error on Eclipse Mars. Changed to Eclipse Neon, everything works fine.

**Comment by wangshiyang** [comment]
when i changed http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/
the problem is solve.
