### ISSUE TITLE
JDT code status of Groovy (integration of fixes)

### ISSUE THREAD

**Issue by maggu2810** [groovy/groovy-eclipse#181]
Hello,
I recently run into this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=465693#c14

"Groovy replaces the JDT bundles with a hacked version, and I don't know whether they ship a version that includes 4.5.1"

I have also read: https://github.com/groovy/groovy-eclipse/issues/168
If my reading is correct, there will be no fixes for Mars.

Is this correct?

**Comment by aclement** [comment]
The only upgrade route currently is to move to Eclipse 4.6 - there is a groovy-eclipse for that version which includes fixes beyond what was in Eclipse 4.5. It may include a fix you need. (Although I have to say I haven't tried installing that groovy-eclipse into the most recent eclipse 4.6 builds.)

**Comment by maggu2810** [comment]
Oh, sorry for keeping it open such long time.
