### ISSUE TITLE
Compile only groovy files

### ISSUE THREAD

**Issue by danielburrell** [groovy/groovy-eclipse#183]
Is it possible for groovy-eclipse-compiler to compile just groovy code rather than both java and groovy? 

I want the regular java compiler to be invoked for java (src/main/java, src/test/java), and the groovy-eclipse-compiler used exclusively for anything in src/main/groovy or src/test/groovy. I can't find an example of this on the wiki.
`
<plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <compilerId>groovy-eclipse-compiler</compilerId>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>2.9.1-01</version>
                    </dependency>
                    
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.3.7-01</version>
                    </dependency>
                </dependencies>
            </plugin>
`

**Comment by eric-milles** [comment]
Groovy does not compile Java.  It delegates this task to javac in a typical command-line or Ant setting and to ecj in an Eclipse or maven setting.  If you want total isolation in a maven setting, you should put Java sources in src/main/java and Groovy/Java interdependent sources in src/main/groovy.
