### ISSUE TITLE
Eclipse Neon dark theme issues

### ISSUE THREAD

**Issue by jbaranski** [groovy/groovy-eclipse#184]
Is this an eclipse thing or something that can be changed in the plugin you offer?

Notice how the imports and variables are black... 

![image](https://cloud.githubusercontent.com/assets/10889950/16357511/e9ad8a54-3ac6-11e6-8532-0da4e43a8dea.png)

**Comment by eric-milles** [comment]
In preferences under Groovy, there are a few color settings that can be changed. They don't inherit from the Java colors at the moment.
