### ISSUE TITLE
How to run a groovy script at generate-source phase

### ISSUE THREAD

**Issue by CrowleyPrograms** [groovy/groovy-eclipse#187]
Hello everyone and thanks for taking your time to read through this!
This is the first time I work with groovy and I decided to write up a script to automatically create an enum out of a properties file.
So far so good, but how do I make the script compile at the generate-sources phase? I have only found solutions with maven, however I keep getting errors when I try to install this plugin via maven. Note: This is also the first time I am working with maven.

Have a nice day ~Crowley

**Comment by eric-milles** [comment]
This sounds like a question for a Maven forum.  You want to run an executable at a specific phase of a Maven build.  The fact that the process is a Groovy script is not important in this context.
