### ISSUE TITLE
Parameter type is ambiguous in Java5.java

### ISSUE THREAD

**Issue by hammenb** [groovy/groovy-eclipse#194]
I'm getting multiple build errors in this file when building with Eclipse:

https://github.com/groovy/groovy-eclipse/blob/master/attic/org.codehaus.groovy/src/org/codehaus/groovy/vmplugin/v5/Java5.java

The java.lang.reflect and org.codehaus.groovy.ast packages are both imported and both contain a Parameter class. Explicitly importing org.codehaus.groovy.ast.Parameter resolves the ambiguity and it builds without errors.

Am I doing something wrong, or does this need to be fixed?

**Comment by felixdo** [comment]
This was fixed in the master branch a few weeks ago.
