### ISSUE TITLE
Groovy: Arbitrary code execution Version < 2.4.5

### ISSUE THREAD

**Issue by gmkll** [groovy/groovy-eclipse#204]
To resolve [Groovy: Arbitrary code execution Version](https://security.gentoo.org/glsa/201610-01) at least groovy version 2.4.5 is required. Is there no other (easier) way to update the groovy in eclipse than https://github.com/groovy/groovy-eclipse/wiki/Updating-the-groovy-in-groovy-eclipse? May be just announce a fix for that soon? Thanks

**Comment by eric-milles** [comment]
There is a pull request for 2.4.7.  I also have 2.4.8 current with latest snapshot build.

**Comment by gmkll** [comment]
+1

**Comment by eric-milles** [comment]
2.4.7 has been merged; could you close this issue?

**Comment by gmkll** [comment]
ok, I close it, PR was #199..
