### ISSUE TITLE
IntelliSense not working properly in build.gradle: computeCompletionProposals() took too long

### ISSUE THREAD

**Issue by SilverJan** [groovy/groovy-eclipse#209]
I enabled the groovy-eclipse-plugin to support development in build.gradle files. But every time I write '<objectOrClassName>.' Eclipse is blocked, waits 5secs and then shows me the following error:

> The 'Groovy Code Completions' proposal computer from the 'org.codehaus.groovy.eclipse.codeassist.completion' plug-in did not complete normally. The extension took too long to return the 'computeCompletionProposals()' operation.'
> 
> To avoid this message, disable the 'org.codehaus.groovy.eclipse.codeassist.completion' plug-in or disable the 'Groovy Content' category on the content assist preference page.

IntelliSense in .groovy files works fine and without delay.

**Comment by eric-milles** [comment]
This should be fixed.  Can you retest with the latest snapshot?

**Comment by SilverJan** [comment]
Works. Thanks.
