### ISSUE TITLE
Latest release (11/9/2016) has issues

### ISSUE THREAD

**Issue by doktorjw** [groovy/groovy-eclipse#221]
Just updated to the latest release; projects that compiled fine are now showing issues. In this particular case, I'm using Groovy 2.2.2 (though the issue does not show using 2.3.11).

This issue is when using Groovy 2.2.2 (it is not present with 2.3.11): Create an inner class extending from an interface, and then use the quick fix to add unimplemented methods. The methods are all annotation with @Override, which is normal, but the compiler indicates this is an error. In my case, I implemented javax.persistence.AttributeConverter

An issue that exists when using both Groovy 2.2.2 and 2.3.11 is not as straight forward. We have a custom annotation that we use, which takes a class argument. For one particular class, UOM, this line is indicated as being in error, saying "Type mismatch: cannot convert from UOM to Class". Just a half dozen lines above, this same annotation is used with a different class without error. The line would be like:

@MyAnnotation( clazz = UOM, .... )

Changing clazz=UOM to clazz=UOM.class eliminates the error, but it shouldn't be necessary.

The only other issue I currently see in both 2.2.2 and 2.3.7 is in the use of another custom annotation, this one that takes a closure as an argument. I get an error that "The value for annotation attribute AlternateValueOnToMapConversion.closure must be a class literal" (my annotation is named AlternateValueOnToMapConversion and it takes an attribute of type Class to which we had always set a closure, like:

@AlternateValueOnToMapConversion( closure={ 2 * this.blah } )
Integer foo

The code the AlternateValueOnToMapConversion is easy enough:

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@interface AlternateValueOnToMapConversion {
  Class closure()
  String name()
}

**Comment by eric-milles** [comment]
Thanks for the report.  The closure for the annotation was a missed use case on my part.  I'll need to account for it when creating annotations within the Java model.

As for the override issue, does your error go away if you drop the override annotation?

**Comment by eric-milles** [comment]
I think it comes down to this block in GroovyCompilationUnitDeclaration.createAnnotationMemeberExpression:
```java
            } else if (expr instanceof VariableExpression) {
                String name = ((VariableExpression) expr).getName();
// TODO: Look up name to determine if it is a class or a constant
                if (name.matches("[a-z_]\\w*|[A-Z][A-Z_0-9]*")) {
                    // could be a class field or statically imported constant also...
                    return new SingleNameReference(name.toCharArray(), toPos(expr.getStart(), expr.getEnd() - 1));
                }
                // likely a class literal; Groovy does not require ".class"
                return new ClassLiteralAccess(expr.getEnd(), new SingleTypeReference(name.toCharArray(), toPos(expr.getStart(), expr.getEnd() - 1)));
```

I used a simple regular expression to choose between class literal and constant reference.  You class is all uppercase and so it matches the check.

**Comment by doktorjw** [comment]
That would do it, and explain how just a few lines above, the other class works just fine. Interesting.

As soon as I get a break on the current tidbit I'm working on (have to pay the bills), I'll try removing the @Override and see if the error goes away. I suspect it will, but best to be sure.

The closure-as-annotation-attribute case would be an easy one to miss; we can't think of all possible cases all the time, can we?

By the way --- thanks so much for supporting groovy-eclipse.

**Comment by eric-milles** [comment]
ExtendedVerifier.visitOverride is the source of the error for your implementation of AttributeConverter.  Groovy 2.3 made significant changes to visitOverride to deal with generics.  I enabled, then backported Groovy 2.2's version to 2.1 and 2.0 to fix GRECLIPSE-1773 and STS-3822 across the board.

**Comment by eric-milles** [comment]
@doktorjw Could you please recheck with the latest build and let me know?  I have created a test case for your UOM vs UOM.class issue, but have nothing solid as far as a fix.  Hopefully the workaround I proposed gets you by for now.

**Comment by doktorjw** [comment]
Just installed the latest release and the only issue that I see remaining is that UOM vs UOM.class issue. For now, it's easily handled by pegging it with the .class extension ... just annoying to do so .. lol. I don't know why something different needs done for the ide-modified compiler, but then I'm just not that familiar with the internals and how it ties into Eclipse.

Since this is the only issue I see that remains for me, I might be able to convince my buddy here to install it, too --- though he'll have to make the same change (UOM -> UOM.class) that I did, and likely commit it. A bit ugly, but if the plugin is better with this latest version, so be it.

You wouldn't happen to have a list of changes, would you? ala release notes?

**Comment by eric-milles** [comment]
Sorry, I could go into detail why the annotation/class combo changed, but it may be a lot to take in.  There are no release notes at the moment since a release has not been created in quite some time.  We're working on getting issues patched up and tests running in Bamboo before cutting a release.

As far as what have I changed besides patching several exceptions:
- semantic highlighting now includes static methods, groovy methods (determined by inferencing not a fixed token list), parameters, variables, and a few more items.
- code completion and selection have improved largely to the same changes that helped semantic highlighting; you can hover over most common elements (types, fields, methods, packages) and get a javadoc hover.
- import organization works for static imports now and should not drop imports in the face of syntax errors
- G icon should appear in editor tab
- Groovy 1.8-2.4 all should be at the latest release
- some more stuff I am forgetting...

**Comment by doktorjw** [comment]
Here's another one that was weird:

    @Test( expected=org.mule.module.apikit.exception.NotFoundException )

flags an error as it cannot convert NotFoundException to subclass of Throwable (something like that). Easily fixed via:

    @Test( expected=org.mule.module.apikit.exception.NotFoundException.class )

so it's kind of in the same ball park as the UOM one ... though we're pretty sure that was because of the all-caps. I'm not 100% sure it's related ...

And thanks for the notes; while it elicited a cheer from my buddy, I can't convince him to install the latest yet. 8^(

**Comment by eric-milles** [comment]
Funny, cause I tested for that case:

```java
    void testCodeSelectOnAttributeValue2b() {
        BrowsingTestSetup.addJUnit4()

        String source = '''\
            import org.junit.Test
            class C {
              @Test(expected=java.lang.Exception)
              void testSomething() {
              }
            }
            '''.stripIndent()

        def elem = assertCodeSelect([source], 'Exception')
        assert elem.inferredElement instanceof ClassNode
    }
```

Let me see if there is a warning emitted.

**Comment by doktorjw** [comment]
That is an odd one; I just double checked and with what I picked up yesterday (), with groovy 2.3.11 and jdk 1.7 .... without .class, this particular one shows an error. I did find another place where I just use expected=RuntimeException (no path or .class) and that doesn't flag an error. And yes, that's what it indicates as the displayed error.

**Comment by eric-milles** [comment]
Can you try with the latest snapshot?  You should be able to use fully-qualified types with or without ".class" as long as they don't appear to be static constants (all uppercase with underscores).

**Comment by eric-milles** [comment]
The restriction from the last comment (static constant-like references) should be removed.  Can you check again?

**Comment by doktorjw** [comment]
Indeed, the ones that would appear to be static constants (my UOM.class) is now functional with just "UOM" .... and the odd case of NotFoundException.class is also (apparently) resolved.

I think we're good on the issues that I reported.

Many thanks!

-- john
