### ISSUE TITLE
Issue with @AnnotationCollector in release 11/10/2016

### ISSUE THREAD

**Issue by admxiii** [groovy/groovy-eclipse#224]
Seems to be an issue with the annotation collector annotation in the latest build. The attributes are no longer inherited in the new annotation. Here is a simple example.

// File - MyEqualsAndHashCode.groovy
@EqualsAndHashCode
@AnnotationCollector
@interface MyEqualsAndHashCode {
}

// SomeObjectTO.groovy
@MyEqualsAndHashCode(includes=['id'])
class SomeObjectTO {
	// some fields....
}

// Error in eclipse problems view during compile
The attribute includes is undefined for the annotation type MyEqualsAndHashCode	

This worked prior to 11/09/2016 snapshot and still doesn't work in 11/10/2016 snapshot.

**Comment by eric-milles** [comment]
Having a look

**Comment by admxiii** [comment]
this is working again, thanks for the quick fix!

**Comment by eric-milles** [comment]
Could you close the issue?
