### ISSUE TITLE
wrong indentation of single statement ifs/etc

### ISSUE THREAD

**Issue by webczat** [groovy/groovy-eclipse#239]
I have noticed that when you write a line such as:
if (a == 1)
and then press enter, the next statement does not get properly indented. When manually formatting the source using the format menu item, it is indented correctly.

**Comment by eric-milles** [comment]
Just double-checking, do you have the option "Enter key adjusts the indentation on the new line" checked in Preferences > Java > Editor > Typing?

**Comment by eric-milles** [comment]
This test should confirm your issue
```groovy
    void testIndentAfterIfStatement() {
        makeEditor("""\
            class Bagaga {
                def foo(def a, def b) {
                    if (a == b)${CARET}
                }
            }
            """.stripIndent())

        send('\n')

        assertEditorContents("""\
            class Bagaga {
                def foo(def a, def b) {
                    if (a == b)
                        ${CARET}
                }
            }
            """.stripIndent())
    }
```

**Comment by eric-milles** [comment]
Looks like this guy does not find an imbalance in braces or parens and so returns the same indent level.
```java
    private int simpleComputeNextLineIndentLevel(int indentLevel, List<Token> tokens) {
        int adjust = getOpenVersusCloseBalance(tokens);
        if (adjust > 0)
            indentLevel += getPrefs().getIndentationSize();
        else if (adjust < 0)
            indentLevel = indentLevel - getPrefs().getIndentationSize();
        return indentLevel;
    }
```

**Comment by eric-milles** [comment]
Should be fixed.

**Comment by webczat** [comment]
I do not know what I have enabled, but I have definitely tested some nonsensical instructions like if (1==2)\nreturn and stuff in both java and groovy, and in java it indented, in groovy it didn't.
If you still need this test after this comment, do you need me to paste that in any source code or where?

**Comment by eric-milles** [comment]
Sorry, I made a small error that failed the build.  This should be available for test in a few minutes.

**Comment by webczat** [comment]
okay, I downloaded the latest update and tried to use it.
If I write something like (without indentation here):
if (1 == 2)
return
//whatever

then the if line is of course correctly indented, return is correctly indented (shifted right), but the next line has not been unindented properly.

**Comment by eric-milles** [comment]
Was your original request satisfied?  Can you close this issue and open a new one with current and expected code snippets?  Use three backticks to start and end a multi-line code block.
