### ISSUE TITLE
Change of Bundle-ClassPath in Manifest.MF of org.codehaus.groovy.eclipse.ant breaks headless build with ANT

### ISSUE THREAD

**Issue by AndreasTu** [groovy/groovy-eclipse#244]
In the commit f7b348cb6f8ca36b7d2a8bbe5f9874c8146a839e the Manifest.MF file was changed to include the groovyAntEclipse.jar in the Bundle-ClassPath.

This breaks the headless Eclipse ANT execution of the `GroovyCompilerAdapter`: 

    "Class org.codehaus.groovy.eclipse.ant.GroovyCompilerAdapter could not be loaded because of an invalid dependency."

See Stacktrace below.

The `GroovyCompilerAdapter` is loaded via the `EquinoxBundleLoader` of the groovy.eclipse.ant plug-in (due to the new entry), which then could not load the `JDTCompilerAdapter`, because the org.eclipse.jdt.core plugin has no `Bundle-ClassPath` entry for the jdtCompilerAdapter.jar file.

But it would work without the `Bundle-ClassPath`, because the `AntClassLoader` would find the `GroovyCompilerAdapter` and the JDTCompilerAdapter due to the plugin.xml entries for ANT.

When a remove the new entry the build works again.

I'm wondering why the new entry in the Manifest.MF file was made?

The stacktrace of the error is attached.
[Stacktrace.txt](https://github.com/groovy/groovy-eclipse/files/641721/Stacktrace.txt)

The tested version was `org.codehaus.groovy.eclipse.feature_2.9.2.xx-201612082348-e46`

**Comment by eric-milles** [comment]
It was changed to fix this warning.  I see now that it is also wired in using the Ant extension points in plugin.xml.

![groovyant](https://cloud.githubusercontent.com/assets/18193802/21054250/72813016-bdf2-11e6-9b1d-3a60934ee173.png)
