### ISSUE TITLE
Groovy eclipse compiler maven plugin and groovy-eclipse-batch for java8

### ISSUE THREAD

**Issue by steveash** [groovy/groovy-eclipse#246]
Are there any plans to release a groovy eclipse compiler maven artifact (etc) so that we can use the maven compiler plugin to compile groovy 2.4.x and java 8 files at the same time?

**Comment by eric-milles** [comment]
We are working towards a release.  I'm hopeful that it will be before the end of the year.  I will talk to Andy about releasing the batch compiler artifacts at that time as well.

**Comment by PascalSchumacher** [comment]
A release of the groovy-eclipse-batch plugin would be very nice indeed.

**Comment by astral303** [comment]
Are there any updates on a release of the groovy-eclipse-batch artifact?

There are compilation bugs fixed since 2.4.3 that make my IDE pass compilation (due to use of Groovy 2.4.12), but then fail in Maven due to groovy-eclipse-batch being 2.4.3-01.

Is it possible to reconstruct a groovy-eclipse-batch JAR from the nightly Eclipse snapshots?

**Comment by aclement** [comment]
If you mean you want to locally patch the maven jar with eclipse jar contents, that should be possible, shouldn't be too tricky. (unjar what you want to use, jar -uvf the batch jar in your mvn cache) - not exactly robust though. Unfortunately we've had no cycles to look at rebuilding/republishing the groovy-eclipse-batch artifact ourselves.

**Comment by eric-milles** [comment]
@astral303 I managed to get the batch artifact build running locally.  I don't have the steps to get it out to Maven Central yet, but you could install this to your local maven repository (under repository/org/codehaus/groovy/groovy-eclipse-batch).  I haven't verified its contents yet, but the size was close to the 2.4.3-01 jar's.

[groovy-eclipse-batch-2.4.13-SNAPSHOT.zip](https://github.com/groovy/groovy-eclipse/files/1185338/groovy-eclipse-batch-2.4.13-SNAPSHOT.zip)

**Comment by eric-milles** [comment]
I think I have the publishing into bintray working.  For starters, I just pushed out the latest Groovy 1.8 batch compiler.  Could anyone give it a try on a decent sized project?

You can link to it by adding this to your POM:
```xml
  <pluginRepositories>
    ...
    <pluginRepository>
      <id>bintray</id>
      <name>Groovy Bintray</name>
      <url>https://dl.bintray.com/groovy/maven</url>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
```

**Comment by DevInsanity** [comment]
Can confirm that this solved the problem that I was having at least. It no longer chokes when compiling certain java parts of my code.
