### ISSUE TITLE
Code formatting requires selection of code to be formatted

### ISSUE THREAD

**Issue by lucasvc** [groovy/groovy-eclipse#248]
Default installation allows formatting the code using the same Java key binding <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>F</kbd>.

In Java editor, you can format the whole current file only using the keybinding.

Within the Groovy editor you could do the same, until a few days/weeks ago.
Now you have to select the code to be formatted, and when none is selected the file doesn't change.

**Comment by eric-milles** [comment]
Can you try with the latest snapshot build?  I believe I fixed this over the weekend.

**Comment by lucasvc** [comment]
Sorry, I could not test it before.
Is working using `Groovy-Eclipse Feature	2.9.2.xx-201612170628-e46	org.codehaus.groovy.eclipse.feature.feature.group	Codehaus.org`  (from Help > Installation Details).
Thanks!
