### ISSUE TITLE
Eclipse Neon.2 release due to conflicts cannot install groovy-eclipse m2e 

### ISSUE THREAD

**Issue by SanjayGautam** [groovy/groovy-eclipse#257]
Hi Community Team , 

I installed the new neon2 release eclipse version and I am not able to install the GroovyEclipse M2e , I tried uninstalling the conflicting features but then it does not work 

Cannot complete the install because of a conflicting dependency.
  Software being installed: Groovy-Eclipse M2E integration 2.9.2.xx-201701222307-e45 (org.codehaus.groovy.m2eclipse.feature.feature.group 2.9.2.xx-201701222307-e45)
  Software currently installed: Eclipse Java Development Tools 3.12.2.v20161124-1400 (org.eclipse.jdt.feature.group 3.12.2.v20161124-1400)
  Only one of the following can be installed at once: 
    Object Teams Development Tooling Core 3.12.2.v_OTDT_r252_201612071657 (org.eclipse.jdt.core 3.12.2.v_OTDT_r252_201612071657)
    Object Teams Development Tooling Core 3.12.0.v_OTDT_r250_201606070956 (org.eclipse.jdt.core 3.12.0.v_OTDT_r250_201606070956)
    Object Teams Development Tooling Core 3.12.1.v_OTDT_r251_201609131451 (org.eclipse.jdt.core 3.12.1.v_OTDT_r251_201609131451)
    Java Development Tools Core 3.11.2.xx-201701222307-e45 (org.eclipse.jdt.core 3.11.2.xx-201701222307-e45)
    Java Development Tools Core 3.12.2.v20161117-1814 (org.eclipse.jdt.core 3.12.2.v20161117-1814)
    Java Development Tools Core 3.12.0.v20160516-2131 (org.eclipse.jdt.core 3.12.0.v20160516-2131)
    Java Development Tools Core 3.12.1.v20160829-0950 (org.eclipse.jdt.core 3.12.1.v20160829-0950)
    Java Development Tools Core 3.9.2.v20140114-1555 (org.eclipse.jdt.core 3.9.2.v20140114-1555)
  Cannot satisfy dependency:
    From: Groovy-Eclipse Compilerless Feature 2.9.2.xx-201701222307-e45 (org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201701222307-e45)
    To: org.codehaus.groovy.headless.feature.feature.group [2.9.2.xx-201701222307-e45]
  Cannot satisfy dependency:

Thanks
Sanjay Gautam

**Comment by eric-milles** [comment]
I think you are pointed to the wrong Groovy-Eclipse update site: Java Development Tools Core 3.11.2.xx-201701222307-e45 (org.eclipse.jdt.core 3.11.2.xx-201701222307-**e45**)

This indicates to me you are trying to install Mars patch into Neon.

**Comment by SanjayGautam** [comment]
yes you are right , Thanks Eric for the I was able to uninstall and install with right update site !!
