### ISSUE TITLE
Cannot complete the install because one or more required items could not be found.

### ISSUE THREAD

**Issue by magick93** [groovy/groovy-eclipse#261]
Im trying to install groovy-eclipse into Eclipse Neon, but get the following error:

`Cannot complete the install because one or more required items could not be found.
  Software being installed: Groovy-Eclipse Feature 2.9.2.xx-201701301643-e47 (org.codehaus.groovy.eclipse.feature.feature.group 2.9.2.xx-201701301643-e47)
  Software currently installed: SwitchYard 2.2.0.Final-v20161110-1803-B65 (org.switchyard.tools.feature.feature.group 2.2.0.Final-v20161110-1803-B65)
  Missing requirement: Java Development Tools Core 3.13.0.xx-201701301643-e47 (org.eclipse.jdt.core 3.13.0.xx-201701301643-e47) requires 'bundle org.eclipse.core.resources [3.12.0,4.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Groovy-Eclipse Compilerless Feature 2.9.2.xx-201701301643-e47 (org.codehaus.groovy.compilerless.feature.feature.group 2.9.2.xx-201701301643-e47)
    To: org.codehaus.groovy.headless.feature.feature.group [2.9.2.xx-201701301643-e47]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Feature 2.9.2.xx-201701301643-e47 (org.codehaus.groovy.eclipse.feature.feature.group 2.9.2.xx-201701301643-e47)
    To: org.codehaus.groovy.compilerless.feature.feature.group [2.9.2.xx-201701301643-e47]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Headless Feature 2.9.2.xx-201701301643-e47 (org.codehaus.groovy.headless.feature.feature.group 2.9.2.xx-201701301643-e47)
    To: org.codehaus.groovy.jdt.patch.feature.group [2.9.2.xx-201701301643-e47]
  Cannot satisfy dependency:
    From: SwitchYard 2.2.0.Final-v20161110-1803-B65 (org.switchyard.tools.feature.feature.group 2.2.0.Final-v20161110-1803-B65)
    To: org.eclipse.jdt.feature.group 3.6.0
  Cannot satisfy dependency:
    From Patch: org.codehaus.groovy.jdt.patch.feature.group 2.9.2.xx-201701301643-e47 Eclipse Java Development Tools 3.12.1.v20160907-1200 (org.eclipse.jdt.feature.group 3.12.1.v20160907-1200)
    To: org.eclipse.jdt.core [3.13.0.xx-201701301643-e47]`

What is the best way to solve this?

**Comment by eric-milles** [comment]
You are using the Oxygen (4.7) update site.  The Neon (4.6) update site is what you want.

**Comment by magick93** [comment]
That did it. Thanks.
