### ISSUE TITLE
Unable to use eclipse revert installation feature because old version are not available on update site

### ISSUE THREAD

**Issue by kaxelson** [groovy/groovy-eclipse#263]
eclipse has a feature under Help | Installation Details on the Installation History tab that allows you to revert your eclipse configuration to a previous configuration.  This depends on the older version of the plugins you were using being available at the various plugin update sites.  Because groovy-eclipse does not keep older plugin versions available on the update sites, attempting to revert fails saying "No repository found containing ..." for all of the old groovy-eclipse bundles and features.  To fix this, old plugin versions must be kept available on the update sites.

**Comment by eric-milles** [comment]
The release update sites maintain this property.  The snapshot sites do not.  However, you can still access the zipped update site archive for any build should you wish to return to it.  These can be found on the Bamboo CI server under artifacts tab for an individual build.

**Comment by kaxelson** [comment]
I'm only seeing artifacts for the last 10 builds.  I need a zipped update site older than that.
