### ISSUE TITLE
BigDecimal is not Visible

### ISSUE THREAD

**Issue by kenwdelong** [groovy/groovy-eclipse#268]
I am using Eclipse Neon 4.6.2.  I'm updating Groovy Eclipse from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/.  I'm using Java 8_121.  I have a mixed Java/Groovy project. I have Groovy beans that have BigDecimal properties:

    public class MyBean
    {
        BigDecimal amount
    }

Other (Java) classes reference that property.
`myBean.getAmount().doubleValue()`
With today's update, I am now getting an error "The type BigDecimal is not visible".

![image](https://cloud.githubusercontent.com/assets/6744405/23765481/333d6e32-04b6-11e7-9da7-f57252ea1a1b.png)

![image](https://cloud.githubusercontent.com/assets/6744405/23765317/aaa6aa5c-04b5-11e7-9986-58919b10a1e8.png)

Groovy compiler level is 2.4 (same problem at 2.3).

**Comment by eric-milles** [comment]
Probably caused by my optimization in getDefaultImports.  I'll get that rolled back and add a test case.  Thanks for reporting this issue.

**Comment by kenwdelong** [comment]
Thanks for the quick response, and thanks for keeping this project going!!!

**Comment by kenwdelong** [comment]
Fix confirmed on 
![image](https://cloud.githubusercontent.com/assets/6744405/24017607/e732794a-0a4d-11e7-86ef-07dd13034f40.png)

Thank you!
