### ISSUE TITLE
NullPointerException in TypeSystem.getUnannotatedType

### ISSUE THREAD

**Issue by cw124** [groovy/groovy-eclipse#272]
Building the below code via Maven using the Groovy-Eclipse compiler fails with:

```
[ERROR] /Users/cw/code/compiler-error/src/main/java/com/qriously/Main.java: 1. ERROR in /Users/cw/code/compiler-error/src/main/java/com/qriously/Main.java (at line 0)
    package com.qriously;
    ^
Internal compiler error: java.lang.NullPointerException at org.eclipse.jdt.internal.compiler.lookup.TypeSystem.getUnannotatedType(TypeSystem.java:72)
```

The code is:

```
public class Main {

    public static void main(String[] args) {
        postProcess(
                Stream.of(3),
                s -> s
                    .map(c -> c)
                    .collect(Collectors.toList()));
    }

    public static <T, U> Supplier<U> postProcess(Stream<T> stream, Function<Stream<T>, U> postProcessor) {
        return () -> postProcessor.apply(stream);
    }
}
```

Removing the map or the collect (or both) makes the problem go away. Also, extracting the map argument (c -> c) into a variable, or replacing it with Function.identity() fixes the problem. Building with javac works.

I'm using groovy-eclipse-compiler 2.9.2-01 and groovy-eclipse-batch 2.4.3-01.

I realise this may be an Eclipse JDT bug. Let me know if I should raise it at bugs.eclipse.org instead.

**Comment by eric-milles** [comment]
This was fixed a couple months ago.  We just need to get a new release of the batch compiler out.  Sorry for any delays on that front.  We have been sorting out some permissions stuff on the build side.
