### ISSUE TITLE
Can't install m2e connector in Eclipse Luna

### ISSUE THREAD

**Issue by cbaldan** [groovy/groovy-eclipse#273]
Hello.

I'm trying to install **Groovy-Eclipse M2E integration	2.9.1.xx-201411061335-e44-RELEASE** in Eclipse Luna Service Release 2 (4.4.2) from this update site:
http://dist.springsource.org/release/GRECLIPSE/e4.4/

And I'm getting this error after the **Install Details** screen:
![2017 03 21 - groovy luna me2 error](https://cloud.githubusercontent.com/assets/11215911/24168516/71686ad6-0e48-11e7-8667-45dfd229dcc4.PNG)

`An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.m2e.archetype.common,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.core,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.core.ui,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.discovery,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.editor,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.editor.xml,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.jdt,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.jdt.ui,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.launching,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.lifecyclemapping.defaults,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.logback.appender,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.logback.configuration,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.indexer,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.runtime,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.runtime.slf4j.simple,1.7.0.20160603-1931
No repository found containing: osgi.bundle,org.eclipse.m2e.model.edit,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.profiles.core,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.profiles.ui,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.refactoring,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.scm,1.7.0.20160603-1933
No repository found containing: org.eclipse.update.feature,org.eclipse.m2e.feature,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.importer,1.7.0.20160603-1933
No repository found containing: org.eclipse.update.feature,org.eclipse.m2e.logback.feature,1.7.0.20160603-1933
No repository found containing: osgi.bundle,org.eclipse.m2e.workspace.cli,0.3.1
`

Am I missing something?
Thanks,
Cleber.

**Comment by mpiggott** [comment]
Add the m2e 1.7 repository see http://www.eclipse.org/m2e/ - possible it may still not work, I recall m2e breaking compatibility with older Eclipse versions but not the specifics.

**Comment by cbaldan** [comment]
@mpiggott thanks, it worked! I was able to get it installed and it's working on Luna!
