### ISSUE TITLE
file associations question

### ISSUE THREAD

**Issue by muyun12** [groovy/groovy-eclipse#275]
eclipse neon.2
New java project with gradle builder. The *.gradle file was associated with groovy editor。The eclipse config of Content Types is **Groovy Source File(for Groovy projects)** .
How to config greclipse only for groovy project?

**Comment by eric-milles** [comment]
For the benefit of others, file extension association can be viewed under Window > Preferences > General > Content Types > Text > Java Source File > Groovy Source File.

In Window > Preferences > General > Editors > File Associations, you can select *.groovy and then in Associated editors, you should be able to pick another editor besides Groovy Editor and click Default.

**Comment by muyun12** [comment]
Thank you so much !
