### ISSUE TITLE
When I install this plugin, gradle scripts show up with an Error icon.

### ISSUE THREAD

**Issue by sc1478** [groovy/groovy-eclipse#277]
My need for this plugin is primarily to write Gradle plugins in groovy.

There is an issue, mostly cosmetic, that I can't solve.  When this plugin is NOT installed, but the Buildship plugin IS installed, then the display of gradle buildscripts in the Project Explorer is correct (the gradle scripts have elephant icons).

![2017-04-03_14-34-35](https://cloud.githubusercontent.com/assets/15382550/24628536/513d3726-187c-11e7-8cec-ae38e8955dce.png)

But after installing this plugin then the display of gradle buildscripts in Project Explorer is incorrect (Big fat ugly exclamation mark for the gradle scripts in project explorer, but no error messages in the Markers tab or Problems tab).

![2017-04-03_14-44-51](https://cloud.githubusercontent.com/assets/15382550/24628553/62548e4c-187c-11e7-94ed-18b5952da74b.png)

This seems to be purely cosmetic but it's annoying.  The gradle building within Eclipse is not affected.  But, since I need to edit code for a gradle plugin, I want the groovy editor support, but it seems to mess up at least the cosmetics of the Eclipse Project Explorer.

**Comment by eric-milles** [comment]
If you add the Groovy nature to your project, this will cease.

**Comment by sc1478** [comment]
I'll confirm that adding 
`<nature>org.eclipse.jdt.groovy.core.groovyNature</nature>` 
in my project file makes the ugly exclamation points go away, but it doesn't revert to the elephant Gradle icon.  It becomes something else (I can't quite make out what)

![2017-04-03_16-00-09](https://cloud.githubusercontent.com/assets/15382550/24631683/d625a270-1886-11e7-96df-598de82edd1d.png)

And it seems wrong to have to do it.  My project might have no connection to groovy other than its build script being written in gradle.  It might be something like a project that packages a bunch of shell scripts into an RPM for example.  If anything should add this nature it should be the Gradle project importer or else the Gradle project nature should somehow imply the groovy nature.

**Comment by eric-milles** [comment]
That icon indicates that the file will not be compiled when/if you run Build Project.

**Comment by sc1478** [comment]
What would it take to just leave the original gradle elephant icon in place, as it would be if the Groovy plugin were not installed?

**Comment by eric-milles** [comment]
If you follow the directions in issue #275, I think you can restore the association between the Gradle editor and *.gradle files.

**Comment by sc1478** [comment]
No, that doesn't work either.  Although it shows up as the default editor, it looks like the groovy plugin has locked it.   And I don't mind editing the script with the groovy editor - it's preferable actually, But changing that preference doesn't fix the icon.

![2017-04-03_16-25-31](https://cloud.githubusercontent.com/assets/15382550/24632627/7ecc2b1c-188a-11e7-8e62-3509856c063d.png)

**Comment by sc1478** [comment]
Another odd thing is that the elephant shows up in other views such as the Git Repositories view.

**Comment by eric-milles** [comment]
So you would like the Groovy Editor to be used for .gradle files, but the icon determined by the non-default Gradle Editor?  It seems that if you want the Groovy Editor that its icon should be used.

**Comment by sc1478** [comment]
I guess you've made the assumption that icon maps to editor choice.  Is that correct?  I'm not sure it is, given that many file types have several "Open With" choices.

To me, the elephant icon is highly desirable because it makes the build scripts for a project stand out from other files, regardless of what editor may be used to edit them.  In any case, once the groovy plugin is installed, I lose the elephant icon.

**Comment by eric-milles** [comment]
In Eclipse, the icon used for a resource is the summation of all the contributors that are asked if they wish to provide an icon for a resource.  It is not trivial to control this behavior from the UI.  Groovy-Eclipse was written to find *.gradle files interesting and so to provide an icon (and editor).

I could try setting the priority to `normal` instead of `high`.  Or separate out Gradle as its own content type with a low priority so that if you have Buildship installed, it takes precedence.

```xml
   <extension point="org.eclipse.core.contenttype.contentTypes">
      <content-type
           base-type="org.eclipse.jdt.core.javaSource"
           file-extensions="groovy,gradle,gpp,grunit"
           id="org.eclipse.jdt.groovy.core.groovySource"
           name="Groovy Source File (for Groovy projects)"
           priority="high"/>
   </extension>
```

**Comment by sc1478** [comment]
Yes.  While I was tempted to say, I want everything exactly the way I want it, I realized that you as developer could be whipsawed by competing demands.  So I tried to keep mine reasonable.

I would say the groovy plugin should find *.gradle files interesting enough to provide the groovy editor as a non-default choice.  Gradle editor would be default choice (if Buildship is installed), and the icon would show up as the elephant (either always, if that is possible, or at the very least when groovy has not been defined as the default editor).  Often build scripts are simple enough that syntax highlighting etc. are not required.  But they occasionally get more complex, when the syntax highlighting becomes a real help.  Those cases could be handled with alternate Open With groovy editor.

If you don't mind, I'll stay out of the question of how you implement this.  But thanks for your efforts.

**Comment by eric-milles** [comment]
I split Gradle files out as a separate content type with a low priority.  This should be enough for Buildship to take precedence.  The build will take about 30ish minutes.  Then you can run update and try it out.

**Comment by sc1478** [comment]
Thanks.  Please tell me how/where I can get this new version?

**Comment by eric-milles** [comment]
Once build completes (you can monitor it at https://build.springsource.org/browse/GRECLIPSE), you run Help > Check for Updates.

**Comment by sc1478** [comment]
OK, your fix didn't help, sorry.

I have the new plugin installed:  org.codehaus.groovy25.feature (2.9.2.xx-201704041513-e46) "Groovy-Eclipse" and I still get the exclamation point icon even though gradle editor is the default editor for these files.

**Comment by eric-milles** [comment]
Can you send a screenshot of your Preferences > General > Content Types > Java Source File > Groovy Source File > *

**Comment by sc1478** [comment]
![2017-04-04_12-23-44](https://cloud.githubusercontent.com/assets/15382550/24669899/ae07ec66-1931-11e7-9ade-972c07747806.png)

**Comment by sc1478** [comment]
![2017-04-04_12-27-00](https://cloud.githubusercontent.com/assets/15382550/24670009/19f9d222-1932-11e7-8bd0-6e56870bc016.png)

**Comment by sc1478** [comment]
and here are the file associations

**Comment by eric-milles** [comment]
So it looks like the Gradle plug-in has taken precedence.  Is this not what you are seeing?

**Comment by sc1478** [comment]
This is what I see:

![2017-04-04_12-35-36](https://cloud.githubusercontent.com/assets/15382550/24670364/549f5bf8-1933-11e7-95e1-0807581ab6be.png)

The editor panes show the icon of whatever editor is active.   In this view I have settings gradle open twice, one with the default gradle editor and once with groovy editor  It would be nice if the groovy editor didn't show the error icon, but at least the gradle editor shows it correctly.

In the project explorer, it shows the error icon for all gradle scripts, even though groovy is the default editor..

**Comment by sc1478** [comment]
Eh, why is this closed?  Your fix didn't solve the issue.

**Comment by eric-milles** [comment]
I did not close.  I was wondering why you closed it yesterday.

**Comment by sc1478** [comment]
Don't know how it got closed.  I didn't do it, or at least not knowingly. :-)

**Comment by eric-milles** [comment]
Can you send me the update site link for the Gradle plug-ins?

**Comment by sc1478** [comment]
http://download.eclipse.org/buildship/updates/e46/releases/2.x

**Comment by eric-milles** [comment]
Could you let Buildship project know that they have an unresolved dependency in their manifest for org.eclipse.buildship.core?  I'll try to find a way around this, but it is slowing me down.

[cid:image001.png@01D2AE00.316C2650]

**Comment by sc1478** [comment]
I will but your image is not readable by me and may not be readable by the Gradle folks.

**Comment by eric-milles** [comment]
Can you retest with the latest snapshot?

**Comment by aax** [comment]
With the latest snapshot, the following error occurs several times in our logs on startup. We don't have the buildship plugin installed.

> !ENTRY org.eclipse.core.runtime 4 0 2017-04-07 16:03:37.656
!MESSAGE Invalid input url:platform:/plugin/org.eclipse.buildship.ui/icons/full/obj16/gradle_file.png
!STACK 0
java.io.IOException: Unable to resolve plug-in "platform:/plugin/org.eclipse.buildship.ui/icons/full/obj16/gradle_file.png".
	at org.eclipse.core.internal.runtime.PlatformURLPluginConnection.parse(PlatformURLPluginConnection.java:61)
	at org.eclipse.core.internal.runtime.FindSupport.find(FindSupport.java:290)
	at org.eclipse.core.runtime.FileLocator.find(FileLocator.java:152)
	at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:209)
	at org.eclipse.jface.resource.URLImageDescriptor.access$1(URLImageDescriptor.java:200)
	at org.eclipse.jface.resource.URLImageDescriptor$URLImageFileNameProvider.getImagePath(URLImageDescriptor.java:53)
	at org.eclipse.swt.internal.DPIUtil.validateAndGetImagePathAtZoom(DPIUtil.java:407)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:684)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:244)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:224)
	at org.codehaus.groovy.eclipse.ui.decorators.GroovyPluginImages.createDescriptor2(GroovyPluginImages.java:37)
	at org.codehaus.groovy.eclipse.ui.decorators.GroovyPluginImages.<clinit>(GroovyPluginImages.java:23)
	at org.codehaus.groovy.eclipse.ui.decorators.GroovyImageDecorator.getJavaElementImageDescriptor(GroovyImageDecorator.java:101)
	at org.codehaus.groovy.eclipse.ui.decorators.GroovyImageDecorator.decorateImage(GroovyImageDecorator.java:64)
	at org.codehaus.groovy.eclipse.editor.GroovyEditor.getTitleImage(GroovyEditor.java:709)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditorErrorTickUpdater.updateEditorImage(JavaEditorErrorTickUpdater.java:73)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.doSetInput(CompilationUnitEditor.java:1420)
	at org.codehaus.groovy.eclipse.editor.GroovyEditor.doSetInput(GroovyEditor.java:875)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2126)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3197)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:362)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:318)
...

**Comment by sc1478** [comment]
Well, I DO, of course, have the buildship plugin installed and this release fixes my original issue.  Everything looks good.  .gradle build scripts open by default with the gradle script editor or optionally (Open with) the groovy editor.  No matter which editor they are opened with, the Elephant icon is shown.  This is all good.
Thanks.

But I suppose I will have to do one more test when aax's issue is addressed.

**Comment by eric-milles** [comment]
Something had to give somewhere.  I checked for the existence of the buildship icon and if it is found it is used.  If not found, there will be a couple entries in the log.  I may find a way to clean that up in the future, but I have already put way more time into this than I planned on.

**Comment by sc1478** [comment]
Thanks!  I appreciate the effort!
