### ISSUE TITLE
Groovy-eclipse - confused by annotations on enum values

### ISSUE THREAD

**Issue by simonmarshall** [groovy/groovy-eclipse#278]
If i place an annotation on an enum value, it doesn't work.  It doesn't identify the annotation as a syntax error, but it does mis-highlight it and refuse to import the annotation class (if that is necessary).  The same code (when ported) works fine in Java.

Here's how I can reproduce it:

- download eclipse-jee-neon-3-win32-x86_64.zip
- run eclipse
- create new workspace
- install new software using http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/ and select all and install
- create new project containing attached source
- see file A.groovy contains:
`
@Target([ElementType.FIELD, ElementType.TYPE])
@Retention(RetentionPolicy.RUNTIME)
@interface A {
    String value()
}
`
- see file E.groovy contains:
`
@A("C")
enum E {
    @A("B")
    C
}
`
- see script S.groovy contains:
`
println 'Class annotations = ' + E.class.getAnnotations()
`
`
println 'Field annotations = ' + E.class.getField(E.C.name()).getAnnotations()
`
- run script and you will see:

Class annotations = [@enumsgroovy.A(value=C)]
Field annotations = []

such that it has not found the annotation on E.C.

[src.zip](https://github.com/groovy/groovy-eclipse/files/893667/src.zip)

**Comment by eric-milles** [comment]
Can you retest with the latest snapshot?

**Comment by simonmarshall** [comment]
> Can you retest with the latest snapshot?
fantastic - now works (tested with 2.4.10 and 2.5.0.snapshot) - many thanks
