### ISSUE TITLE
Source code for groovy-all (still) not available

### ISSUE THREAD

**Issue by aax** [groovy/groovy-eclipse#280]
Same problem as #120: The source code and javadoc for groovy JDK code is not available in the Editor and Eclipse is asking to attach a sources file.

Now it seems the groovy-all-x.y.z-sources.jar is excluded from the compiler plugins due to #198:
`bin.excludes = lib/*-sources.jar`
(e.g. in [build.properties](/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy23/build.properties) )

Also see [GroovyClasspathContainer.java](/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.core/src/org/codehaus/groovy/eclipse/core/builder/GroovyClasspathContainer.java) where the sources jar is referenced if found.

Is there a reason for this exclusion?

**Comment by eric-milles** [comment]
Can you retest with the latest snapshot?

**Comment by PascalSchumacher** [comment]
Works for me with the latest snapshot.

Great that this is finally fixed! Thank you very much!

**Comment by aax** [comment]
I can confirm it works, too. Thanks a lot!
