### ISSUE TITLE
Wiki: update for compatbility with newer Lombok versions

### ISSUE THREAD

**Issue by StefanMaler** [groovy/groovy-eclipse#282]
https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin#project-lombok

is out of date. Newer versions of Lombok, probably from v1.16.0 onwards, have the Agent in a different package:

`lombok.launch.Agent`

instead of

`lombok.core.Agent`

**Comment by eric-milles** [comment]
Updated and added a comment for future safety.

**Comment by StefanMaler** [comment]
Thank you, it might save someones time
