### ISSUE TITLE
PDE build for Mars.2 and Groovy-eclipse

### ISSUE THREAD

**Issue by BluAge** [groovy/groovy-eclipse#283]
Hi,

I'm currently trying to package an eclipse ditribution for my plugins, based on Eclipse Mars.2 and that includes Groovy-eclipse. I installed the Groovy-eclipse from the update site http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/ on my reference eclipse, and it worked without problem (version is from yesterday).
Now I want to package thanks to PDE, in order to get a build with all my base eclipse plugins (including groovy-eclipse) and my own. The problem I get is that as soon as I add groovy-eclipse to my product definition, PDE starts failing with the following message:

```
[eclipse.buildScript] Bundle org.eclipse.jdt.core:
[eclipse.buildScript] 	Another singleton version selected: org.eclipse.jdt.core_3.11.2.xx-201704180433-e45

```

At the beginning I had trouble because I was not in Mars.2 but in Mars.1, so the org.codehaus.groovy.jdt.patch was trying to patch a feature that I did not even have. But now I'm correctly upgraded to Mars.2, the patch seems to work, at runtime my OSGI environment tells me that the patched jdt.core plugin is taken instead of the normal one. I do not see why PDE complains. Any idea?

Note: I saw on some resources on the Internet that this message might be normal and non-blocking. But I have no doubt here that this message is the cause of my failure. If I remove groovy-eclipse from my product definition, I get the same log except the message above and the packaging continues and ends with success.

Thanks in advance,

**Comment by BluAge** [comment]
After more digging, I found that in fact, my assertion that "If I remove groovy-eclipse from my product definition, I get the same log except the message above" is wrong (funny, it seemed to work this way yesterday, maybe a clean in the meantime changed the behavior). Now even if I remove the groovy-eclipse from the product definition, I get the same error in PDE. I have to uninstall groovy-eclipse AND manually remove the patched jdt.core plugin to have it work.

As I had to manually remove one version of the plugin in that last test, I also tried the other way around: leave groovy-eclipse in my eclipse and in my product definition, and manually remove the standard version of jdt.core plugin, but then I get "Processing inclusion from feature org.eclipse.jdt: Unable to find plug-in: org.eclipse.jdt.core_3.11.2.v20160128-0629" as if the patch was ignored.

**Comment by eric-milles** [comment]
Not sure I totally follow.  If you start with base Eclipse, then add PDE, then add Groovy-Eclipse last, does it work?  I run Eclipse PDE with Groovy-Eclipse with no issues.

**Comment by BluAge** [comment]
I think there is a misunderstanding here.
Groovy-eclipse works in my Eclipse (which contains PDE and many other features).
What I intend to do is a PDE build to package a new Eclipse with my own features (as described in https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_product_build.htm). And here the Groovy-eclipse JDT Patch seems to somehow prevent the mechanics because of the "Another singleton..."

**Comment by eric-milles** [comment]
Because Groovy-Eclipse involves a patch feature, it is not always that easy to incorporate in setups like this.  You need to search the documentation of these types of things for any required extra steps when using patches.  Or if patches are supported at all.

**Comment by BluAge** [comment]
Well, you are right, it does seem to be a problem in PDE Build in general and not in your patch in particular.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=84351
I'll try what is advised in their Comment 22.
