### ISSUE TITLE
The literal -1 of type int is out of range

### ISSUE THREAD

**Issue by AntonPanikov** [groovy/groovy-eclipse#285]
As soon as you have any other compile errors in your code, any constant (static final fields) of type int and long produce an additional compiler error:

The literal -1 of type int is out of range

and by the way -1 is not out for range of int or long. You can easily reproduce it by the next example:
```groovy
package test

class Test {

    static final long VAR = -1  // this will be marked as compile error with message: 'The literal -1 of type int is out of range' as soon as you have any other compile error, like type 'qwe' in the main()

    static main(args) {
        qwe // compile error on purpose, comment it out to see the difference
        println 'hello groovy'
    }

}
```

I am using groovy-eclispe of:   Groovy-Eclipse Feature	2.9.2.xx-201704202017-e46	org.codehaus.groovy.eclipse.feature.feature.group	Codehaus.org

**Comment by eric-milles** [comment]
Literal is built with the sign character included (which is not correct for JDT) in org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.UnitPopulator.createConstantExpression.  I will get this fixed.
