### ISSUE TITLE
Wrong code assist order in method call completion

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#287]
From the old GRECLIPSE-1800

Consider the following:

```java
package c 
class C { 
    class MyBean { 
        String foo 
        int bar 
    } 
    class AnotherClass { 
        int createInt() { 
            return 1 
        } 
        String createString() { 
            return 'foo' 
        } 
    } 

    void doSomething() { 
        def a = new AnotherClass() 
        def b = new MyBean() 
        b.foo = a.cre|
    } 
}
````

When invoking code assist at | Greclipse is curently suggesting `c.C.AnotherClass.createInt()` before `c.C.AnotherClass.createString()`, I suspect following an alphabetical criteria, but I would expect the latter one to be proposed first, since `c.C.MyBean.foo` is of type String.
The same applies with the following alternative invocation:

```java
        b.with { 
            foo = a.cre|
        } 
```

**Comment by eric-milles** [comment]
Can you retest?  This should be fixed.

**Comment by mauromol** [comment]
```b.foo = a.cre|``` and ```b.with { foo = a.cre| }``` actually work now, thank you! But if I try (combining this with ticket #286): ```new MyBean(foo: a.cre|)```, although code assist now works, the ```createInt``` is suggested first, while ```createString``` should be the preferred choice.

**Comment by eric-milles** [comment]
The type of the parameter is not known at the time of the completion.  Only assignments are tracked for this kind of preference.  There would need to be an enhancement for it all to come together.

**Comment by mauromol** [comment]
Ok, so I will open another ticket for that.
This one can be closed, thank you very much 👍
