### ISSUE TITLE
Missing DSLD docs

### ISSUE THREAD

**Issue by aeisenberg** [groovy/groovy-eclipse#294]
When the transfer of the Groovy-Eclipse docs and wiki from Codehaus to Github was completed, it looks like a few pages were missed. One of them is the _DSL Descriptors for Groovy-Eclipse_ page.  Currently, it only exists at the [Web archives](https://web.archive.org/web/20150408031019/http://docs.codehaus.org/display/GROOVY/DSL+Descriptors+for+Groovy-Eclipse).

Over the years, I've gotten a handful of requests about DSLDs (I'm the original author of them and for that, I apologize :) ) and I noticed that the docs were missing, but I've never gotten around to dredging them up again.

I have a bit of time right now and I'll try to put them together again.

**Comment by aeisenberg** [comment]
I've created a `adds-dsld-page` branch in the `groovy-eclipse.wiki` repository with the new page.  But I don't think you can do pull requests for wiki repositories. 

There is a problem that no code snippets exist in the web archives. So, I've replaced them with ??? for now. I've Asked a question on the [Apache Groovy issue tracker](https://issues.apache.org/jira/browse/GROOVY-8191) to see if we can get access to the original wiki (I think the answer is no).

**Comment by aeisenberg** [comment]
Oops. I thought I created a PR for this page, but since it's part of the wiki it didn't work. I just pushed the changes directly to the wiki and created the page. I hope you don't mind. Feel free to suggest any edits, make any changes, or revert if you don't like.

**Comment by eric-milles** [comment]
Fine with me.  You are still one of the main contributors.

Would you mind looking at issue 267, and at least saying if it makes sense what is being requested?

**Comment by eric-milles** [comment]
Do any of your code snippets live on here: http://spring.io/search?q=groovy+dsld

Or in https://dzone.com/articles/add-editor-support-to-your-groovy-builder-with-a-d

**Comment by aeisenberg** [comment]
None of these have the original code snippets. 

Though, probably good to add some of these articles to the docs. I can do it when I get the chance.

**Comment by eric-milles** [comment]
Also: http://modularity.info/conference/2013/greclipse.html

**Comment by taurus227** [comment]
I'd like to fix this. Could you add me as a contributor?

**Comment by taurus227** [comment]
Also found this list:
https://docs.google.com/spreadsheets/d/1uZ2U2rByRIte2t9yUm0XkGNEMVz9Tao_ZjTDkLSdAFw/edit?usp=sharing
