### ISSUE TITLE
Default Groovy compiler is 2.4 in Eclipse Neon

### ISSUE THREAD

**Issue by vinaygkotresh** [groovy/groovy-eclipse#300]
I was using Groovy in Eclipse-4.4 (Luna) package. Recently i moved everything into Eclipse-4.6 (Neon.2) package. What i observed was the default Groovy compiler is 2.4. I have a code which need to compile things in 2.3 compiler. I just want to remove 2.4 compiler from Neon.2 package and make 2.3 compiler as default one.

Things which i tried are:
- Setting groovy compiler to 2.3 for each project. But still throws error saying Project and workspace compiler settings are different.
- I tried copying preference related to groovy compiler which points to 2.3 compiler when i create a new workspace. Even after doing this, application need to be restarted to take that into effect.

I need a solution when i open an Eclipse application, Groovy compiler-2.3 should be set for workspace.﻿

Can someone recompile the groovy source by making Groovy compiler-2.3 as default.

**Comment by eric-milles** [comment]
You should be able to enable the 2.3 compiler for your workspace.  This is done in Window > Preferences > Groovy > Compiler.  In the Groovy Compiler Settings section, there should be a drop-down where you can choose 2.3 and restart your eclipse to enable it.

**Comment by vinaygkotresh** [comment]
Hi @eric-milles , Thanks for your immediate reply. Yes i have an option of doing that. But in my situation i am giving a Eclipse package to my customer and in this case he expects Groovy compiler 2.3 to be set automatically.

**Comment by felixdo** [comment]
Do you distribute a package or an application? In case of application you could maybe use plugin-customization.ini to set 2.3 as default?

**Comment by vinaygkotresh** [comment]
Hi @felixdo, i distribute a package. I tried setting 2.3 in plugin-customization.ini, it didn't work for me.

I observed that 2.4 feature is included in Groovy-Eclipse feature. May be i will recompile the groovy source by removing 2.4 feature from Groovy-Eclipse feature. Hoping this will work for me.

**Comment by eric-milles** [comment]
Groovy-Eclipse will always select the highest compiler level that is available by default.  You can set an instance preference ahead to simulate the user making a selection.

The preference can be found in: <workspace>/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.codehaus.groovy.eclipse.compilerResolver.prefs
The preference is:
groovy.compiler.level=21

Or you can set it programatically using the IScopeContext APIs --
 `InstanceScope.INSTANCE.getNode("org.codehaus.groovy.eclipse.compilerResolver").put("groovy.compiler.level", "2x")`

It also appears that you can set the System property "groovy.compiler.level" to override the preference value.
