### ISSUE TITLE
GroovyCompletionProposalComputer is unable to return any proposals due to incorrect completion expression

### ISSUE THREAD

**Issue by tappio** [groovy/groovy-eclipse#302]
**GroovyCompletionProposalComputer** is unable to return any proposals due to incorrect completion expression returned by **ExpressionFinder**.

Let's consider the following code snippet:
```
void testMethod() {
   def testVariable = "";
   testV // cursor is placed at the end of this line
}
```
If user tries to complete this code (cursor is placed after "_testV_") everything works as expected without any issues. In this particular case **ExpressionFinder** will return "_testV_" completion expression and **GroovyCompletionProposalComputer** will be able to handle this case.

Now let's change _testVariable_'s value a little bit and add two slashes (might be any string which contains two slashes):
```
void testMethod() {
   def testVariable = "//";
   testV // cursor is placed at the end of this line
}
```
In this case, if user tries to complete this code (cursor is placed after "_testV_") no completion will be returned by the **GroovyCompletionProposalComputer**. This happens because **ExpressionFinder** can't handle this particular case and returns something like "_//\n\ttestV_" instead of "_testV_" which in turn leads to empty completion for a user.

**Comment by eric-milles** [comment]
Exception encountered is: org.codehaus.groovy.eclipse.core.util.TokenStreamException: Could not close quoted string.  I'll see if I can figure out why this is happening.

**Comment by eric-milles** [comment]
Can you retest with latest snapshot?

**Comment by tappio** [comment]
@eric-milles, unable to reproduce on the latest snapshot. Thank you!
