### ISSUE TITLE
JDT Core Extension Point Schemas cannot be found with JDT-Patch installed

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#307]
Hi,

I try to add a org.eclipse.jdt.core.classpathContainerInitializer extension to my plugin, but the context menu doesn't know how such an extension looks like, it only shows "Generic" as a submenu entry:
![image](https://user-images.githubusercontent.com/179663/27031569-1ff2aa12-4f71-11e7-8372-82792c51538a.png)
I wonder if this has something to do with having the jdt core patch installed.

**Comment by eric-milles** [comment]
The schemas are part of the JDT Core source bundle.  It is missing from the update site due to #296.
