### ISSUE TITLE
Groovy Compiler Switcher misbehaving and breaking various things (but mainly STS)

### ISSUE THREAD

**Issue by kdvolder** [groovy/groovy-eclipse#309]
We've received this bug report: https://github.com/spring-projects/spring-ide/issues/151

We spent a bit of time experimenting with it and as far as we can tell right now the Groovy Eclipse 'CompilerChooser' is responsible. I am vaguely familiar with that part of Greclipse (from my past life working on Greclipse) and willing to expend some effort in looking for a solution, though I have to admit, at this moment I don't have good ideas on how to fix this.

At the moment, I have seen that it breaks STS in rather severe way, I suspect other Eclipse plugins might / will also be affected but haven't seen direct evidence of that yet (other than some messages in error log pointing at egit might be getting affected).

**Comment by eric-milles** [comment]
This sounds like the same problem as issue #317.   I did manage to reduce the scope of the problem to use of Groovy version other than most current. Can anyone confirm an improvement for STS?

**Comment by eric-milles** [comment]
This issue appears to be isolated to Eclipse Neon.
