### ISSUE TITLE
Package rename: import in Groovy class not updated

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#310]
This was the old GRECLIPSE-1795.

Consider the following Java Class:

```java
package test1;

public class MyClass {

	public static final String FOO = "foo";
}
```

and the following Groovy class:

```groovy
package testg 
import static test1.MyClass.* 
import test1.MyClass; 

class MyGroovyClass {
	void doSomething() {
		MyClass c = new MyClass()
	} 
	
	void bar() {
		def c = FOO
	}
}
```

Now rename package test1 to test2: the import declarations (both the normal one and the static one) in MyGroovyClass are not updated.

**Comment by eric-milles** [comment]
Here's a quick update on this.  `MoveCuUpdateCreator.addReferenceUpdates` seems to be the critical method.  It uses Search to find all references to the moved compilation unit(s): `SearchResultGroup[] references= getReferences(movedUnit, pm, status);`.  Then it uses Search again to return the enclosing element: `IImportDeclaration importDecl= (IImportDeclaration) SearchUtils.getEnclosingJavaElement(results[j]);`.  This is not resolving a search hit on the static import to the correct import declaration.  I think correcting this will resolve the issue.

**Comment by eric-milles** [comment]
To get the import reference correct, `TypeInferencingVisitorWithRequestor.visitImports` runs.  Here is a snippet from it:
```
    public void visitImports(ModuleNode node) {
        for (ImportNode imp : GroovyUtils.getAllImportNodes(node)) {
            IJavaElement oldEnclosingElement = enclosingElement;

            visitAnnotations(imp);

            // this will not work for static or * imports, but that's OK because
            // as of now, there is no reason to do that.
            ClassNode type = imp.getType();
            if (type != null) {
                String importName = imp.getClassName().replace('$', '.') +
                        (imp.getFieldName() != null ? "." + imp.getFieldName() : "");
                enclosingElement = unit.getImport(importName);
                if (!enclosingElement.exists()) {
                    enclosingElement = oldEnclosingElement;
                }
            }
```
The comment clearly states the source of this issue.

**Comment by mauromol** [comment]
> The comment clearly states the source of this issue.

Yes, the comment is quite self-explanatory ;)

It's strange that there should be "no reason to do that" for static imports... And that comment also suggests to try another test case for "*" imports, indeed...

I see your commit, do you have published a new build for me to test?

**Comment by eric-milles** [comment]
Yes, this issue should be fixed.  You can move one or more files and the references should be updated.  Also, you should be able to rename an entire package and the references should be updated.  This should work across source folders (your related issue) as well.

**Comment by mauromol** [comment]
Also note the "test2" text overwriting "class" before "MyGroovyClass"!

**Comment by eric-milles** [comment]
Let me see if I understand, you have one Java class in package test1 and one Groovy class in package test1.  If you have edit selection over test1 in Java class and rename the package, the Groovy source is coming out mangled.  Is that about right?

Is this more like issue #311 or this one?  Just want to know which to reopen or should a new issue be created.

**Comment by mauromol** [comment]
Sorry for the mess, I tried to explain better in #311.

Consider the above use case, but with a small change: let `MyGroovyClass` be itself in package `test1` instead of `testg`. So:

```java
package test1;

public class MyClass {

	public static final String FOO = "foo";
}
```

and:

```groovy
package test1 
import static test1.MyClass.* 
import test1.MyClass; 

class MyGroovyClass {
	void doSomething() {
		MyClass c = new MyClass()
	} 
	
	void bar() {
		def c = FOO
	}
}
```

Let those classes be in the same source folder, so both of them are below the `test1` package in Project Explorer. In Project Explorer, select `test1`, hit F2 and rename it to `test2`. You'll see these two problems:

1. the first problem (which can be tracked here) is the mangling: `import test2` declaration is added before `import test1` instead of replacing it and `class` is replaced with `test2`
1. the second problem (let's track it in #311) is the unexpected "binary references" warning which is shown during the refactoring operation

I hope I've been more clear now.

**Comment by mauromol** [comment]
So, in the end I think both issues should be reopened...

**Comment by eric-milles** [comment]
2 defects exist.  First, the JavaElement returned for the match on "package test1" in the groovy source is the CompilationUnit and not the PackageDeclaration.  This appears to be the source of the binary references.  Second, the class declaration is being returned as a package reference in the part of the code looking for fully-qualified class literals.

**Comment by mauromol** [comment]
I tested with 2.9.2.xx-201708312110-e46 and it seems like both problems with `MyGroovyClass` being itself in `test1` package are fixed now! 👍 

Thank you! :-)
