### ISSUE TITLE
unable to install in Neon 3

### ISSUE THREAD

**Issue by brwarren** [groovy/groovy-eclipse#314]
installing from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/

choose all artifacts.

This error occurs.

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.jdt.core,3.12.3.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy,1.8.9.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy,2.0.8.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy,2.1.9.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy,2.2.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy,2.3.11.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy,2.4.11.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy,2.5.0.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.compilerless.feature,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ant,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.astviews,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codeassist.completion,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codebrowsing,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.compilerResolver,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.core,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.dsl,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.eclipse.feature,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.quickfix,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.refactoring,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ui,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.headless.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.jdt.patch,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.codehaus.groovy.m2eclipse,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.m2eclipse.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy18.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy20.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy21.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy22.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy23.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy24.feature,2.9.2.xx-201706221457-e46
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy25.feature,2.9.2.xx-201706221457-e46
No repository found containing: osgi.bundle,org.eclipse.jdt.groovy.core,2.9.2.xx-201706221457-e46

**Comment by eric-milles** [comment]
Can you try again?  You may have been installing when the build was deploying.

**Comment by brwarren** [comment]
now this:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/org.codehaus.groovy.eclipse.ui_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/org.codehaus.groovy.eclipse.ui_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy.headless.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy.headless.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy.jdt.patch_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy.jdt.patch_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/org.codehaus.groovy.m2eclipse_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/org.codehaus.groovy.m2eclipse_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy.m2eclipse.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy.m2eclipse.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy18.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy18.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy20.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy20.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy21.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy21.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy22.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy22.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy23.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy23.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy24.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy24.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy25.feature_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/org.codehaus.groovy25.feature_2.9.2.xx-201706221457-e46.jar
Artifact not found: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/org.eclipse.jdt.groovy.core_2.9.2.xx-201706221457-e46.jar.
http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/org.eclipse.jdt.groovy.core_2.9.2.xx-201706221457-e46.jar

**Comment by brwarren** [comment]
stupid corporate firewall blocking stuff

**Comment by hsp-harut** [comment]
Have you solved this? I have similar issue
