### ISSUE TITLE
Cannot switch groovy compiler level

### ISSUE THREAD

**Issue by muyun12** [groovy/groovy-eclipse#320]
**eclipse info**
Eclipse Java EE IDE for Web Developers.
Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

**greclipse info**
GRECLIPSE 2.9.2.xx-201707202212-e47

i cannot switch groovy compiler level, settings page :
![groovy](https://user-images.githubusercontent.com/14314544/28452567-d4b8c62a-6e25-11e7-9464-6cd4a9983987.jpg)

The update can be switched before

**Comment by eric-milles** [comment]
Can you try again with the latest snapshot?

**Comment by eric-milles** [comment]
I'm going to assume this is a one-time issue due to an update that wasn't applied properly.
