### ISSUE TITLE
Formatter not wrapping function calls

### ISSUE THREAD

**Issue by ilor** [groovy/groovy-eclipse#328]
I wanted to try the groovy source code formatter and found that while a bunch of features worked (semicolons removed when setting set, lists aligned and indented) one thing seems to not work -- function argument wrapping. Basically I'd expect a `foo(very, long, list, of, arguments)` to be wrapped in some way (any way really, as long as it's somewhat consistent) when the length exceeds the max. However, nothing substantial happens when I try to format such code.

Am I doing something wrong, or is this something that's not a thing (yet)?

Version: I followed the [wiki](https://github.com/groovy/groovy-eclipse/wiki) instructions for a developer build and ended up with bd36cc298d11085e39aadaebef346eac64512c0f checked out.

**Comment by eric-milles** [comment]
The formatter is an area that needs a lot of new development effort.  I could help you locate the code and tests if you're looking to make some enhancements.

**Comment by ilor** [comment]
Hi, thanks for the response. Unfortunately I don't have the necessary familiarity and/or time; I come from a different background and only do incidental Groovy scripting. Just cheering for a clang-format equivalent, I'm afraid.

**Comment by eric-milles** [comment]
Basic line wrapping implemented by https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.refactoring/src/org/codehaus/groovy/eclipse/refactoring/formatter/GroovyLineWrapper.java.  However it is not integrated into the formatter.  My concern with it would be that it could change the semantics of code by adding line breaks arbitrarily.
