### ISSUE TITLE
collectEntries notified as deprecated

### ISSUE THREAD

**Issue by DarioArena87** [groovy/groovy-eclipse#333]
I'm not a really expert Groovy programmer but by what i've found on the Internet (Groovy official documentation and StackOverflow) i learned that in Groovy one way of transforming any collection to a map is by using Iterable.collectEntries(Closure transforming). When i use this method in Eclipse in any jdk data structure that inherits from Iterable and Collection (Set and List) i receive the warning "Deprecated.  Use the Iterable version of collectEntries instead". I'm not really sure if this is a bug or not but shouldn't the parser recognize that theese structures ARE Iterables?

**Comment by eric-milles** [comment]
Nothing wrong with using `collectEntries`.  `DefaultGroovyMethods` offers over a dozen overloads of this method and some are deprecated.  When you have a `List` and call `collectEntries` from it, Groovy-Eclipse finds the closest matching overload, which is `public static <K, V> Map<K, V> collectEntries(Collection<?> self)`.  And it is deprecated.

This closest matching selection is how you can overload `method(Object)` and `method(String)` and get the method you'd expect called when your argument is a String.

**Comment by DarioArena87** [comment]
Indeed i'm not saying that wrong method is called or wrong results are produced. Everything works fine and i find programming in Groovy really fun. The only thing that to me feels funny is that, for example, let's suppose that i want to build a map with the square root of the first 10 natural numbers to further use. A simple solution would be to write something like 
`def firstTenSquareRoots = (0..10).collectEntries({[(it): Math.sqrt(it)]})`. 
When i write something like this in Eclipse, even if it works fine, the code is not really readable because by default Eclipse marks `collectEntries` as deprecated and it is shown with the strikethrough. In the tooltip it is suggested to use the iterable version but ranges ARE Iterables. My "solution" was to edit the default java syntax coloring settings to show deprecated members without the strikethrough but i think that because code like this is really simple and common and it is not using some strange Groovy or Java features it should be shown fine "out of the box".
Is there a simple way to achieve this or am i totally wrong and this is not the way this is done in "usual" Groovy?

**Comment by eric-milles** [comment]
If you want to force the use of the Iterable version (and therefore no deprecation highlighting), you would need to use a cast/coercion, like:

Map m = (0..10 as Iterable).collectEntries { [(it): Math.sqrt(it)] }

**Comment by eric-milles** [comment]
Or you can break it up using a local variable, where you would get a chance to declare a type:

Iterable range = 0..10
range.collectEntries { [(it): Math.sqrt(it)] }

**Comment by DarioArena87** [comment]
Nice! This seems to be resolved with latest releases! Really groovy work to everyone! :)
