### ISSUE TITLE
4.7 Network Timeouts 

### ISSUE THREAD

**Issue by kurtg123** [groovy/groovy-eclipse#334]
I'll admit that I'm on a weak internet given that I'm on a 1 Mbit here in the dominican republic, but the download is very slow 1-2 kb/sec and eventually timesout.    I did manage to download the 300+Mb Oxygen IDE, so my network isn't hopeless.   I'll be back in the states monday, so problem solved, but in a nod to developing economies, it would be great if a zip or similar binary could be provided.



**Comment by missedone** [comment]
well, though it's not formal, you can get the zipped update-site from the CI server: https://build.spring.io/browse/GRECLIPSE-GE47/latest
click the "Artifacts" tab, then you will see the link for download zipped update-site, for example: https://build.spring.io/browse/GRECLIPSE-GE47-320/artifact/JOB1/Zipped-Update-Site/org.codehaus.groovy-2.9.2.xx-201708312109-e47-updatesite.zip
