### ISSUE TITLE
Unable to upgrade to 2.9.2.xx-201709080001-e45

### ISSUE THREAD

**Issue by zosrothko** [groovy/groovy-eclipse#337]
Hello

Upgrading on Eclipse Mars 2 brings a stack of exception as below
```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.dsl, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.gradleware.tooling.client,0.19.3.v20170801075239
No repository found containing: osgi.bundle,com.gradleware.tooling.model,0.19.3.v20170801075239
No repository found containing: osgi.bundle,com.gradleware.tooling.utils,0.19.3.v20170801075239
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ant,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.astviews,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codeassist.completion,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codebrowsing,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.compilerResolver,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.core,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.dsl,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.quickfix,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.refactoring,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ui,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy.m2eclipse,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.eclipse.buildship.branding,2.1.2.v20170807-1318
No repository found containing: osgi.bundle,org.eclipse.buildship.core,2.1.2.v20170807-1318
No repository found containing: osgi.bundle,org.eclipse.buildship.stsmigration,2.1.2.v20170807-1318
No repository found containing: osgi.bundle,org.eclipse.buildship.ui,2.1.2.v20170807-1318
No repository found containing: osgi.bundle,org.eclipse.jdt.core,3.11.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.eclipse.jdt.groovy.core,2.9.2.xx-201709080001-e45
No repository found containing: osgi.bundle,org.gradle.toolingapi,3.5.0.v20170801075239
No repository found containing: osgi.bundle,org.codehaus.groovy,2.3.11.xx-201709080001-e45
No repository found containing: osgi.bundle,org.codehaus.groovy,2.4.12.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.compilerless.feature,2.9.2.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.eclipse.feature,2.9.2.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.headless.feature,2.9.2.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.jdt.patch,2.9.2.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.m2eclipse.feature,2.9.2.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy23.feature,2.9.2.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy24.feature,2.9.2.xx-201709080001-e45
No repository found containing: org.eclipse.update.feature,org.eclipse.buildship,2.1.2.v20170807-1318
```

Eclipse version
```
Eclipse DSL Tools

Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
```
```
C:\Users\fandre>java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by eric-milles** [comment]
The snapshots update site is connected directly to the CI builds.  Can you give it another try?

**Comment by zosrothko** [comment]
Same error.. tried 3 times, one with the Install new software tab on http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/

**Comment by eric-milles** [comment]
I was able to install Groovy-Eclipse into a fresh Mars.2 Eclipse DSL Tools package.

**Comment by zosrothko** [comment]
@eric-milles It does not work on my laptop. What should I check on my Eclipse to get more detailled log or trace to understand where the problem is?

**Comment by eric-milles** [comment]
Are you trying to update or add the plug-ins for the first time?  Are you running behind a proxy server or firewall that prevents non-https resources?

**Comment by zosrothko** [comment]
This is an Check for update and the PC is not behind a firewall nor proxy server... It seems strange because the Change for update process finds out what to update -- otherwise I wouldn't be able to specify them in this issue -- and upon uploading them, it fails....

**Comment by eric-milles** [comment]
Under the main menu, Window > Preferences > Install/Update > Available Software Sites, can you uncheck all sites and enable only the one for Groovy-Eclipse?  If update completes, you can re-enable the others later.

**Comment by zosrothko** [comment]
Tried by allowing only the http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/ but fails in same way. Ok, I give up. Thanks for your help and patience.

**Comment by eric-milles** [comment]
You can always download the update site archive from the build server and factor out any network issues.

https://build.springsource.org/browse/GRECLIPSE > click on the e45 build definition > Artifact tab of one of the completed builds

**Comment by cebaa** [comment]
Looks like @zosrothko  is not the only user having this issue. E.g. I just (so more than a year later) tried and got this:

{code}
An error occurred while collecting items to be installed
session context was:(profile=C__pf_eclipse_java-photon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ant,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.astviews,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codeassist.completion,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.codebrowsing,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.compilerResolver,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.core,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.dsl,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.quickfix,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.refactoring,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.eclipse.ui,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy.m2eclipse,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.eclipse.jdt.groovy.core,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy,2.4.15.xx-201811260558-e48
No repository found containing: osgi.bundle,org.codehaus.groovy,2.5.4.xx-201811260558-e48
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.compilerless.feature,3.2.0.xx-201811260558-e48
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.eclipse.feature,3.2.0.xx-201811260558-e48
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.headless.feature,3.2.0.xx-201811260558-e48
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.jdt.patch,3.2.0.xx-201811260558-e48
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.m2eclipse.feature,3.2.0.xx-201811260558-e48
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy24.feature,3.2.0.xx-201811260558-e48
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy25.feature,3.2.0.xx-201811260558-e48
No repository found containing: osgi.bundle,org.eclipse.jdt.core,3.14.0.xx-201811260558-e48
{code}

I tried what you suggested [above](https://github.com/groovy/groovy-eclipse/issues/337#issuecomment-328565565), i.e. only enabled this repository:

{code}
org.codehaus.groovy.eclipse.site	http://dist.springsource.org/snapshot/GRECLIPSE/e4.8	Enabled
{code}

and it still failed.

I'm able to download http://dist.springsource.org/snapshot/GRECLIPSE/e4.8/site.xml without issues and also the files (e.g. I tried http://dist.springsource.org/snapshot/GRECLIPSE/e4.8/features/org.codehaus.groovy.eclipse.feature_3.2.0.xx-201811260558-e48.jar and it downloaded fine).

Aside from scrapping the update process altogether and doing it manually as per [your other suggestion](https://github.com/groovy/groovy-eclipse/issues/337#issuecomment-329003142), any other recommendations?
