### ISSUE TITLE
Installed, but cannot see groovy-eclipse

### ISSUE THREAD

**Issue by DerekSansom** [groovy/groovy-eclipse#341]
I've installed this, but see nothing, no groovy file highlighting, no Groovy in preferences etc.
Do i need to enable or configure something?
Eclipse Mars, linux, java 8

**Comment by eric-milles** [comment]
You can check Help > About Eclipse Platform... > Installation Details (button) > Installed Software (tab) to see if Groovy-Eclipse is listed as an installed feature.  Once installed, *.groovy files should show with a lowercase-G icon.  If you had previously opened a file with another editor, you may need to choose Open With > Groovy Editor from the context menu for the file.
