### ISSUE TITLE
Static type checking errors on maven compile.

### ISSUE THREAD

**Issue by dsaita** [groovy/groovy-eclipse#344]
Hello.
I have a java 7 project that I want to use Groovy in.
I am migrating some classes that I believe should compile but I get errors.
Here is an example:
```java
@CompileStatic
class StaticCompileTest {

    private Number value


    public BigDecimal compiles() {
        return this.value == null || value instanceof BigDecimal ? (BigDecimal) value : new BigDecimal(this.value.toString())
    }

    private BigDecimal doesNotCompile() {
        return this.value == null || value instanceof BigDecimal ? value : new BigDecimal(this.value.toString())
    }

    void doesNotCompileToo(Integer other) {
        if (other.compareTo(0) == 0) {
            //
        }
    }

}
```
> [ERROR] return this.value == null || value instanceof BigDecimal ? value : new BigDecimal(this.value.toString())
[ERROR] ^
[ERROR] Groovy:[Static type checking] - Cannot return value of type java.lang.Number on method returning type java.math.BigDecimal
[ERROR] 
[ERROR] if (other.compareTo(0) == 0) {
[ERROR] ^^^^^^^^^^^^^^^^^^^
[ERROR] Groovy:[Static type checking] - Reference to method is ambiguous. Cannot choose between [int java.lang.Integer#compareTo(java.lang.Integer), int java.lang.Integer#compareTo(java.lang.Object)]
[ERROR]

**Comment by eric-milles** [comment]
The code snippet below from `StaticTypeCheckingVisitor` determines the type of the ternary expression (and hence the return statement).  Near the end, `typeOfTrue` is `Number` and `typeOfFlase` is `BigDecimal`.  This is why the error is shown.

I'm not sure why this passes for Groovyc and Groovy Console.  If I could find where flow-typing for the instanceof check is implemented, I may be able to understand the difference.  The variable expression for the field (the true expression) did not have an inferred type set in its metadata, so the field type was used directly.  If that type metadata was set, it would be used.

```java
    public void visitTernaryExpression(final TernaryExpression expression) {
        Map<VariableExpression, List<ClassNode>> oldTracker = pushAssignmentTracking();
        // create a new temporary element in the if-then-else type info
        typeCheckingContext.pushTemporaryTypeInfo();
        expression.getBooleanExpression().visit(this);
        Expression trueExpression = expression.getTrueExpression();
        Expression falseExpression = expression.getFalseExpression();
        trueExpression.visit(this);
        // pop if-then-else temporary type info
        typeCheckingContext.popTemporaryTypeInfo();
        falseExpression.visit(this);
        ClassNode resultType;
        if (isNullConstant(trueExpression) || isNullConstant(falseExpression)) {
            BinaryExpression enclosingBinaryExpression = typeCheckingContext.getEnclosingBinaryExpression();
            if (enclosingBinaryExpression != null && enclosingBinaryExpression.getRightExpression()==expression) {
                resultType = getType(enclosingBinaryExpression.getLeftExpression());
            } else if (isNullConstant(trueExpression) && isNullConstant(falseExpression)) {
                resultType = OBJECT_TYPE;
            } else if (isNullConstant(trueExpression)) {
                resultType = wrapTypeIfNecessary(getType(falseExpression));
            } else {
                resultType = wrapTypeIfNecessary(getType(trueExpression));
            }
        } else {
            // store type information
            final ClassNode typeOfTrue = getType(trueExpression);
            final ClassNode typeOfFalse = getType(falseExpression);
            resultType = lowestUpperBound(typeOfTrue, typeOfFalse);
        }
        storeType(expression, resultType);
        popAssignmentTracking(oldTracker);
    }
```

**Comment by eric-milles** [comment]
This should be fixed in the deployed plug-ins.  It will take me some time to create and publish a new batch compiler artifact.

FYI, I posted an issue to Groovy for the `instanceof` check because I think there is an improvement opportunity in `StaticTypeCheckingVisitor`: https://issues.apache.org/jira/browse/GROOVY-8337

**Comment by dsaita** [comment]
I can't seem to find the newer artifacts on the maven repository. Do I have to use bintray?

**Comment by eric-milles** [comment]
The latest batch compiler and compiler adapter versions are on bintray only at the moment.  They will be published to Maven Central once 2.9.2 is released.

**Comment by dsaita** [comment]
Is there a release calendar I can follow? Also, thank you very much for your help. Really appreciate it.

**Comment by eric-milles** [comment]
You can link to the latest compiler from bintray like this:

```xml
  <pluginRepositories>
    <pluginRepository>
      <id>groovy-bintray</id>
      <name>Groovy Bintray</name>
      <url>https://dl.bintray.com/groovy/maven</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.1</version>
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>2.9.2-03</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>2.4.12-03</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```
Here are the latest versions available:
groovy-eclipse-compiler:  [ ![Download](https://api.bintray.com/packages/groovy/maven/groovy-eclipse-compiler/images/download.svg) ](https://bintray.com/groovy/maven/groovy-eclipse-compiler/_latestVersion)

groovy-eclipse-batch: [ ![Download](https://api.bintray.com/packages/groovy/maven/groovy-eclipse-batch/images/download.svg) ](https://bintray.com/groovy/maven/groovy-eclipse-batch/_latestVersion)

**Comment by dsaita** [comment]
Will it be available on Maven?
My company has a mirror and it does not contain bintray.
I could ask them to mirror it, but if these artifacts are eventually going to Maven Central, I could wait.

**Comment by eric-milles** [comment]
It will.  I'm not sure of the timetable for completing the necessary setup.
