### ISSUE TITLE
Wrong completion for constructor code on a generic class

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#346]
This was the old GRECLIPSE-1761:

Consider the following Java class:

```java
package m; public class JavaClass<T extends Number> { }
```

And the following Groovy class:
```groovy
package m 

class M { 
	JavaClass<Integer> foo = new JavaCl| 
} 
```

Invoke code assist at "|" and choose the first suggestion.
The expected behaviour is to get either `new JavaClass<Integer>()` or `new JavaClass<>()`.
What I get instead is: `new JavaClass<Number>()`.

**Comment by eric-milles** [comment]
Is there a completion setting that must be enabled to get the generics in the completion proposal?  All I get is `JavaClass()` for the completion.  This matches what I would expect since the generics need not be given in Groovy.

**Comment by mauromol** [comment]
I was not aware of this, but after you told me, I discovered that this behaviour happens when the following option is enabled:
Preferences | Java | Editor | Content Assist | Fill method arguments and show guessed arguments
(with either of the radio buttons selected)

I have this option enabled in my workspaces, I can't remember whether I enabled it explicitly or if it is the default value.

**Comment by eric-milles** [comment]
Thanks.  That helps in recreation.  Do you actually want the generics for the constructor?  Or would a completion of `new JavaClass()` be acceptable?

**Comment by mauromol** [comment]
I would say `new JavaClass()` is perfectly acceptable, I can't think of any side effect (on subsequent type inference or such), as it should be roughly equivalent to `new JavaClass<>()`.

**Comment by mauromol** [comment]
In 2.9.2.xx-201710051703-e46 this works correctly, thank you! 👍
