### ISSUE TITLE
Navigation not working

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#347]
This use case is taken from the old GRECLIPSE-1755, but the symptom is different.

Create a Groovy project which depends on `org.hibernate:hibernate-core:3.5.6-Final` and write the following class:

```groovy
package f

import org.hibernate.SQLQuery
import org.hibernate.SessionFactory
import org.hibernate.impl.SessionFactoryImpl

class F { 
	static main(args) { 
		SessionFactory sf = new SessionFactoryImpl(null, null, null, null, null) 
		SQLQuery query = sf.currentSession.createSQLQuery('SELECT BLA BLA') 
	} 
}
```

When I opened GRECLIPSE-1755, Greclipse was confusing `org.hibernate.Session.createSQLQuery(String)` with `org.hibernate.classic.Session.createSQLQuery(String, String, Class)`, which is deprecated, and hence it was showing my method call with the deprecation highlighting.
This does not happen any more, but what I see now is that I can't navigate to `org.hibernate.impl.SessionFactoryImpl.getCurrentSession()` (by hitting F3 on `currentSession`) or to `org.hibernate.Session.createSQLQuery(String)` (by hitting F3 on `createSQLQuery`). Eclipse does nothing, apart from writing "Current text selection cannot be opened in an editor" in the status bar.

By the way, I noticed a lot of such problems in one of our main projects, but it's hard to extract a small and sharable use case from there. While trying to reproduce GRECLIPSE-1755 I could finally reproduce this behaviour, I hope you'll be able to reproduce as well.

**Comment by eric-milles** [comment]
Could you open the Console view and then the Groovy Event Console withi it?  Code Select should log its progress and any errors it encounters trying to resolve the methods.

**Comment by mauromol** [comment]
This is what Greclipse writes to the Groovy Event Console when I click on `currentSession`:

    Code select : 17:13:06 F.groovy at [272,0]
       Code select : 17:13:06 F.groovy at [272,0]
       Code select : 17:13:06 Event complete: 0ms: Code select: F.groovy
       Code select : 17:13:06 Event complete: 0ms: Code select: F.groovy

**Comment by eric-milles** [comment]
Bummer.  I'll have a look when I get some free time.

**Comment by eric-milles** [comment]
Interesting.  Ctrl clicking on `currentSession` goes to `org.hibernate.SessionFactory.getCurrentSession()` as expected.  Only the F3 (Open Declaration) key binding fails.

**Comment by mauromol** [comment]
Yes, it's interesting. I didn't realize that, I never use Ctrl+Click...

**Comment by eric-milles** [comment]
Ctrl-click is entering CodeSelectHelper.select with a offset and length that cover the entire name.  F3 enters the same with the offset of the cursor and a length of 0.  Because of this difference, the string literal check (below) is improperly returning true.

```java
    protected static boolean isStringLiteral(ASTNode node, char[] contents, int start, int length) {
        if (node instanceof ConstantExpression && ClassHelper.STRING_TYPE.equals(((ConstantExpression) node).getType())) {
            return (start > node.getStart() && length < node.getLength());
        }
        return false;
    }
```

**Comment by mauromol** [comment]
Hi Eric,
I tested this with 2.9.2.xx-201710020138-e46 and this use case works well now, thank you! 👍
