### ISSUE TITLE
Provide Example pom's in Documentation

### ISSUE THREAD

**Issue by cgorshing** [groovy/groovy-eclipse#349]
When building up a basic pom to use, I used https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin as the reference point. It took me a while to get this working the way I wanted and thought if a reference project/pom would be beneficial to others so they can copy/clone and go.

I've created https://github.com/cgorshing/groovy-simple as a starting point where all a dev wants is just groovy. I understand the other situations are valid and I would be happy to create those as starting points as well. If I do so, can we get those added to the docs too?

**Comment by eric-milles** [comment]
There are complete examples for each of the possibilities in the maven tests:  https://github.com/groovy/groovy-eclipse/tree/master/extras/groovy-eclipse-compiler-tests/src/it

**Comment by eric-milles** [comment]
There are also the quick-start archetype provided by the [groovy-eclipse-quickstart](https://github.com/groovy/groovy-eclipse/tree/master/extras/groovy-eclipse-quickstart) project.
