### ISSUE TITLE
Groovy repository for Oxygen provides wrong jdt.core?

### ISSUE THREAD

**Issue by NiciaB** [groovy/groovy-eclipse#350]
When installing oxygen SR 1 without groovy via oomph, the org.eclipse.jdt.core with version 3.13.0.v20170516-1929 is installed.

If we include groovy from http://dist.springsource.org/snapshot/GRECLIPSE/e4.7/ the following plugin is provided.

org.eclipse.jdt.core_3.13.50.xx-201710020138-e47

We encounter incompabilities with xText, NoSuchMethodErrors regarding
org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots.

**Comment by eric-milles** [comment]
Sorry, I got the impression when the release candidates for 4.7.1 stopped and candidates for 4.7.1a started that the Java 9 integration was part of the next Service Release.  I tested JDT Core 3.13.50 patch against the last Oxygen 4.7.1 RC and found no issues.

You could up to Oxygen 4.7.1a RC2 using this update site:  http://download.eclipse.org/eclipse/updates/4.7-M-builds/M-4.7.1aRC2-201709281310/

Or if you want to stick with SR1, I did save the last snapshot update site before the Java 9 patch.  It's 90MB so I would need a way to get it to you.

**Comment by NiciaB** [comment]
Thanks for your reply. I think there is no need to provide the last snapshot. I will retest with the 4.7.1a RC and xtext 2.13 and if the problem persists, I will inform the xtext team.

**Comment by hazemelraffiee** [comment]
I had the same problem, then I fixed it.
This is what I did:
1. Added http://download.eclipse.org/eclipse/updates/4.7/ as an update site, it showed me I can update the JDT, and I did
2. Restarted Eclipse
3. Then tried again installing Groovy from the update site http://dist.springsource.org/release/GRECLIPSE/e4.7 and it worked this time without this error
