### ISSUE TITLE
commons-cli dependency missing

### ISSUE THREAD

**Issue by SiKing** [groovy/groovy-eclipse#351]
I am not quite certain what is the root of my problem.

Running Eclipse Mars.2 latest (version 4.5.3) and latest greclipse from snapshot/GRECLIPSE/e4.5.

I have a Groovy script like:
```
def cli = new CliBuilder(
	usage: 'Some usage',
	header: 'Some header'
	)
cli.with { h longOpt: 'help', 'print this message' }
def options = cli.parse(args)
if(!options || options.h || options.arguments().size() == 0)
    cli.usage()
```

Running this from command line `groovy MyScript.groovy` works as expected.

I now create a Groovy project in Eclipse, and recreate the same script. Running this same script in Eclipse, produces:

```
Caught: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at CliProblem.run(CliProblem.groovy:1)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	... 1 more
```

I need to have an explicit dependency on commons-cli in order to make it run? When I created the project I already have the Groovy Libraries which contains groovy-all-2.4.12.jar. Even including something like:
```
@Grab(group='commons-cli', module='commons-cli', version='1.4')
```
does not fix the problem.

**Comment by eric-milles** [comment]
When you run the script in Eclipse, what command (menu item) are you using?

It is intentional that Groovy-Eclipse excludes the commons-cli, jline, and some other dependencies required for command line or shell execution.  They can be added to a project by a number of means.

To fully support everything that an install of groovy provides, all the following dependencies would be required:

ant
ant-antlr
ant-junit
ant-launcher
bsf
commons-cli
gpars
hamcrest-core
jansi
jcommander
jline
jsp-api
jst166y
junit
multiverse-core
qdox
servlet-api
testing
xmlpull
xstream

**Comment by SiKing** [comment]
To run the script from Eclipse I use: Run As > Groovy Script.

I did not realize that all those dependencies are up to the user to add. Would it hurt something if all these were part of the "Groovy Libraries" library in Eclipse?

**Comment by eric-milles** [comment]
If you want to have them with least effort, you can drop them into ~/.groovy/lib.  They will appear as part of the Groovy Libraries container after a refresh/restart.

**Comment by SiKing** [comment]
Without doing anything, in my Groovy Libraries I have:
groovy-all
bsf
ivy
servlet-api

I guess at this point I am wondering how is it determined which dependencies are included and which are not.

**Comment by eric-milles** [comment]
Groovy-Eclipse bundles those jars.  The others are considered infrequently used and need to be added to ~/.groovy/lib manually or included with Gradle, Ivy, Grab or some other means.

**Comment by unhuman** [comment]
Wow - late to this game - but I had a similar issue in IntellJ after some environmental issues and a restart of the project.  Turned out I just needed to Grab the Grape.
