### ISSUE TITLE
Support custom compiler annotations

### ISSUE THREAD

**Issue by nigelsim** [groovy/groovy-eclipse#353]
I'm using Groovy-Eclipse on a Grails 3 project. We are starting to the the @GrailsCompileStatic annotation to have Goovy do static type checking, but also not fail the methods that come from Grail's metaclasses. However, in Eclipse these methods are still marked as missing, so it appears that annotation isn't being applied in the same way it does from the command line. 

For instance, the `log` and `respond` methods on controllers are provided by metaclasses, but show up as errors.

[GrailsCompileStatic code](https://github.com/grails/grails-core/blob/246b7264e8a638ada188ddba7a7a8812ba153399/grails-core/src/main/groovy/grails/compiler/GrailsCompileStatic.groovy)
[GrailsCompileStatic docs](https://docs.grails.org/latest/guide/staticTypeCheckingAndCompilation.html)

Thanks

**Comment by eric-milles** [comment]
Can you provide a very small example?  CompileStatic and type checking extensions are indeed applied.  However, a command-line compilation is not the equivalent of opening a file for edit, parsing it, resolving types, and whatnot.  Some of the Groovy code is exported to the Java model so that the base JDT can do its thing.

**Comment by nigelsim** [comment]
Hi @eric-milles , please see https://github.com/nigelsim/grails-test-compile-static

From the command line this compiles fine
`
$ ./grailsw compile
> Configuring > 0/1 projects > root project > Resolving dependencies ':classpath:compileJava NO-SOURCE
:compileGroovy
:buildProperties
:processResources
:classes

BUILD SUCCESSFUL
`

But from the Grails project it fails.
![log method not found](https://user-images.githubusercontent.com/2869/31847439-088234c8-b660-11e7-9f2a-98bdf12c33ed.png)


Is it possible I've not properly configured something?

**Comment by eric-milles** [comment]
Here is a quick update.  The file did compile (there is a class file) with no errors (see Problems view).  The type checking error is in the editor only.

The `log` field is created by `org.grails.compiler.logging.LoggingTransformer`, which is executed by `org.grails.compiler.injection.GlobalGrailsClassInjectorTransformation`.  Do you have the [Grails tooling](https://github.com/spring-projects/grails-ide) installed?

![grails-transforms](https://user-images.githubusercontent.com/18193802/31914260-9471065c-b80f-11e7-9ee4-afd22a70df23.png)

**Comment by eric-milles** [comment]
To enable the global transformation on reconcile (editor opens file buffer, parses the source code, and resolves the types) you can add the system property `greclipse.globalTransformsInReconcile=org.grails.compiler.injection.GlobalGrailsClassInjectorTransformation` to your Eclipse (like in eclipse.ini).  I think GGTS did this as part of the distro.

**Comment by nigelsim** [comment]
Thanks @eric-milles, that addition to my eclipse.ini file does seem to have solved the issue. It's good to understand that the editor and the compiler have their own distinct views of the code. 

What are the consequences of putting that line in my eclipse.ini file? 

I'm not using any other Grails specific tools. It seems that everything that does exist (GGTS, Grails-IDE, etc) were pretty poor at best, and I've got far more mileage out of goovy-eclipse + buildship.

I'll give this a go on my main project today and will let you know how it goes.

**Comment by eric-milles** [comment]
I believe the global transforms were excluded from reconcile for efficiency.  Since the end result is not bytecode, no need to run stuff that does nothing to enhance the understanding of the lexical structure.  Only a few transforms actually add methods or fields that are then referred to in the source.  STC came later and so this efficiency gain may need to be reevaluated.  I'll add it to the 3.0 list.

**Comment by nigelsim** [comment]
Interestingly the use of `globalTransformsInReconcile` removes some, but not all type check errors from the editor. As you pointed out, these errors are only in the editor, not the compiler.

With globalTransformsInReconcile:
![with-globaltransformsinreconcile](https://user-images.githubusercontent.com/2869/32038456-59f57566-ba6d-11e7-9e6b-16ed23d53417.png)

Without globalTransformsInReconcile:
![without-globaltransformsinreconcile](https://user-images.githubusercontent.com/2869/32038457-5cba2562-ba6d-11e7-9332-eca5b7fe49ab.png)

I've pushed the change to demonstrate this to the previous repo.

**Comment by eric-milles** [comment]
There are more global transforms that were discovered on the classpath.  You could try adding one or more of them:

org.grails.datastore.gorm.query.transform.GlobalDetachedCriteriaASTTransformation
org.grails.compiler.gorm.GlobalTraitRepairTransformation
org.spockframework.compiler.SpockTransform
and one or more from Geb...
