### ISSUE TITLE
Camel-case code assist not working for property name completion in map-style constructor invocation

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#358]
Issue #331 added code assist for property name completion in map-style constructor invocation when the user starts to type the name of a property. However, the current implementation seems to correctly suggest results with a prefix-only guess, not with camel-case (which in Eclipse is usually found elsewhere in code assist, Groovy included).

Consider the slightly modified example:

```groovy
package c
class MyBean {
	String foo
	void setBar(String bar) {
		foo = bar.toUpperCase()
	}
        String thisIsAPropertyWithALongName
}
```

And: 

```groovy
package c
class ConstructorTest {
	static main(args) {
		MyBean b = new MyBean(tIAP|)
	}
}
```

When you invoke code assist at "|", no suggestion is shown.
Please note that:

- if you do the same after `b` instance has been created, to directly reference `b.thisIsAPropertyWithALongName`, camel-case completion works there (i.e.: `b.tIAP|` <= invoke code assist here)
- the case in which the property is defined by a setter only (like for `MyBean.bar` property) should also be covered

**Comment by eric-milles** [comment]
Can you re-test this?

**Comment by mauromol** [comment]
With 2.9.2.xx-201711022118-e46 this works fine, thank you! 👍 
(sorry, GitHub does not send a mail notification when you just commit, so I may miss some updates until you ping me)
