### ISSUE TITLE
Missing code assist while typing a ternary operator

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#359]
Consider this example:

```groovy
package test

class Ternary {

	static main(args) {
		def a = true? String.val|
	}
}
```

Assume I want to call `String.valueOf(boolean)`. Invoke code assist at "|": no suggestion is given.
In order to make Groovy give me some suggestions, I have to complete the second assignment, i.e. something like this:

```groovy
def a = true? String.val| : 'false'
```

If you invoke code assist at "|", it then works.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric, I tested this with 3.0.0.xx-201802242107-e47 and it seems to work fine now, thank you! 👍
