### ISSUE TITLE
Missing code assist within 'with' closure in static method

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#360]
Consider the following Java class:

```java
package test3;

import java.net.URL;

public class MyBean {

	private URL url;
	
	public URL getUrl() {
		return url;
	}
	
	public void setUrl(URL url) {
		this.url = url;
	}
}
```

And the following Groovy class:

```groovy
package test3

import groovy.transform.CompileStatic

@CompileStatic
class TestDotCompletion {

	static main(args) {
		MyBean b = new MyBean()
		// b.url.getAuthority()
		b.with {
			u|
		}
	}
}
```

Invoke code assist at "|" (I want to reference `b.url`): no suggestion for `b.url` is given. I would expect to find it as the top candidate.

Please note that if the method `main` is not static, code assist works ok for this case.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric, I tested this with 2.9.2.xx-201711060326-e46 and now `u|` is correctly completed inside the `with` closure. However, any attempt to request further code assist on `url.|` fails (no suggestions at all).
Should we open a new issue or rather keep this open?

**Comment by eric-milles** [comment]
Without the `@CompileStatic` the requested completions appear.  Static compilation has some strange AST conversions built into it.  I will need to decipher just what structure is there for `url.|`.

**Comment by eric-milles** [comment]
Can you open a separate ticket?  I know it seems lame, but the missing proposal for `url` is there now so the original issue has been fixed.
