### ISSUE TITLE
Missing code assist trigger with dot ('.') when referencing an object within a 'with' closure

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#361]
Consider the following Java class:

```java
package test3;

import java.net.URL;

public class MyBean {

	private URL url;
	
	public URL getUrl() {
		return url;
	}
	
	public void setUrl(URL url) {
		this.url = url;
	}
}
```

The following Groovy class:

```groovy
package test3

class MyGroovyBean {
  URL expectedUrl
}
```

And the following class:

```groovy
package test3

import groovy.transform.CompileStatic

@CompileStatic
class TestDotCompletion {
	void doSomething(MyGroovyBean groovyBean) {
		MyBean b = new MyBean()
		b.with {
			b.url = groo|
		}
	}
}
```

Invoke code assist at "|", highlight the first suggestion (`groovyBean`) and use "." (the dot) instead of Enter to accept the proposal: completion is not performed.
This is not coherent, I use "." a lot to accept completion proposals, either in Java or in Groovy.
Please note that if you try to following (more complex) case, it works instead:

```groovy
  b.url = new MyBe|
```

Invoke code assist at "|" and use "." to accept the `MyBean()` suggestion: completion is performed as expected.

**Comment by eric-milles** [comment]
Here are the current trigger characters, in case you think there are some keys missing.  For any case you run into that these are not causing the completion to be applied, the code is missing a call to `setTriggerCharacters`.

```java
    /** Triggers for method proposals without parameters. Do not modify! */
    public static final char[] METHOD_TRIGGERS = { ';', ',', '.', '[', ' ', '\t' };

    /** Triggers for method proposals. Do not modify! */
    public static final char[] METHOD_WITH_ARGUMENTS_TRIGGERS = { '(', '{', '-', ' ' };

    /** Triggers for types. Do not modify! */
    public static final char[] TYPE_TRIGGERS = { ';', '.', '=', '[', '(', ' ', '\t' };

    /** Triggers for variables. Do not modify! */
    public static final char[] VAR_TRIGGER = new char[] { ';', '.', '=', '[', '(', '{', ' ', '\t' };
```

**Comment by mauromol** [comment]
With 2.9.2.xx-201711022118-e46 this works now, thank you! 👍
