### ISSUE TITLE
Import declaration not added when requesting a constructor completion for a class in a different package

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#362]
Consider the Groovy class:

```groovy
package test4
class MyBean {
   String foo
}
```

and the following:

```groovy
package test5
class MyBean {
  int bar
}
```

(please note: two classes with the same name in different packages)
Then the following:

```groovy
package test5
class TestCompletion {
	void doSomething() {
		new MyB|
	}
}
```

(please note: same package as the second `MyBean` class).
Invoke code assist at "|" and choose `test4.MyBean()`: the constructor invocation is completed, but no import statement is added, hence the class being constructed is indeed `test5.MyBean` instead of `test4.MyBean`.

**Comment by eric-milles** [comment]
Can you re-test this?

**Comment by mauromol** [comment]
With 2.9.2.xx-201711022118-e46 this works fine, thank you! 👍
