### ISSUE TITLE
Code assist does not add necessary "owner" qualifier when accepting owner property suggestions within 'with' closure

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#364]
Consider the following:

```groovy
package test

class Test {
  static class Foo {
	  String someString = 'foo'
  }
  
  static class Bar {
	  String someString = 'bar'
	  Foo foo = new Foo()
	  
	  void doSomething() {
		  foo.with {
			  println "someString inside with closure = $someString"
			  println "someString of owner inside with closure = $owner.someString"
			  someS|
		  }
	  }
  }
  
  static main(args) {
	  Bar b = new Bar()
	  println "b.someString = $b.someString"
	  println "b.foo.someString = $b.foo.someString"
	  b.doSomething()
  }
}
```

Invoke code assist at "|": Greclipse correctly suggests both `Foo.someString` and `Bar.someString`, but if you choose any of those, it completes with just `someString`.
However, if I choose `Bar.someString`, I would expect code assist to change/complete my word as `owner.someString`, as this is the right way (AFAIK) to actually reference `Bar.someString` from there.

**Comment by eric-milles** [comment]
Looks like it can be determined by looking at the method declaration in some cases:
```java
    public static <T,U> T with(
            @DelegatesTo.Target("self") U self,
            @DelegatesTo(value=DelegatesTo.Target.class,
                    target="self",
                    strategy=Closure.DELEGATE_FIRST)
            @ClosureParams(FirstParam.class)
            Closure<T> closure)
```

**Comment by mauromol** [comment]
Yes, I think some way should exist, at least for API methods, because otherwise I can't imagine how `@CompileStatic` could work...

**Comment by mauromol** [comment]
I see your commit of 4 days ago is referencing this bug too, but with 2.9.2.xx-201711070247-e46 code assist is still just completing to `someString` whichever choice I make.

**Comment by eric-milles** [comment]
The commit was just a step towards identifying `delegate` and `owner` correctly in this situation.

**Comment by eric-milles** [comment]
Could you join me on [Slack](https://groovy-community.slack.com/) so we can talk priority order for issues?

**Comment by mauromol** [comment]
I don't know Slack very well. I believe I need an invitation from you to join your workspace?

**Comment by eric-milles** [comment]
You can sign up at https://groovycommunity.com/

**Comment by mauromol** [comment]
I've joined the Slack workspace.

**Comment by eric-milles** [comment]
Proposal de-duplication changes for #735 have affected this use case.  The proposals from both Foo and Bar will need to be offered again before the missing qualifier can be sorted out.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
With 3.2.0.xx-201811292113-e48 the mentioned use case works, although I would expect `Foo.someString` to be proposed before `Bar.someString` in this context.

Also, neither `someString` nor `owner.someString` are found when searching for references or invoking call hierarchy on `Foo.someString` and `Bar.someString` respectively. Should I open a new issue for this?

**Comment by eric-milles** [comment]
Please open as separate issues.  If qualifier is added when required, this issue is completed.
