### ISSUE TITLE
Missing code assist in static method with @CompileStatic

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#371]
Follow-up to #360.

Consider the following Java class:

```java
package test3;

import java.net.URL;

public class MyBean {

	private URL url;
	
	public URL getUrl() {
		return url;
	}
	
	public void setUrl(URL url) {
		this.url = url;
	}
}
```

And the following Groovy class:

```groovy
package test3

import groovy.transform.CompileStatic

@CompileStatic
class TestDotCompletion {

	static main(args) {
		MyBean b = new MyBean()
		// b.url.getAuthority()
		b.with {
			url.|
		}
	}
}
```

Invoke code assist at "|": no suggestion at all is shown.

Please note that if you remove `@CompileStatic` or if you replace it with `@TypeChecked`, it works fine.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric, I tested this with 2.9.2.xx-201711160311-e46, but it works partially.
Completion invoked as "url.|" works, but if you try to invoke completion like this: "url.a|" no suggestions are shown, while I should be able to insert "url.authority".

This discrepancy on code assist "right after the dot" working, but not "after some letters have been typed", is not rare in Greclipse and is really annoying indeed :-( It makes the whole thing feel "fragile" to use.

**Comment by eric-milles** [comment]
From a user's perspective, this may all seem like the same thing.  But under the covers, recognizing "url.|" (i.e. no expression after the dot) and "url.a|" are actually two very different things.  The ASTs are quite different.  It does not always follow that one will work if the other does.  This may seem slow and painful, but each issue needs to be rooted out on its own.  Adding @CompileStatic in 2.0 created a lot of tech debt all at once.

**Comment by mauromol** [comment]
I understand. Do you wish me to open a separate issue for this or let we keep this bug report as the "user perspective" on proper autocompletion in this scenario?

**Comment by eric-milles** [comment]
I am working on a fix.  I thought I had tried this out before checking in last time, but I must have been trying that case with @CompileStatic off.  Please understand the level of effort required to get it to this point.  When I picked up development of Groovy-Eclipse, @CompileStatic was barely handled by the inferencing engine.

**Comment by mauromol** [comment]
Don't worry Eric, no negligence by your side, you're doing a great job, really!

**Comment by eric-milles** [comment]
Here's the kinda stuff I'm dealing with.  No source position for the object expression (aka `url`) in this case.

![sc-completion](https://user-images.githubusercontent.com/18193802/32903251-26cac60c-caba-11e7-995d-212ab3338c27.png)

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Tested again with 2.9.2.xx-201711162156-e46, now all seems to work fine, even camel-case completion! 👍 
Thank you!
