### ISSUE TITLE
Wrong call detected on Date.parse(String, String)

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#372]
Consider the following:

```groovy
class TestDateParse {
	static main(args) {
		Date.parse('dd/MM/y', "16/09/1980")
	}
}
```

As you can see, Greclipse is highlighting the call as deprecated, but if you use F2 or F3 over `parse` you see that this is because it's thinking it's calling `Date.parse(String)` rather than `Date.parse(String, String)` (which is not deprecated).

This is a regression, because the exact same problem was fixed already in the past with GRECLIPSE-1396.

**Comment by eric-milles** [comment]
I only see one parse method.

![date-parse](https://user-images.githubusercontent.com/18193802/32499977-a757df8a-c399-11e7-8c98-5cb11801a56d.png)

**Comment by mauromol** [comment]
Groovy JDK adds more methods to `Date`: http://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Date.html#parse(java.lang.String,%20java.lang.String)
I think it's implemented through `org.codehaus.groovy.runtime.DefaultGroovyStaticMethods.parse(Date, String, String)`.

**Comment by eric-milles** [comment]
Detection of static Groovy methods is not very complete.  I'm not that surprised the DGSM is missed.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric, I tested this with 2.9.2.xx-201711130408-e46 and it seems to be fixed, thank you! 👍
