### ISSUE TITLE
Invalid reference detected by Call Hierarchy

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#373]
Consider the following two Groovy classes:

```groovy
package test6

class Foo {
  URL doSomething(String s, URL u) {
  }
  
  URL doSomething(Integer i, URL u) {
  }
}
```

And:

```groovy
package test6

class Test6 {
	
	Foo foo = new Foo()
	
	void bar() {
		URL u = new URL('www.example.com')
		foo.doSomething('ciao', u)
	}
}
```

As you can see with F2 or F3 over the call of `doSomething()` on `foo`, Greclipse correctly detects that the call references `Foo.doSomething(String, URL)`. However, if you put the cursor over `Foo.doSomething(Integer, URL)` and you press Ctrl+Alt+H (Call Hierarchy), you'll see that a reference from `Test6.bar()` is detected, which is not the case indeed.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric, I tested this with 2.9.2.xx-201711262138-e46 and it works correctly now! Thank you! 👍
