### ISSUE TITLE
Conflict with servlet-api

### ISSUE THREAD

**Issue by TobiX** [groovy/groovy-eclipse#375]
I was a little surprised that groovy-eclipse bundles servlet-api 2.4 and apparently adds it to the classpath of all Eclipse run configurations. Is this really necessary?

I noticed this with a project which uses a somewhat modern Jetty, which depends on servlet-api 3.0.1 - Unfortunatly, the project cannot be launched from Eclipse anymore, since servlet-api 2.4 ends up on the classpath before servlet-api 3.0.1 and they conflict.

**Comment by eric-milles** [comment]
I stopped doing this for Groovy 2.5.  If you don't want it, you can change the classpath container to the "minimal" setting (groovy-all jar only) by right clicking on it and picking Properties.

**Comment by eric-milles** [comment]
Another note: If you use Ivy, Gradle or Maven to import dependencies, you can bring in `groovy-all` that way and ditch the Groovy Libraries classpath container altogether.
