### ISSUE TITLE
Method not recognized when invoked from an anonymous inner class

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#378]
Consider the following Groovy class:

```groovy
package test8
class A {
	protected def m() { }
	
	Object p = new Object() {
		String toString() {
			m()
		}
	}
	
	void init() {
		def whatever = new Object() {
		  def something() {
			m()
		  }
		}
	  }
  }
```

What I see is that `m()` call from the definition of `A.p` field (with an inner class) is underlined.
Instead `m()` call from the definition of `whatever` local variable is not underlined, by nevertheless it seems like the call is not recognized (F2 and F3 do not work).
Funny enough, if you comment out the p field definition, then the second call to `m()` becomes underlined :-)

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
With 2.9.2.xx-201711100505-e46 this works partially. If you use the use case I provided, now, the `m()` call from the anonymous inner class of `p =` assignment is recognized, while the `m()` call from the anonymous inner class of `whatever = ` assignment is not. If you comment out the `p` assignment, then the second call is recognized, too.

You can see this by trying to refactor `m` to `doSomething`: you'll see that only the first method call is renamed.

**Comment by eric-milles** [comment]
They're not underlined at least.  ;)

**Comment by eric-milles** [comment]
Actually, the local variable assignment case is not type inferencing / semantic highlighting any part of the anon. inner definition.  This is what all anon. inners used to be like.

**Comment by eric-milles** [comment]
Could you open a separate issue for the 2 anon. inners causing the second to be unprocessed?

**Comment by mauromol** [comment]
> Actually, the local variable assignment case is not type inferencing / semantic highlighting any part of the anon. inner definition. This is what all anon. inners used to be like.

Sorry, I think I didn't understand :-(
Anyway, it's strange the behaviour of Greclipse once you comment out the `p` assignment. You'll see `m()` underlined then even in `whatever` assignment.

I'll open a separate issue.
