### ISSUE TITLE
Import not updated for nested enum class

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#379]
Consider the following Java class:

```java
package test9;
public class Outer {
  public static enum MyEnum {
	  A, B;
  }
}
```

And the following Groovy class:

```groovy
package test9
import test9.Outer.MyEnum
class GroovyClass {
	void doSomething() {
		MyEnum myEnum = MyEnum.A
	}
}
```

Now refactor `Outer` class and rename it to `Outer2`.
The following line in `GroovyClass` is not updated:
`import test9.Outer.MyEnum`

**Comment by eric-milles** [comment]
Same issue exists if `MyEnum` is a class, trait or interface.

**Comment by eric-milles** [comment]
ready to test

Fully- or partially-qualified names within the class or script body are a bit trickier.  They may contain extra whitespaces and have some other complications that I did not deal with quite yet.

**Comment by mauromol** [comment]
Hi Eric, I tested this with 2.9.2.xx-201711140121-e46 but the behaviour I see is not correct.

After renaming `Outer` to `Outer2`, this is what I expect:

```groovy
package test9
import test9.Outer2.MyEnum
class GroovyClass {
	void doSomething() {
		MyEnum myEnum = MyEnum.A
	}
}
```

This is what I get instead:

```groovy
package test9
import test9.Outer2.Outer2
class GroovyClass {
	void doSomething() {
		Outer2 myEnum = Outer2.A
	}
}
```

In other words, not only the `Outer` class name is changed in the import declaration, but also `MyEnum` is changed to `Outer2` (both in the import declaration and in the method body), which is of course wrong.

**Comment by eric-milles** [comment]
Bummer.  I forgot to test with non-star imports.  My final tweaks must have reversed a previous check that I had to prevent this matching which I was seeing early on.

**Comment by eric-milles** [comment]
ready to re-test

**Comment by mauromol** [comment]
Seems to work fine now with 2.9.2.xx-201711150348-e46, thank you! 👍
