### ISSUE TITLE
Can not install latest version (2.9.2) with Eclipse Oxygen

### ISSUE THREAD

**Issue by andersb** [groovy/groovy-eclipse#381]
Hi

I'm having problem installing this plugin for Eclipse Oxygen.
Just downloaded Oxygen Java IDE package so JDT is included.

In the release notes for 2.9.2 (https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-2.9.2-Release-Notes), the url for to use is for Eclipse Oxygen 
http://dist.springsource.org/release/GRECLIPSE/2.9.2/e4.7

That url doesn't exist. 

On the other hand, the snapshot for 4.7 is working, http://dist.springsource.org/snapshot/GRECLIPSE/e4.7/

Am I missing something here?

**Comment by eric-milles** [comment]
Yes, sorry for the confusion.  The release does not yet exist.  I have been preparing the release notes for when it is available.  Unitl then, only the snapshot update sites are live.
