### ISSUE TITLE
Field initializer anonymous inner class fouling up type inferencing / semantic highlighting

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#383]
Follow-up to #378.
Consider the following Groovy class:

```groovy
package test8
class A {
	protected def m() { }
	
	Object p = new Object() {
		String toString() {
			m()
		}
	}
	
	void init() {
		def whatever = new Object() {
		  def something() {
			m()
		  }
		}
	  }
  }
```

`m()` call from the definition of `whatever` local variable is not underlined, but it's not actually recognized, as you can see with F2 or F3 on it, or by trying to rename `m()` to something else.

Please note that if you comment out the p field definition, then the second call to `m()` becomes recognized.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric, I tested this with 2.9.2.xx-201711130408-e46 and it seems to be fixed, thank you! 👍
