### ISSUE TITLE
Please update stable releases

### ISSUE THREAD

**Issue by cbruchert** [groovy/groovy-eclipse#385]
Why are there no stable releases since 4.4 (Luna)? Using snapshot builds is annoying since it requires restarting Eclipse almost every day.

**Comment by eric-milles** [comment]
I am in the process of fixing the last few bugs and cutting a release.  If you wish to have a particular snapshot available indefinitely for you or your organization, you can copy the update site artifact of a particular build from the Bamboo CI server.

**Comment by eric-milles** [comment]
I have even prepared [release notes](https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-2.9.2-Release-Notes) as a sign I am planning on releasing very soon.
