### ISSUE TITLE
Significant performance impact in the latest builds

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#386]
With the latest Greclipse builds I noticed a significant performance impact when the Groovy parser/compiler is invoked when validating JSF facelets (i.e.: .xhtml files containing JSF tags and Expression Languages) in WTP Dynamic Web Projects.

I'm attaching here some thread dumps. They were taken during the validation of a single .xhtml file. As you can see, the validation took almost 7 minutes!! Fortunately, not all .xhtml take so long to validate: my feeling is that the first .xhtml file of each DWP project in the workspace takes a lot, the other are much faster (and, I would say, comparable to what happened in the past). As a reference, to validate all the 67 .xhtml files in two DWPs, Eclipse took about 15 minutes. Problem is that validation may block user actions (like saving an open editor), so the user cannot just ignore and let Eclipse do the whole work in the background. The feeling may be that Eclipse is just hanged, while it is not (validation finishes at last).

Working with a Haswell i7 CPU with 4 cores (8 threads) and 32 GB RAM. The CPU works a lot.

I'm not sure which version of Greclipse introduced this performance regression, it's certainly >= 2017-11-15 (before, I was working on another project for which I did not notice this kind of problem).

Here you can find the thread dumps:
https://www.dropbox.com/sh/tvgum35phfi94ip/AAA7GROVYwZVxGTg_hwlo8iSa?dl=0
They were all taken while validating a single .xhtml file. They are 9 dumps that spawn about 7 minutes of processing.

**Comment by eric-milles** [comment]
I think it was when I added `unit.getModuleNode()` to this line in `TypeInferencingVisitor.visitMethodCallExpression`:

```
        VariableScope.CallAndType call = new VariableScope.CallAndType(node, t.declaration, t.declaringType, unit.getModuleNode());
```

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Tested with 2.9.2.xx-201711162156-e46, now performance is back to normal, great job! 👍 
Validating those 67 .xhtml now takes about 2 minutes (instead of 15).
