### ISSUE TITLE
Missing incoming/outgoing decorations in Synchronize View for Groovy files

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#388]
This is a long standing issue, originally reported as GRECLIPSE-1691 and also tracked in the Eclipse Bugzilla at: https://bugs.eclipse.org/bugs/show_bug.cgi?id=397118

Since this happens specifically with Groovy files, I suspect it's somewhat a Greclipse fault. I reproduce this with a Subversion repository (using Subeversive), I don't know if this happens with eGit too.

If you change a shared Groovy file  and then right click on the project => Team => Synchronize with Repository, the Synchronize View of the of Team Synchronizing perspective opens: changed .groovy files do not show incoming/outgoing decorations, in contrast to what happens with other files like .java or .xml. I see this happending with .gradle files too, which are handled by the Groovy editor in my system, as well.

**Comment by eric-milles** [comment]
Can you provide a screenshot here that contrasts Java files with the decorations and Groovy files missing them?  I know where in the code all this is done, I just need to be able to see what success looks like.

And if you could provide a reliable link to a current Subersive install, that might help.  Or do you know if the decorations are missing in Synchronize view for other source control systems?

**Comment by mauromol** [comment]
Subversive can be installed from the Oxygen or Neon Update sites. If you have troubles with the connectors installation, let me know (there's an open issue with Oxygen).

I don't know if decorations are missing in the Synchronize View for other source control systems.

A screenshot to compare the behaviour for Java and Groovy files is here:
https://bugs.eclipse.org/bugs/attachment.cgi?id=225015

You'll find just outgoing changes, let me know if you need me to build a screenshot with incoming changes as well. However, the concept is that the "arrow" is towards the left instead of towards the right.

**Comment by eric-milles** [comment]
Interesting that for Git, the same issue can be seen in the upper tree, but the lower Git Commits tree shows the arrows.

![synchronize-view](https://user-images.githubusercontent.com/18193802/32957643-eff76324-cb81-11e7-9a09-ac061e643fb1.png)

**Comment by eric-milles** [comment]
For this to work, Groovy files that are outside of source folders had to be sacrificed.  In the Package Explorer and Project Explorer, they will show the external Java resource icon.  They are not easily distinguished from Groovy sources that are properly located within a source folder when viewed in the Navigator, Synchronize and other content-type config based views.

**Comment by eric-milles** [comment]
Also, Gradle files will still suffer from this issue.  Precedence had to be given to a correct file icon ahead of the image overlays.

**Comment by mauromol** [comment]
I think it's a good compromise. Groovy files inside source folders are the most important ones. Also, I think I've read Buildship guys are working on a dedicated editor for Gradle files, so I don't think Greclipse will still be of much use there.

**Comment by eric-milles** [comment]
The conflict with Gradle is due to Greclipse defining a content type for Gradle files and so the JDT sees them as Java resources.  If this definition were removed, there would be no more special case.  I did not remove for backwards compatibility.  But could do so in the next major release.

**Comment by mauromol** [comment]
Hi Eric,
I tested this with 2.9.2.xx-201711221437-e47, but I still see no overlays.
See here:

![immagine](https://user-images.githubusercontent.com/1742494/33167046-9ed288ba-d03c-11e7-9b2d-0bd390cc264f.png)

**Comment by eric-milles** [comment]
Can you uncheck _Preferences > General > Appearance > Label Decorations > Groovy Source File_ and reopen the sync view?

**Comment by mauromol** [comment]
If I uncheck that option, I do have incoming/outgoing decorations, but Groovy files have then the same icon of Java files.

**Comment by eric-milles** [comment]
Okay, that means the files are seen as compilation units.  This is different from how the Git integration saw the files.  A little background: Navigator and other like views deal with Resources (aka Files) only.  Therefore the Content Type config XML works as defined and the icons show up properly without the Label Decorator enabled.  Java-based views like Package Explorer and Project Explorer see another type of abstraction: Compilation Units.  Because Groovy content type is a child of the Java content type, the Java views try to apply Java handling to the Groovy Compilation Units.  That is why you would see J file icons instead of G ones in the Project Explorer -- and as it turns out Subversive/Synchronize view.

The label decorator tries to tread as lightly as possible, however it must replace the base image for Compilation Units to overwrite the J icon.  My recent change was to leave the base image alone for Resources.  Synchronize view for Git used Resources and so the incoming/outgoing decorations would remain.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
I tested this with Greclipse 2.9.2.xx-201712032337-e47.
As you explained my in Slack, now you're disabling icons in the Synchronize View, so that decorations for incoming/outgoing changes are now shown correctly, although as overlays to the standard Java icons.

I think it's a good compromise, at least it's better than the previous behaviour. Thank you!
