### ISSUE TITLE
Method renaming not working in @CompileStatic Groovy enum

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#390]
This was GRECLIPSE-1538 and very similar to #389, but having `@CompileStatic` annotation.

Consider the following:

```groovy
package b; 

import groovy.transform.CompileStatic

@CompileStatic
enum R { 
	A() { 
		@Override 
		String getFoo() { 
			
		} 
	}, 
	B() {
		 @Override 
		 String getFoo() { 
			 "bar" 
		 } 
	} 
	
	String getFoo() { 
		
	} 
} 
```

Now, select `getFoo` in either `A` or `B` definition and hit Ctrl+Shift+R to rename. Greclipse complains that "Cannot refactor on current selection".

Now try to do the same on the base declaration of `getFoo()` and change `getFoo()` into `getBar()`: the corresponding overridings in `A` and `B` are not updated, hence a compilation error is produced.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Tested with 2.9.2.xx-201711162156-e46. Now refactoring from the base `getFoo()` works. The behaviour is equal to the non-`@CompileStatic` case, hence #389 applies too.
