### ISSUE TITLE
Create getter and setter proposals shown even if the field does not exist

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#392]
Consider the following Groovy class:

```groovy
package a 

class TestF { 
	Stri|
} 
```

Invoke code assist at "|". What I want to do is to type "String" to define a `String` class field. However, the first suggestions given by Greclipse are for the creation of `getStri()` and `setStri(Object)`. These completions, which are very useful when a field exists and you want to create the corresponding getter and setter, is quite useless IMHO if the field does not exist. There may be cases in which I want to create a getter/setter without having the corresponding class variable, but in this case I would place suggestions about class name completions BEFORE those of getter/setter creation, because it's much more likely that I just want to complete a class name for type declaration in this scenario.

**Comment by eric-milles** [comment]
The idea is when typing in the class body to suggest the creation of new members.  These need not be backed by anything.

**Comment by mauromol** [comment]
I see, but what about the ordering of proposals? Don't you think that in this scenario 90% or even more of the times you want to type in a class name, rather than to create a getter/setter with no backing field?

**Comment by eric-milles** [comment]
Types have very low relevance score because there can be so many type proposals.

**Comment by mauromol** [comment]
Well, it depends on how many characters you type... And there's camel-case match... ;-)
