### ISSUE TITLE
"Assign statement to new local variable" quickfix producing a compilation error when "return" is present

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#393]
This was inspired by the old GRECLIPSE-1523.

Consider the following:

```groovy
package a 

class TestF { 
	public PrintStream test() { 
		return System.out 
	} 
} 
```

Highlight "System.out", press Ctrl+1 and choose "Assign statement to new local variable". This is the result:

```groovy
return def temp = System.out
```

which produces a compilation error.

Probably, in this case that quickfix should not be available (just like in JDT), because a more proper quickfix is "Extract to local variable" (which, by the way, produces the correct result).

**Comment by eric-milles** [comment]
Okay, I got it.  So "Assign statement to local variable" is an invalid quick assist for a return statement.  If you use "Extract local variable" you get the desired effect.

**Comment by mauromol** [comment]
Exactly!

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
I tested this with 2.9.2.xx-201711221440-e46 and the "Assign statement to local variable" quick fix is no longer available in this case, thank you! 👍
