### ISSUE TITLE
Missing code assist proposals to implement missing methods in anonymous inner class

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#395]
This is somewhat the old GRECLIPSE-1426.

Consider the following Java interface:

```java
package test;

public interface I {
	void myMethod(String a, int b);
}
```

And the following Groovy class:

```groovy
package test

class B { 
	void test() { 
		I myvar = new I(){ 
			 |
		} 
	} 
}
```

Invoke code assist at "|": I would expect to see the following proposal:

myMethod(String a, int b): void - Override method in 'I'

(indeed, it should be "implement missing method", rather than "override", but it's not that important)

However, no proposal at all is shown.

**Comment by eric-milles** [comment]
Probably a model thing again.  If anonymous inners are represented in the JDT model the same way plain inners are, they should receive the same checks.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
I probably need to wait more for a new build, because on 3.1.0.xx-201808212342-e47 I still see no improvement here.

**Comment by mauromol** [comment]
Ok, a new build is available now: 3.1.0.xx-201808220545-e47.
There's an improvement, but this is what is produced after I choose to implement `myMethod`:

```groovy
package test

class B { 
	void test() { 
		I myvar = new I(){ 
			 void myMethod(String arg0, int arg1) {};|
		} 
	} 
}
```

(cursor at "|")
Expected behaviour:

```groovy
package test

class B { 
	void test() { 
		I myvar = new I(){ 
			 void myMethod(String a, int b) {
				 |
			 }
		} 
	} 
}
```

**Comment by mauromol** [comment]
I know the missing parameter names is due to #394, but what I think is still wrong here is the `{};` after the method name, instead of opening a block, placing the cursor inside of it and not adding any trailing `;`.

**Comment by eric-milles** [comment]
`org.eclipse.jdt.internal.ui.text.java.OverrideCompletionProposal.updateReplacementString(IDocument, char, int, ImportRewrite)` is returning the wrong node for `ASTNode node= NodeFinder.perform(unit, offset, 1);` and so the wrong parent type for `node= ASTResolving.findParentType(node);`.  This prevents the abstract method lookup and so a plain stub is inserted.

**Comment by eric-milles** [comment]
I've got this working locally.  I'm just working out some JDT resolve issues for anonymous inners that use a non-default constructor.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
The latest build that gets downloaded is 3.1.0.xx-201808242320-e47, and what I see with this is exactly the same behaviour I described in my previous comment.

**Comment by eric-milles** [comment]
![1](https://user-images.githubusercontent.com/18193802/44668958-69f37280-a9e4-11e8-8e30-ce258f4517e0.png)

![2](https://user-images.githubusercontent.com/18193802/44668962-6c55cc80-a9e4-11e8-9340-8cefe26862e4.png)

**Comment by eric-milles** [comment]
I tried unix line endings, tabs, no space between ctor call and block start.  All are generating the proper method stub for me.  I'm not sure what is different.

**Comment by mauromol** [comment]
Is the build I'm using the right one?
