### ISSUE TITLE
Import not added when using a nested class in current package

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#403]
Consider the following:

```groovy
package test14
class Outer {
  static class Nested {
	  String foo
	  Integer bar
  }
}
```

And:

```groovy
package test14
class Test14 {
  void foobar() {
	  def n = new Nes|
  }
}
```

Invoke code assist at "|" and choose "Nested() - test14.Nested": no import declaration is added and Groovy complains that it is "unable to resolve class Nested".

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Yes, this use case works with 3.0.0.xx-201802132346-e47 already, thank you! 👍
