### ISSUE TITLE
Luna release repository is broken

### ISSUE THREAD

**Issue by sjka** [groovy/groovy-eclipse#406]
http://dist.springsource.org/release/GRECLIPSE/e4.4/

points to 

http://dist.springsource.org/release/GRECLIPSE/2.9.2/e4.4

which apparently doesn't exist anymore.

**Comment by eric-milles** [comment]
2.9.2 releases are being built this week (1st week of January 2018).  Previously that link pointed to 2.9.1.

**Comment by eric-milles** [comment]
You may also reference the 2.9.1 release update site directly if you want to go that route.

http://dist.springsource.org/release/GRECLIPSE/2.9.1/e4.4

**Comment by sjka** [comment]
That's a surprising way of dealing with supposably stable release repositories, but I assume you will have your reasons...
Thanks for your hint, that indeed did the trick for me!
