### ISSUE TITLE
In "org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler": Failed compilation, but no messages (including suggestion to fix)

### ISSUE THREAD

**Issue by dtonhofer** [groovy/groovy-eclipse#407]
When compiling with Maven from the command line using _groovy-eclipse-compiler_ plugin , compilation of a mixed Java/Groovy project (which compiles properly inside Intellij IDEA) fails but doesn't say why (not forking, verbose true):

> $ mvn compile
> ....
> [INFO] All args: ....
> [INFO] Compilation complete.  Compiled 0 files.
> [INFO] Found 0 errors and 0 warnings.
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.556 s
> [INFO] Finished at: 2018-01-07T01:36:23+01:00
> [INFO] Final Memory: 14M/48M
> [INFO] ------------------------------------------------------------------------

This is due to messages being dropped in 

> org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.parseMessages()
 
called by

> org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.internalCompile()
 
In this case, a modified `internalCompile()` shows that the string `Compliance level '1.4' is incompatible with target level '9'. A compliance level '9' or better is required` was elided.

> [INFO] All args: ...
> [INFO] In-process (not forking) mode
> [INFO] Compilation complete.  Compiled 0 files.
> [INFO] Success: false
> [INFO] Out string: Compliance level '1.4' is incompatible with target level '9'. A compliance level '9' or better is required
> 
> [INFO] Found 0 errors and 0 warnings.
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.520 s
> [INFO] Finished at: 2018-01-07T01:41:02+01:00
> [INFO] Final Memory: 14M/48M
> [INFO] ------------------------------------------------------------------------

Note that this loop I added to print `CompilerMessage` (see further below for context) prints nothing:

```
                for (CompilerMessage cm : newMsgs) {
                    getLogger().info(cm.toString()); // added
                }
```

The message should be displayed lest the user be left in the dark as to what's going on.

Here is the modified `internalCompile()` logging the above:

```
private boolean internalCompile(CompilerConfiguration config, List<CompilerMessage> messages) throws CompilerException {
        String[] args = createCommandLine(config);
        if (args.length == 0) {
            getLogger().info("Nothing to compile - all classes are up to date");
            return true;
        }
        boolean success;
        if (config.isFork()) {
            getLogger().info("Forking mode"); // added
            String executable = config.getExecutable();
            if (isBlank(executable)) {
                try {
                    executable = getJavaExecutable();
                } catch (IOException e) {
                    getLogger().warn("Unable to autodetect 'java' path, using 'java' from the environment.");
                    executable = "java";
                }
            }

            String groovyEclipseLocation = getGroovyEclipseBatchLocation();
            success = compileOutOfProcess(config, executable, groovyEclipseLocation, args, messages);
        } else {
            getLogger().info("In-process (not forking) mode"); // added
            StringWriter out = new StringWriter();
            Result result = InternalCompiler.doCompile(args, out, getLogger(), verbose);
            success = result.success;
            String outStr = out.getBuffer().toString();  // added
            try {
                int exitCode = success ? 0 : 1;  // rearranged
                List<CompilerMessage> newMsgs = parseMessages(exitCode, outStr, config.isShowWarnings());
                messages.addAll(newMsgs);
                for (CompilerMessage cm : newMsgs) {
                    getLogger().info(cm.toString()); // added
                }
            } catch (IOException e) {
                getLogger().warn(e.toString()); // added to not have silent exceptions
                messages = new ArrayList<CompilerMessage>(1);
            }
            getLogger().info("Success: " + success); // added to get at success flag
            getLogger().info("Out string: " + outStr); // added to see raw outStr
            if (!success) {
                messages.add(formatResult(success, result.globalErrorsCount, result.globalWarningsCount));
            }
        }
        return success;
    }
```
Not completely sure where the parsing of the compiler message fails as the code that processes the compiler messages looks like a hairy/ad-hoc affair (is there a better way to do that? Unprocessable lines should definitely be collected then dumped out later) and it's late.

(Additionally there are some typos in the code error messages and a few lines of fishiness, interested in pull request? I don't know how to run a test suite on the plugin though)

**Comment by eric-milles** [comment]
What versions of groovy-eclipse-compiler and groovy-eclipse-batch are you using?  I thought I fixed the hidden compiler messages.

**Comment by dtonhofer** [comment]
Hi Eric,

That would be: groovy-eclipse-compiler 2.9.2-04, groovy-eclipse-batch 2.4.13-02

And I looked at the source code of "commit 3bfa051 18 days ago"

**Comment by eric-milles** [comment]
Okay, thanks.  You can test any changes by running "mvn clean integration-test" on the groovy-eclipse-compiler-tests project.  You may need to intall your groovy-eclipse-compiler changes and then set the revision in the pom.xml of the compiler tests project.

I'd be happy to look at a pull request.  You'll need to sign the Pivotal CLA first.

**Comment by eric-milles** [comment]
I'd like to try and fix parseMessages so it does not throw and each message is parsed or added as-is in case of error.  Do you have the pom file that resulted in getting the error message that you mentioned above?

**Comment by dtonhofer** [comment]
Hi Eric. I can look at this this evening, I'm currently not getting all my stuff done...
