### ISSUE TITLE
BUG! exception in phase 'class generation' in source unit '/Users/xxxxx/a/b/c/Test.groovy' unsupported Target TYPE_USE

### ISSUE THREAD

**Issue by satishgudluru** [groovy/groovy-eclipse#425]
Getting the following error when compiling from maven using groovy-eclipse-compiler (with couple of versions including latest 2.9.2-01) . 

_**BUG! exception in phase 'class generation' in source unit '/Users/xxxxx/a/b/c/Test.groovy' unsupported Target TYPE_USE. at org.codehaus.groovy.vmplugin.v5.Java5.getElementCode(Java5.java:371)**_

If the Test.groovy uses @NotNull annotation  from javax.validation.constraints package of java 8 throws this error.
TYPE_USE has been added in java 8. 
I'm able to build the project with IntelliJ's build option with the latest groovy (version = 2.4.13). 
but I'm not able to compile it from maven.
Here is my pom.xml plugin configuration.

`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <compilerArguments>
                        <source>1.8</source>
                        <target>1.8</target>
                    </compilerArguments>
                    
                    <compilerId>groovy-eclipse-compiler</compilerId>
                    
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>2.9.2-01</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.4.3-01</version>
                    </dependency>
                </dependencies>
            </plugin>
`
And the groovy dependencies
` <properties>
     <groovy.version>2.4.13</groovy.version>
       ......
       .......        
</properties>
<dependencies>       
            <dependency>
                  <groupId>org.codehaus.groovy</groupId>
                  <artifactId>groovy-all</artifactId>
                   <version>${groovy.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-json</artifactId>
            <version>${groovy.version}</version>
        </dependency>
        ......
       .......   
</dependencies>`

My observations:
I can see the Java5 class in groovy has the fix for this issue. 
`default:
                if ("TYPE_USE".equals(value.name()) || "TYPE_PARAMETER".equals(value.name()) || "MODULE".equals(value.name())) {
                    // return 0 value because we are binary or'ing this and want to ignore without failing
                    // later version plugins will override and provide sensible values for jdk8+
                    return 0;
                }
                throw new GroovyBugError("unsupported Target " + value);
`
that is why I can compile it in IDE.
So from this we can understand that groovy-eclipse compiler is not using the latest groovy.
Is there any way to force this compiler to use latest groovy.

Thanks

.

**Comment by eric-milles** [comment]
Could you share your pom.xml?  Have you tried groovy-eclipse-compiler 2.9.2-04 and groovy-eclipse-batch 2.4.13-02?  They should be Java 8 compatible.  All of the Groovy-Eclipse tests are compiled using this combo and have a Java 8 minimum.

**Comment by satishgudluru** [comment]
@eric-milles,
Here is the extract of my pom.xml ( also mentioned in the issue).
Also as you mentioned groovy-eclipse-compiler 2.9.2-04 and groovy-eclipse-batch 2.4.13-02, 
I don't see these versions in maven repository.
`<plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-compiler-plugin</artifactId> <version>3.7.0</version> <configuration> <compilerArguments> <source>1.8</source> <target>1.8</target> </compilerArguments>  <compilerId>groovy-eclipse-compiler</compilerId>  </configuration> <dependencies> <dependency> <groupId>org.codehaus.groovy</groupId> <artifactId>groovy-eclipse-compiler</artifactId> <version>2.9.2-01</version> </dependency> <dependency> <groupId>org.codehaus.groovy</groupId> <artifactId>groovy-eclipse-batch</artifactId> <version>2.4.3-01</version> </dependency> </dependencies> </plugin>
And the groovy dependencies
<properties> <groovy.version>2.4.13</groovy.version> ...... ....... </properties> <dependencies> <dependency> <groupId>org.codehaus.groovy</groupId> <artifactId>groovy-all</artifactId> <version>${groovy.version}</version> </dependency> <dependency> <groupId>org.codehaus.groovy</groupId> <artifactId>groovy-json</artifactId> <version>${groovy.version}</version> </dependency> ...... ....... </dependencies>`

**Comment by eric-milles** [comment]
Here is my recommendation for you POM.  Newer Groovy-Eclipse Maven plug-ins are hosted in Bintray.
```xml
  <pluginRepositories>
    <pluginRepository>
      <id>groovy-bintray</id>
      <name>Groovy Bintray</name>
      <url>https://dl.bintray.com/groovy/maven</url>
    </pluginRepository>
  </pluginRepositories>
  ...
  <properties>
    <groovy.version>2.4.13</groovy.version>
    <maven.compiler.fork>true</maven.compiler.fork>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  ...
  <dependencies>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>${groovy.version}</version>
    </dependency>
    <!-- groovy-json is redundant -->
  </dependencies>
  ...
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>2.9.2-04</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>2.4.13-02</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```

**Comment by satishgudluru** [comment]
@eric-milles , Thanks a lot, it worked. I appreciate your quick responses.
