### ISSUE TITLE
Not formatting files without *.groovy extension

### ISSUE THREAD

**Issue by lucasvc** [groovy/groovy-eclipse#437]
[Jenkinsfile's is a DSL language based on Groovy](https://jenkins.io/doc/book/pipeline/jenkinsfile/), so Groovy editor can be used.
But when editing those files with Groovy editor, if the extension is not `.groovy` the formatter is not applied.
If renaming file to end with `.groovy`, the formatter works as expected.

My Eclipse installation:
```
Eclipse Java EE IDE for Web Developers.

Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600
```

Groovy installation settings:
```
  Eclipse Groovy Development Tools	3.0.0.xx-201801222116-e47	org.codehaus.groovy.eclipse.feature.feature.group	Codehaus.org
    Groovy Compiler 2.4	3.0.0.xx-201801222116-e47	org.codehaus.groovy24.feature.feature.group	Codehaus.org
    Groovy-Eclipse Compilerless Feature	3.0.0.xx-201801222116-e47	org.codehaus.groovy.compilerless.feature.feature.group	Codehaus.org
      Groovy-Eclipse Headless Feature	3.0.0.xx-201801222116-e47	org.codehaus.groovy.headless.feature.feature.group	Codehaus.org
  Groovy-Eclipse M2E integration	3.0.0.xx-201801222116-e47	org.codehaus.groovy.m2eclipse.feature.feature.group	Codehaus.org
```

**Comment by urosvonta** [comment]
yes, this is really annoying

**Comment by eric-milles** [comment]
You can add "Jenkinsfile" to the list of Groovy content types here:
![image](https://user-images.githubusercontent.com/18193802/86275236-8f310900-bb98-11ea-8063-63d795e78c36.png)
