### ISSUE TITLE
Class rename does not update generic references

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#442]
Consider the following:

```groovy
package test20
class MyBean {}
```

And:

```groovy
package test20
class Test20 {
	List<MyBean> list
}
```

Now rename `MyBean` to `MyBean2`: the reference to `MyBean` type in the declaration of `Test20.list` is not updated with the new name.

**Comment by eric-milles** [comment]
It all comes down to the indexing performed by `org.codehaus.jdt.groovy.integration.internal.GroovyIndexingVisitor`.  If I add an import, the file gets identified by the indexing search for further AST searching.  `GroovyIndexingVisitor.visitField` has the type visitation commented out.

**Comment by eric-milles** [comment]
Ready to test.

**Comment by mauromol** [comment]
Hi Eric,
the latest version that gets downloaded if I do "check for updates" is 3.0.0.xx-201801262137-e47, which still exhibits this problem.

**Comment by eric-milles** [comment]
I forgot to mention that you will need to rebuild your Java indexes for this change to help.  The rename relies on the indexes to determine what to search for references.  The indexing was improved and so a new index should result in more possible matches.

**Comment by mauromol** [comment]
I tried to clean the Groovy project the test case is in, isn't it enough to rebuild the index?

Also, your "ready to test comment" was published on 2018-01-27, the latest snapshot is from 2018-01-26... isn't it a snapshot publish problem?

**Comment by eric-milles** [comment]
Cleaning does not rebuild the index.  There is a button under Window > Preferences > Java to do so.

**Comment by mauromol** [comment]
Ok, thank you, seems to work now, after rebuilding the index. I really thought a complete project rebuild would cause the index to be rebuilt as well.
Thanks!
