### ISSUE TITLE
Incorrect handling of non-starred static imports w/o explicit public declarations

### ISSUE THREAD

**Issue by FlasH-RUS** [groovy/groovy-eclipse#444]
Hi,

It looks like groovy-eclipse is not able to handle non-starred static imports of fields w/o an explicit _public_ modifer from a different package correctly. I.e. I have a pkg.Constants class like that:
```
package pkg;

class Constants {
    static final String HELLO = 'Hello'
}
```
Doing `import static pkg.Constants.HELLO` from anywhere outside of this _pkg_ package results in my Eclipse complaining that "The field Constants.pkg.Constants.HELLO is not visible". At the same time it runs with plain Groovy and doing `import static pkg.Constants.*` is also fine from Eclipse perspective.
Here's an example project: https://github.com/FlasH-RUS/groovy-eclipse-static-imports

Configuration used:
- Eclipse Oxygen.2 Release (4.7.2), build: 20171218-0600
- groovy-eclipse version: 3.0.0.xx-201801262137-e47

**Comment by eric-milles** [comment]
This has been reaised in the past; I do not have the issue number at hand.  The field reference is private and so JDT warns of access issues.  If you add a modifier to the Property, it becomes a field and behavior of the modifier is predictable.  This is one of those transparency issues between Groovy/groovyc and Greclipse/ecj.

**Comment by eric-milles** [comment]
The star import `import static pkg.Constants.*` is the equivalent of `import static pkg.Constants.getHELLO`.  The getter generated for the property has public access.  The field `HELLO` is private.

**Comment by FlasH-RUS** [comment]
Ok, so the public modifier is my bet bet... Will trigger another holy war round with IDEA lovers :)
Thanks for quick response anyway.

**Comment by eric-milles** [comment]
For reference, #336 discusses this same issue.  My opinion with regards to code style is to use the explicit `public` for constant fields.  This prevents Groovy from generating `getCONSTANT` method that is unnecessary and just plain ugly.  This also means all accesses go directly to the field and may be inlined.  Hope that helps explain my position and gives you something to take to your team as to why adding the modifier could be a positive change.

**Comment by jeacott** [comment]
personally I feel that whilst it might be a good idea to add the explicit public moniker, the language itself has rules and this breaks them. it makes eclipse useless when dealing with code you have no option but to leave as is.
groovy-eclipse should perhaps offer a warning, but it certainly should not enforce this.
