### ISSUE TITLE
Code select missing for type in map constructor expression

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#452]
Consider the following:
```groovy
class Test {
  void meth() {
    new Bean(number: 0, string: '')
  }
}

class Bean {
  Number number
  String string
}
```

Code select is not available on `Bean` in "new Bean)...".

Also, if `number: 0, string: ''` is replaced with `/*number: 0, string: ''*/`, "number" and "string" are still code selectable.

**Comment by mauromol** [comment]
I also noticed this problem.

**Comment by mauromol** [comment]
I confirm this is fixed for me too.
