### ISSUE TITLE
Map-style contructor call not shown in call hierarchies

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#489]
Consider the following Java class:

```java
package test22;
public class MyBean {
	private String foo;
	public void setFoo(String foo) {
		this.foo = foo;
	}
}
```

and the following Groovy class:

```groovy
package test22
class Test22 {
	public Test22() {
		def b = new MyBean(foo: 'hello')
	}
}
```

Invoke Call Hierarchy (Ctrl+Alt+H) on `MyBean.setFoo(String)`: the implicit call to that setter triggered by the map-style constructor call in `Test22` is not reported.

**Comment by eric-milles** [comment]
Quick note on why Call Hierarchy is showing a different result from Search for References (Ctrl-Shift-G): reference search is invoking both method and field search; Call Hierarchy is invoking method search only.  Currently the field search is what finds the map ctor reference.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Hi Eric,
I tested with 3.0.0.xx-201802242107-e47 but I don't see any difference in behaviour. Invoking Call Hierarchy on `MyBean.setFoo(String)` does not show any reference from `Test22`. Nor it does if I reference it through `b.foo = 'foo'`. May the snapshot update site not be updated?

**Comment by eric-milles** [comment]
In your example, are you sure you have both a field and a setter?  There is a bit of a gap between synthetic and non-synthetic property access searching.  I tested specifically with the test case you gave.

**Comment by mauromol** [comment]
Yes, I tested with this exact test case.

**Comment by eric-milles** [comment]
Just for some extra background, Search for References (Ctrl-Shift-G) executes a method pattern search but also invokes any IQueryParticipant extensions that are registered.  Groovy adds the SyntheticAccessorSearchRequestor as a participant.  It finds "foo.bar" where "bar" is "getBar", "setBar" or "isBar".  But it is limited to looking for synthetic accesses (that is no field "bar" exists).  Between the MethodReferenceSearchRequestor and SyntheticAccessorSearchRequestor, searching for references covers a lot of ground.

However, Call Hierarchy (Ctrl+Alt+H) only triggers the MethodReferenceSearchRequestor.  I modified it to locate non-synthetic accesses (getters/setters when there is a backing field), which was not covered by SyntheticAccessorSearchRequestor.  There is some tension in making one too powerful as the raname participant handles a rename of "setBar" and must differentiate between references to "bar" vs "setBar" when renaming.

This method is from MethodReferenceSearchRequestor.  The commented check at the end previously only accepted matches for the exact method name in the source.  I relaxed this, but needed to be careful not to relax it too much to keep rename tests working.  I went through a couple iterations of this but what was committed passed all my tests.  I'm not sure if reindexing or something had an impact on my results.
```java
    public VisitStatus acceptASTNode(ASTNode node, TypeLookupResult result, IJavaElement enclosingElement) {
        if (result.declaringType == null) {
            // GRECLIPSE-1180: probably a literal of some kind
            return VisitStatus.CONTINUE;
        }

        boolean isDeclaration = (node instanceof MethodNode);
        int start = 0;
        int end = 0;

        if (result.declaration instanceof MethodNode) {
            if (methodName.equals(((MethodNode) result.declaration).getName())) {
                if (isDeclaration || node instanceof StaticMethodCallExpression) {
                    start = ((AnnotatedNode) node).getNameStart();
                    end = ((AnnotatedNode) node).getNameEnd() + 1;
                } else {
                    String text = node.getText(); // check for non-synthetic match; SyntheticAccessorSearchRequestor matches "foo.bar" to "getBar()" w/o backing field
                    if (methodName.equals(text) || result.declaringType.getField(text) != null) {
                        start = node.getStart();
                        end = node.getEnd();
                    }
                }
            }
        }
```

**Comment by mauromol** [comment]
I just tried to rebuild the index, but I still don't get references from `Test22` in the above use case :-(

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Does not work for me yet on 3.0.0.xx-201802282219-e47, even after rebuilding the index...
Does the above use case work for you?

**Comment by eric-milles** [comment]
Is the constructor named argument the only reference you have to setFoo in the file?  I have been testing with multiple different references, like this:
```groovy
def bean = new test22.MyBean(foo: '123')
bean.setFoo(null)
bean.@foo = null
bean.&setFoo
```

**Comment by mauromol** [comment]
I'm using the exact same code above (copy 'n' paste), hence two classes, just one reference to foo (the constructor call).

**Comment by eric-milles** [comment]
Indexing fix is testing now

**Comment by mauromol** [comment]
If I add a call to `b.setFoo('foo')`, then hits start to appear. The hits that are shown are:
- the constructor call
- `b.setFoo('foo')`
However, I would also expect that `b.foo = 'foo'` (missing in your example) were found, because it is indeed an implicit setter call. However, this is not the case.
I don't know well the `@` and `&` syntaxes, I guess they should not be found.

If I remove the `b.setFoo('foo')` call, no hit is shown at all.

**Comment by mauromol** [comment]
Sorry, I have to remove both references to `b.setFoo('foo')` and `b.&setFoo` to make Groovy stop find anything in call hierarchy.

**Comment by eric-milles** [comment]
The type inference engine is missing the "method call arguments" in the expression "bean.foo = null".  Without them, it is returning a match for Bean.setFoo with loose confidence.  If the argument was matched to the parameter, the confidence would be higher and therefore the call hierarchy reference would show through.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
With 3.0.0.xx-201803020428-e47, given this:

```groovy
package test22
class Test22 {
	public Test22() {
		def b = new MyBean(foo: 'c')
		b.foo = 'foo'
		b.@foo = 'foo'
		b.setFoo('foo')
		def m = b.&setFoo
	}
}
```
And invoking Call Hierarchy on `MyBean.setFoo(String)`, now these matches are found:
- `def b = new MyBean(foo: 'c')` (which was the subject of this issue)
- `b.setFoo('foo')` (which always worked)

But this is not found:
- `b.foo = 'foo'`

Do you wish me to open a new issue for the last case or do you prefer to use this one?

**Comment by mauromol** [comment]
Also, what do you think about this?

```groovy
def m = b.&setFoo
m('foo')
```

**Comment by eric-milles** [comment]
Not sure about that.  The method reference and call may be separated by quite a distance in the code.

**Comment by mauromol** [comment]
Right. So, could this case be considered in a similar fashion on what happens when you have Anonymous Inner Classes in Java?

Look at this example:

```java
package test22;
public interface TestInterface {
  void bla();
}
```

And:

```java
package test22;
public class TestBla {
	public TestBla() {
		TestInterface t = new TestInterface() {
			
			@Override
			public void bla() {
			}
		};
		t.bla();
	}
}
```

Invoke Call Hierarchy on `TestInterface.bla()` and look at the result, where there are special branches for "constructor" and "callers". Maybe we could use a special branch for `def m = b.&setFoo` named "references" to highlight that there is a method reference there that could be subsequently used to invoke the referenced method somewhere else?

**Comment by eric-milles** [comment]
I'd have a look at how method references are handled.  They are the closest peer in Java.  Please file separate issues for property access (should work for getter/isser case, just not setter) and for method pointers (if there is a specific behavior you'd like to see that is comparable to how method references are handled).
