### ISSUE TITLE
JDT compiler fails to compile legitimate Java code

### ISSUE THREAD

**Issue by lgoldstein** [groovy/groovy-eclipse#495]
Initially opened as [Eclipse issue 531414](https://bugs.eclipse.org/bugs/show_bug.cgi?id=531414) - so more details there, but the gist of it:

I have some _CQEngine_ code that compiles and runs just fine when compiled and generated via _Maven_ and the JDK compiler. However, when compiled by JDT it fails and creates a malformed class which means I cannot debug the code. Furthermore, this same code used to compile and run just fine up until a few days back when some patch/update of the JDT was applied. I can't say which - I just clicked Install when the update dialog was presented.  Basically, it claims that the following code invokes a non-existing constructor:

```java
public abstract class NonConcurrentAbstractMapBasedAttributeIndex<A, O, MapType extends Map<A, StoredResultSet<O>>> extends AbstractAttributeIndex<A, O> {

    protected NonConcurrentAbstractMapBasedAttributeIndex(
        Factory<MapType> indexMapFactory,
        Factory<StoredResultSet<O>> valueSetFactory,
        Attribute<O, A> attribute, Set<Class<? extends Query>> supportedQueries) {
    super(attribute, supportedQueries);
}
```

The error is: 

>> The constructor AbstractAttributeIndex<A,O>(Attribute<O,A>, Set<Class<? extends Query>>) is undefined

But if we look at _AbstractAttributeIndex_ we see this is not the case:

```java
public abstract class AbstractAttributeIndex<A, O> implements AttributeIndex<A, O> {
    protected AbstractAttributeIndex(Attribute<O, A> attribute, Set<Class<? extends Query>> supportedQueries) {
        ...
    }
}
```

I think I have confirmed this to be a Groovy JDT issue:

1. I re-installed Eclipse Oxygen 2 with (!) Groovy support and JDT "patch" and the problem was re-produced
2. After re-installing Eclipse Oxygen 2, this time without any Groovy support the problem was not re-produced

Luckily I no longer need Groovy support (at least not in the near future), but the issue should be resolved. Some further research might seem to indicate that this happens if one uses the [nightly snapshot](http://dist.springsource.org/snapshot/GRECLIPSE/e4.7/) instead of the [release](http://dist.springsource.org/release/GRECLIPSE/e4.7) - although I have not confirmed this 100% (lack of time...) it may indicate a bug in the making nevertheless so worth some research.

**Comment by eric-milles** [comment]
I can take a quick look.  Please be advised that the current Greclipse snapshot builds for Eclipse Oxygen are current with [4.7.3rc2](http://download.eclipse.org/eclipse/downloads/drops4/M-4.7.3RC2-201802150545/).  So you should try that out for a fair comparison.

**Comment by eric-milles** [comment]
I was unable to reproduce the error with the snippets you supplied.

**Comment by lgoldstein** [comment]
Thanks for the effort - I will keep an eye out if/when I re-install _Greclipse_ - this time only from the release repository - and see if it happens again and perhaps I can focus the failure to a more specific code snippet...
