### ISSUE TITLE
Wrong insertion of guessed argument when "Completion overwrites" is chosen

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#500]
Found while verifying #367.

Consider the following Java enum:

```java
package b;
public enum MyEnum {
	VAL1, VAL2, VAL3;
}
```

the following Java class:

```java
package b;
public class Utility {
	public static void doSomething(MyEnum enumValue) {
	}
}
```

and the following Groovy class:

```groovy
package b 

class Test4 { 
	void doSomething() { 
		Utility.doSom|
	} 
}
```

Consider these options in Java | Editor | Content assist:
- Completion overwrites CHECKED
- Use static imports UNCHECKED
- Fill method arguments and show guessed arguments CHECKED
- Insert best guessed arguments CHECKED

Invoke code assist at "|": you'll get `Utility.doSomething(VAL3)` (`VAL3` highlighted) and then choose `VAL1`. The result is: `Utility.doSomething(MyEnum.VAL3VAL1)`.

If "Use static imports" is CHECKED, the result, instead, is: `Utility.doSomething(VAL3VAL1)` (the added static import is correct, though).

The problem doesn't happen if you check "Completion inserts" instead of "Completion overwrites".

**Comment by eric-milles** [comment]
`org.codehaus.groovy.eclipse.codeassist.completions.ParameterGuesserDelegate#newEnumProposal` is where enum value arguments are created with supporting import or qualifier.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
With 3.1.0.xx-201808210011-e47 it works as expected.
Although I was wondering why the "insert best guessed arguments" with Groovy Editor suggests VAL3. The Java editor suggests null, because there's no hint in that context that suggests something different.

**Comment by eric-milles** [comment]
The list of proposals for each parameter is built up in: https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.codeassist.completion/src/org/codehaus/groovy/eclipse/codeassist/completions/ParameterGuesserDelegate.java#L52

The array of enum elements is iterated from end to beginning.  Not sure why it is done that way.  Iterating in the natural order would probably give the result you expect.

**Comment by mauromol** [comment]
Not yet, I would expect `null`, because nothing in the surrounding context suggests any concrete enum value (in the form of a local variable, parameter, field or anything else) to be suggested. See how JDT behaves. It's not a big deal, though, if you agree with this point of view I can open a new issue.
