### ISSUE TITLE
Unrecognized static method call from within closure

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#502]
Consider this:

```groovy
package test25
class Test25 {
	static void foo() {
		String a = 'a'
		File b = new File()
		new Object().each {
			bar(a, b)
		}
	}
	
	static void bar(String a, File b) {
		
	} 
}
```

The call to `Test25.bar(String, File)` from `Test25.foo()` (inside the closure) is not recognized: it's underlined and navigation with F3 or Ctrl+Click does not work correctly.

**Comment by eric-milles** [comment]
If `static` is removed from `foo`, the reference is resolved.  It is missed from a static scope because `Class<Test25>` is being passed around in the type inferencer.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Tested with 3.0.0.xx-201802282219-e47: the above use case works, but this does not work yet (i.e.: closure inside closure):

```groovy
package test25
class Test25 {
	static void foo() {
		String a = 'a'
		File b = new File()
		new Object().each {
			new Object().each {
				bar(a, b)
			}
		}
	}
	
	static void bar(String a, File b) {
	
	} 
}
```

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
With 3.0.0.xx-201803020428-e47 even the case of static call in closure-inside-closure works, thank you!
