### ISSUE TITLE
Errors occurred during the build with a Grails 3 application and  Eclipse

### ISSUE THREAD

**Issue by sdelamo** [groovy/groovy-eclipse#504]
I am trying to use  Grails 3 with Eclipse. 

I have installed Eclipse Oxygen.

I have installed groovy-eclipse para eclipse as described here:

https://github.com/groovy/groovy-eclipse/wiki#how-to-install

I have set the Groovy Compiler in eclipse to use 2.4.13 which is the groovy version of the Grails 3.3.2 version which I want to use.  

I have installed Buildship Gradle Plugin:

https://projects.eclipse.org/projects/tools.buildship

When I import the Grails 3 project, a Gradle project,  I get this error: 

Errors occurred during the build.
Errors running builder 'Java Builder' on project 'geb-example-grails'.
org.grails.compiler.gorm.GlobalJpaEntityTransform.hasAnnotation(Lorg/codehaus/groovy/ast/ClassNode;Lorg/codehaus/groovy/ast/ClassNode;)Z

Any idea what can I do?

Thanks,
Sergio del Amo

**Comment by eric-milles** [comment]
Do you have a stack trace for the error?  Looks like Grails/GORM is experiencing a method not found error.

**Comment by sdelamo** [comment]
This is what I get. 

<img width="744" alt="napkin 7 02-03-18 7 58 05 am" src="https://user-images.githubusercontent.com/864788/36887018-72176876-1def-11e8-9378-0036b8fa48d1.png">

I don't know how to get a better trace: 

```
The following will be send to: Eclipse


REPORT

anonymousId         62fea7b8-38a4-49d2-b753-951371853618
name                
email               
comment             
eclipseBuildId      4.7.2.M20171130-0510
eclipseProduct      org.eclipse.epp.package.java.product
javaRuntimeVersion  1.8.0_161-b12
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.13.3
osgiArch            x86_64
severity            UNKNOWN


STATUS

pluginId            org.eclipse.core.resources
pluginVersion       3.12.0.v20170417-1558
code                75
severity            4
message             Errors occurred during the build.
fingerprint         eff79aefae060a9482cf05b162202c44

Exception:org.eclipse.epp.logging.aeri.core.util.NoStackTrace: This event was logged without a stack trace. A synthetic stack trace was hence inserted.
	 at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:702)
	 at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:114)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:78)


STATUS

pluginId            org.eclipse.jdt.core
pluginVersion       3.13.101.xx-201802282219-e47
code                75
severity            4
message             Errors running builder 'Java Builder' on project 'geb-example-grails'.
fingerprint         57e92a834b6062322d876e32ca78d6a5

Exception:java.lang.NoSuchMethodError: org.grails.compiler.gorm.GlobalJpaEntityTransform.hasAnnotation(Lorg/codehaus/groovy/ast/ClassNode;Lorg/codehaus/groovy/ast/ClassNode;)Z
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:897)
	 at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:141)
	 at java.lang.Thread.run(Thread.java:748)


BUNDLES

name                org.codehaus.groovy
version             2.6.0.xx-201802282219-e47

name                org.eclipse.core.jobs
version             3.9.2.v20171030-1027

name                org.eclipse.jdt
version             3.13.2.v20171130-0510

```

**Comment by eric-milles** [comment]
Can you open up the Error Log view?  There should be more details there.  I would need a stack trace from the exception to have any hope.  You may also want to switch Groovy compiler versions to 2.4 under Window > Preferences > Groovy > Compiler.

**Comment by sdelamo** [comment]
I set the groovy compiler to 2.4.13 and that seems to solve the issue. I could swear I had tried that yesterday before submitting the issue. Thanks a lot. I am going to close the issue
