### ISSUE TITLE
Create of element failed in Eclipse 4.7 on Fedora 27

### ISSUE THREAD

**Issue by sdhawley** [groovy/groovy-eclipse#505]
I've tried this with both release and snapshot builds of groovy eclipse plugin and keep getting this error:
org.eclipse.jdt.internal.core.CompilationUnit cannot be cast to org.codehaus.jdt.groovy.model.GroovyCompilationUnit

This comes with an error running Java Builder.

The file is created but cannot be viewed with the groovy editor.

Preferences screen says I'm using groovy compiler version 2.4.13 (installed from the update site), my system has 2.4.8 installed (Fedora 27).

Uninstalling my local groovy installation (2.4.8) seems to resolve the issue, but I also had to make a fresh install of eclipse due to some dependencies on the groovy-libs@2.4.8.

My question, is there anything we can do to ensure the independence of the groovy installed in eclipse and the version installed with the system? Make sure the plugin uses only the specified version?

**Comment by eric-milles** [comment]
Do you have a file and line for the cast exception?

**Comment by eric-milles** [comment]
For the Groovy installed on the system, does that occupy/populate `~/.groovy/lib`?  Within Eclipse at Window > Preferences > Groovy > Compiler, you can uncheck "Include jars in ~/.groovy/lib on the classpath" (enabled by default).  This should increase the independence of your Eclipse runtime.

**Comment by sdhawley** [comment]
I'm sorry, I didn't save the stack trace but it did get submitted through the automatic error capture facility.

The system groovy was under /usr, there wasn't anything in ~/.groovy/lib

**Comment by eric-milles** [comment]
Do you know what was depending on Groovy 2.4.8?  You mentioned you needed to reinstall Eclipse after removing the system groovy.

**Comment by sdhawley** [comment]
It was a bunch of things, Fedora packaged eclipse 4.7 and it somehow was depending on groovy-libs package, I had to uninstall the system eclipse and a bunch of other java packages before I could remove the groovy-libs@2.4.8 package. Once that was all out I installed eclipse 4.7 to my home directory, installed the groovy plugin from the update site, and everything worked fine.

**Comment by eric-milles** [comment]
Would it be possible for you to capture the Configuration information (Help > About Eclipse Platform > Installation Details button > Configuration tab) -- at least the Features and Plug-in Registry sections -- from the system Eclipse?  I can't really determine the nature of the conflict without more details.

**Comment by sdhawley** [comment]
Unfortunately I can't, I uninstalled the system eclipse. I don't have time right now to do a reinstall and try to recreate but I suspect it could be reproduced with a fresh install of fedora in a virtualbox.

**Comment by eric-milles** [comment]
The issue as I see it is the Fedora-supplied eclipse install is heavily provisioned through RPM.  This means features and plugins are in /usr/lib/eclipse, /usr/share/eclipse, ~/.eclipse and probably more.  The JDT Core patch that Groovy-Eclipse requires appears to be applied in terms of the Installation Details.  But the errors in the Java Builder and the Groovy Editor indicate that the patch has not been applied.

This issue should be moved to eclipse.org so they can determine how eclipse is provisioned under Fedora and if patch features are supported in this environment.

Here is the error during startup:
```
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jdt.core [642]
  Another singleton bundle selected: osgi.identity; type="osgi.bundle"; version:Version="3.13.100.v20171217-1438"; osgi.identity="org.eclipse.jdt.core"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1613)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```
