### ISSUE TITLE
Implicit getter and setter accesses not shown in Call Hierarchy

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#508]
Something like a follow-up to #489.
Consider the following Java class:

```java
package test22;
public class MyBean {
	private String foo;
	public void setFoo(String foo) {
		this.foo = foo;
	}
	public String getFoo() {
		return foo;
	}
}
```

And the following Groovy class:

```groovy
package test22

import groovy.transform.CompileStatic

@CompileStatic
class Test22 {
	public Test22() {
		def b = new MyBean(foo: 'c')
		b.foo = 'foo'
		def c = b.foo
	}
}
```

Invoke Call Hierarchy on `MyBean.setFoo(String)`: I would expect to see references from `def b = new MyBean(foo: 'c')` and `b.foo = 'foo'`. However, I just see the first (thanks to #489), not the second.

Invoke Call Hierarchy on `MyBean.getFoo()`: I would expect to see references from  `def c = b.foo`, but I don't see it.

**Comment by eric-milles** [comment]
`org.eclipse.jdt.groovy.search.MethodReferenceSearchRequestor.acceptASTNode(ASTNode, TypeLookupResult, IJavaElement)` finds the desired reference, but returns it as an "inaccurate" match and so the Call Hierarchy does not show it.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
This works well in 3.1.0.xx-201809022023-e47! This is a **great** improvement, thank you! 👍
