### ISSUE TITLE
Exclamation mark without proper problem marker

### ISSUE THREAD

**Issue by ctron** [groovy/groovy-eclipse#515]
All groovy files do have a red exclamation mark, however there is no problem marker registered with this file and so there is no way to find out what is actually wrong. Also there is no indication in the editor that there is any problem. I am sure there is no filter hiding the problem marker.

Eclipse: Oxygen.2
Groovy Development Tools: 3.0.0.xx-20180306

Screenshot:

![image](https://user-images.githubusercontent.com/202474/37036106-f5d7ee8a-214e-11e8-9996-29ab2b415813.png)

**Comment by eric-milles** [comment]
This is an indication that you have groovy sources but Groovy nature and builder is not configured for the project.  This is consistent with Java indication for sources without nature/builder.

**Comment by ctron** [comment]
> This is an indication that you have groovy sources but Groovy nature and builder is not configured for the project. This is consistent with Java indication for sources without nature/builder.

I am sorry, but this is not correct. See:

![image](https://user-images.githubusercontent.com/202474/37041494-a6642a4a-215c-11e8-97d1-7b29da33ae94.png)

**Comment by eric-milles** [comment]
Does your project have Groovy nature?  If not, you can add from context menu Configure > Convert to Groovy Project.  If it is a Maven project, then a Maven > Update Project... should update the nature and classpath entries.

**Comment by ctron** [comment]
It does not have the Groovy nature and I also don't want to convert it to a Groovy project. It is a Java Maven project which contains Groovy files.

**Comment by eric-milles** [comment]
A project can have both the Java and Groovy natures.

**Comment by ctron** [comment]
Great, but does it need to have? Maybe registering a proper error marker would help here.

**Comment by eric-milles** [comment]
If you don't want to add the nature, you can continue as-is with editing capability for the Groovy sources.  If you don't like the red exclamation marks, you need to add the Groovy nature to your project.
