### ISSUE TITLE
Using ASTParser

### ISSUE THREAD

**Issue by marcingrabda** [groovy/groovy-eclipse#528]
Hey,

How can I use ASTParser to parse Groovy code using org.eclipse.jdt.groovy.core? I can't seem to find any examples.

Thanks,
Marcin

**Comment by eric-milles** [comment]
I'm not sure I follow what your trying to accomplish.  Could you give a hint on what your larger goals are?

The editor accesses parsed results through working copy extensions.  The compiler creates a parser like this:
this.parser = LanguageSupportFactory.getParser(this, this.options, this.problemReporter, this.options.parseLiteralExpressionsAsConstants, 1);

**Comment by marcingrabda** [comment]
What is the most basic way of parsing Groovy code into Eclipse JDT AST? I already have some code, which loads Java files using ASTParser:
```
ASTParser parser = ASTParser.newParser(JLS8);
parser.setSource(source.toCharArray());
parser.setKind(K_COMPILATION_UNIT);
parser.setCompilerOptions(compilerOptions());
CompilationUnit cu = (CompilationUnit) parser.createAST(null);
```
How can I tell ASTParser to accept Groovy source code?

**Comment by eric-milles** [comment]
If the JDT is patched with the Groovy enhancements (aka org.eclipse.jdt.core and Feature-org.codehaus.groovy.jdt.patch), you can use the sequence you indicated.

For example, this is the sequence the JDT debugger uses:
      private void createEvaluationSourceFromSource(String source, IType type, int line, boolean createInAStaticMethod, IJavaProject project) throws DebugException {
            ASTParser parser = ASTParser.newParser(AST.JLS4);
            parser.setSource(source.toCharArray());
            Map<String, String> options = getCompilerOptions(project);
            String sourceLevel = project.getOption(JavaCore.COMPILER_SOURCE, true);
            parser.setCompilerOptions(options);
            CompilationUnit unit = (CompilationUnit) parser.createAST(null);


But it's best if you provide a hint that it is a Groovy source being parsed; I think that is ASTParser.setUnitName(String).  Without calling set unit name, we need to do a bit of sleuthing (see org.codehaus.jdt.groovy.integration.internal.MultiplexingCommentRecorderParser):

    public CompilationUnitDeclaration dietParse(ICompilationUnit sourceUnit, CompilationResult compilationResult) {
        if (isGroovyLikeFileName(sourceUnit.getFileName()) || isGroovyLikeSourceUnit(sourceUnit)) {
            if (this.scanner != null) {
                this.scanner.setSource(sourceUnit.getContents());
            }
            return groovyParser.dietParse(sourceUnit, compilationResult);
        }
        return super.dietParse(sourceUnit, compilationResult);
    }

    private static boolean isGroovyLikeSourceUnit(ICompilationUnit sourceUnit) {
        if (sourceUnit.getFileName() == null || !isJavaLikeButNotGroovyLikeFileName(String.valueOf(sourceUnit.getFileName()))) {
            if (GROOVY_SOURCE_DISCRIMINATOR.matcher(new CharArraySequence(sourceUnit.getContents())).find()) {
                Util.log(1, "Identified a Groovy source unit through inspection of its contents: " +
                    String.valueOf(sourceUnit.getContents(), 0, Math.min(250, sourceUnit.getContents().length)));
                return true;
            }
        }
        return false;
    }

**Comment by marcingrabda** [comment]
Thanks for the explanation. This is really helpful. Can you think of any project that's similar to what I am trying to achieve? I am currently facing dependency issues. Maybe instead of bothering you with all my problems, you could point me to an existing project?

**Comment by eric-milles** [comment]
I'm not sure I know what you're trying to do yet, besides produce JDT model data from Groovy source text.  You can view/run just the command-line compiler (aka `org.eclipse.jdt.internal.compiler.batch.Main`) to see parser and compiler support minus all the UI stuff.

**Comment by marcingrabda** [comment]
Ok, sorry for not explaining it well enough earlier.

I have a tool written in Java, using Eclipse JDT parser, which loads Java source code, applies transformations and writes transformed code back. It is used to help with refactoring of legacy code. I'm trying to change it, so that it can be used to transform Groovy code. I was hoping I could add Groovy support by adding groovy-eclipse, so that it could load Groovy files, apply the same transformations, etc... Do you think the idea is correct, or do you see any flaws here?

At this point I have the examples you gave me earlier, but I am struggling to set up the project dependencies, as I think I don't understand them... Do I need a special version of Groovy? What is the minimum set of dependencies needed to run the code you posted above?

**Comment by eric-milles** [comment]
I guess that depends on how you plan to run the code.  To execute the tests, Maven boostraps an Eclipse Target Platform.  That's probably much more than you want because that includes enough support for UI testing.  Have a look at the groovy-eclipse-batch-builder project in the extras.  This project assembles a standalone jar (the batch compiler) that can be run to compile sources and produce class files.  The build.xml shows just what parts of the Eclipse Target Platform are necessary for headless compilation.

You may be able to add just groovy-eclipse-batch as a dependency and call into the parser that way.  You can get a pre-baked jar from bintray: https://bintray.com/groovy/maven/groovy-eclipse-batch

**Comment by marcingrabda** [comment]
Thanks for all your help, although I think this is a bit too heavy for my needs. I'm saving the idea for later... Thanks once again...
