### ISSUE TITLE
I use -Dmaven.test.skip=true in maven compile command, but I get compile error in test files 

### ISSUE THREAD

**Issue by StephenLiuYa** [groovy/groovy-eclipse#533]
Command: /usr/local/apache-maven-3.3.9/bin/mvn -f ./pom.xml clean install -Dmaven.test.skip=true

Error: 

15:56:04 [INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
15:56:04 [INFO] Found location </var/lib/jenkins/.m2/repository/org/codehaus/groovy/groovy-eclipse-batch/2.4.3-01/groovy-eclipse-batch-2.4.3-01.jar> for className <org.eclipse.jdt.internal.compiler.batch.Main>
15:56:04 [INFO] Found location </var/lib/jenkins/.m2/repository/org/projectlombok/lombok/1.16.8/lombok-1.16.8.jar> for className <lombok.launch.Agent>
15:56:04 [INFO] Compiling in a forked process using /var/lib/jenkins/.m2/repository/org/codehaus/groovy/groovy-eclipse-batch/2.4.3-01/groovy-eclipse-batch-2.4.3-01.jar
15:56:05 [INFO] -------------------------------------------------------------
15:56:05 [ERROR] COMPILATION ERROR : 
15:56:05 [INFO] -------------------------------------------------------------
15:56:05 [ERROR] Failure executing groovy-eclipse compiler:
15:56:05 ----------
15:56:05 1. ERROR in /var/lib/jenkins/workspace/htl-order-customer-notification-service/notification-domain/src/test/java/com/XXXl/order/customer/notification/domain/repository/OnlineRoomSelectInfoRepositoryTest.java (at line 4)
15:56:05 	import org.junit.Assert;
15:56:05 	       ^^^^^^^^^
15:56:05 The import org.junit cannot be resolved
15:56:05 ----------
15:56:05 2. ERROR in /var/lib/jenkins/workspace/htl-order-customer-notification-service/notification-domain/src/test/java/com/XXX/order/customer/notification/domain/repository/OnlineRoomSelectInfoRepositoryTest.java (at line 5)
15:56:05 	import org.junit.Ignore;
15:56:05 	       ^^^^^^^^^
15:56:05 The import org.junit cannot be resolved
15:56:05 ----------
15:56:05 3. ERROR in /var/lib/jenkins/workspace/htl-order-customer-notification-service/notification-domain/src/test/java/com/XXX/order/customer/notification/domain/repository/OnlineRoomSelectInfoRepositoryTest.java (at line 6)
15:56:05 	import org.junit.Test;
15:56:05 	       ^^^^^^^^^
15:56:05 The import org.junit cannot be resolved

**Comment by eric-milles** [comment]
Can you try with groovy-eclipse-batch-2.4.14-01?  Can you send link to Maven's definition/specification of "-Dmaven.test.skip=true"?  My impression is that it skips running tests, not compiling them.
