### ISSUE TITLE
plugin build failing

### ISSUE THREAD

**Issue by vbhavsingh** [groovy/groovy-eclipse#540]
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.codehaus.groovy.eclipse.astviews 3.0.0.qualifier
[ERROR]   Missing requirement: org.codehaus.groovy.eclipse.astviews 3.0.0.qualifier requires 'bundle org.eclipse.jdt.core [3.13.0,4.0.0)' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshootingfor help.
[ERROR] Cannot resolve dependencies of MavenProject: org.codehaus.groovy.eclipse:org.codehaus.groovy.eclipse.astviews:3.0.0-SNAPSHOT @ C:\Users\me\Downloads\groovy-eclipse-master\ide\org.codehaus.groovy.eclipse.astviews\pom.xml: See log
 for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by eric-milles** [comment]
What is your command line to run the build?  I think you are missing a profile setting.

**Comment by vbhavsingh** [comment]
i am running "mvn clean build"

**Comment by eric-milles** [comment]
You need to add " -Pe47".  There are more details in the top-level pom.xml.
