### ISSUE TITLE
Cannot add breakpoints in groovy class from jar file 

### ISSUE THREAD

**Issue by moley** [groovy/groovy-eclipse#544]
Hi, 

I have different gradle plugin projects, which are dependend from each other. They are built with gradle and published via gradle maven-publish plugin. If I open the groovy file from jar in my project and want to add a breakpoint to a valid line, this does not work. With IntelliJ it is working for my scenario, so I think it is an eclipse bug and not a bug in maven-publish plugin. 
I have uploaded a small github project to extract this behaviour. 
To reproduce do the following: 

- Download project from https://github.com/moley/eclipseGroovyDebug
- step into subproject groovylib and call `./gradlew publishToMavenLocal`
- a version of the groovylib should be available in `~/.m2/repository/groovylib`
- open subproject groovyapp by "File->Import...->Existing Gradle Project" or call ./gradlew eclipse on this project and open via "File->Import...->Existing projects into workspace"
- Open the dialog "Open Type" and search for "SomeLibClass"
- Try to add breakpoint -> nothing happens

Does not work for version 3.0.0.xx-201803261849-e47 of Eclipse Groovy Development Tools in Oxygen and does not work with Photon either

**Comment by eric-milles** [comment]
Thanks for submitting this issue.  The recreation steps are very helpful.  Greclipse does not register the proper editor extension for the Class File Editor to allow toggling of breakpoints from there.  I'll have a look at what is required.  In the meantime, you should at least be able to set method enter/exit breakpoints.

**Comment by moley** [comment]
You're welcome, thank you for the hint with the enter/exit breakpoints. 
If you have further questions, simply call
Cheers
Markus

**Comment by eric-milles** [comment]
Double-clicking in the left vertical ruler of a class file should work now.  The ruler's context menu items (Disable Breakpoint and Toggle Breakpoint) are not yet hooked up.

**Comment by moley** [comment]
thank you for your fast fix, I will try it when released
