### ISSUE TITLE
Ctrl+X (cut) for a selected string freeze eclipse

### ISSUE THREAD

**Issue by ahoehma** [groovy/groovy-eclipse#547]
It's strange :)

I select a string-concat piece of code (I think it happens also with a normal string) ... then I want cut this code into clipboard. I press ctrl+x ... then eclipse hangs:

![image](https://user-images.githubusercontent.com/548214/38161997-54a4d8ea-34d9-11e8-9472-893ba8e3b490.png)

Here is the ThreadDump:

[groovy_cut_string_eclipse_hangs-threaddump.txt](https://github.com/groovy/groovy-eclipse/files/1865353/groovy_cut_string_eclipse_hangs-threaddump.txt)

**Comment by eric-milles** [comment]
What version of eclipse and greclipse do you have?

**Comment by eric-milles** [comment]
The 3 threads stuck in ASTProvider.getAST are waiting for reconcile to finish; this includes the UI thread where the clipboard action is running.  Reconcile should execute as a background job; I'm not sure if one did not complete successfully or did not run for some reason.  You could  check the Error Log view to see if there is anything helpful in there.
