### ISSUE TITLE
How to exclude script from compile?

### ISSUE THREAD

**Issue by ilofgam** [groovy/groovy-eclipse#553]
Some groovy script is only for runtime excute, other source need compile for test.
So I set exclude in maven-compiler-plugin tag, but it not work.
```
<build>
    ...
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5</version>
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
          <excludes>
                    <exclude>**/rest/*</exclude>
          </excludes>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>2.9.2-01</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>2.4.3-01</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
    ...
</build>
```

**Comment by eric-milles** [comment]
`org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler` is the front-end for `groovy-eclipse-compiler`.  It scans for files to compile like this:
```java
    private File[] recalculateStaleFiles(CompilerConfiguration config) throws CompilerException {
        config.setSourceFiles(null);
        long staleMillis = 0; // Can we do better than using 0?
        Set<String> includes = config.getIncludes();
        if (includes == null || includes.isEmpty()) {
            includes = Collections.singleton("**/*");
        }
        Set<File> staleSources = computeStaleSources(config, new StaleSourceScanner(staleMillis, includes, config.getExcludes()));
        config.setSourceFiles(staleSources);
        return staleSources.toArray(new File[staleSources.size()]);
    }
```

Excludes are being read from `CompilerConfiguration` and passed to `org.codehaus.plexus.compiler.util.scan.StaleSourceScanner` which delegates to `org.codehaus.plexus.util.DirectoryScanner`.

**Comment by eric-milles** [comment]
A quick debug session reveals the excludes elements are making it down to the compiler adapter (aka `GroovyEclipseCompiler`).

**Comment by eric-milles** [comment]
Looks like this is the culprit: https://issues.apache.org/jira/browse/MCOMPILER-216

Could you please work with the maven-compiler-plugin project to have this issue resolved?  The code change is pretty small.  In https://github.com/apache/maven-compiler-plugin/blob/master/src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java#L586 the config is created.  Simply call `compilerConfiguration.setIncludes(includes)`, `compilerConfiguration.setExcludes(excludes)` and so on for test includes/excludes.
