### ISSUE TITLE
Default text color is black and no option exists to change the font color

### ISSUE THREAD

**Issue by rustyscottweber** [groovy/groovy-eclipse#554]
![image](https://user-images.githubusercontent.com/4672283/38588411-e4e75b88-3ce2-11e8-97a3-3dea2c8416b7.png)

Eclipse IDE for Java Developers
Version: Oxygen.3 Release (4.7.3)
Build id: 20180308-1800
OS: Windows 10, v.10.0, x86_64 / win32

While using the dark theme in eclipse, there seems to be a problem with dark text on a dark background.
Looking at all of the options available to me in any of the options, there doesn't seem to be any options to change the color of the text, only the syntax highlighting. This is including the options inherited from java as opening a java file appears like it should.

An effective option is needed or the inheritance from Java needs to be corrected.

**Comment by eric-milles** [comment]
If you want to change the syntax colors for the Groovy Editor, you can do that at _Window > Preferences > Groovy > Editor_ and also _Window > Preferences > Java > Editor > Syntax Coloring_.
