### ISSUE TITLE
Groovy Eclipse plugin contributes to "Invalid registry object" at Eclipe start

### ISSUE THREAD

**Issue by davidmichaelkarr** [groovy/groovy-eclipse#555]
For a long time now, I've been annoyed by the symptoms described in this Eclipse bug report that I created: https://bugs.eclipse.org/bugs/show_bug.cgi?id=528462 .

Today I realized that if I don't have the Groovy Eclipse plugin installed, this doesn't happen.  I've now tried going back and forth, verifying that it only happens when I have that plugin installed. I verified this with the same version of Eclipse, but on two different computers (ok, a Windows laptop and a Linux VM running on that laptop).

I also have a bunch of other plugins installed, so this could very well be a subtle plugin interaction problem, but it's at least related to this.

**Comment by eric-milles** [comment]
This sounds like a familiar old issue that cropped up with Neon and went away quietly.  Do you have multiple Groovy Compiler versions installed?  Are you running with the latest Eclipse Oxygen and Groovy-Eclipse versions?

**Comment by eric-milles** [comment]
You can look to #317 for reference.  There were some fixes realized for Oxygen.

**Comment by davidmichaelkarr** [comment]
I do have multiple compiler versions installed.  I'm using the latest
Oxygen and latest Groovy eclipse version.

I looked through the history of that issue, but I'm unsure what the
workaround is.  Is the point to remove all but the newest compiler version?

**Comment by davidmichaelkarr** [comment]
4.7.3a and 3.0.0.xx-201804112146-e47 , but reinstalling with only the 2.4
compiler has fixed this problem. I no longer get the registry error on
start.

**Comment by xenonrider** [comment]
How do you reinstall only the 2.4 compiler?
