### ISSUE TITLE
Groovy Eclipse 2.9.2.xx incompatible to Oxygen 3a

### ISSUE THREAD

**Issue by JanMosigItemis** [groovy/groovy-eclipse#566]
Hi there,

the other day I noticed that there might be some incompatibility between the latest official Groovy for Eclipse release and the latest Eclipse 4.7.3a (Oxygen 3a)

**Versions and Environment**  
* Groovy for Eclipse Feature 2.9.2.xx-201801041714-e47-RELEASE
* Eclipse for Java Developers Oxygen.3a Release (4.7.3a) Build id: 20180405-1200
* Java 1.8.0_172
* Microsoft Windows [Version 10.0.16299.371]

**Observed Behavior**  
* When starting Eclipse with one Java class opened, the error log contains two new entries (see also attached logs):
** `Error in JDT Core during reconcile`
** `Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ui".`
* When I open a *.java file in any project (Groovy nature or not) I get the following error:
** `An internal error occurred during: "Requesting Java AST from selection".`
** This error keeps appearing whenever I interact with the opened file.

**How to reproduce**  
* Download "vanilla" Oxygen 3a for Java Developers from http://www.eclipse.org/downloads/eclipse-packages
* Start it and install Groovy Eclipse Feature from http://dist.springsource.org/release/GRECLIPSE/e4.7
* Restart and import https://github.com/JanMosigItemis/testproject
* Open the class `de.itemis.mosig.testproject.HelloWorld`

**Why is that bad?**  
The errors keep coming which effectively renders my IDE unusable.

**Expected Behavior**  
Well, no errors at all.

**Further Details**  
This does not happen when using Groovy Eclipse snapshot build as of 2018-16-04.

**Logs**  
[problem_invoking_jdt.txt](https://github.com/groovy/groovy-eclipse/files/1923529/problem_invoking_jdt.txt)
[Error in JDT Core during reconcile.txt](https://github.com/groovy/groovy-eclipse/files/1923540/Error.in.JDT.Core.during.reconcile.txt)
[error_requesting_ast.txt](https://github.com/groovy/groovy-eclipse/files/1923544/error_requesting_ast.txt)

**Comment by eric-milles** [comment]
Greclipse 3.0 supports Eclipse 4.7.3a; more details posted in #556.
