### ISSUE TITLE
Add support for Groovy in Expressions view

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#569]

**Comment by mojo2012** [comment]
How come such a basic feature has not yet implemented? Will it ever be release. Because for me (and all developers I know) this is an absolute showstopper!

**Comment by mojo2012** [comment]
Maybe it would be easiert to just create a new view? I always wanted to have something like in intellij - a combined variables + expression view (with autocomplete).
Manually created expressions are just appended to the list of variables.
Currently my debugging workflow (in java) is spread out to variables, expressions and debug/display view - and I always kinda hated that.

**Comment by mojo2012** [comment]
I added a bug request: https://bugs.eclipse.org/bugs/show_bug.cgi?id=552561

**Comment by eric-milles** [comment]
@mojo2012 I gather from your posts that you are having trouble using Eclipse to debug Groovy code.  This is fully supported and is used daily by developers in my organization.  If there is a specific debugging problem you are having, could you open a new issue ticket with a description of the problem?

**Comment by eric-milles** [comment]
![image](https://github.com/groovy/groovy-eclipse/assets/18193802/0326fd9a-f11c-4af7-bbd7-1de4a01c7e37)
