### ISSUE TITLE
Support for groovy < 2.4 in Groovy Eclipse 3.0+?

### ISSUE THREAD

**Issue by doktorjw** [groovy/groovy-eclipse#580]
Are there plans for supporting older versions of groovy, prior to v2.4 in the latest Groovy Eclipse?

We have code bases that probably should be updated, that are running with Groovy 1.8 ... I couldn't find mention in any release notes about removed support for < 2.4.

Thx

**Comment by eric-milles** [comment]
2.9.2 release and 2.9.3 snapshots support Groovy 1.8 through 2.4 and Eclipse 3.7 (Indigo) through 4.7.2 (Oxygen).  Greclipse 3.0 is a chance to move to Java 8 and limit the amount of patching for Groovy and Eclipse.
