### ISSUE TITLE
Getting code=10053 error while installing groovy-eclipse on Eclipse IDE (Oxygen) for Eclipse Committers

### ISSUE THREAD

**Issue by ybayk** [groovy/groovy-eclipse#592]
After following the steps in https://github.com/groovy/groovy-eclipse/blob/master/docs/Getting-Started-with-Groovy-Eclipse-Source-Code.md getting an error:
```
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1527811536694
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1527811536694 requires 'org.codehaus.groovy.alltests.feature.feature.group 0.0.0' but it could not be found
```
Issue is reproducible on both mac and pc. Used anonymous github url for the groovy-eclipse source (https://github.com/groovy/groovy-eclipse.git)

**Comment by eric-milles** [comment]
I'm most the way through editing the setup file.  Just trying to button up a few more items before committing.

**Comment by eric-milles** [comment]
The setup should execute to completion now.  All imported projects should build with no errors and you should be able to launch Eclipse Application or JUnit Plug-in Tests from Run As or Debug As.

I could not figure out how to exclude `org.mockito` plug-in from the Target Platform, so there will be a framework error that will trip up `ErrorLogTest` unless you edit the target platform definition first.
