### ISSUE TITLE
Way to disable grapes while building workspace, not just when running code.

### ISSUE THREAD

**Issue by benjamincampbell** [groovy/groovy-eclipse#609]
I've been trying to figure out if there is a way so that, when Eclipse is building the workspace (or, say, editing the grapes in a file), it isn't looking through all of the grapes. When even a few projects are open for me, Eclipse will often freeze up for anywhere from 2-5 minutes (depending on how many projects are open) while it inspects the grapes.

I've seen this bit here in the Groovy code, [where you can use System Variables to disable auto-downloading, or disable grapes all together.](https://github.com/apache/groovy/blob/6a7c42e8c7b2edb2ab957abe0f670195e0ca2e5c/src/main/groovy/groovy/grape/Grape.java#L36) However, this doesn't seem to work when I'm developing in Eclipse. (I tried this by adding the environment variable `JAVA_OPTS` to have a value of `-Dgroovy.grape.enable=false`, and when I check this in Groovy Console, the value is correctly set so that grapes *should* be disabled)

I'm fairly certain this is what's happening, at least, since if I edit any Grapes in a file, Eclipse suddenly starts lagging pretty hard and begins re-building the workspace. 

If I am incorrect, asking the wrong question, or am otherwise off base, please just let me know, but this seemed the best place to ask about it. Thank you for your time!

**Comment by eric-milles** [comment]
Would you be able to share your project structure?  I'm curious if you have scripts (with grapes) within Eclipse project source folders.  And if so, do you have script filters enabled to prevent compilation.

**Comment by benjamincampbell** [comment]
Sure; our projects look like this:

```
├──src
|  ├──Project1
|  |  ├──SubProject1
|  |  |  ├──SourceMainClass.groovy (Includes a Grape/Grab)
|  |  |  ├──MiscFiles
|  |  ├──SubProject2
|  |  |  ├──SourceMainClass.groovy (Includes a Grape/Grab)
|  |  |  ├──MiscFiles
|  |  ├──SubProject3
|  |  |  ├──SourceMainClass.groovy (Includes a Grape/Grab)
|  |  |  ├──MiscFiles
```

Some of these classes will have a Grapes block at the top looking something like this (I've replaced the specific names of packages and folders):

```
@Grapes([
	@GrabResolver(name='package', root='file://localRepo/Repository'),
	@Grab(group='group', module='module', version='[1.6.0,1.7.0)'),
	@GrabExclude('org.codehaus.groovy:groovy-all')
])
```

This is above the main class, and most of the time this file is a majority of the code used for that subproject. So yes, there are several scripts with grapes. I assume it runs the grabs when building the workspace, or when saving any changes to the file, and that's the reason for the freezing. Of course, I'm not sure if this is the case, and please correct me if I'm wrong.

For kicks and giggles, I added `src/*` to the script filters and enabled them (this should match every file in the project), but I don't believe this is working; If I edit any of the .groovy files containing grapes and save, it still freezes and locks up for about 20-30 seconds. Any files *not* containing grapes are fine to edit, no freezing at all.

**Comment by eric-milles** [comment]
With the script filter enabled, does the file icon change to show a small circle-slash in the lower left corner?

BTW, I can discuss on [Slack](https://groovy-community.slack.com/) if you want quicker back-and-forth.

**Comment by eric-milles** [comment]
When a file is opened for edit or edited, a process called "reconcile" brings the editor buffer back in sync with the JDT model/index.  During reconcile, the Grapes must be resolved so that type references can be properly resolved.  There are a few stages of reconcile and it is possible that the Grapes are processed more than necessary.  However, once retrieved the artifacts should come from cache, unless you have disabled caching through configuration.

If you want to edit the source quickly with no grapes processing whatsoever, you can open the source in the plain text editor.  I know this sounds lame, but if you have a small change to make and the delay is large, this workaround can be performed immediately.

**Comment by benjamincampbell** [comment]
So I did actually notice that the file icon changes from what appears to be a Groovy icon to a Groovy Script icon; there's a black S in the upper left corner. No crossed-out-circle or anything like that.

Also, thank you for shedding some light on the underlying processes going on when files are being edited. I wasn't really sure what was, nor how best to research that.

So it seems to me that it's likely it's behaving as intended? Since it's just grabbing a `.jar` file, if that library itself includes grabs, would that also increase the time required for this step? I figure by the time my project is grabbing this library, it's already in `.jar` form, and thus its grapes have been called long ago when the `.jar` was created.

Again, thank you for your timely responses!

**Comment by eric-milles** [comment]
Thanks for the update.  If you are seeing a black S on the icon, you are using quite an old version.  I strongly recommend updating to the latest release (2.9.2) or snapshots (3.0.0).

You can go to the Console view and open a new Groovy Event Console to get more details.

Re time to grab; when I open a script that has 1 dependency, it takes roughly 30 seconds to open in the editor.  However, after the first time, it takes less than a second to re-open.

**Comment by benjamincampbell** [comment]
Hey, sorry for the delay,

I just checked, we actually are using version 2.9.2 of the plugin. Specifically: `Version: 2.9.2.xx-201801041714-e47-RELEASE`, so I suppose I'm probably doing something wrong in regards to the script filtering.

Also, I checked the groovy event console, and it looks like there are a couple (5 actually) of unresolved dependencies from the one @Grab that we have in this particular example I've been playing with, so it's probably spending time looking for those before timing out?

Here's the console with some names replaced:

```
Compiler : 08:29:20 D:\[folders]\src\Project\SubProject\MainClass.groovy: 13: 
Error grabbing Grapes -- [unresolved dependency: CompanyName#Library1;[0.1.0, 0.2.0): not found, 
                          unresolved dependency: CompanyName#Library2;[0.2.0, 0.3.0): not found, 
                          unresolved dependency: CompanyName#Library3;[0.2.0, 0.3.0): not found, 
                          unresolved dependency: CompanyName#Library4;[1.2.0, 1.3.0): not found, 
                          unresolved dependency: CompanyName#Library5;[0.1.0, 0.2.0): not found]
@ line 13, column 6.
 @Grab(group='group', module='module', version="[1.6.0,1.7.0)"),
  ^
AST Transforms : 08:29:20 Global transform groovy.grape.GrabAnnotationTransformation on D:\[folders]\src\Project\SubProject\MainClass.groovy = 22842ms
Compiler : 08:29:21 Event complete: 24111ms: Build structure: MainClass.groovy : main
```

It actually shows this exact error twice (with all of the same unresolved dependencies); the first takes roughly 22-24 seconds as you can see, and the second time takes roughly 12 seconds. So I suppose it just attempts to check twice?

Either way this seems to be a specific issue to how we have things set up, and not an issue with the plugin at this point.

**Comment by benjamincampbell** [comment]
Lo and behold, once I figured out how to make those correctly resolve, the time shoots way down to only a few seconds. Much better.

Thank you for your help, Eric!
