### ISSUE TITLE
DSLD: Context information popup highlights wrong parameter name in case of a trailing closure

### ISSUE THREAD

**Issue by ybayk** [groovy/groovy-eclipse#613]
Consider the following DSLD:
`method name: "foo", type: "void", noParens: true, namedParams: [bar: String], params: [block: 'groovy.lang.Closure']`

If we select the foo method from the auto-complete menu, 'bar' is initially selected in the editor as expected, but the context popup highlights the 'block' in bold:

![image](https://user-images.githubusercontent.com/1779404/41870857-19263d5e-7872-11e8-9b55-8501fce34c7a.png)

After hitting tab, the 'block' gets selected, but 'bar' gets highlighted:

![image](https://user-images.githubusercontent.com/1779404/41870873-2219f5c2-7872-11e8-8d19-88f38f159249.png)

The context popup is rendered deep inside Eclipse/Java logic which is not aware of Groovy nature of a trailing closure parameter.
I would propose to "fix" the order of parameters just in the context popup, so at least switching and highlighting would work consistently with the editor, like this:

![image](https://user-images.githubusercontent.com/1779404/41871816-e528444a-7874-11e8-9a9c-754d635667d4.png)

**Comment by ybayk** [comment]
PR is coming along with fixes for https://github.com/groovy/groovy-eclipse/issues/603

**Comment by eric-milles** [comment]
In general, no use of named parameters has highlighting that matches the context information.  Please be sure to test non-DSLD cases where Map is first method parameter.

**Comment by eric-milles** [comment]
If you plan on developing PR immediately, issue serves no purpose.  All discussion and review can happen as part of PR.

**Comment by ybayk** [comment]
I just followed the protocol: https://github.com/groovy/groovy-eclipse/blob/master/docs/Getting-Started-with-Groovy-Eclipse-Source-Code.md#track-work

**Comment by ybayk** [comment]
yes, will make sure non-DSLD cases are not affected.

**Comment by ybayk** [comment]
@eric-milles The problem seems to be more wide. When mixing named and regular params, DSLD signatures are generated with named params in front, but core Java signatures are other way around (regular params first).  
I wonder if this is a bug or intentional behavior:
https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.codeassist.completion/src/org/codehaus/groovy/eclipse/codeassist/completions/GroovyJavaMethodCompletionProposal.java#L503-L505

**Comment by ybayk** [comment]
The above snippet contradicts the following code, where it generates a method signature with regular params first, following by named params:

https://github.com/groovy/groovy-eclipse/blob/ebd954983e8fad65fa88a02a0b4bd4ea986af3be/ide/org.codehaus.groovy.eclipse.codeassist.completion/src/org/codehaus/groovy/eclipse/codeassist/completions/NamedArgsMethodNode.java#L44-L46

**Comment by eric-milles** [comment]
Re issue vs. pull request: I prefer an issue followed by discussion before any coding takes place.  If you submit a comment immediately stating you have a PR forthcoming, I assume you are not receptive to discussion of direction and options.  So why not just a PR.  That said, let me restate that I prefer discussion here or on slack before moving to coding.

As I mentioned above, yes the issue of context hover of method call parameters with named parameters is wider than just DSLD.  When you have `def x(Map np, int one, def two)`, if using named arguments, you typically do not pass the map and you may have the named arguments interleaved with the positional ones: `x(one, named:three, two, named2:four)`.

The Map being a faux-positional param and the interleaving makes deciding which parameter to highlight in the hover non-trivial.

As for the DSL NamedArgsMethodNode, I don't know why the named params are displayed first.  It may have something to do with recognizing that `Closure` is the last parameter and so may be completed outside the parentheses.

**Comment by ybayk** [comment]
Sorry just meant that I started work on a PR to avoid other contributors jump on an the issue.
After I got more familiar with the code, I tend to agree you. Named params come first because it was easy to deal with a potential trailing closure which is handled as a special case. 

What we currently have is a disagreement in parameter order between NamedArgsMethodNode and GroovyJavaMethodCompletionProposal
Former: 1) positional 2) trailing closure 3) named
Latter: 1) named, 2) positional 3) trailing closure

I believe either is actually bad, and the ideal order should be:
1) positional (excluding trailing closure), 2) named, 3) trailing closure

What I propose to fix:
1) In NamedArgsMethodNode: Change the logic of concatParams(), so that the trailing closure (if present) is appended at the end of the parameter list

2) In GroovyJavaMethodCompletionProposal: Move positional parameters to the front, but keep the trailing closure at the end 

Yes, the changes are not trivial, and I now think this work should be separate from #603

@eric-milles, Does it all make sense ?

**Comment by eric-milles** [comment]
You can assign the issue to yourself.  If that option does not sow for you, I can assign it.

If you try changing just `GroovyJavaMethodCompletionProposal` to your proposed order, do any of the tests fail (besides ones that perform the proposal replacement)?  I'm not sure I would suggest separating the trailing closure from the positional params.  It would require that you check the type of the last param for every proposal.  And I don't think NamedArgsMethodNode needs to be altered for content assist to do what your looking for.

**Comment by ybayk** [comment]
I don't have write access to the repository, so I can't assign it to myself.

If NamedArgsMethodNode is not touched, another place where the signature can be altered is here:
https://github.com/groovy/groovy-eclipse/blob/bbb89420b7f47285310772adbf1c0ec539abcdff/ide/org.codehaus.groovy.eclipse.codeassist.completion/src/org/codehaus/groovy/eclipse/codeassist/ProposalUtils.java#L163-L167

Are you suggesting to keep named parameters in front?

**Comment by eric-milles** [comment]
Just wondering what the minimal change would be.  And if you could run an experiment or two to see if an improvement could be made with just one participant altered.  Not saying that's the end state, but wanting to see if we can get a look at something quickly.

Can you try a couple of your proposed changes and see what you see in terms of trade-offs?

**Comment by eric-milles** [comment]
Also, can you find a good test suite to add some tests to illustrate the issue?  Or is it 100% to do with the little context info hover?

I agree with the original post that the proposal replacement text and the context information box are not in agreement.  What I'm thinking about at the same time is if you typed out `foo {...}, bar: xyz` and then brought up the context hover (Ctrl+Space after a comma).  In that case the parameter highlighting would line up.

I'm a tad worried that the named argument support is not very complete and we are going to end up with a lot of use cases to understand.

**Comment by ybayk** [comment]
The issue manifests itself in 2 places:  

1) Context popup issue which messes up parameter selection behavior so I think it is more critical (see images attached in comments above)

2) Proposed method signatures in the autocompletion menu:
![image](https://user-images.githubusercontent.com/1779404/42052649-35b16a4e-7ac4-11e8-9c9b-6695847879a9.png)

So it is visual inconsistency between what you see and what you get:

![image](https://user-images.githubusercontent.com/1779404/42052822-b6b2e21c-7ac4-11e8-9213-fab207d86c33.png)

**Comment by ybayk** [comment]
I will issue PR soon, I think ended up in minimal changes.
Not sure what you mean regarding named parameter label - all named parameters are already present in both popups, but they are indistinguishable from positional ones.
