### ISSUE TITLE
DSLD: noParens=true with a trailing closure should force parentheses

### ISSUE THREAD

**Issue by ybayk** [groovy/groovy-eclipse#614]
Consider the following DSLD:
`method name: "foo", type: "void", noParens: true, namedParams: [bar: String], params: [block: 'groovy.lang.Closure']`

If we select the foo method from the auto-complete menu, parentheses are ignored which leads to a wrong Groovy syntax:
![image](https://user-images.githubusercontent.com/1779404/41872920-368b8024-7878-11e8-98e6-42b88e857adc.png)

Expected completion with noParens=true:
`foo (bar: bar) { it }`

Expected completion with noParens=false:
`foo (bar: bar, { it })`

**Comment by ybayk** [comment]
PR is coming along with https://github.com/groovy/groovy-eclipse/issues/603

**Comment by eric-milles** [comment]
I'm not 100% on command syntax.  Are you getting an error for `foo bar: baz, { it }`?  What about `foo bar: baz { it }` or `def blk ={ it }; foo bar: baz, blk`?

**Comment by ybayk** [comment]
Oops, sorry, my bad. 
`foo bar:bar, {it}` is a legit syntax as long as the comma remains before the trailing closure.

**Comment by ybayk** [comment]
Not a bug.
