### ISSUE TITLE
type groovy.lang.Closure cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by iseehk** [groovy/groovy-eclipse#615]
When I use groovy-eclipse to compile my groovy (joint compilation), it throws captioned error.
It does not copy my .groovy file to taget\package\.grovvy (built with Maven).

therefore I cannot run the Junit on Spock.

**Comment by eric-milles** [comment]
If this is a Maven build, can you share your project (or at least your POM)?  It sounds like you have missed the groovy dependency.

**Comment by iseehk** [comment]
Sure.

`<build>
 <sourceDirectory>${basedir}/src        </sourceDirectory>
   <testSourceDirectory>${basedir}/src</testSourceDirectory>
   <resources>
       <resource>
           <directory>${basedir}/resources</directory>
           <excludes>
               <exclude>**/*.java</exclude>
           </excludes>
       </resource>
       
   </resources>
   <plugins>
       <plugin>
           <artifactId>maven-compiler-plugin</artifactId>
           <configuration>
               <source>1.6</source>
               <target>1.6</target>
               <encoding>${project.build.sourceEncoding}</encoding>
           </configuration>
       </plugin>

       <plugin>
           <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-surefire-plugin</artifactId>
           <configuration>
               <includes>
                   <include>**/*Spec.groovy</include>
                   <include>**/*Spec.java</include>
                   <include>**/*.groovy</include>
               </includes>
               
               <argLine>${ArgLineValue}</argLine>
               <testFailureIgnore>true</testFailureIgnore>
               <forkCount>1</forkCount>
               <reuseForks>true</reuseForks>
           </configuration>
       </plugin>

   </plugins>
/build>

reporting>
   <plugins>
       <plugin>
           <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-surefire-report-plugin</artifactId>
           <version>2.5</version>
       </plugin>
   </plugins>
/reporting>

dependencies>
   <dependency>
       <groupId>org.codehaus.groovy</groupId>
       <artifactId>groovy-all</artifactId>
       <version>2.4.13</version>
       <scope>test</scope>
   </dependency>

   <dependency> 
       <groupId>net.bytebuddy</groupId>
       <artifactId>byte-buddy</artifactId>
       <version>1.6.5</version>
       <scope>test</scope>
   </dependency>


   
   <dependency>
       <groupId>cglib</groupId>
       <artifactId>cglib-nodep</artifactId>
       <version>3.1</version>
       <scope>test</scope>
   </dependency>


   
   <dependency>
       <groupId>org.objenesis</groupId>
       <artifactId>objenesis</artifactId>
       <version>2.5.1</version>
       <scope>test</scope>
   </dependency>
   <dependency>
       <groupId>org.spockframework</groupId>
       <artifactId>spock-core</artifactId>
       <version>1.1-groovy-2.4</version>
   </dependency>
   <dependency>
       <groupId>commons-logging</groupId>
       <artifactId>commons-logging</artifactId>
       <version>1.2</version>
   </dependency>

   <dependency>
       <groupId>org.codehaus.gmaven.runtime</groupId>
       <artifactId>gmaven-runtime-2.0</artifactId>
       <version>1.5</version>
   </dependency>

/dependencies>
profiles>
   <profile>
       <id>emma</id>
       <properties>
           <backgroundStyle>3</backgroundStyle>
       </properties>
       <build>
           <resources>
               <resource>
                   <directory>${basedir}/../ACON_PC_SHARED/resources</directory>
                   <includes>
                       <include>client.cst.xml</include>
                       <include>_aconShared.properties</include>
                   </includes>
                   <filtering>true</filtering>
               </resource>
           </resources>
           <plugins>

               <plugin>
                   <groupId>org.apache.maven.plugins</groupId>
                   <artifactId>maven-surefire-plugin</artifactId>
                   <configuration>

                       <skipTests>${skip.pc.module.tests}</skipTests>
                   </configuration>
               </plugin>

               
               <plugin>
                   <groupId>org.codehaus.gmavenplus</groupId>
                   <artifactId>gmavenplus-plugin</artifactId>
                   <version>1.5</version>
                   <executions>
                       <execution>
                           <goals>
                               <goal>compile</goal>
                               <goal>testCompile</goal>
                           </goals>
                       </execution>
                   </executions>

                   <configuration>
                       <sources>
                           <source>
                               <directory>${basedir}/src/groovy</directory>
                               <includes>
                                   <include>**/*.groovy</include>
                               </includes>
                           </source>
                       </sources>
                       <testSources>
                           <testSource>
                               <directory>${basedir}/src/groovy</directory>
                               <includes>
                                   <include>**/*.groovy</include>
                               </includes>
                           </testSource>
                       </testSources>

                   </configuration>

               </plugin>
               


               <plugin>
                   <groupId>                        org.codehaus.groovy.maven                    </groupId>
                   <artifactId>gmaven-plugin</artifactId>
                   <version>1.0-rc-3</version>
                   <extensions>true</extensions>
                   <executions>
                       <execution>
                           <goals><goal>testCompile</goal></goals>
                           <configuration>
                               <sources>
                                   <fileset>
                                       <directory>
                                           ${pom.basedir}/src/java
                                       </directory>
                                       <include>**/*.groovy</include>

                                   </fileset>
                               </sources>

                           </configuration>
                       </execution>


                   </executions>

               </plugin>

               
               
                   
                   
               
               

           </plugins>
        </build>`

**Comment by eric-milles** [comment]
You have the `groovy-all` dependency as scope:test.  That is probably your issue.  Also, it appears you are using GMavenPlus.  Please open a support ticket with that project if you continue to have issues building with it.

**Comment by iseehk** [comment]
Sorry for giving you a GMavenPlus. I should give you the pom.xml which groovy-eclipse-compiler.

Error is 
`


`[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] C:\trunkNew\MODULE_TEST\package\ABCSpockTestSpec.groovy:[1,-1] 1. ERROR in C:\trunkNew\MODULE_TEST\package\ABCSpockTestSpec.groovy (at line 1)
	/*
	^
The type groovy.lang.GroovyObject cannot be resolved. It is indirectly referenced from required .class files
----------

[ERROR] C:\trunkNew\MODULE_TEST\package\ABCSpockTestSpec.groovy:[1,-1] 2. ERROR in C:\trunkNew\MODULE_TEST\package\ABCSpockTestSpec.groovy (at line 1)
	/*
	^
The type groovy.lang.MetaClass cannot be resolved. It is indirectly referenced from required .class files
----------

[ERROR] Found 3 errors and 0 warnings.
[INFO] 3 errors 
`


My project structure is like this (my company decision, i cannot control :( ).

Module_SERVER_SIDE
   src // the implementation class here 
Module_SERVER_SIDE_TEST  (extends PARENT_MODULE_TEST)
   java\package\package\*Test.java  // (put the existing java test source code)
   groovy\package\package\*Test.java  // (put the new groovy source code)

I am using java 1.6, Maven 3.25, groovy compiler 2.4
Thank you

Here is the corresponding pom.xml

`	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<!--<excludes> -->
					<!--<exclude>*/.java</exclude> -->
					<!--</excludes> -->
					<compilerId>groovy-eclipse-compiler</compilerId>
					<source>1.6</source>
					<target>1.6</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
				<dependencies>
				<dependency>
                    <groupId>org.codehaus.groovy</groupId>
                    <artifactId>groovy-eclipse-compiler</artifactId>
                    <version>2.8.0-01</version>
				</dependency>
				<dependency>
                    <groupId>org.codehaus.groovy</groupId>
                    <artifactId>groovy-eclipse-batch</artifactId>
                    <version>2.1.8-01</version>
				</dependency>
				</dependencies>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<includes>
						<include>**/svc/entity/**</include>
						<include>**/svc/task/**</include>
						<include>**/svc/util/**</include>
						<include>**/svc/app/InvoiceFslAccrualFunctionalTest.class</include>
						<include>**/*Spec.java</include>
						<include>**/svc/task/*Spec.groovy</include>
						<include>**/svc/task/*Spec.java</include>
						<include>**/svc/task/*.groovy</include>
					</includes>
					<!-- <excludes> <excludes>**/somepackage/**</excludes> </excludes> -->
					<argLine>${ArgLineValue}</argLine>
					<testFailureIgnore>true</testFailureIgnore>
					<forkCount>1</forkCount>
					<reuseForks>true</reuseForks>
				</configuration>
			</plugin>



			<!-- Build Helper: will add Groovy sources to path -->
			<!--<plugin> -->
			<!--<groupId>org.codehaus.mojo</groupId> -->
			<!--<artifactId>build-helper-maven-plugin</artifactId> -->
			<!--<version>1.12</version> -->
			<!--<executions> -->
			<!--<execution> -->
			<!--<id>add-source</id> -->
			<!--<phase>generate-sources</phase> -->
			<!--<goals> -->
			<!--<goal>add-source</goal> -->
			<!--</goals> -->
			<!--<configuration> -->
			<!--<sources> -->
			<!--<source>${basedir}/src/java</source> -->
			<!--<source>${basedir}/src/groovy</source> -->
			<!--</sources> -->
			<!--</configuration> -->
			<!--</execution> -->
			<!--<execution> -->
			<!--<id>add-test-source</id> -->
			<!--<phase>generate-sources</phase> -->
			<!--<goals> -->
			<!--<goal>add-test-source</goal> -->
			<!--</goals> -->
			<!--<configuration> -->
			<!--<sources> -->
			<!--<source>${basedir}/src/groovy</source> -->
			<!--<source>${basedir}/src/java</source> -->
			<!--</sources> -->
			<!--</configuration> -->
			<!--</execution> -->
			<!--</executions> -->
			<!--</plugin> -->

		</plugins>
	</build>


		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			<version>2.4.13</version>
			<scope>test</scope>
		</dependency>

		<dependency> <!-- enables mocking of classes (in addition to interfaces) -->
			<groupId>net.bytebuddy</groupId>
			<artifactId>byte-buddy</artifactId>
			<version>1.6.5</version>
			<scope>test</scope>
		</dependency>


		<!-- Enables mocking of classes (in addition to interfaces) -->
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib-nodep</artifactId>
			<version>3.1</version>
			<scope>test</scope>
		</dependency>


		<!-- enables mocking of classes without default constructor (together with 
			CGLIB) -->
		<dependency>
			<groupId>org.objenesis</groupId>
			<artifactId>objenesis</artifactId>
			<version>2.5.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.spockframework</groupId>
			<artifactId>spock-core</artifactId>
			<!-- <version>1.1-groovy-2.4</version> -->
			<version>0.7-groovy-2.0</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>
		<!-- <dependency> -->
		<!-- <groupId>org.spockframework</groupId> -->
		<!-- <artifactId>spock-core</artifactId> -->
		<!-- <version>RELEASE</version> -->
		<!-- </dependency> -->
		<!-- start experiment by Glen 2018Mar05 Spock with Java -->

		<dependency>
			<groupId>org.codehaus.gmaven.runtime</groupId>
			<artifactId>gmaven-runtime-2.0</artifactId>
			<version>1.5</version>
		</dependency>

	</dependencies>
	<profiles>
		<profile>
			<id>emma</id>
			<properties>
				<backgroundStyle>3</backgroundStyle>
			</properties>
			<build>
					<!-- START experiment by DW 20120402 -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<configuration>

							<skipTests>${skip.pc.module.tests}</skipTests>
						</configuration>
					</plugin>
					<!-- END experiment by DW 20120402 -->

					<!-- start experiment by Glen 2018Mar05 Spock with Java -->

					<plugin>
						<groupId>org.codehaus.gmavenplus</groupId>
						<artifactId>gmavenplus-plugin</artifactId>
						<version>1.5</version>
						<executions>
							<execution>
								<goals>
									<goal>generateStubs</goal>
									<goal>compile</goal>
									<goal>testGenerateStubs</goal>
									<goal>testCompile</goal>
								</goals>
							</execution>
						</executions>

						<configuration>
							<sources>
								<source>
									<directory>${basedir}/src</directory>
									<includes>
										<include>**/*.groovy</include>
										<include>**/svc/task/*Spec.groovy</include>
										<include>**/svc/task/*Spec.java</include>
										<include>**/svc/task/*.groovy</include>
									</includes>
								</source>
							</sources>
							<testSources>
								<testSource>
									<directory>${basedir}/src</directory>
									<includes>
										<include>**/*.groovy</include>
									</includes>
								</testSource>
							</testSources>

						</configuration>

					</plugin>

					<plugin>
						<groupId>org.codehaus.gmaven</groupId>
						<artifactId>gmaven-plugin</artifactId>
						<version>1.5</version>
						<executions>
							<execution>
								<configuration>
									<providerSelection>2.0</providerSelection>
								</configuration>
								<goals>
									<goal>generateStubs</goal>
									<goal>compile</goal>
									<goal>generateTestStubs</goal>
									<goal>testCompile</goal>
									<goal>addSources</goal>
									<goal>addTestSources</goal>
									<goal>compileTests</goal>

								</goals>
							</execution>
						</executions>
					</plugin>


					<!-- start experiment by Glen 2018Mar05 Spock with Java -->


					<plugin>
						<groupId>                        org.codehaus.groovy.maven                    </groupId>
						<artifactId>gmaven-plugin</artifactId>
						<version>1.0-rc-3</version>
						<extensions>true</extensions>
						<executions>
							<execution>
								<goals>
									<goal>generateStubs</goal>
									<goal>compile</goal>
									<goal>generateTestStubs</goal>
									<goal>testCompile</goal>
								</goals>
								<configuration>
									<sources>
										<fileset>
											<directory>
												${pom.basedir}/src/java
											</directory>
											<include>**/*.groovy</include>
											<include>**/svc/task/*Spec.groovy</include>
											<include>**/svc/task/*Spec.java</include>
											<include>**/svc/task/*.groovy</include>
										</fileset>
									</sources>

								</configuration>
							</execution>


						</executions>
					</plugin>

					<!-- If run following plugin , then it cannot resolve the traditional 
						JUnit, when I put them into src/java and src/groovy separately -->
					<!--<plugin> -->
					<!--<groupId>org.codehaus.gmaven</groupId> -->
					<!--<artifactId>groovy-maven-plugin</artifactId> -->
					<!--<version>RELEASE</version> -->
					<!--<dependencies> -->
					<!--<dependency> -->
					<!--<groupId>org.codehaus.groovy</groupId> -->
					<!--<artifactId>groovy-all</artifactId> -->
					<!--<version>2.4.13</version> -->
					<!--<scope>test</scope> -->
					<!--</dependency> -->

					<!--<dependency> -->
					<!--<groupId>org.codehaus.gmaven.runtime</groupId> -->
					<!--<artifactId>gmaven-runtime-2.0</artifactId> -->
					<!--<version>1.5</version> -->
					<!--</dependency> -->
					<!--<dependency> -->
					<!--<groupId>org.codehaus.groovy</groupId> -->
					<!--<artifactId>groovy</artifactId> -->
					<!--<version>1.8.6</version> -->
					<!--</dependency> -->
					<!--</dependencies> -->
					<!--<configuration> -->
					<!--<debug>true</debug> -->
					<!--<verbose>true</verbose> -->
					<!--<stacktrace>true</stacktrace> -->
					<!--<defaultScriptExtension>.groovy</defaultScriptExtension> -->
					<!--<providerSelection>2.0</providerSelection> -->
					<!--</configuration> -->
					<!--<executions> -->
					<!--<execution> -->
					<!--<goals> -->
					<!--<goal>testCompile</goal> -->
					<!--<goal>compile</goal> -->
					<!--</goals> -->
					<!--</execution> -->
					<!--</executions> -->
					<!--</plugin> -->
					<!-- If run following plugin , then it cannot resolve the traditional 
						JUnit, when I put them into src/java and src/groovy separately -->

				</plugins>
			</build>

**Comment by Sandeep0511** [comment]
Any Resolution @eric-milles. Because I'm facing the same issue.

**Comment by eric-milles** [comment]
@Sandeep0511 Can you please open a new issue ticket with your recreation steps?
