### ISSUE TITLE
Documentation of DSLD not shown with Eclipse Photon

### ISSUE THREAD

**Issue by j3rem1e** [groovy/groovy-eclipse#628]
With Eclipse Photon, when I hover an element in a Groovy Script documented by a DSLD, the documentation is not shown. A generic description of the element is show instead (in a builder, the tooltip shows for example the javadoc for the Closure class).

A workaround is to uncheck the "Combined Hover" in the preference, under "Java > Editor > Hovers"

**Comment by eric-milles** [comment]
Can you share a screenshot of current state and desired state?  Combined Hover is also present on Eclipse Oxygen.  Are you saying there is different output for Oxygen vs Photon?

**Comment by eric-milles** [comment]
Can you take a quick screenshot of what you are normally used to and one for Combined Hover enabled?

**Comment by j3rem1e** [comment]
The tooltip shows this :

![groovy_default](https://user-images.githubusercontent.com/2384547/42948048-f7f46006-8b6e-11e8-9e1c-df43b03ff5f4.png)

And I am expecting this (I can see the documentation when I activate "Groovy Information Hover" with a hot key :

![groovy_expected](https://user-images.githubusercontent.com/2384547/42948047-f7d6d0c2-8b6e-11e8-9505-345798fc2994.png)

This documentation come from this kind of DSLD : 

```
contribute(isFormScript() & enclosingCallName("form") & isThisType()) {

  ...

	method name:'style', noParens:true,
		params: [ css: String ],
		doc:'''
		Feuille de style CSS.
		<p>
		La feuille de style est présente dans la page tant que le formulaire la définissant est visible.
	'''

  ...
}
```

**Comment by eric-milles** [comment]
Thanks.  I'll have a look.

**Comment by eric-milles** [comment]
I am seeing two different states of the Hovers preferences dialog.  In the image below, Groovy Information Hover can be seen as the second item, just below Combined Hover.  In my test eclipse -- and I assume yours as well -- Groovy Information Hover appears at the end of the list.  Combined Hover goes through the other items in the list and returns the first/best, which is the Javadoc Hover in the case of this issue.

I'm not sure how this list gets ordered.

![hovers](https://user-images.githubusercontent.com/18193802/42953443-1275dfec-8b40-11e8-937e-6b0ba664c51f.png)

**Comment by eric-milles** [comment]
You can assign the Groovy Information Hover a modifier key and check it in the list.  Then, holding that key down when hovering over should trigger the groovydoc.

**Comment by j3rem1e** [comment]
Thanks for your help.

The order of the hovers plugins looks like to be drived by a [ConfigurationElementSorter](https://github.com/eclipse/eclipse.platform.text/blob/master/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/ConfigurationElementSorter.java), which use the dependencies of the bundles implementing the hover interface (the Require-Bundle manifest entry). 

If Bundle X depends on Bundle Y, then the hover implemented by X will be before the hover implemented by Y.

However, "org.codehaus.groovy.eclipse.ui" doesn't require "org.eclipse.jdt.ui" but only "org.eclipse.jdt.debug.ui", that's why I assume the order is not consistent. 

[This commit](https://github.com/groovy/groovy-eclipse/commit/7e73bf4a6acd1f2115ec65deaf9080325740ea59#diff-f865dcbca5d938729872652c2eed98ff) has removed the dependencies to jdt.ui. That's maybe why after upgrading the groovy plugin I observed this issue.

I am not an Eclipse developer so I may be wrong, and I apologize for my bad English :-)

**Comment by eric-milles** [comment]
ready to test

**Comment by j3rem1e** [comment]
Thanks.

After upgrading the plugin, "Groovy Inferencing" is now the first item in my installation, and the documentation worked without a modifier key. Tested on Photon & Oxygen.
