### ISSUE TITLE
Position of meminitial and memmax on comand line

### ISSUE THREAD

**Issue by TobiX** [groovy/groovy-eclipse#648]
It seems groovy-eclipse-batch since 2.4.13-02 doesn't like the extra option for meminitial (`-J-Xms`) and memmax (`-J-Xmx`) after the arguments file anymore. You get this error:
```
Failure executing groovy-eclipse compiler:
File -J-Xmx2048m is missing
```

The simplest fix seems to me to move this block of code
https://github.com/groovy/groovy-eclipse/blob/e90dd75c52aae86996cd33e078735ac84dff5bfe/extras/groovy-eclipse-compiler/src/main/java/org/codehaus/groovy/eclipse/compiler/GroovyEclipseCompiler.java#L353-L359
some lines up before the argument file, right?

**Comment by eric-milles** [comment]
Yes, Oxygen and Photon insert the @file arguments inline with the @ arg.  Not sure if/when this changed.

I should be able to patch using your suggestion and deploy `groovy-eclipse-compiler:3.0.0-01` sometime today.
