### ISSUE TITLE
Is the release update site available?

### ISSUE THREAD

**Issue by tomcruise81** [groovy/groovy-eclipse#649]
Trying to access http://dist.springsource.org/release/GRECLIPSE/e4.7/site.xml results in:
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>release/GRECLIPSE/e4.7/site.xml</Key>
<RequestId>3F2D5392EFC8B515</RequestId>
<HostId>
MHgfJtT8e+x5sunjIJhp7/s72nPt7rTEwbtX5gNX66+SaQs/PjkoHmKQJrtcRMpuYeGsqxDnOcE=
</HostId>
</Error>
```

We have a Nexus artifact repository that our agency utilizes that proxies all external repositories, and it's currently unable to proxy this update site (although it's had success in the past).

**Comment by eric-milles** [comment]
I am able to access it:

![update-site](https://user-images.githubusercontent.com/18193802/43267618-0ef2a9a8-90b4-11e8-8d12-5b0db53eacf2.png)

**Comment by tomcruise81** [comment]
Thanks for checking. Then I'm guess it's our Nexus implementation having trouble proxying it.
