### ISSUE TITLE
Unable to resolve Groovy classes from other source folder of the same project

### ISSUE THREAD

**Issue by christian-ertl** [groovy/groovy-eclipse#652]
In recent snapshots, Groovy classes cannot be resolved from Groovy classes/scripts in other source folders (e.g. in tests). The same Groovy classes can be used in Java classes in that source folder.

The used Eclipse version is the latest Eclipse Oxygen release.

**Comment by eric-milles** [comment]
Can you provide a sample project that demonstrates this issue?  We have multiple tests for this and are not aware of inability to use classes from another source folder or another project.

**Comment by christian-ertl** [comment]
I will try to provide a sample with a clean IDE.
(Btw. I wanted to reproduce it with Photon, but the latest Groovy-Eclipse release is not compatible with the JEE distribution.)
