### ISSUE TITLE
Photon greclipse 4.8 XmlParser missing in indy jar

### ISSUE THREAD

**Issue by BrokenRolex** [groovy/groovy-eclipse#665]
Just downloaded photon and installed http://dist.springsource.org/snapshot/GRECLIPSE/e4.8 but the groovy XmlParser (and XmlSlurper) seems to be missing. Did I miss some part of the install?

edit...

The difference between this install in my Oxygen install is the groovy jar.

Oxygen = groovy-all-2.4.15.jar (installed with release/GRECLIPSE/e4.7)
Photon = groovy-2.5.1-indy.jar

The photon version does not have the *all* jar. Is this by design? Is there a way to get the missing classes from the *all* version?

**Comment by eric-milles** [comment]
See #656 for options.  You may also continue to use the Groovy 2.4 compiler which includes the groovy-all jar.

**Comment by BrokenRolex** [comment]
This is what I just did, and It seems to work... so far.

1. Configure my project as a Maven project
2. Add the following dependency to the project pom...

  <dependencies>
  	<dependency>
  		<groupId>org.codehaus.groovy</groupId>
  		<artifactId>groovy-all</artifactId>
  		<version>2.5.1</version>
  		<type>pom</type>
  	        <exclusions>
                     <exclusion>
     		        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy</artifactId>
                    </exclusion>
               </exclusions>
  	</dependency>
  </dependencies>

This adds all the groovy jar modules to project but ecludes groovy-2.5.1.jar because groovy-2.5.1-indy.ar is already there because of the plugin.

I'm not sure where the official list of groovy modules list is. I deduced it by looking at the groovy all pom on maven central. [groovy-all-2.5.1.pom](http://search.maven.org/remotecontent?filepath=org/codehaus/groovy/groovy-all/2.5.1/groovy-all-2.5.1.pom)

Here is the list I found...

- groovy
- groovy-ant
- groovy-cli-commons
- groovy-cli-picocli
- groovy-console
- groovy-datetime
- groovy-docgenerator
- groovy-groovydoc
- groovy-groovysh
- groovy-jmx
- groovy-json
- groovy-jsr223
- groovy-macro
- groovy-nio
- groovy-servlet
- groovy-sql
- groovy-swing
- groovy-templates
- groovy-test
- groovy-test-junit5
- groovy-testng
- groovy-xml

**Comment by eric-milles** [comment]
You need not exclude the groovy jar if you remove the Groovy Libraries container from the project.  The POM is really the official list.  If you start excluding a bunch, I would recommend just selectively including what you need instead.

**Comment by BrokenRolex** [comment]
If i removed the groovy library container I'd then have to add ivy back in the project pom

**Comment by eric-milles** [comment]
Only if you are using `@Grab`.  If you are using Ivy/Maven/Gradle, I would use that for all dependencies so you get a portable project.
