### ISSUE TITLE
Compilation error using static class in annotation

### ISSUE THREAD

**Issue by danielebosetti** [groovy/groovy-eclipse#668]
I have a gradle-based, groovy project which makes use of spring-test.

For the following code, a compilation error is shown in Eclipse, with message (MyConf1 cannot be resolved). But the code is correct, and it is compiled correctly using gradle.

`package pack1`
`import org.springframework.test.context.ContextConfiguration;`
`@ContextConfiguration(classes=[MyConf1])`
`class MyClass1 {`
`    static class MyConf1 { }`
`}`

If I substitute
`@ContextConfiguration(classes=[MyConf1])`
with either
`@ContextConfiguration(classes=[MyClass1.MyConf1])` or
`@ContextConfiguration(classes=[MyConf1.class])` , then compilation is ok.

Could this be fixed so that no code changes are needed to "help" eclipse with the nested type?

**Comment by eric-milles** [comment]
A type annotation is outside the scope of the type (`MyClass1` in this case).  I have filed a bug with Groovy to correct this: [GROOVY-8063](https://issues.apache.org/jira/browse/GROOVY-8063)  Eclipse compiler respects the scope of type annotations; you will need to add a qualifier for correct resolution.
