### ISSUE TITLE
groovy eclipse cannot resolve classes in maven dependencies

### ISSUE THREAD

**Issue by spierepf** [groovy/groovy-eclipse#680]
I am using the latest released version of groovy-eclipse in Photon, with the M2E integration, but my groovy/maven project cannot resolve classes provided by jars listed under Maven Dependencies:

Groovy:class griffon.core.test.TestFor is not an annotation in @griffon.core.test.TestFor
Groovy:unable to resolve class griffon.core.test.GriffonUnitRule
Groovy:unable to resolve class org.awaitility.Awaitility

these classes are provided by griffon-core-test-2.15.0.jar and awaitility-3.1.0.jar both of which are listed under Maven Dependencies.

Also:

    $ mvn clean package

works correctly.

**Comment by eric-milles** [comment]
Can you include a small sample project that can be used to recreate?  I suspect the new "test sources" feature in Photon is to blame.
