### ISSUE TITLE
Inconsistent code assist suggestions for range expression

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#690]
Found while verifying #676.

Ensure auto activation is enabled and type: `(1..2).ea`. Code assist will be shown and will list `each` and `eachWithIndex`. While code assist suggestion list is open, hit Ctrl+Space to cycle through proposals.  Otherwise, close the suggestion list and hit ctrl+space: a new suggestion list is shown, including, for instance, `forEach`.
It seems like that when auto-activation occurs, the range is evaluated as Object, while after you call code assist "manually", it's evaluated as `Iterable`, hence giving additional proposals.

**Comment by eric-milles** [comment]
If you pause before typing the dot, does it change?  When typing quickly, reconcile does not run and so the semantics of the new code is not known.

**Comment by mauromol** [comment]
I tried to type `(1..2)`, wait for 5 seconds, then `.eac`, but I still see the same behaviour (i.e.: only suggestions for `Object`, not for `Iterable`, unless I close the suggestion list and reopen, or cycle through proposal lists).

**Comment by mauromol** [comment]
In any case, I would say that I would prefer to be blocked for a while waiting for the reconciler to produce a consistent suggestion list rather than having an inconsistent suggestion list appear quickly...

**Comment by eric-milles** [comment]
Could you increase the auto-activation delay?  There may be a number that allows the reconciler to finish and give you the proper suggestions.  If we can establish what a working delay is, we can then discuss what a preferred delay would be.

**Comment by mauromol** [comment]
I've risen the auto-activation delay up to 5000 ms (a looong delay), but I still see the same behaviour.
I would guess it's not a timing issue, then...

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
Tested with 3.1.0.xx-201808212342-e47, works as expected! 👍 
Now just seeing what described in #674 ;-)
