### ISSUE TITLE
Groovy 2.5 compiler cannot be excluded from main GDT installation or uninstalled separately

### ISSUE THREAD

**Issue by taikikim** [groovy/groovy-eclipse#692]
Thanks for your response to #681. There you mentioned that the 2.5 compiler is an optional dependency for the GDT plugin, and that it should be possible to uninstall the 2.5 compiler. Unfortunately that seems not to be the case. 

When installing GDT there is no option to uncheck the 2.5 compiler:
![no-groovy25-install-option](https://user-images.githubusercontent.com/25621976/44543696-25569700-a6c5-11e8-9732-8f9a2d7d8f72.PNG)

The above screenshot was taken while installing from the Eclipse Marketplace, but the same occurs when attempting to install from the http://dist.springsource.org/snapshot/GRECLIPSE/e4.8 update site.

Once the GDT is installed, the 2.5 compiler is shown as a subitem of the GDT under "Installed Software". When the 2.5 compiler is selected, the Uninstall button is disabled:
![no-groovy25-uninstall](https://user-images.githubusercontent.com/25621976/44543911-bd548080-a6c5-11e8-8ed8-cf5f9722fd41.PNG)

**Comment by eric-milles** [comment]
I changed the feature.xml so that the lowest Groovy Compiler is the default.  This will allow the workaround to live on.
