### ISSUE TITLE
Anonymous inner class: wrong "override method" result when a space is present

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#695]
Followup to #395 (where the mentioned `I` interface is defined).

Consider the following (watch carefully the whitespace characters!):

![immagine](https://user-images.githubusercontent.com/1742494/44771469-545c8500-ab6b-11e8-9a92-953a411ade78.png)

When you hit Ctrl+Space to add the unimplemented method `mymethod` you get:

![immagine](https://user-images.githubusercontent.com/1742494/44771920-b8337d80-ab6c-11e8-8d36-732a6e71d970.png)

When you have this, instead (please note the missing space after the last-but-one closed bracket):

![immagine](https://user-images.githubusercontent.com/1742494/44771554-97b6f380-ab6b-11e8-95bc-c483616f6d73.png)

Then you get the correct result:

![immagine](https://user-images.githubusercontent.com/1742494/44771959-da2d0000-ab6c-11e8-98cd-faf17e2ca670.png)

Please note, however, that, even in the correct result, I would expect the cursor to be placed inside the implemented method body, not after its closing bracket.

**Comment by eric-milles** [comment]
The transfer of Groovy class members to the JDT model, especially method statements is very sensitive to the source position information.  I needed to subtract 1 from the `bodyEnd` property of a `MethodDeclaration` for the body parsing to start succeeding.  JDT is expecting that the body ends at the offset of the closing brace.  Groovy has an end position for the closing brace or probably more correctly the next newline minus 1.

Your example with an extra space after the closing brace of a method body will need to be corrected for.  The Antlr2 grammar has a bad tendency of sucking in those whitespaces as part of the token.

**Comment by mauromol** [comment]
This use case works well in 3.1.0.xx-201808311121-e47, thank you! 👍
