### ISSUE TITLE
Inconsistent code assist suggestions when invoking method that may accept a class property

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#698]
Consider this Java class:

```java
package test34;

public class A {
	public void foo(String v) {
	}
}
```

and this Groovy class:

```groovy
package test34

class Test34 {

	String myprop
	
	void doSomething() {
		def a = new A();
		a.foo(|)
	}
}
```

Invoke code assist at "|": `myprop` is not proposed.
Then try to invoke code assist at: `a.foo(my|)`: now `myprop` is proposed.

**Comment by eric-milles** [comment]
When invoking content assist after the opening parenthesis of a method call, method context proposals are provided.  No expression, package or type completions are given.  This is consistent with the Java editor.
