### ISSUE TITLE
Bogus error over class member visibility on static import

### ISSUE THREAD

**Issue by simonmarshall** [groovy/groovy-eclipse#703]
When statically importing a member (but not a method) from a class in another package (but not when in the same package), groovy-eclipse shows the import as an error.  With the defining class:

    static final String CONST2 = 'const2'

This import is wrongly shown as an error in eclipse:

    import static constants.Constants.CONST2

Note that the problems error description wrongly refers to the "field Constants.constants.Constants.CONST2", not constants.Constants.CONST2.  Note also that this is a regression from eclipse neon, at least.

The code will compile and run fine outside of eclipse.

See the attached workspace and screenshot for details.

Eclipse Java EE IDE for Web Developers.
Version: Photon Release (4.8.0)
Build id: 20180619-1200

Eclipse Groovy Development Tools
Version: 3.1.0.xx-201809031245-e48

Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Groovy Compiler version 2.5.2.

[workspace.zip](https://github.com/groovy/groovy-eclipse/files/2348005/workspace.zip)

![workspace](https://user-images.githubusercontent.com/26903735/45027199-a48a8a00-b038-11e8-961b-9926cdc2403f.PNG)

**Comment by eric-milles** [comment]
This has been reported previously as #336 and #444.  There is more detail in each of those issues.  The import refers to the field created for a property, which is in fact private.  If you want to import it, you can import `getCONST2` or make the property a field by adding public modifier.
