### ISSUE TITLE
"Override method in" implemented trait not proposed

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#705]
Consider this:

```groovy
package test30
trait T {
	String getFoo() { 'foo' }
}
```

And:

```groovy
package test30

class A implements T {
  |
}
```

Invoke code assist at "|": the suggestion list proposes to override methods inherited from `Object`, but not `T.getFoo()`.
If `T` is an interface, it works correctly instead.

**Comment by eric-milles** [comment]
What am I missing?

![traits](https://user-images.githubusercontent.com/18193802/45255566-c85a1280-b34d-11e8-9a40-dd84a39d799b.png)

**Comment by mauromol** [comment]
Honestly I don't know... here is what I see:

![immagine](https://user-images.githubusercontent.com/1742494/45300385-7f9d8780-b50e-11e8-8282-c0916ebbb33f.png)

**Comment by eric-milles** [comment]
Are you updated to the latest snapshot?

**Comment by mauromol** [comment]
I'm using Greclipse 3.1.0.xx-201809082200-e47.

**Comment by mauromol** [comment]
Hi Eric, I see you deleted comments, were you able to reproduce then?

**Comment by eric-milles** [comment]
The comments did not add anything information not in original submission, so I removed them.


________________________________

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
It works with 3.1.0.xx-201809160114-e48, thank you! 👍
