### ISSUE TITLE
Error mark on class when nesting methods with same parameter names

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#707]
Consider this interface:

```java
package test;
public interface I {
	void myMethod(String a, int b);
}
```

and this Groovy class:

```groovy
package test
class A implements I {
	public void myMethod(String a, int b) {
		def i = new I() {
			public void myMethod(String a, int b) {

			}
		}
	}
}
```

I don't know if this is the intended behaviour, but an error mark is shown on the first line, saying that "The current scope already contains a variable of the name a" (and another equivalent error for b in this case).

In Java this construct is perfectly legal: of course, if you reference `a` from `new I().myMethod(String,int)`, you'll be operating over the `a` parameter defined in the inner scope, and you won't be able to reference the outer `a`. It's not good programming practice, but I was wondering whether it's like this by Groovy design or rather because of a problem in Greclipse.

**Comment by eric-milles** [comment]
This is a Groovy Compiler issue.  I agree, it should be allowed.  If nothing else, the error should be associated with the line,column of the offending variable.

![image](https://user-images.githubusercontent.com/18193802/46834442-0a251100-cd71-11e8-886b-2e3b325fd2e4.png)
