### ISSUE TITLE
Inner static block is causing compilation error

### ISSUE THREAD

**Issue by AntonPanikov** [groovy/groovy-eclipse#718]
Inner static init block is causing compilation error:
```groovy
package test

class Test {
    class TestInner {
        static {
        }
    }
}
```
Compile error:
>The method \<clinit\> cannot be declared static; static methods can only be declared in a static or top level type

I am on 3.1.0.xx-201809160115-e47

**Comment by eric-milles** [comment]
If your `TestInner` class does not need to reference any instance members of `Test`, you can add the `static` modifier to the inner class.  This will suppress the error.

**Comment by eric-milles** [comment]
Ready to test

**Comment by AntonPanikov** [comment]
Tested on 3.1.0.xx-201809172153-e47
It is fixed
