### ISSUE TITLE
Improper constructor name on Groovy class after copy-and-paste

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#723]
Consider this Groovy class:

```groovy
package test36

class Test36 {
  Test36() {}
}
```

Now, copy and paste it, to create `Test36b`: the result is:

```groovy
package test36

class Test36b {
  Test36() {}
}
```

This class does not compile, of course, because the constructor hasn't been renamed.

**Comment by eric-milles** [comment]
Can you try this again?  When I try this now, I get the correct constructor.

**Comment by mauromol** [comment]
Indeed, it seems to work fine in 3.3.0.xx-201901082257-e49, thank you!
