### ISSUE TITLE
Problem marker decorations missing in Project Explorer

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#725]
Groovy compilation units with error, warning or other problem markers are missing the label decoration in the Project Explorer view, as seen here:

![immagine](https://user-images.githubusercontent.com/1742494/45738951-01b63c00-bbf2-11e8-876a-e48bb6bcf7ad.png)

**Comment by eric-milles** [comment]
Package Explorer uses a different path from the Project Explorer; the latter was added more recently and has more behavior that is pluggable via extension points.

Groovy-Eclipse provides compilation unit images with the following extensions.  These should apply to the Navigator view as well, but not the Package Explorer view.
```xml
   <extension point="org.eclipse.ui.navigator.navigatorContent">
      <navigatorContent
            activeByDefault="true"
            contentProvider="org.eclipse.jdt.internal.ui.navigator.JavaNavigatorContentProvider"
            id="org.codehaus.groovy.eclipse.ui.groovyContent"
            labelProvider="org.codehaus.groovy.eclipse.ui.GroovyNavigatorLabelProvider"
            name="Groovy Sources"
            priority="high">
         <triggerPoints>
            <or>
               <instanceof value="org.codehaus.jdt.groovy.model.GroovyCompilationUnit" />
               <instanceof value="org.eclipse.core.resources.IFile" />
             </or>
         </triggerPoints>
         <possibleChildren>
            <or>
               <instanceof value="org.codehaus.jdt.groovy.model.GroovyCompilationUnit" />
               <instanceof value="org.eclipse.core.resources.IFile" />
            </or>
         </possibleChildren> 
         <override
               policy="InvokeAlwaysRegardlessOfSuppressedExt"
               suppressedExtensionId="org.eclipse.jdt.java.ui.javaContent">
         </override>
      </navigatorContent>
   </extension>

   <extension point="org.eclipse.ui.navigator.viewer">
      <viewerContentBinding viewerId="org.eclipse.ui.navigator.ProjectExplorer">
         <includes>
            <contentExtension pattern="org.codehaus.groovy.eclipse.ui.groovyContent" />
         </includes>
      </viewerContentBinding>
   </extension>
```

**Comment by eric-milles** [comment]
I can get the decorations to display on the compilation unit and child element (if applicable).  I'm just doing some extra checking to see if there are any additional views affected by this.

One thing that is still different between Java and Groovy editors is the title image.  Java editor shows the problem indicators; I explicitly disabled those some time back.  See upper right of this image:
![error](https://user-images.githubusercontent.com/18193802/45775482-84042780-bc15-11e8-8ddf-0235e4672181.png)

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
Works well for me with 3.1.0.xx-201809192124-e48!

**Comment by wzurborg** [comment]
Not sure where to ask and if this is the right place... I am writing my own Explorer with decorations based on Eclipse resource markers. I found that erroneous Groovy source files do not have any markers. Is that true? Would I have to inspect the extensions mentioned in https://github.com/groovy/groovy-eclipse/issues/725#issuecomment-422902853 to derive my decorations?

**Comment by eric-milles** [comment]
> I am writing my own Explorer with decorations based on Eclipse resource markers. I found that erroneous Groovy source files do not have any markers. ... Would I have to inspect the extensions mentioned [above]

Navigator view uses `navigatorContent` and `ILabelProvider` extensions.  Package Explorer and Project Explorer views use the newer label decorators.  I think the older ones are strictly based on content type config and only one applies for a given file.  If you are creating your own explorer-style view, you should be able to access the decorator's like the Project Explorer does.  GDT registers a decorator for the main image, but relies upon the problems decorator to provide error/warning/info decorations.

**Comment by wzurborg** [comment]
Ok thanks Eric.
