### ISSUE TITLE
@Trait applied to interface with generic cause compile error

### ISSUE THREAD

**Issue by AntonPanikov** [groovy/groovy-eclipse#733]
I found one more bug related to Grails projects, but I do not think it is Grails related, but @Trait annotation related. I was unable to extract and isolate this issue in the pure groovy project.

I am using:
Eclipse Oxygen.3a Release (4.7.3a)
Groovy-Eclipse 3.1.0.xx-201809251603-e47

It is easy to reproduce with SDKMAN:

    Install sdkman:
    curl -s "https://get.sdkman.io" | bash
    Source or open new shell:
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    Install grails:
    sdk i grails
    Create sample app in some folder (grails-example):
    grails create-app --profile web --inplace
    Create sample service:
    grails create-service sample

Import this project into eclipse and add Gradle nature. Edit grails-sample/grails-app/services/grails/sample/SampleService.groovy, like this:

```groovy
package grails.sample

import grails.events.Events
import grails.gorm.transactions.Transactional

@Transactional
class SampleService implements Events {
}
```
Copy this service as SampleService2 and just add reference to the previous one:
```groovy
package grails.sample

import grails.gorm.transactions.Transactional

@Transactional
class SampleService2 {
    SampleService sampleService
}
```
The second one will start complain about:
> Inconsistent classfile encountered: The undefined type parameter T is referenced from within SampleService

I believe it is T generic from Event interface, but I can not reproduce it in pure groovy.

Same complain from generated UnitTest class. Sometime this error is gone, but as soon as I clean or edit the source, just adding and removing space character for example, it will come back.

I am attaching my sample app zip here, just in case.
[grails-sample.zip](https://github.com/groovy/groovy-eclipse/files/2417316/grails-sample.zip)

**Comment by eric-milles** [comment]
I'm not seeing any error.  In the sample project supplied, `grails.events.Events` resolves to a deprecated trait that does not have any type parameters.  Most methods do have generic types, but you aren't referencing any of those yet.

**Comment by AntonPanikov** [comment]
This is from grails 3.2 where events is not deprecated, but I have compile error on 3.3 project that I attached. As I said it is tricky and sometimes error not show up until you edit file. Just try to edit SampleService2, just add new empty line and save. It will show up.

I believe it is refer to T type from grails.events.Events:
```groovy
<T> Event<T> eventFor(T var1);
```
![compile_error1](https://user-images.githubusercontent.com/24574076/46103410-c0e49700-c19e-11e8-8115-5902331e163c.png)
![compile_error2](https://user-images.githubusercontent.com/24574076/46103409-c0e49700-c19e-11e8-8456-eb9040cade52.png)

**Comment by eric-milles** [comment]
Got it.  So this only happens on incremental build.  If you need to get unstuck, you can clean and rebuild all.

When SampleService2 is trying to resolve the reference to SampleService, it encounters this error when lazily resolving methods.  In this case, the method appears to be:
```
org.eclipse.jdt.internal.compiler.classfmt.MethodInfo{public grails_events_Eventstrait$super$sendAndReceive<E:Lreactor/bus/Event<*>;>(Ljava/lang/Object;Lgroovy/lang/Closure;)Lreactor/bus/Bus;}

<E:Lreactor/bus/Event<TT; ^ >;>(Ljava/lang/Object;Lgroovy/lang/Closure<TE;>;)Lreactor/bus/Bus;

Unresolved type reactor.bus.Event
```

This may be a flavor of #548.  I'll have more info on that soon.

**Comment by eric-milles** [comment]
See [GROOVY-8815](https://issues.apache.org/jira/browse/GROOVY-8815)

**Comment by eric-milles** [comment]
Ready to test

**Comment by AntonPanikov** [comment]
Tried on: 3.1.0.xx-201810010340-e47
I am still having this issue. Once I make any changes in SampleService2 or SampleServiceSpec and save it, after incremental build, it is showing the same error. I am using the same sample project attached above.

**Comment by eric-milles** [comment]
Did you clean your workspace and rebuild the project?

**Comment by AntonPanikov** [comment]
I tried to Clean/Build all. I even deleted and re-imported project form the zip. Even after that, incremental build casing the error.

**Comment by eric-milles** [comment]
What version of the Groovy Compiler are you using?  This all has to do with the compiler and any compiler besides the Groovy-Eclipse compiler will not have the necessary patch.

**Comment by AntonPanikov** [comment]
As I mentioned:
Groovy Compiler 2.4
3.1.0.xx-201810010340-e47

**Comment by eric-milles** [comment]
It should look something like this, 3.1.0 will not be on the compiler plug-in.

![image](https://user-images.githubusercontent.com/18193802/46372580-2f1ed300-c651-11e8-83d1-74b8b132a1bc.png)

**Comment by AntonPanikov** [comment]
![groovy_compiler](https://user-images.githubusercontent.com/24574076/46376856-1c15fe00-c665-11e8-8c1e-a2d25f8801ae.png)

**Comment by eric-milles** [comment]
Could you attach your `SampleService.class` file?

**Comment by AntonPanikov** [comment]
[SampleService.class.zip](https://github.com/groovy/groovy-eclipse/files/2439834/SampleService.class.zip)

**Comment by eric-milles** [comment]
I see the error.  I'm not sure if it is because Events was compiled with generics that the current compiler doesn't produce.  That class is pre-compiled in your scenario.  I tried to extract the test case from it and so I have a source file in its place.

**Comment by eric-milles** [comment]
Ready to test

**Comment by AntonPanikov** [comment]
Tested on:
Groovy Compiler 2.4 3.1.0.xx-201810082206-e47
Groovy Runtime 2.4.15.xx-201810082206-e47

It is working now.

**Comment by eric-milles** [comment]
Thanks for trying it out.  I am testing one final version of a fix for this.  Would you mind testing that when the build completes?

**Comment by AntonPanikov** [comment]
Yes, sure. Just let me know when it is ready for test again.

**Comment by eric-milles** [comment]
Ready to retest

**Comment by AntonPanikov** [comment]
Tested on:
Groovy Compiler 2.4: 3.1.0.xx-201810091927-e47
Groovy Runtime:      2.4.15.xx-201810091927-e47

It is working.
