### ISSUE TITLE
Errors when Gradle BuildShip plugin is not installed

### ISSUE THREAD

**Issue by mpiggott** [groovy/groovy-eclipse#734]
When the Gradle Buildship plugin is not installed in Eclipse errors start appearing in the log when files are opened:

`The content type with id "org.eclipse.buildship.core.files.gradlebuildscript" specified in the extension point does not exist.`

**Comment by eric-milles** [comment]
Buildship recently added a new content type definition for Gradle scripts.  In order for Groovy-Eclipse to maintain support for the Groovy Editor as a choice for Gradle scripts, an association had to be made with the new content type:

```xml
   <extension point="org.eclipse.ui.editors">
      <editor
            class="org.codehaus.groovy.eclipse.editor.GroovyEditor"
            contributorClass="org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditorActionContributor"
            default="true"
            icon="$nl$/icons/groovy_file.png"
            id="org.codehaus.groovy.eclipse.editor.GroovyEditor"
            name="Groovy Editor"
            symbolicFontName="org.eclipse.jdt.ui.editors.textfont">
         <contentTypeBinding
               contentTypeId="org.eclipse.jdt.groovy.core.groovySource">
         </contentTypeBinding>
         <contentTypeBinding
               contentTypeId="org.eclipse.buildship.core.files.gradlebuildscript">
         </contentTypeBinding>
      </editor>
   </extension>
```

The unfortunate side-effect of this is when Buildship is not installed, the content type reference generates a pair of errors.

**Comment by mpiggott** [comment]
Doesn't that suggest this extension should be part of a non-greedy optional bundle which requires buildship?
