### ISSUE TITLE
Cannot run all spock tests in a directory

### ISSUE THREAD

**Issue by monrealis** [groovy/groovy-eclipse#736]
1. Create a Maven project with groovy, spock and junit.
2. Create a spock test case with `def variable = new ....() {}` declaration (`{}` is the key here). For example,

```groovy
class MySpec extends Specification {
    def list = new ArrayList() {
    }

    def "..."() {
...
    }
}
```

3. Run all tests in a package/directory

Eclipse shows "No tests found with test runner 'JUnit 4'.

![2018-09-30_2341](https://user-images.githubusercontent.com/2280367/46262543-5e2b2c80-c50b-11e8-8f88-42bc03bcb3a6.png)

[test-project.zip](https://github.com/groovy/groovy-eclipse/files/2432052/test-project.zip)

Maven build succeeds.

**Comment by eric-milles** [comment]
Type Hierarchy (Ctrl+T) is not working for the class and this is a necessary part of JUnit test location.

**Comment by eric-milles** [comment]
Ready to test
