### ISSUE TITLE
With eclispe groovy plugin 3.x we can't compile our project anymore

### ISSUE THREAD

**Issue by wagnerma** [groovy/groovy-eclipse#737]
We try to switch our project to the Eclipse-Groovy 3.x plugin. But the project now has errors ;-(. There seems some strange problems perhaps in the area CompileStatic in combination with Java, no clue. The code is correct, it runs and compile fine with the old Eclipse-Groovy plugin.

The groovy code is CompileStatic and uses a java class of the type:

```java
public class OpCaldocitemtypeType extends OptionObject {
    private static final long serialVersionUID = -1462780516731381671L;

	// STL-Position/Komponente
	public static final Integer BOM_ITEM = 10;
	// Arbeitsgang
	public static final Integer ROU_OPR = 20;
	// Variable
	public static final Integer VAR_ENTRY = 30;
	// Referenz auf anderes Schema
	public static final Integer CAL_DOCREF = 40;
	// Extrakosten
	public static final Integer EXTRA_COST = 50;
	// Zuschlag
	public static final Integer ITEM_OVH = 60;
	// Erlösminderung
	public static final Integer PROC_RED = 70;
    
    public static final Integer _defaultValue = 10;
    
    public static Map<String,Integer> getValues() {
        return getValues(OpCaldocitemtypeType.class);
    } 
}
```

Referencing such a class in groovy with:

OpCaldocitemtypeType.BOM_ITEM

creates an error: Groovy:[Static type checking] - The variable [OpCaldocitemtypeType] is undeclared.

But thats wrong, the include is available, the quick fix to import the class is not functioning.

I only see in the error log:
```
CodeSelectRequestor: Could not proceed due to null declaring type for org.codehaus.groovy.ast.expr.PropertyExpression@13673e2[object: org.codehaus.groovy.ast.expr.ClassExpression@78f7777[type: de.effectivecompany.app.app.OpCaldocitemtypeType] property: ConstantExpression[BOM_ITEM]]
```
Regards, Marcel

**Comment by eric-milles** [comment]
Do you have a snippet of the Groovy code that has the error?  Accessing a public static final field should be no problem.  I can't tell from the submission if you are static importing the field, importing the type or referring to the type by name from the same package.

**Comment by eric-milles** [comment]
Is it possible you have an extra ".app" in "de.effectivecompany.app.app.OpCaldocitemtypeType"?

**Comment by wagnerma** [comment]
The package names are all fine. It seems something different. It was not possible to isolate the problem, so I zip you the complete project. You can download the project here: [https://drive.google.com/file/d/1zWgTUoJjrSyHlgC2DV98yh10HdPyZU06/view?usp=sharing](url)
It is a gradle project, you can do a gradle project import, I use the newest Eclipse 2018-09 and the 2.5.2 compiler. There you see the strange static compile issues. Hope you can find somthing.

**Comment by eric-milles** [comment]
Thanks for the project archive.  You may want to remove it from online now.  Not sure if you meant to make it public.

**Comment by wagnerma** [comment]
You are right, I corrected it. But still some wired things are goning on. The updated project:
[https://drive.google.com/file/d/1tH_6_b8M_ly5CZBQJ-r-DXuqNnvW6MWy/view?usp=sharing](url)

**Comment by eric-milles** [comment]
Can you give some details on what you mean by "wierd"?

**Comment by wagnerma** [comment]
Well, for example the SvBoDocNewImpl.groovy, There the plugin says OptionTools import is missing. The quick fix want's to add the import "import de.effectivecompany.util.OptionTools" but it is already there, nothing happens. Adding a ";" behind the "import de.effectivecompany.util.OptionTools", or change something different and save the file, a lot of errors disappears, only one missing method.

**Comment by eric-milles** [comment]
Ready for test
