### ISSUE TITLE
Error in update

### ISSUE THREAD

**Issue by reny77** [groovy/groovy-eclipse#743]
When I try to update my Eclipse Photon I have this error:
![selection_002](https://user-images.githubusercontent.com/4334500/47078239-2a3a5180-d203-11e8-81a6-d74863e3094f.jpg)

Can I help with other informations about my system?

**Comment by eric-milles** [comment]
This is not an error, just a statement of what features are available for update.  You should be able to click Finish and Groovy will be updated.
