### ISSUE TITLE
currentType with annotatedBy does not match for local variable/method arguments

### ISSUE THREAD

**Issue by ybayk** [groovy/groovy-eclipse#767]
The following example works as expected
```
contribute(enclosingMethod(annotatedBy(name('java.lang.Deprecated')))) {
  method name:'foo', type:void
}
```
![image](https://user-images.githubusercontent.com/1779404/48738884-2be2a500-ec07-11e8-8288-f9c30cb669b1.png)

However, when the same annotation is applied on a method argument (along with currentType) contribution is not applied:
```
contribute(currentType(annotatedBy(name('java.lang.Deprecated')))) {
  method name:'bar', type:void
}
```
![image](https://user-images.githubusercontent.com/1779404/48739103-c511bb80-ec07-11e8-9cbe-3479e20264ac.png)

Note that the annotation and argument type used in this example is irrelevant. General use case is to enhance an object (in this case a local argument) by adding an extra method based on annotation applied.

**Comment by eric-milles** [comment]
In this case, the annotation is applied to the parameter, not the type.  So the DSLD check should be:
```groovy
contribute(enclosingMethod(hasArgument(annotatedBy(Deprecated)))) {
  ...
}
```

If deprecated is specifically what you are looking for, you can use the modifier pointcut:
```groovy
contribute(enclosingMethod(hasArgument(isDeprecated()))) {
  ...
}
```

**Comment by ybayk** [comment]
I agree I gave a wrong dsld snippet for the expected outcome. 
What am actually looking for is a way to "add" an extra method (foo) on annotated (by a custom annotation) argument (arg) through DSLD, so that arg.foo() is proposed and not underscored. 
Is it possible?

**Comment by eric-milles** [comment]
Yes, if the annotation is for the parameter and not the type, this will get matches within the method block:
```groovy
contribute(enclosingMethod(args: hasArgument(annotatedBy(WhateverAnnotation)))) {
}
```
After that, the trick is to apply your new method or property additions to only the variable expressions that are associated with the parameter.  If you want support for methods only, you can remove the check for PropertyExpression:
```groovy
import org.codehaus.groovy.ast.expr.*
contribute(enclosingMethod(args: hasArgument(annotatedBy('p.A')))) {
  if ((enclosingNode instanceof MethodCallExpression || enclosingNode instanceof PropertyExpression) &&
      enclosingNode.objectExpression instanceof VariableExpression &&
      enclosingNode.objectExpression.accessedVariable in args) {
    property name: "someProp", type: Double
  }
}
```

**Comment by eric-milles** [comment]
If your annotation applies to the type and not the parameter, you can use a pointcut like this (and then use the same checks in the contribution block):
```groovy
contribute(enclosingMethod(args: hasArgument(type(annotatedBy(WhateverAnnotation))))) {
}
```

**Comment by ybayk** [comment]
I need to use it on an arguments and maybe fields. The solution for an argument seems to work but looks a bit verbose, maybe the scenario with non-type-based annotations deserves a dedicated pointcut?

**Comment by eric-milles** [comment]
You can use a similar technique for fields and properties. It may require more than just point it expressions, but you can just copy as is and fill in only the methods or properties. 

If you want to cut down on the repetition or verbosity, you can use registerPointcut to do the object expression checking. 

If you want a new built-in pointcut, you will need to wait for it to be implemented and your users will have a minimum version constraint.

**Comment by eric-milles** [comment]
And you could parameterize the annotation check so you can repeat it for many annotations:
```groovy
def variableAnnotatedBy = { tag -> enclosingClass(vars: fields(annotatedBy(tag))) | enclosingMethod(vars: hasArgument(annotatedBy(tag))) }

contribute(variableAnnotatedBy(WhateverAnnotation)) {
  if (objectExpressionCheck(vars, enclosingNode)) {
    // method, property, etc. contributions
  }
}
```

**Comment by yurgisbaykshtis** [comment]
One more use case I am not sure how to create dsl for. Here is what I tried but it does not work:

```
contribute(enclosingCall(hasParameter(annotatedBy(MyAnnotation)))) {
  method name:'foo', type:void
}

def bar(@MyAnnotation Closure block) {
}

bar {
     //we are really in the closure being passed as a parameter to bar() method
     //need foo() to be proposed here based on annotation of its 'block' parameter 
}
```

**Comment by ybayk** [comment]
and one additional case:

@MyAnnotation def bar = {
   //propose method foo() here but only is the variable assigned to the enclosing closure is annotated by MyAnnotation
}

**Comment by eric-milles** [comment]
@yurgisbaykshtis You can try this:
```groovy
contribute(enclosingCall(hasParameter(annotatedBy(MyAnnotation) & type(Closure))) & inClosure() & isThisType()) {
  method name:'foo', type:void
}
```

@ybayk This may get you started for `@Tag def bar = { ... }`:
```groovy
contribute(enclosingAssignment(annotatedBy(MyAnnotation))) {
}
```
