### ISSUE TITLE
Overloading not properly handled for constructor calls

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#768]
Somewhat a followup to #765.

Consider these java classes:

```java
package test42;

import java.util.Set;

public class MyService {

	public static class MyBean {

		public final boolean foo;
		public final Set<String> bar;
		public final Set<Integer> foobar;

		public MyBean() {
			this(false, null, null);
		}

		public MyBean(final boolean foo, final Set<String> bar,
				final Set<Integer> foobar) {
			this.foo = foo;
			this.bar = bar;
			this.foobar = foobar;
		}
	}

	public class MyBean3 {

		public final boolean foo;
		public final Set<String> bar;
		public final Set<Integer> foobar;

		public MyBean3() {
			this(false, null, null);
		}

		public MyBean3(final boolean foo, final Set<String> bar,
				final Set<Integer> foobar) {
			this.foo = foo;
			this.bar = bar;
			this.foobar = foobar;
		}
	}
}
```

```java
package test42;

import java.util.Set;

public class MyBean2 {

	public final boolean foo;
	public final Set<String> bar;
	public final Set<Integer> foobar;

	public MyBean2() {
		this(false, null, null);
	}

	public MyBean2(final boolean foo, final Set<String> bar,
			final Set<Integer> foobar) {
		this.foo = foo;
		this.bar = bar;
		this.foobar = foobar;
	}
}
```

and this Groovy class:

```groovy
package test42

import test42.MyService.MyBean
import test42.MyService.MyBean3

class Test42 {

	void doSomething() {
		def b = new MyBean(true, null, null)
		def b2 = new MyBean2(true, null, null)
		
		def s = new MyService()
		def b3 = new MyBean3(s, true, null, null)
	}		
}
```

Overloading is not properly handle, as you can see by:

- clicking F3 over "MyBean3" at row `def b3 = new MyBean3(s, true, null, null)` brings to 
`test42.MyService.MyBean3.MyBean3()` instead of `test42.MyService.MyBean3.MyBean3(boolean, Set<String>, Set<Integer>)`; this only happens for the inner class, does not happen for top-level and nested class
- invoking Ctrl+Alt+H (call hierarchy) or Ctrl+Shift+G (find references) from the no-args constructors of `MyBean`, `MyBean2` and `MyBean3` matches calls from `Test42` class, which however only calls constructors with args; this seems not to happen with regular method calls

**Comment by eric-milles** [comment]
Ready to test

`this(...)` and `super(...)` constructor calls should be found when searching.

Incomplete use cases: default parameters, anonymous inner calls, `@Newify` constructor call transformations

**Comment by mauromol** [comment]
Tested with 3.2.0.xx-201811260558-e48 for `MyBean` and `MBean2`, it works. Also works for `this(...)` and `super(...)` when Groovy beans are involved.
Does not work yet for the `MyBean3` case, I guess it has something to do with what you call "anonymous inner calls" and that is missing.
Not tested default parameters and `@Newify`.

**Comment by eric-milles** [comment]
Ah yes, `MyBean3` is a non-static inner class.  I'm still not used to seeing those created from outside of the enclosing type.  There needs to be accommodation for the implicit `MyService` parameter.

There was just so much to unpack for this issue...

**Comment by eric-milles** [comment]
Ready to test for inner class case

**Comment by mauromol** [comment]
Works with inner classes in 3.2.0.xx-201811262337-e48 👍 

Not tested default parameters and `@Newify` yet, let me know when I should.

**Comment by eric-milles** [comment]
Anonymous inner construction, default parameters, and `@Newify` support will need to come as separate issues.  Hopefully what is there now is an improvement over previous behavior.
