### ISSUE TITLE
Irrelevant suggestions given when invoking code assist for annotation attributes

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#769]
Follow up to #761.

The following screenshots show that useless suggestions are given when invoking code assist for annotation attribute completion:

![immagine](https://user-images.githubusercontent.com/1742494/48189603-deca1d80-e340-11e8-9de5-f55c1b1c5e25.png)

In the above case, probably no suggestion at all should be given, or rather just "true"/"false" to replace the current "false"? I don't know how JDT behaves in this case.

![immagine](https://user-images.githubusercontent.com/1742494/48834539-61f66500-ed7e-11e8-9d53-bfa213cf431a.png)

Here only the first 4 suggestions are relevant, the others are not.

**Comment by eric-milles** [comment]
The case of completing a member name should not have type proposals.  Value completion is next.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
Works well with 3.2.0.xx-201811260558-e48, thank you! 👍
