### ISSUE TITLE
No code assist at all for this(...) and super(...)

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#770]
When you are writing a constructor of a Groovy class, you won't have any code assist for completing `this(...)` and `super(...)`, neither for the keyword (like: `th|` or `sup|` to complete `this` and `super` respectively) nor for arguments (like `this(|` or `super(|` to invoke a constructor overload with params).

**Comment by eric-milles** [comment]
It is a bit of a work in progress, but you should be able to get context proposals for `this(...)` and `super(...)`.  The enclosing constructor is not filtered out when using `this(...)` in all cases.  And proposals for `th` or `su` are not there yet.  But it should give some usable results.

**Comment by mauromol** [comment]
Hi Eric, I made some quick tests with 3.2.0.xx-201812021946-e48 and indeed I see an improvement when invoking code assist as `this(|)` or `super(|)`, but, apart from `th|` and `sup|` not working (as you said), I noticed that also `this(|` and `super(|` (missing closed parenthesis) don't work.

**Comment by eric-milles** [comment]
Proposals for `th|` and `sup|` should be provided now.  I'm not planning on supporting `this(` and `super(` in the near term.
