### ISSUE TITLE
Default parameters: wrong navigation on constructor call

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#774]
Somewhat follow up to #768 

Consider this:

```groovy
package test42

class GBean {

	GBean() {}
	
	GBean(String foo, String bar = 'hello') {}
	
	void doSomething() {}
	
	void doSomething(String foo, String bar = 'bar') {}
}
```

And this:

```groovy
package test42;

class Test43 {

	void test() {
		def b2 = new GBean('foo')
		
		b2.doSomething()
		b2.doSomething('foo')
		b2.doSomething('foo', 'bar')
	}
}
```

Put the cursor over `GBean` on `def b2 = new GBean('foo')` and hit F3: you're brought to the first line of `GBean` class, while you should be brought to `test42.GBean.GBean(String, String)`.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
Works in 3.2.0.xx-201812021946-e48, thank you! 👍
