### ISSUE TITLE
Default parameters: constructor call not found by Call Hierarchy

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#775]
Somewhat follow up to #768 

Consider this:

```groovy
package test42

class GBean {

	GBean() {}
	
	GBean(String foo, String bar = 'hello') {}
	
	void doSomething() {}
	
	void doSomething(String foo, String bar = 'bar') {}
}
```

And this:

```groovy
package test42;

class Test43 {

	void test() {
		def b2 = new GBean('foo')
		
		b2.doSomething()
		b2.doSomething('foo')
		b2.doSomething('foo', 'bar')
	}
}
```

Go to `test42.GBean.GBean(String, String)`. and invoke Call Hierarchy: the call from `test42.Test43.test()` is not found.

**Comment by eric-milles** [comment]
I had started to look into this one when adding support for find references of overloaded constructors.  If `GBean` is in the same file, I think the search and Call Hierarchy works as expected.  When they are in separate sources, the conversion from Groovy to Java model is missing the links between the original constructor (the one with 2 parameters) and the generated constructor (the synthetic one with 1 parameter).  The conversion is done in `JDTClassNode` and I am looking for some clue in the `MethodBinding` that a given method or constructor is generated as a result of a defaulted parameter.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
This works fine in 3.3.0.xx-201901152207-e49, thank you! 👍
