### ISSUE TITLE
Default parameters: wrong signature considered when invoking Call Hierarchy from a method/constructor call omitting optional parameters

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#776]
Consider this:

```groovy
package test42

class GBean {

	GBean() {}
	
	GBean(String foo, String bar = 'hello') {}
	
	void doSomething() {}
	
	void doSomething(String foo, String bar = 'bar') {}
}
```

And this:

```groovy
package test42;

class Test43 {

	void test() {
		def b2 = new GBean('foo')
		
		b2.doSomething()
		b2.doSomething('foo')
		b2.doSomething('foo', 'bar')
	}
}
```

Now put the cursor on:
- `doSomething` on `b2.doSomething('foo')`
- `GBean` on `def b2 = new GBean('foo')`

Invoke Call Hierarchy in both cases. Greclipse respectively:
- searches for references to `test42.GBean.doSomething(String)`, which does not exists; it should match `test42.GBean.doSomething(String, String)` and search references for that instead
- searches for references to `test42.GBean.GBean(String)`, which does not exists; it should match `test42.GBean.GBean(String, String)` and search references for that instead

**Comment by eric-milles** [comment]
One misconception is the statement "does not exist" for the one-parameter variants of constructor and method in your example.  Shortly after parsing, the constructors/methods with default values parameters have variant(s) generated.  Thus, references to `GBean('foo')` and `doSomething('foo')` do actually map directly to a model element, the same as the other call expressions.

What I have found is that you can search starting from the constructor or method declaration and find call references of differing number of arguments with relative ease.  Each generated method in the Groovy AST has a link back to the original.  However, when initiating the search from a call expression, JDT is in control and the search pattern specifies the number of parameters that matches the call expression.  So at the moment it is a one-way function.  I'd recommend searching for references starting from the declaration for best results.

**Comment by mauromol** [comment]
Hi Eric, just one clarification: by "does not exist" I mean "in the source code": since navigation, call hierarchy and search for references are features of the IDE that ease navigation and refactoring within the source code I believe the behaviour should be coherent with what the source code shows, rather than what is indeed generated under the hood.

This said, I also perfectly agree that "call hierarchy" and "search for references" are more naturally invoked from the declaration site, rather than from the call site, nonetheless it would be nice if Greclipse could handle call site invocations in the right way, especially because navigation seems to work fine instead.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
This works fine in 3.3.0.xx-201901152207-e49, great work! 👍
