### ISSUE TITLE
Update frequency too high

### ISSUE THREAD

**Issue by veita** [groovy/groovy-eclipse#778]
Currently updates for Eclipse-Groovy are delivered daily. Given several workspaces and different Eclipse installations I find it very distracting to get a popup windows all the time.

It would be nice to have an additional update site with a lower update frequency. Personally I would prefer two or four substantial updates per year.

**Comment by eric-milles** [comment]
I'm assuming you are referring to the Eclipse Marketplace install.  What version of eclipse are you using?  There are formally 4 releases per year scheduled.  I setup the supported eclipse versions with snapshots instead of releases.  But I can reduce snapshots to the leading-edge eclipse releases, like 2018-09 and 2018-02.

**Comment by veita** [comment]
Yes, I think all are Eclipse Marketplace installs.

Currently I'm using Eclipse Photon, 2018-09, and 2018-12 M3. I understand that it might be necessary to have a high update frequency for development versions of Eclipse. For released versions, it would be nice if users had the choice between normal and snapshot releases.

**Comment by eric-milles** [comment]
You may choose between snapshots and release at any time.  The update site links are all provided here: https://github.com/groovy/groovy-eclipse/wiki

As for the Marketplace entry, I have older releases of Eclipse set to GDT releases and newer releases of Eclipse set to GDT snapshots.  When Eclipse 2018-12 is released (in a few days), GDT will follow suit with the 3.2.0 release.  Soon after, Eclipse 2019-03 will have a milestone available and the Marketplace entry will be updated.
