### ISSUE TITLE
Problems during content assist (only happens with '@')

### ISSUE THREAD

**Issue by seongbin9786** [groovy/groovy-eclipse#780]
## Related Issue
#209 

## Environment
- OS: Windows 10 x64
- IDE: Spring Tool Suite 4 (4.0.2 RELEASE + it says there's nothing to update)
- Spring Boot with Maven
- Spock

## Symptoms

1. Type `@` around class/method/field/...
2. Type `Ctrl + Space` (it's a shortcut for Auto Complete)
3. Stops for a bit (>= 5 sec)
4. Error Prompt pops up
5. Click 'OK' button then panel is still activated (picture below)
    - it works fine while the panel is open

## It doesnt happen when..

1. Type `@` with one or more letter
    - **LIKE:**
        - `@W` - suggestion works normally - such as `WebMvcTest`
        - `@D` - suggestion works normally - such as `DataJpaTest`

2. Or Type anything other than `@`
    - works perfectly fine

## The error prompt
![prompt](https://user-images.githubusercontent.com/28754907/50323696-1b7f5c00-051e-11e9-8b01-5e0b4cce3560.png)

## Suggestion panel after the prompt closed
![panel](https://user-images.githubusercontent.com/28754907/50324474-787d1100-0522-11e9-8943-b10f66938b5e.png)

**Comment by seongbin9786** [comment]
Thanks for your response :)

1. Groovy Development Tools 3.2.0.SNAPSHOT
2. Groovy 2.5.4 (packed within spock-core-1.2-groovy-2.5)

Annotations are proposed as expected:
![image](https://user-images.githubusercontent.com/28754907/50360782-8d9a8400-05a4-11e9-8899-7b842ad15a39.png)

Loading suggestions takes too much time therefore the error prompt pops up quite often 😢

**Comment by eric-milles** [comment]
Some background information for any interested parties: Groovy cannot satisfy this request from the Java annotations index alone.  Groovy annotation collector types like `@Canonical` and `@CompileStatic` are compiled to regular classes from Java's perspective.  So, the Groovy completion processor needs to examine all classes to determine if any are annotation collectors.  In a project with many dependencies, this can take some time.

With some prefix character(s), the names index can cut down the number of types that must be examined quite a bit and so you should experience "normal" responsiveness in that case.

**Comment by seongbin9786** [comment]
Awesome! Thank you very much 😄
