### ISSUE TITLE
Missing reference to setter when in with { }

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#784]
Consider this Java class:

```java
package test44;

public class MyBean {
	private String foo;
	
	public String getFoo() {
		return foo;
	}
	
	public void setFoo(String foo) {
		this.foo = foo;
	}
}
```

and this Groovy class:

```groovy
package test44

class Test44 {
	
	void doSomething() {
		def b = new MyBean()
		b.with { 
			foo = 'foo'
		}
	}
}
```

Now either:

1. invoke Call Hierarchy for `test44.MyBean.setFoo(String)`
2. search for References to `test44.MyBean.setFoo(String)`
3. rename `test44.MyBean.setFoo(String)` to something else

In all cases, the reference in `test44.Test44.doSomething()` is not found. In case 3., the result of the refactoring is invalid code.

**Comment by eric-milles** [comment]
Call Hierarchy and Find References should be ready to test.  Some other items that came up include replacing `foo = 'foo'` with `def bar = foo` and checking for references to `getFoo()` and `foo += 'foo'` as another form of reference to `setFoo(String)`.

Rename refactor of `getFoo` or `setFoo` has not been fixed yet.

**Comment by mauromol** [comment]
Hi Eric, sorry for the delay. I verified that with 3.3.0.xx-201901020255-e49 all the mentioned cases work fine, thank you!
