### ISSUE TITLE
Issue in Release Update Site links

### ISSUE THREAD

**Issue by fkrebs** [groovy/groovy-eclipse#785]
When Installing new Software, the update site URL with the Release Update Site links provided doesn't work 
I change it and it works
OLD : http://dist.springsource.org/release/GRECLIPSE/e4.10
NEW: http://dist.springsource.org/release/GRECLIPSE/3.2.0/e4.10

**Comment by lgoldstein** [comment]
Ditto - please make sure that the Wiki matches reality.

**Comment by eric-milles** [comment]
This is being sorted out.  The release went out over winter break.  Please bear with us.

**Comment by aclement** [comment]
Should all be fixed up now 4.7>4.10 update sites point at 3.2.0 release.

**Comment by lgoldstein** [comment]
Does not look like they are fixed - the wiki site still shows `http://dist.springsource.org/release/GRECLIPSE/e4.10` and this is where the link leads to:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>release/GRECLIPSE/e4.10</Key>
<RequestId>09C5B28025E5DCE7</RequestId>
<HostId>
81XYLnRMvkFXjaJO6fIS4Xz/RQUKEgLIoyYoNsuBn8RiA+M+/kOAGKsrualkR3x8XHs4T8wajBM=
</HostId>
</Error>
```

**Comment by eric-milles** [comment]
The links are not web sites, they are eclipse update sites.  If you add one within Eclipse > Window (menu) >Preferences > Install/Update > Available Software Sites, you can see if Eclipse recognizes it using Help (menu) > Install New Software...

**Comment by lgoldstein** [comment]
Actually, it doesn't do that - it says "No updates found". It works only if one enters the `xxx/3.2.0.xxx` link, so I think this issue is not resolved...

**Comment by eric-milles** [comment]
The site aliases were just corrected yesterday.  If you have not restarted your Eclipse, it will used cached site content which pointed to 3.1.0 release.
