### ISSUE TITLE
Outer references proposed before self references in Code Assist within 'with' closure

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#787]
Follow up of #364. Related to the discussion made on #674.

Consider this Groovy class:

```groovy
package test45

class Test45 {
  static class Foo {
	  String someString = 'foo'
  }
  
  static class Bar {
	  String someString = 'bar'
	  Foo foo = new Foo()
	  
	  void doSomething() {
		  foo.with {
			  println "someString inside with closure = $someString"
			  println "someString of owner inside with closure = $owner.someString"
			  someS|
		  }
	  }
  }
  
  static main(args) {
	  Bar b = new Bar()
	  println "b.someString = $b.someString"
	  println "b.foo.someString = $b.foo.someString"
	  b.doSomething()
  }
}
```

Invoke code assist at "|": I would expect to see `Foo.someString` proposed before `Bar.someString`, because in this context (closure with delegation to `self`) it is reasonably the most natural choice.

**Comment by eric-milles** [comment]
Are you looking for all proposals from delegate to come before owner proposals?  Or just in the case of ties?

**Comment by mauromol** [comment]
Hi Eric,
as already discussed in #674 IMHO the first criterion for sorting suggestion should not be the declaration scope, but rather a prediction of the user intent. For this reason I'm saying that exact matches should be shown first, followed by prefix matches, followed by substring matches, followed by camel case matches. In case of multiple options with the same relevance (what you call a "tie", I guess), then thinking about the scope is surely reasonable. In this case (probably in any similar case, when you're typing within a closure body?), I would say that the delegate proposals should be shown before the owner proposals, because, IMHO, in case of a tie they should be preferred (and this is confirmed by the fact that, in the above example, the delegate field is referenced by just `someString`, while the owner one by `owner.someString`, so in some way Groovy itself is giving precedence to the delegate).
So, in general, I would not say that ALL proposals from the delegate should come before ALL the owner proposals, but only when their relevance is the same with regards to the predicted user intent.

**Comment by mauromol** [comment]
Testing with 3.3.0.xx-201901072218-e49 I still see this:

![immagine](https://user-images.githubusercontent.com/1742494/50820638-7c37d280-132d-11e9-838c-ebd9959a5359.png)

**Comment by mauromol** [comment]
I verified that 3.3.0.xx-201901082257-e49 works fine on this case, but not unfortunately on that of #674.
Thank you!
