### ISSUE TITLE
No code assist for 'super(' and 'this('

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#789]
Follow-up to #770.

Consider the following Groovy classes:

```groovy
package test46

class Base {
	Base(String foo, int bar) {}	
}
```

```groovy
package test46
class Ext extends Base {
	Ext(String foo, int bar) {
		super(|
	}
}
```

Invoke code assist at "|": no suggestion is given.

Also consider this variant:

```groovy
package test46
class Ext2 extends Base {
	Ext2(String foo, int bar) {
		super(foo, bar)
	}

	Ext2() {
		this(|
	}
}
```

Invoke code assist at "|": no suggestion is given.

Note: they are given if there's a trailing closed parenthesis ")".

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
I confirm it works in 3.3.0.xx-201901180207-e49, thank you! 👍
