### ISSUE TITLE
Display and edit Groovy code in a text widget that is part of another editor

### ISSUE THREAD

**Issue by wzurborg** [groovy/groovy-eclipse#791]
I am involved in the development of a mixed e3/e4 RCP application for the management of EMF based data models. There is a form editor displaying model objects with their various properties. Properties are displayed according to their type in widget types like checkboxes and text fields. One of the property may be a Groovy expression, so there is a user requirement to display the Groovy code in a "Groovy aware" text widget embedded in the outer editor with syntax highlighting, formatting, and all the other nice features the Groovy editor has. I guess such a text field would be difficult to implement, because most of the nice UI features are part of the Groovy Editor class and cannot simply be re-used in a text field.

Alternatively, we could put a button on the form and open the Groovy Editor in its own separate part/view. As far as I can see, it is based on the JDT CompilationUnitEditor, so I guess it can only handle EditorInput coming from a file in the Eclipse workspace. Or is it possible to feed it with source code coming from memory or from a database? 

It would be nice if someone could give me pointers or ideas on how to approach this problem.

Thanks in advance
Wernke

**Comment by eric-milles** [comment]
@wzurborg I think you can get basic recognition and code completion by creating a text field with a completion processor attached.  This is done in the new type wizard for completion of type names (see `org.codehaus.groovy.eclipse.wizards.NewTypeWizard.PageTwo.createSuperClassControls(Composite, int, String, String)`).

To add syntax highlighting requires a lot of components working together.  Groovy Editor makes use of a lot of components to provide the editing experience.  You may have a look at how JDT does completion and syntax coloring in the Breakpoints view for conditional breakpoints.
