### ISSUE TITLE
 the latest Groovy-Eclipse release cannot access

### ISSUE THREAD

**Issue by jimokuqidehai** [groovy/groovy-eclipse#793]
the latest Groovy-Eclipse release cannot access，Where can I download the offline installation package?
4.10 (2018-12)    "http://dist.springsource.org/release/GRECLIPSE/e4.10"

**Comment by eric-milles** [comment]
Each release lists update sire archive links at the end of the release notes: https://github.com/groovy/groovy-eclipse/wiki/3.2.0-Release-Notes#update-sites
