### ISSUE TITLE
Is groovy-eclipse project compatible with checker-framework?

### ISSUE THREAD

**Issue by croesch** [groovy/groovy-eclipse#799]
Hello we'd like to run some [spock tests](https://github.com/spockframework/spock) but we're also using [checker-framework](https://github.com/typetools/checker-framework).

We have trouble to get the project run. Basically we posted the information [on stackoverflow](https://stackoverflow.com/questions/54327174/how-to-analyze-compilation-error-with-groovy-eclipse-batch-compiler) yesterday.

Basic question is: **Is groovy-eclipse project compatible with checker-framework?**

If yes: **What am I doing wrong / how can I solve my issues?**

Could somebody have a look at the question, I'd like to avoid redundancy but I feel like nobody could easily answer the question - so maybe you could help me. If necessary I can repost everything here :)

Thanks in advance.

**Comment by croesch** [comment]
Currently we're using Java 7. Newest versions of the frameworks require Java 8 as far as I can see - but the problem still exists in newer (`-compiler 3.0.0-02` + `-batch 2.4.16-02`) versions.

**Comment by eric-milles** [comment]
@croesch Could you attach your sample maven project zip (or a link to it on github)?  Also do you have a java-only example that works so I could compare?  I can take a look from there.

Java 8 is required to use newer batch compiler, but you still should be able to target Java 7 with no issue.

**Comment by croesch** [comment]
Thanks for the quick reply, I uploaded the project files [croesch/groovy-spock-checkerframework-test](https://github.com/croesch/groovy-spock-checkerframework-test).

Please note that **the application doesn't use any spock or checkerframework features currently**. It's just about compiling an empty repository - if you would like some source code that uses either checkerframework or spock features, let me know - but at the current stage I think this is not necessary.

**Branch only-checkerframework** contains the *SUCCESS*-bringing POM using only the checker-framework.

**Branch spock-groovy-checkerframework** contains the *FAILURE*-bringing POM.

**Comment by eric-milles** [comment]
I was able to get the compler and tests to run successfully with this POM.  I tried to remove some of the extra property indirection.  I think the most notable change from the original is the addition of `pluginRepositories`.

If you can supply me with some checker-framework code and the expected results, I can try that out too.

```xml
<project
 xmlns="http://maven.apache.org/POM/4.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                     http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <org.checkerframework.version>2.1.14</org.checkerframework.version>
  </properties>

  <pluginRepositories>
    <pluginRepository>
      <id>bintray</id>
      <name>Groovy Bintray</name>
      <url>https://dl.bintray.com/groovy/maven</url>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.checkerframework</groupId>
        <artifactId>checker</artifactId>
        <version>${org.checkerframework.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.checkerframework</groupId>
      <artifactId>checker</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.4.16</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.2-groovy-2.4</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>3.0.0-01</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>2.4.16-02</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>checkerframework-jdk7</id>
      <activation>
        <activeByDefault>false</activeByDefault>
        <jdk>1.7</jdk>
      </activation>

      <dependencies>
        <dependency>
          <groupId>org.checkerframework</groupId>
          <artifactId>compiler</artifactId>
          <version>${org.checkerframework.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.checkerframework</groupId>
          <artifactId>jdk7</artifactId>
          <version>${org.checkerframework.version}</version>
          <scope>provided</scope>
        </dependency>
      </dependencies>

      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <inherited>true</inherited>
            <executions>
              <execution>
                <id>default-compile</id>
                <configuration>
                  <compilerArgs>
                    <arg>-J-Xbootclasspath/p:${org.checkerframework:compiler:jar}</arg>
                    <arg>-Xbootclasspath/p:${org.checkerframework:jdk7:jar}</arg>
                  </compilerArgs>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>checkerframework-jdk8</id>
      <activation>
        <activeByDefault>false</activeByDefault>
        <jdk>1.8</jdk>
      </activation>

      <dependencies>
        <dependency>
          <groupId>org.checkerframework</groupId>
          <artifactId>jdk8</artifactId>
          <version>${org.checkerframework.version}</version>
          <scope>provided</scope>
        </dependency>
      </dependencies>

      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <inherited>true</inherited>
            <executions>
              <execution>
                <id>default-compile</id>
                <configuration>
                  <compilerArgs>
                    <arg>-Xbootclasspath/p:${org.checkerframework:jdk8:jar}</arg>
                  </compilerArgs>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>checkerframework</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>

      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>properties</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <inherited>true</inherited>
            <executions>
              <execution>
                <id>default-compile</id>
                <configuration>
                  <compilerId>groovy-eclipse-compiler</compilerId>
                  <verbose>true</verbose>
                  <annotationProcessorPaths>
                    <path>
                      <groupId>org.checkerframework</groupId>
                      <artifactId>checker</artifactId>
                      <version>${org.checkerframework.version}</version>
                    </path>
                  </annotationProcessorPaths>
                  <annotationProcessors>
                    <annotationProcessor>org.checkerframework.checker.nullness.NullnessChecker</annotationProcessor>
                  </annotationProcessors>
                  <useIncrementalCompilation>false</useIncrementalCompilation>
                  <compilerArguments>
                    <AprintErrorStack />
                    <AprintAllQualifiers />
                    <AprintVerboseGenerics />
                    <Adetailedmsgtext />
                  </compilerArguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
```

**Comment by croesch** [comment]
Oh sure, I added the repository on company's proxy repo, thx for the hint. I updated the POM.

But are you sure that you run the checkerframework? You have to activate the provile `$ mvn clean verify -Pcheckerframework`

I added code in both branches that will fail if the checkerframework runs. It will produce output like this:
```
[ERROR] /home/user/public/my-app/src/main/java/com/mycompany/app/App.java:[19,13] error: (return.type.incompatible) $$ 2 $$ @FBCBottom @Nullable  null $$ @Initialized @NonNull String $$ ( 363, 367 ) $$ incompatible types in return.
  found   : @FBCBottom @Nullable  null
  required: @Initialized @NonNull String
```

**Comment by eric-milles** [comment]
I suspect this issue is to blame: https://github.com/pdurbin/maven-hello-world/issues/3

I'm trying to follow the setup instructions for the specific checkerframework version: https://checkerframework.org/releases/2.1.14/manual/#maven

What I am finding is that passing the 2 different type of compiler arguments is difficult.  `ecj` (aka `groovy-eclipse-batch`) wants "-bootclasspath" "path/to/jdk7-compat-jar" as two separate arguments and the JVM wants "-Xbootclasspath/p:${org.checkerframework:compiler:jar}" to augment the compiler classpath.  I'll edit the POM above if I can get this going.

**Comment by eric-milles** [comment]
So I think I have everything wired up as best as can be hoped.  The exception below is from the snippet of JavacTask.  It is expecting a very specific ProcessingEnvironment type.  I don't think the Eclipse compiler is supplying this -- it is likely supplying an instance of  `org.eclipse.jdt.internal.compiler.apt.dispatch.BatchProcessingEnvImpl`.

    Internal compiler error: java.lang.IllegalArgumentException at com.sun.source.util.JavacTask.instance(JavacTask.java:66)

```java
    public static JavacTask instance(ProcessingEnvironment processingEnvironment) {
        if (!processingEnvironment.getClass().getName().equals(
                "com.sun.tools.javac.processing.JavacProcessingEnvironment"))
            throw new IllegalArgumentException(); // line 66
```

**Comment by eric-milles** [comment]
One idea I had late yesterday is to split compilation into two phases.  In one, you could have the traditional maven java compiler run the checkerframework with compiler argument "-proc:only".  In the other, you could configure the groovy compiler adapter to skip annotation processing with compiler argument "-proc:none".  This should give you both checkerframework and joint groovy/java compilation.

**Comment by croesch** [comment]
Thanks for the information about the different compiler arguments - did you get it working?

Is your last idea of the two-phase-compilation simple to setup because I have no experience with something like that - any way could you assist me with the final solution?

Checkerframework and groovy-compiler is both only important for testing (in my scenario), so it would be acceptable to have some setup that compiles multiple times with different compilers while testing whereas the "normal" compilation would only use the default compiler without further magic.

**Comment by eric-milles** [comment]
I edited the POM above.  It should use standard maven compiler for `src/main/java` and this includes checker-framework processor.  And it should use Groovy-Eclipse compiler adapter for `src/test/groovy` and `src/test/java`.  In my case, I just put one empty test file in `src/test/java` and all the tests in `src/test/groovy`.

**Comment by croesch** [comment]
Thanks very much - that setup is working and I think it's an acceptable workaround.

So the answer of the original question still might be `no`, groovy-compiler cannot work on the same sources as the checkerframework!?

**Comment by eric-milles** [comment]
Correct, the eclipse compiler is not compatible with the checker framework.  This is because of the very strict type checking deep in the Java compiler supplied by the framework (see details above).  If this were loosened up, ecj and therefore groovy-eclipse-batch could work with it.
