### ISSUE TITLE
Could not compile graphql-java

### ISSUE THREAD

**Issue by etienne-sf** [groovy/groovy-eclipse#800]
Hello,

  I'm desperatly trying to compile the graphql-java project, with eclipse-2018-12 and either jdk8 or jdk11.
But I have no success.
5 groovy compilation errors always remain:
* Once: "The method toMixedCase cannot be declared static; static methods can only be declared in a static or top level type..."
* 4 times : "Type mismatch: cannot convert from new Coercing(){} to GraphQLScalarType"

This project is available here : https://github.com/graphql-java/graphql-java.git

It's too bad, I'd like to contribute to graphql, but I need my prefered IDE...

Notes : 
1) I'm using a windows 7 laptop, with 64 bits JDKs.
2) the project properly builds with gradlew started on the command line.
3) the gradle eclipse plugin doesn't add the ./build/generated-src/antlr/main source folder. It must be added manually.

Regards
Etienne

**Comment by eric-milles** [comment]
@etienne-sf Could you point out the file and line of each of these?  I'd like to browse the source a bit on github before trying to import and build the whole project.

**Comment by eric-milles** [comment]
If you want eclipse to run the antlr build steps, that can be achieved.  It is not part of the build script right now and so there is no way for buildship/gradle to know to add an eclipse source folder.

For "The method toMixedCase cannot be declared static...", just remove the static modifier.  Static members of anonymous inner types don't make a whole lot of sense.

For "Type mismatch: cannot convert from new Coercing(){} to GraphQLScalarType" I need to do some more investigation.  I think the JDT model that is built up for fields and anonymous inner classes is breaking down in this case.  You can assign "new Coercing()..." to a field and pass that to the GraphQLScalarType constructor to get the error to stop.

**Comment by etienne-sf** [comment]
Hello, thanks for this response.

You'll find below the detailed way to reproduce it (but I guess you already did).
And the list of errors, as requested.

(I'll try the workaround you explain)

You said "no way for buildship/gradle to know to add an eclipse source folder".
It's too bad ! I'll stay with maven for my own projects, in this case.

Steps to reproduce:
- jdk11, v11.0.1, from Oracle, installed as a zip
- Use of eclipse installer (simple mode)
- Install "Eclipse IDE for Java Developers", based on jdk11
- Once installed, open the marketplace, type groovy, and install "Groovy Development Tools 3.3.0.SNAPSHOT" (oups, I didn't realise it was a snapshot)
- Select only "Eclipse Groovy Development Tools"
	Not the 2.5 compiler (which generates error when restarting eclipse) and not the m2e plugin, as graphql-java is a gradle project
- Clone the graphql-java project:  https://github.com/graphql-java/graphql-java.git (only the master branch)
    Don't select the "Import all existing Eclipse projects after clone finishes"
- Import a project, select "Existing gradle project"
	Let "gradle wrapper", and click finish
- This leads to tons of error (ok, 74). You need to properly build the project, then add the generated source folder to the project :
    In the "Gradle Task view" (below the source window), Run the Build / build Gradle Task
    Right-click on the project name
	Click on "Configure buildpath"
	In Source, click on "Add folder". 
	Add the "Build/generated-src/antlr/main" folder

The number of errors drops to 5 errors within groovy files.
Which is my issue here.

A direct build on the command line generates no issue at all.


The error are :
Description	Resource	Path	Location	Type
The method toMixedCase cannot be declared static; static methods can only be declared in a static or top level type	SchemaGeneratorDirectiveHelperTest.groovy	/graphql-java/src/test/groovy/graphql/schema/idl	line 251	Java Problem
Type mismatch: cannot convert from new Coercing(){} to GraphQLScalarType	CoercingTest.groovy	/graphql-java/src/test/groovy/graphql/schema	line 20	Java Problem
Type mismatch: cannot convert from new Coercing(){} to GraphQLScalarType	Issue938.groovy	/graphql-java/src/test/groovy/graphql	line 16	Java Problem
Type mismatch: cannot convert from new Coercing(){} to GraphQLScalarType	SchemaDiffTest.groovy	/graphql-java/src/test/groovy/graphql/schema/diff	line 38	Java Problem
Type mismatch: cannot convert from new Coercing(){} to GraphQLScalarType	SchemaPrinterTest.groovy	/graphql-java/src/test/groovy/graphql/schema/idl	line 52	Java Problem


Etienne

**Comment by etienne-sf** [comment]
By the way, your workaround works really nicely !

I should have read you message, before putting all the above details together !
:(

**Comment by eric-milles** [comment]
As the project is, buildship can't see the antlr steps.  That's not to say you can make edits to build.gradle so that it can inform eclipse/buildship on how to 1) generate the parser sources from the grammar(s) and 2) add the generated source location as a source folder (or generate into `src/main/antlr`).

I'd suggest looking into this so the project is easier to work with for others.  Also for me the build script choked right away because I don't have command-line git.  That could easily be solved as well in build.gradle.

Let me know if you're interested in making any changes to build.gradle and sending them to the project as a PR.  I'd be happy to help determine what changes to make and test them out now that I have the project imported.

**Comment by etienne-sf** [comment]
Hi,

  I created this issue [https://github.com/eclipse/buildship/issues/853](https://github.com/eclipse/buildship/issues/853) for the eclipse graddle plugin, about the fact that it doesn't the folder to the eclipse projet. But I had no answer there.
  And yes, it would be nice to make this easier to use.

But entering graphql add a lot of new technolgies for me. I'll start with a maven plugin for graphql.
;-)
So I won't add graddle to this list.
At least, not yet.

And this last discussion is a little out of topic, as it is not linked to groovy. 


Thanks to your workaround, I can start working on it.

Etienne

**Comment by eric-milles** [comment]
Test created for Coercing anon. inner class errors.  Will try to fix this case soon.

```java
    @Test
    public void testAnonymousInnerClass11() {
        runConformTest(new String[] {
            "A.groovy",
            "class A {" +
            // field with anon. inner initializer argument:
            "  C cee = new C(1, '2', new Runnable() {\n" +
            "    void run() {\n" +
            "      println 'hi!'\n" +
            "    }\n" +
            "  })\n" +
            "  static main(args) {\n" +
            "    new A()\n" +
            "  }\n" +
            "}\n",

            "C.groovy",
            "class C {\n" +
            "  C(int one, String two, Runnable three) {\n" +
            "    three.run()\n" +
            "  }\n" +
            "}\n",
        },
        "hi!");

        checkGCUDeclaration("A.groovy",
            "public class A {\n" +
            "  private C cee = new C(1, \"2\", new Runnable() {\n" +
            "    x() {\n" +
            "      super();\n" +
            "    }\n" +
            "    public void run() {\n" +
            "    }\n" +
            "  });\n" +
            "  public A() {\n" +
            "  }\n" +
            "  public static void main(java.lang.String... args) {\n" +
            "  }\n" +
            "}\n");
    }
```

**Comment by eric-milles** [comment]
The `Coercing` anonymous inner classes in the tests should not require a workaround any more.
