### ISSUE TITLE
Make update sites compatible with https

### ISSUE THREAD

**Issue by nedtwigg** [groovy/groovy-eclipse#821]
Any chance the [update sites](https://github.com/groovy/groovy-eclipse/wiki) can be made HTTPS-compatible?

When I try to use them as https I get this error:

```
Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/e4.8/artifacts.xml.
    ...
Caused by: javax.net.ssl.SSLException: Certificate for <dist.springsource.org> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:165)
```

This is a blocker for us at https://github.com/diffplug/spotless/issues/360

**Comment by eric-milles** [comment]
#119

**Comment by eric-milles** [comment]
I have forwarded your request on to Pivotal.  They manage the Amazon S3 storage that hosts the update sites.

If you don't want to interact with the update sites directly (over http), you can download a release update site archive and create a local update site that you can link your Gradle/Maven build to.

**Comment by nedtwigg** [comment]
Sorry for dup, I thought I searched issues, dunno how I missed it.

**Comment by sorin-costea** [comment]
Changing the update site url to http does not work, the Eclipse marketplace doesn't work either... it only works downloading it by hand like in the 80s.
