### ISSUE TITLE
spock data-table formatted incorrectly

### ISSUE THREAD

**Issue by AnEmortalKid** [groovy/groovy-eclipse#822]
Might be related to the way data-tables are dealt with #812 

Given this test:

```groovy
import spock.lang.*

class TestSpec extends Specification {

	@Unroll
	def "Test downstream build"() {

		given:
		println 'nothing'

		when:
		println 'something'

		then:
		println 'nothing #DOWNSTREAM_STEP'

		where:

		DOWNSTREAM                                                                      |DOWNSTREAM_STEP
		[[job: "../some-job/some-branch",parameters: []]] | true
		[
			[job: "../some-job/master", parameters: [[stuff: "blah"]], wait: false ]] | true
		[
			[job: "../some-job/dev"]] | true
		[
			[job: "../some-job/master"],
			[job: "../another-one/master"]] | true
		[
			[job: "     ", parameters: "param", wait: true]] | false
		[
			[job: "", wait: true]] | false
		null                                                                            | false
	}
}
```

The formatter will mangle the second part of the data-table into a new line:

```groovy
import spock.lang.*

class TestSpec extends Specification {

	@Unroll
	def "Test downstream build"() {

		given:
		println 'nothing'

		when:
		println 'something'

		then:
		println 'nothing #DOWNSTREAM_STEP'

		where:

		DOWNSTREAM                                                                      |DOWNSTREAM_STEP
		[
			[job: "../some-job/some-branch",parameters: []]]
		| true
		[
			[job: "../some-job/master", parameters: [[stuff: "blah"]], wait: false ]]
		| true
		[
			[job: "../some-job/dev"]]
		| true
		[
			[job: "../some-job/master"],
			[job: "../another-one/master"]]
		| true
		[
			[job: "     ", parameters: "param", wait: true]]
		| false
		[[job: "", wait: true]]| false
		null                                                                            | false
	}
}

```

This causes things to not compile. I landed here from a bug I raised with spotless: https://github.com/diffplug/spotless/issues/357

I've gotten around this by writing a `custom` formatter for spotless that basically re-stitches the lines back together (if a line starts with "|" after seeing a `where` clause)

**Comment by eric-milles** [comment]
I will take a quick look at it.  The formatter has not received much attention in the past few years.  I'm certainly open to helping someone get a workspace set up so they can make regular contributions in that space.

What is the desired outcome of formatting the data table example?

**Comment by AnEmortalKid** [comment]
I would settle for either smushing it all into one line:

```
[[job: "../some-job/some-branch",parameters: []]] | true
```

Or maybe:

```
[
  [
    job: "../some-job",
    parameters: []
   ]
] | true
```

As long as there's no lines starting with `|` and it compiles I could go either way. My work around just moves the "| true" back on to the previous line.

**Comment by eric-milles** [comment]
Here is my before state:
![image](https://user-images.githubusercontent.com/18193802/53101533-94d00680-34ef-11e9-836a-065ddec60307.png)


And after formatting (no code changes), I am left with this:
![image](https://user-images.githubusercontent.com/18193802/53101606-bc26d380-34ef-11e9-96f5-f042f9beda62.png)

**Comment by AnEmortalKid** [comment]
Odd! I can gather all the versions of the stuff I have for more info.

That formatting looks exactly like what I want! Maybe i just don't have the right formatter...

**Comment by eric-milles** [comment]
I'm curious why the parser thinks that "[...]\n | true" is not a bitwise-or expression.  I'm aware of "'string' \n + ' more'" and "1\t + 2" not parsing as we would expect.  But "|" is not a unary operator.

**Comment by AnEmortalKid** [comment]
> "[...]\n | true" is not a bitwise-or expression
It might be aware that it's in a `where` chunk... no idea. 

Any versions I can snag to compare formatters? (not sure why yours formats that way but mine doesnt)

**Comment by eric-milles** [comment]
To the Groovy parser, there is no awareness of Spock.  Spock smarts are applied well after parsing and conversion.  "a | b" alone on a line should produce an expression statement with an embedded binary expression that has the operator "|" which is bitwise-or.

Not sure how Spock implements data tables, but in terms of the formatter, that is immaterial.

**Comment by eric-milles** [comment]
You mentioned above that spotless is how you are formatting.  How does that tool work?  What versions of Groovy and Groovy-Eclipse are used?

**Comment by eric-milles** [comment]
You can follow and upvote the root cause of your compiler errors here: https://issues.apache.org/jira/browse/GROOVY-9004

**Comment by AnEmortalKid** [comment]
> How does that tool work? What versions of Groovy and Groovy-Eclipse are used?

Spotless calls the groovy eclipse formatter + some custom steps:

The version used is 3.0.0 (at the moment): https://github.com/diffplug/spotless/blob/master/lib-extra/src/main/resources/com/diffplug/spotless/extra/groovy_eclipse_formatter/v4.8.1.lockfile

properties: https://github.com/diffplug/spotless/blob/master/testlib/src/main/resources/groovy/greclipse/format/greclipse.properties

One of the maintainers tried with the latest release and the formatting still looked dodgy.

Eclipse plugins on my end:

![image](https://user-images.githubusercontent.com/3474369/53124261-89490380-3520-11e9-97c9-a55c1afeb5eb.png)

Version + Build:
```
Version: 2018-12 (4.10.0)
Build id: 20181214-0600
```

**Comment by eric-milles** [comment]
These seem like odd choices:
```
#Whether opening braces position shall be the next line.
#The default value is 'same'.
groovy.formatter.braces.start=next

#Whether closing braces position shall be the next line.
#The default value is 'next'.
groovy.formatter.braces.end=same
```

What I don't know is how is spotless actually calling the GDT formatter.  And is it using the patched Groovy runtime, which has many parser patches.

**Comment by eric-milles** [comment]
For reference, here are the parser patches for the antlr2 groovy parser (search for GRECLIPSE comments):

https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy24/src/org/codehaus/groovy/antlr/groovy.g
https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy24/src/org/codehaus/groovy/antlr/AntlrParserPlugin.java

Core groovy actually has line and column set incorrectly for binary expressions and a number of other expressions.  It only needed to be accurate enough for error messaging (aka compiler errors); the formatter requires a much greater degree of accuracy when trying to reposition tokens.
