### ISSUE TITLE
Request for update site archive

### ISSUE THREAD

**Issue by aroneous** [groovy/groovy-eclipse#829]
Not sure if a bug report is the best avenue for this, but I didn't immediately see a better one available:
Would you consider providing ZIP archives of your update sites, to enable offline installation? Since they're hosted on S3, which doesn't support directory listings, they're tough to download with `wget` or the like. ZIP archives would be very helpful for those of us working in Enterprise organizations with, let's say, a reluctance to let developers point Eclipse at an arbitrary update site URL.

Thanks for the great work on the plugin.

**Comment by eric-milles** [comment]
At the end of each release notes wiki page there are links to the update site archives.

**Comment by eric-milles** [comment]
https://github.com/groovy/groovy-eclipse/wiki/3.2.0-Release-Notes#update-sites

**Comment by aroneous** [comment]
Thanks!! My Mom always said I wasn't very good at looking for things...
