### ISSUE TITLE
Version 3.3.0.xx-201903201444-e1903 breaks Spock test framework

### ISSUE THREAD

**Issue by sobimibos** [groovy/groovy-eclipse#849]
The newest version 3.3.0.xx-201903201444-e1903 breaks the Spock test framework. It's not possible to run Spock tests in the Eclipse IDE anymore. They always fail with the following exception:

org.spockframework.runtime.InvalidSpecException: Specification 'xxx' was not compiled properly (Spock AST transform was not run); try to do a clean build

With the previous version 3.3.0.xx-201903181225-e48 Spock tests run fine.

**Comment by eric-milles** [comment]
Did you also switch from Eclipse Photon to Eclipse 2019-03?  Or did you try and apply to 2019-03 patch onto photon?

**Comment by sobimibos** [comment]
Both. First I upgraded 2018-12 and recognized the problem. Then I restored the older version to verify. that it is a new problem. Then I made a fresh install of 2019-03 and the problem is there again.

**Comment by eric-milles** [comment]
Do you still have your Eclipse Photon install?  If updated to latest snapshot, do spock tests run or fail?

If you have updated to 2018-12, then you need to use the 2018-12 patch.  If you have updated to 2019-03, then you need to use the 2019-03 patch.  I can't tell what state you are in from your descriptions.

**Comment by sobimibos** [comment]
![grafik](https://user-images.githubusercontent.com/18039078/54763999-40f03480-4bf7-11e9-90bd-d9699e302fb2.png)

These are the versions of groovy in the 2019-03 installation, where the the Spock tests do not run.

**Comment by eric-milles** [comment]
If you open the Groovy Console within the Console view and recompile, do you see any errors?  Any errors in the Error Log view?

**Comment by hsudbrock** [comment]
@eric-milles I am having the same issue as @sobimibos ; I do not see any errors in the `Groovy Event Trace Console` (or did you refer to another console?).

I see that AST transforms are in fact applied, but (looking at the names of the AST transforms) I cannot see any for spock. The following AST transforms are applied for my example (both multiple times):
* `AST Transforms : 17:26:30 Global transform groovy.grape.GrabAnnotationTransformation applied to <omitted-class-name>.groovy in 0ms`
* `AST Transforms : 17:26:51 Global transform org.codehaus.groovy.ast.builder.AstBuilderTransformation applied to <omitted-class-name>.groovy in 1ms`

**Comment by eric-milles** [comment]
Can you update to the latest snapshot and retest?

**Comment by hsudbrock** [comment]
I updated to the following version, but the problem remains:

![image](https://user-images.githubusercontent.com/5314568/54810882-7d6b7100-4c87-11e9-9940-419aa58f1fae.png)

**Comment by eric-milles** [comment]
I tried a basic project with spock tests and they ran successfully.  I'm not sure what is different about your project.  Is it an open-source project that I could download and try out?

**Comment by hsudbrock** [comment]
No, it is closed source. My best guess currently is that it somehow relates to the `spock` jar not being on the `Transform classpath`, for whatever reason. (The class path of the project is generated by [bndtools](https://bndtools.org/) - maybe something has changed there. My plan is to investigate this a little further.

**Comment by sobimibos** [comment]
After some investigation it turned out to be caused by interaction of the newest versions of bndtools and groovy development tools. An explicit import of the spock resources (which was not needed before) fixed the problem. So this issue can be closed. Thanks a lot for your help @eric-milles.
