### ISSUE TITLE
Improve code assist in field declaration

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#862]
Consider the following:

```groovy
package test50

class Test50 {
	
	String foo
	
	List|
}
```

Invoke code assist at "|". This is what I see:
- the most obvious suggestions (those that start with List, or even exact matches) are shown below other suggestions that apparently are not relevant; this class is small, so it's not a big issue, a normal class has many fields and methods, so relevant suggestions are lost; this is very annoying
- if I choose "java.awt.List" and hit enter, no import declaration is added

Consider this slight variation:

```groovy
package test50

class Test50 {
	
	String foo
	
	TreeNode|
}
```

and suppose I want to choose `javax.swing.tree.TreeNode`: the fully qualified class name is inserted, instead of keeping just `TreeNode` and adding a new import. This happens although I have the Code Assist option "Add import instead of qualified name" checked.

**Comment by eric-milles** [comment]
There is definitely a bug in `GroovyProposalTypeSearchRequestor`.  This block tries to determine if an import (or qualifier) is required.  Since it has already seen "java.util.List", it fails to make a correct determination for "java.awt.List".

```java
                // check for star import if expression is not qualified and type name not seen already
                if (!qualified && onDemandImports != null && !onDemandFound.containsKey(simpleTypeName)) {
                    char[] qualifier = packageName;
                    if (enclosingTypeNames != null && enclosingTypeNames.length > 0) {
                        qualifier = CharOperation.concatWith(packageName, type.enclosingTypeNames, '.');
                    }

                    for (char[] importName : onDemandImports) {
                        if (CharOperation.equals(qualifier, importName)) {
                            onDemandFound.put(simpleTypeName, type);
                            continue next;
                        }
                    }

                    type.mustBeQualified = true;
                }
                proposals.add(proposeType(type));
            }
```

**Comment by eric-milles** [comment]
The build server went out of service.  I'll update when a new snapshot is available,

**Comment by eric-milles** [comment]
Import/qualifier insertion is ready to test.

**Comment by mauromol** [comment]
Now if I choose the suggestion for "java.awt.List" the editor inserts the fully qualified `java.awt.List`. However I still don't understand why it inserts the fully qualified name if I have the option "Add import instead of qualified name" checked. In all the other parts (for instance if I'm defining a local variable) Greclipse correctly adds the import and keeps the non-qualified name, instead.

Also, please please have a look at the suggestion relevance issue...

**Comment by eric-milles** [comment]
I'm not sure why you get the fully-qualified name.  I get the import in my testing.

The relevance is part of #674.  Types and packages get a very low base relevance score.  So the boosting for prefix match does not impact them much.

**Comment by mauromol** [comment]
> I'm not sure why you get the fully-qualified name. I get the import in my testing.

I don't know. As I said, it's the only place where this happens. And it happens on at least two different workspaces that I don't think have anything in common.

> The relevance is part of #674. Types and packages get a very low base relevance score. So the boosting for prefix match does not impact them much.

Ok, but consider that, in this specific case, there are some aggravating factors:
- it's a place where (most probably) only types make sense (other suggestions are related to new code generation)
- if I really want to have new code generation at this point, there should be some relation with what I have typed (why "getFoo()"/"setFoo()" are suggested after I typed "List"?? They have nothing in common)
- many of the other suggestions given are simply wrong and don't do anything; see this example:

![immagine](https://user-images.githubusercontent.com/1742494/55079280-222cea80-509c-11e9-91eb-97c16f4f12a7.png)

`getList()`/`setList()` are simply wrong. And even if I wanted to any reason to select `getFoo()`/`setFoo()`, after I press Enter nothing occurs (the suggestion list simply gets closed)

- if I type "Lis", then Ctrl+Space, then add "t", at this point the suggestion list is coherent (all irrelevant/wrong suggestions are removed); yes, the order of suggestions is still to be improved (as described in #674) and yes, suggestions are not recomputed (as I outlined in #411), but these are separate issues

So I think there are some additional problems here besides the need for a better suggestion order/update.

**Comment by eric-milles** [comment]
True, that's a bunch of poor suggestions.  I think parser recovery is creating a field with name "List" so that content assist works at this location.  I can look into the filtering for the new method proposals; they all seem like they should be filtered in this case.

**Comment by eric-milles** [comment]
Ready for re-test.

**Comment by mauromol** [comment]
Hi Eric, I tried to update twice today but Eclipse couldn't find any Greclipse update. Mine installed is 3.3.0.xx-201903270059-e1812.

**Comment by eric-milles** [comment]
https://dist.springsource.org/snapshot/GRECLIPSE/e4.10/org.codehaus.groovy-3.3.0.xx-201903271540-e1812-updatesite.zip

**Comment by mauromol** [comment]
Ok, I can use this ZIP update site, but the online update site is not updated yet... Just to let you know.

**Comment by mauromol** [comment]
Ok, I had to change the update site URL from http to https... Is it normal? It's the first time this happens...

**Comment by mauromol** [comment]
I verified with 3.3.0.xx-201903271540-e1812 that irrelevant suggestions are not shown any more, thank you! Now the only issue is sorting.

Though, I still have the problem that the suggestion is inserted fully qualified while it shouldn't. I'm pretty sure this problem started to happen recently.

![immagine](https://user-images.githubusercontent.com/1742494/55229051-2da71f80-521c-11e9-9656-c6d8fa254571.png)

**Comment by mauromol** [comment]
Any idea of what I could investigate to understand why I'm getting fully qualified class names in field declarations?

**Comment by eric-milles** [comment]
You can try changing each content assist option.  Also, do you have any Type Filters or Static Import Favorites configured?

Does it make a difference if you add a newline after your class closing brace?

**Comment by mauromol** [comment]
I have no type filters, while static import favourites are the following ones:

![immagine](https://user-images.githubusercontent.com/1742494/55310729-7c91c680-5461-11e9-808f-567fb3cc60ab.png)

I already tried each content assist option with no luck, even tried to disable auto activation.
In particular "Add import instead of..." or "User static imports..." seem not to have any effect.

Doesn't code inspection reveal any clue of which circumstances can cause the type FQN to be inserted instead of the import, for this specific case?

Also tried to add a trailing newline to the file (remembering a similar case in the past), but again I still get the FQN to be inserted.

**Comment by eric-milles** [comment]
> Doesn't code inspection reveal any clue of which circumstances can cause the type FQN to be inserted instead of the import, for this specific case?

The completion object either gets created with completion "List" (import present) or "java.awt.List".  JDT takes over after this and either inserts a fully-qualified name or the name plus a supporting import.

This is what the proposal creation looks like in `GroovyProposalTypeSearchRequestor` (assume `type.mustBeQualified` is true):
```java
    private ICompletionProposal proposeType(AcceptedType type) {
        int completionOffset = (isImport || type.mustBeQualified ? offset : context.completionLocation - context.getPerceivedCompletionExpression().length());

        GroovyCompletionProposal proposal = createProposal(CompletionProposal.TYPE_REF, completionOffset);
        proposal.setAccessibility(type.accessibility);
        proposal.setCompletion(!type.mustBeQualified ? type.simpleTypeName : CharOperation.replaceOnCopy(type.fullyQualifiedName, '$', '.'));
        proposal.setDeclarationSignature(type.packageName);
        proposal.setFlags(type.modifiers);
        proposal.setPackageName(type.packageName);
        proposal.setRelevance(computeRelevanceForTypeProposal(type.fullyQualifiedName, type.accessibility, type.modifiers));
        proposal.setReplaceRange(completionOffset, context.completionLocation);
        proposal.setSignature(Signature.createCharArrayTypeSignature(type.fullyQualifiedName, true));
        proposal.setTokenRange(completionOffset, context.completionEnd);
        proposal.setTypeName(type.qualifiedTypeName);

        if (type.qualifiedTypeName.length != type.simpleTypeName.length) {
            char[] outerTypeName = CharOperation.subarray(type.qualifiedTypeName, 0, type.qualifiedTypeName.length - type.simpleTypeName.length - 1);
            proposal.setDeclarationSignature(Signature.createCharArrayTypeSignature(CharOperation.concat(type.packageName, outerTypeName, '.'), true));
            proposal.setDeclarationPackageName(type.packageName);
            proposal.setDeclarationTypeName(outerTypeName);
        }

        AbstractJavaCompletionProposal javaProposal;
        if (isImport) {
            String fullyQualifiedName = String.valueOf(type.fullyQualifiedName).replace('$', '.'); // as it would appear in an import statement
            javaProposal = new JavaTypeCompletionProposal(fullyQualifiedName, null, completionOffset, context.completionLocation - completionOffset,
                ProposalUtils.getImage(proposal), ProposalUtils.createDisplayString(proposal), proposal.getRelevance(), fullyQualifiedName, javaContext);
        } else {
            javaProposal = new LazyJavaTypeCompletionProposal(proposal, javaContext);

            // check for required supporting type reference
            if (type.qualifiedTypeName.length != type.simpleTypeName.length) {
                int lastDotIndex = context.fullCompletionExpression.lastIndexOf('.');
                if (lastDotIndex > 0 && !completionExpression.startsWith(String.valueOf(firstSegment(type.packageName, '.')) + '.')) {
                    char[] typeName = CharOperation.subarray(type.qualifiedTypeName, 0, CharOperation.lastIndexOf('$', type.qualifiedTypeName));

                    // expression is partially-qualified; check type name availability
                    char[][] parts = qualifierAndSimpleTypeName(type.packageName, typeName);
                    if (!isImported(parts[0], parts[1])) {
                        GroovyCompletionProposal typeProposal = createProposal(CompletionProposal.TYPE_REF, offset);
                        typeProposal.setCompletion(CharOperation.concat(type.packageName, typeName, '.'));
                        typeProposal.setSignature(Signature.createCharArrayTypeSignature(typeProposal.getCompletion(), true));
                        typeProposal.setReplaceRange(offset, context.completionLocation - (context.fullCompletionExpression.length() - lastDotIndex));

                        proposal.setRequiredProposals(new CompletionProposal[] {typeProposal});
                    }
                }
                if (lastDotIndex > 0) {
                    // boost inner types that satisfy qualifier above DGMs
                    proposal.setRelevance(Relevance.MEDIUM.getRelevance());
                }
            }

            if (context.location == ContentAssistLocation.EXCEPTIONS && isThrowableType((IType) javaProposal.getJavaElement())) {
                proposal.setRelevance(proposal.getRelevance() + 50);
            }
        }

        javaProposal.setTriggerCharacters(ProposalUtils.TYPE_TRIGGERS);
        javaProposal.setRelevance(proposal.getRelevance());
        return javaProposal;
    }
```

If `isImport` is true, it may be forcing the qualification.  Not sure why this would be true, but I suppose its possible...

**Comment by mauromol** [comment]
If I have to make a guess, "isImport" is `true` when you're typing an import declaration at the beginning of you Java file...
Anyway, I'm going to make other attempts to reproduce this and open a new issue.
