### ISSUE TITLE
Error installing the m2e in Eclipse 2019-03 (4.11)

### ISSUE THREAD

**Issue by digulla** [groovy/groovy-eclipse#869]
When trying to install the m2e integration, I get this error:

```
An error occurred while collecting items to be installed
session context was:(profile=_home_swissquant.local_digulla_tools_jee-latest-released_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.codehaus.groovy.m2eclipse,3.4.0.v201904051949-e1812
No repository found containing: org.eclipse.update.feature,org.codehaus.groovy.m2eclipse.feature,3.4.0.v201904051949-e1812
```

even though the plugin is listed in the p2 repos https://dist.springsource.org/snapshot/GRECLIPSE/e4.10 amd https://dist.springsource.org/snapshot/GRECLIPSE/e4.11 **with the same version**.

There are no other update sites listed in Eclipse which contain any Groovy-related plugins.

The Groovy Dev Tools are installed and work as expected. Since I'm one of those people with the weird registry error, I've deinstalled the 2.5 compiler and only have the 2.4 compiler installed.

It's also not visible on the Eclipse Marketplace (I searched for the name from the feature.properties: `Groovy-Eclipse M2E integration`).

**Comment by eric-milles** [comment]
You may need to restart your eclipse to get fresh metadata.  The latest snapshot is from April 9th at the moment.

On the marketplace, it is under Groovy Development Tools.  I may need to add a tag or two so that it appears in searches.

**Comment by digulla** [comment]
"Check for Updates" worked for me, no restart was necessary.

My main issue was to figure out how to get the Marketplace to allow me to select the additional m2e package which I've had omitted the first time around.

For documentation purposes:

1. Search for "groovy"
2. Switch to the "Installed" tab
3. Find the "Groovy Development Tools"
4. Select "Change" in the combobox
5. Select the m2e integration
1. "Confirm", etc.
