### ISSUE TITLE
Installation fails with Could not find https://dist.springsource.org/release/GRECLIPSE/e4.11

### ISSUE THREAD

**Issue by kodstark** [groovy/groovy-eclipse#870]
Release repositories seem not work for groovy plugins. I follow installation steps in [wiki](https://github.com/groovy/groovy-eclipse/wiki#how-to-install) and can add snapshot repository like [snapshot/GRECLIPSE/e4.11](https://dist.springsource.org/snapshot/GRECLIPSE/e4.11) but adding [release/GRECLIPSE/e4.11](https://dist.springsource.org/release/GRECLIPSE/e4.11) fails with error "Couldn't not find https://dist.springsource.org/release/GRECLIPSE/e4.11". I tried also other release repositories with the same result.

It is hard to analyze what is wrong because unfortunately Spring repositories are not browseable.

I am running eclipse-jee-2019-03 behind proxy with httpclient disabled. 

Disabling httpclient in eclipse.ini:
```
-vmargs
-Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclient4
```

Thank you

**Comment by eric-milles** [comment]
Since you are altering the http client behavior, I'm guessing it is not handling the redirect properly.  You can use a direct update site line (from bottom of release notes) https://dist.springsource.org/release/GRECLIPSE/3.3.0/e4.11 or you can download an update site archive.

**Comment by kodstark** [comment]
@eric-milles Hi - direct updatesite is working behind NTLM proxy with JDK client.

**Comment by AlanKavo92** [comment]
Hi - I am having a similar issue with e4.13

@eric-milles is your link meant to display "NoSuchKey"? https://dist.springsource.org/release/GRECLIPSE/3.3.0/e4.11

**Comment by eric-milles** [comment]
Snapshot sites may update daily when frequent changes are made to the codebase.  Eclipse caches update site metadata.  So if you want to check for updates, I recommend doing so after restarting.

@AlanKavo92 The update sites are stored on Amazon S3 and it does not provide directory browsing.  "https://dist.springsource.org/release/GRECLIPSE/3.3.0/e4.11" does not refer to a specific file, so S3 returns its version of a 404 "not found" which is "NoSuchKey".  You should be able to retrieve "https://dist.springsource.org/release/GRECLIPSE/e4.11/compositeContent.xml" from a "composite" site (redirects to another update site) or "https://dist.springsource.org/release/GRECLIPSE/3.3.0/e4.11/artifacts.jar" from a typical update site to confirm it is still there.

**Comment by AlanKavo92** [comment]
@eric-milles thanks I'm downloading the update site archive now. I have created a new issue which may need to be investigated.
