### ISSUE TITLE
Static Type Checking on Map Iteration Shows Incorrect Compile Errors

### ISSUE THREAD

**Issue by ssadedin** [groovy/groovy-eclipse#872]
In the last few days my existing code is suddenly showing compile errors whenever I have enabled static compilation and a Map is being iterated. For example:

![image](https://user-images.githubusercontent.com/138868/56092205-29595280-5efc-11e9-94ca-02fdf1c1f9a3.png)

This code results in this error:

```
Expected parameter of type java.util.Map$Entry <java.lang.Object, java.lang.Object> but got java.util.Map$Entry <String, Object>
```
This is happening across many different instances of iterating over Maps, it is occurring with both the two argument closure and single argument closure. The same code compiles successfully when compiled with `groovyc`.

The only way I seem to be able to get things to work is to remove iteration using closures from the code.

I am running this version of groovy-eclipse:

```
  Eclipse Groovy Development Tools	3.4.0.v201904131343-e1903	org.codehaus.groovy.eclipse.feature.feature.group	Pivotal Software, Inc.
```

I am using the 2.4 groovy compiler.

**Comment by eric-milles** [comment]
This has to do with #863 and the linked Groovy bugs.  The way STC behaves in this situation is not very intuitive IMO due to [flow typing](http://groovy-lang.org/semantics.html#section-flow-typing).

In the statement `Map<String,Object> props = (Map)ois.readObject()`, Groovy actually uses the RHS type, which is `Map<Object, Object>`.  This causes many developers to insert closure parameter types and typecasts, as you have done in the subsequent code.

For best compatibility with current and future STC and compilers/editors, I suggest writing your example like this:
```groovy
def props = (Map<String, Object>) ois.readObject()
props.each { entry ->
  setProperty(entry.key, entry.value)
}
```
In this form, the type for `props` and `entry` is controlled by a single type choice.

**Comment by ssadedin** [comment]
Thanks for the followup! I will read those links a bit more in detail, but just wanted to relate that I'm not sure this is correct behavior as even with your suggestions, I am still getting the error - here is a contrived example:

```groovy
    @CompileStatic
    void compileBug() {
        Map m = [foo: 'cat', bar: 'hat']
        def x = (Map<String,String>)m
        x.each { e ->
            println(e.value)
        }
    }
```

In this case, the error is:

```
Groovy:[Static type checking] - Cannot call <K,V> java.util.Map <String, String>#each(groovy.lang.Closure) with arguments [groovy.lang.Closure] 	
```

As I mentioned before - this all used to compile fine in Eclipse until some recent update, and it still compiles fine with groovyc. I would also tentatively note it seems to work ok with the 2.5 compiler (unfortunately, I'm stuck using 2.4 for this project). Could it be a regression related to the changes to handle 2.4 in #863?

**Comment by ssadedin** [comment]
Apologies, one more update: I found the following does work -

```groovy
    @CompileStatic
    private void compileBug() {
        Map m = [foo: 'cat', bar: 'hat']
        def x = (Map<String,Object>)m // <== instead of Map<String,String>
        x.each { e ->
            println(e.value)
        }
    }
```

ie: the trouble seems to be coming from having anything other than Object as the second generic type parameter. The first type parameter seems to be correctly inferred and respected inside the closure.

**Comment by eric-milles** [comment]
I am not seeing the original issue for the current 2.4.  However I am seeing your second issue and will have a look.  The message seems very strange; not sure exactly what it's describing.

![image](https://user-images.githubusercontent.com/18193802/56143922-0e6ff800-5f67-11e9-9caf-b4016392ed50.png)

**Comment by eric-milles** [comment]
There is definitely something strange going on here because the inferred type of the `entry` parameter changes:
```groovy
@CompileStatic
void meth() {
  def map = [foo: 'cat', bar: 'hat']
  map.each { entry -> // entry seen as Map<String,String>
    println entry.value // entry seen as Map<String,Object>
  }
}
```

**Comment by eric-milles** [comment]
Compatibility check of the DGM is breaking down because typeof(map) is `LinkedHashMap<String,String>` and typeof(1st param of each) is `Map<String, Object>`.

**Comment by eric-milles** [comment]
It appears the extension method cache is getting polluted somehow.

**Comment by eric-milles** [comment]
It looks like any DGM that uses `@ClosureParams(MapEntryOrKeyValue.class)` and possibly others are being modified in the extension method cache.  I have a fix for this testing now.

**Comment by eric-milles** [comment]
ready to test

**Comment by ssadedin** [comment]
Fantastic - thank you for working on it! 

Let me know if anything I can do to help / test / etc.

**Comment by eric-milles** [comment]
Yes, please update to the latest snapshot and try out your source/project with errors.

**Comment by ssadedin** [comment]
It works!  All the errors have gone away.  Thanks so much!
