### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by cstamas** [groovy/groovy-eclipse#899]
$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 11.0.3, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_HU, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"

maven-compiler-plugin: 3.8.0
groovy:2.5.7
groovy-eclipse-compiler: 3.3.0-01
groovy-eclipse-batch: 2.5.7-01

```
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ XXX ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/XXX/org/codehaus/groovy/groovy-eclipse-batch/2.5.7-01/groovy-eclipse-batch-2.5.7-01.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by cstamas** [comment]
Just found https://issues.apache.org/jira/browse/GROOVY-8339 but Groovy 2.5.x is not listed as "fixed in"? Am a bit puzzled.

**Comment by eric-milles** [comment]
Here are the release notes.
http://groovy-lang.org/changelogs/changelog-2.5.7.html
http://groovy-lang.org/changelogs/changelog-3.0.0-beta-1.html

**Comment by cstamas** [comment]
JDK9, 10 and 11 are "just" annoying with emitting that warning, but things are working. According to comments in GROOVY-8339, while it can be turned off (there are some hacks, not applicable in all cases), but "I'd just ignore the errors for now."

**Comment by pieroribeiro** [comment]
Error on installation of Jenkins in Debian 11 (bullseye):

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/var/cache/jenkins/war/WEB-INF/lib/groovy-al>
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

What do I do? I've tried everything...

**Comment by Annaanil** [comment]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/var/cache/jenkins/war/WEB-INF/lib/groovy-al>
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

While i was trying to do jenkins im getting this error please help me.

**Comment by eric-milles** [comment]
These are only warnings.  Groovy 3 and beyond have eliminated most of these warnings.  Often for ones that remain, the code is referencing a private field in a context that would not normally provide access.

**Comment by Annaanil** [comment]
Thanks for your response, i need to do work how can i resolve this issue?

**Comment by eric-milles** [comment]
If your editor is not functioning properly, please open a new ticket with the necessary details and screenshot(s).

**Comment by Annaanil** [comment]
To whom I need send ticket?

**Comment by eric-milles** [comment]
ticket == GitHub Issue
