### ISSUE TITLE
Can't use maven dependency with scope test in groovy test sources

### ISSUE THREAD

**Issue by aurelien-baudet** [groovy/groovy-eclipse#900]
I use some dependencies in my tests defined in `src/test/groovy`.
The dependency are included with scope `test`:

```xml
<dependency>
  <groupId>org.spockframework</groupId>
  <artifactId>spock-core</artifactId>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>org.jsmpp</groupId>
  <artifactId>jsmpp</artifactId>
  <scope>test</scope>
</dependency>
```

Eclipse cannot find the dependency: `Groovy:unable to resolve class spock.lang.Specification`

When I remove the `<scope>test</scope>`, everything works fine in Groovy. But this is **not acceptable** because the test dependencies **must not** be dependencies of the final library.

Moreover, I only use Groovy for my tests (to use Spock framework). All sources are in Java. I also want to include `groovy-all` dependency with scope `test`. But when I do that, Eclipse reports an error on every Groovy file:
```
Multiple markers at this line
	- The type groovy.lang.GroovyObject cannot be resolved. It is indirectly referenced from required .class 
	 files
	- The type groovy.lang.MetaClass cannot be resolved. It is indirectly referenced from required .class files
```
The issue is the same, the test dependencies are not available in src/test/groovy as it should.

---
Eclipse version: Spring Tool Suite 4 (Eclipse 4.11)
Plugin version: 3.4.0
Groovy-Eclipse m2e installed 

groovy-eclipse-compiler configuration:
```xml
<plugins>
  <plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
      <compilerId>groovy-eclipse-compiler</compilerId>
      <includes>
        <include>**/*.java</include>
        <include>**/*.groovy</include>
      </includes>
      <excludes>
        <exclude>scripts/**</exclude>
      </excludes>
    </configuration>
    <dependencies>
      <dependency>
        <groupId>org.codehaus.groovy</groupId>
        <artifactId>groovy-eclipse-compiler</artifactId>
        <version>3.3.0-01</version>
      </dependency>
      <dependency>
        <groupId>org.codehaus.groovy</groupId>
        <artifactId>groovy-eclipse-batch</artifactId>
        <version>2.4.17-01</version>
      </dependency>
    </dependencies>
  </plugin>
</plugins>
```

For information, everything was working fine with gmavenplus, GGTS plugin (Groovy and Grails Tool Suite) and Maven by only including `gmavenplus-plugin` but GGTS is not compatible with Eclipse 4.11...

**Comment by eric-milles** [comment]
I believe this is because Spock comes with a global AST transform.  At the moment, there is no separation between main and test sources/libraries as far as global transforms are discovery and application is concerned.

If you want to use Groovy for tests only, you can define separate compilation for main and test as described in #799

**Comment by aurelien-baudet** [comment]
This doesn't work. The maven build is working but Eclipse compiler doesn't work as it doesn't include maven dependencies declared with `<scope>test</scope>`.

**Comment by eric-milles** [comment]
Sorry, I misunderstood that you were having maven build issues with groovy-eclipse-compiler.  Can your problem be summed up as: successful maven build imported into Eclipse IDE not building as intended due to separated main and test dependencies?

**Comment by aurelien-baudet** [comment]
Yes.

Is there any way to configure the plugin or the compiler to include test dependencies ?
Copying test dependencies to lib folder could work ?

**Comment by eric-milles** [comment]
I will try out this style of project when I get a bit of free time.  Eclipse is actually managing the dependencies as you have set, but the groovy compiler under that is over-reaching when inspecting the project classpath.  This happens in GroovyClassLoaderFactory, where I have a TODO for test classpath entries, which were added in Eclipse Photon.

After you have imported your project into Eclipse, you can manually edit the .classpath file to remove the "test" attribute from any entry you want to make available to main sources.  Just beware that a Maven reconfig will undo your changes, so I would lock the file after editing so you can know when Maven wants to rewrite it.

Here is a sample classpath entry that has a "test" attribute:
```xml
	<classpathentry kind="src" output="target/test-classes" path="src/test/groovy">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
```

If your item falls under the Maven Dependencies classpath container, you may need to remve the scope from the pom temporarily.

**Comment by eric-milles** [comment]
I have this sample project that uses Java for main sources and Groovy for test sources.  I am having no troubles in eclipse.  Can you take a look and see if your issue can be reproduced within this project?

[groovy-for-tests.zip](https://github.com/groovy/groovy-eclipse/files/3316833/groovy-for-tests.zip)

**Comment by aurelien-baudet** [comment]
I tried your project. I found the issue in my project.
There is an issue when refreshing project. To make it REALLY take into
account maven configuration with build-helper-maven-plugin and eclipse
compiler, I had to delete project from workspace, remove all eclipse files
(.settings, .classpath, .project) and re-import it and then update maven
project.
I also had to have the plugin build-helper-maven-plugin to add test
sources. However this is redundant with gmaven-plus plugin that already
adds test sources. It works by using both plugins together in Eclipse.
But when I run maven outside of Eclipse, build fails due to eclipse
compiler. The project that fails uses Spring Boot autoconfiguration and
some classes are not found...

So for the moment I see two options to make it work:
- create profile that is only activated in Eclipse that adds eclipse
compiler to maven
- manually configure my project in Eclipse by adding Groovy lib

**Comment by eric-milles** [comment]
I'm not sure I follow.  I'm not proposing changes to your project.  I'm just trying to understand your problem.  Can you share your project's POM so that I can get a better sense of your problem?

**Comment by aurelien-baudet** [comment]
Here is the POM without specific compiler that doesn't work in Eclipse:
https://github.com/groupe-sii/ogham/tree/develop

You can try on your own starting with develop branch:
1) running ./mvnw clean install outside of Eclipse works
2) Importing project in Eclipse generates compilation errors on ogham-core
project
3) If you add build-helper-maven-plugin and configure maven-compiler-plugin
to compile test sources
with <compilerId>groovy-eclipse-compiler</compilerId> in ogham parent pom,
Eclipse successfully compiles ogham-core project
4) now running ./mvnw clean install outside of Eclipse fails (on another
project)

So the solution I found is to use a profile dedicated to Eclipse. Here is
the POM with a specific profile for Eclipse that works both outside and
inside Eclipse: https://github.com/groupe-sii/ogham/tree/test/testing-tools

**Comment by eric-milles** [comment]
I was able to get it working with these changes:

1. Under `gmavenplus-plugin`, remove goal `compile` since you are not using Groovy in main sources.
1. Remove `org.eclipse.m2e:lifecycle-mapping` workaround so Groovy-Eclipse m2e configurator will run.
1. Add package statement to `/ogham-core/src/test/groovy/fr/sii/ogham/it/core/util/bean/SimpleBeanReadWrapperSpec.groovy`


![image](https://user-images.githubusercontent.com/18193802/60106072-2663b500-972a-11e9-8a83-1b6c4f2d1309.png)
