### ISSUE TITLE
Compiler behaviour mismatch between Greclipse and groovyc

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#904]
I think this is a bug in Groovy and hence I opened: https://issues.apache.org/jira/browse/GROOVY-9170

Anyway, Greclipse does not give any such error when I have the scenario described in the bug above, i.e.: a Groovy class with `@CompileStatic` which overrides `java.lang.Object.clone()` while keeping it `protected`.

**Comment by eric-milles** [comment]
Groovy-Eclipse builds/resolves ClassNode instances differently.  In this case, the representation of the declared methods of an interface is different.  I submitted a Pull Request that screens off non-interface methods from the covariant method check.
