### ISSUE TITLE
Springsource links down?

### ISSUE THREAD

**Issue by XeroAura** [groovy/groovy-eclipse#906]
I'm getting this in Eclipse when I try to download from the marketplace or by manual add of the repo link:

Unable to read repository at https://dist.springsource.org/snapshot/GRECLIPSE/e4.11/content.xml.
Certificate for <dist.springsource.org> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]

Are the packages still being hosted by springsource?

**Comment by eric-milles** [comment]
The snapshot site link works fine for me.  You may have caught it in the middle of a snapshot deployment.

![image](https://user-images.githubusercontent.com/18193802/59615586-61da0000-90e8-11e9-8cfa-f8e94128cff1.png)
