### ISSUE TITLE
Unable to run Groovy classes with a main as a Groovy script

### ISSUE THREAD

**Issue by dhandley12** [groovy/groovy-eclipse#910]
Prior versions of Eclipse and the Groovy-Eclipse plugin allowed us to run groovy classes containing a main method as a groovy script. The current Eclipse 2018-12 plugin for Groovy 2.4 does not allow this anymore. We have to remove the main method in order for it to be run as anything other than a Java application or in Groovy Console. Please let me know what further information you need to diagnose this issue.

**Comment by eric-milles** [comment]
This is by design.  A class with a main is not a script.  Run As > Groovy Script performs separate compilation from your project.  Run As > Java Application will execute your compiled class starting from the main method.

**Comment by dhandley12** [comment]
Thanks for the clarification, that is basically what I was expecting but I had to double check since the behaviour used to be supported.
