### ISSUE TITLE
Can't install Groovy Eclipse from marketplace in 2019-06, and update site doesn't work

### ISSUE THREAD

**Issue by davidmichaelkarr** [groovy/groovy-eclipse#922]
So I gave up on trying to fix the weird update errors I'm seeing for m2e, so I completely reinstalled 2019-06.  After it came up, I installed docker tooling, Spring IDE, Decompiler, moreunit, copied in the Emacs+ plugin jars, and then tried to install Groovy Eclipse from the marketplace.  This is asking me to install 3.5.0-SNAPSHOT. I unchecked groovy compiler 2.5 and checked the m2e integration. This says "Cannot complete operation".  It prompts me to uninstall Spring IDE and Spring XML namespace support in order to install Eclipse Groovy Development Tools and Groovy-Eclipse M2e Integration.  I didn't like those options, so I went to the groovy eclipse wiki and tried to install from the update site, being https://dist.springsource.org/release/GRECLIPSE/e4.12 . This fails, saying "Could not find https://dist...".  I then tried using the 4.11 url, and that lets me go further, but I aborted that, since I don't want the 4.11 release.

**Comment by pzygielo** [comment]
> so I went to the groovy eclipse wiki and tried to install from the update site, being https://dist.springsource.org/release/GRECLIPSE/e4.12 . This fails, saying "Could not find https://dist...". 

The link on home wiki page is different than on [3.4.0-Release-Notes](https://github.com/groovy/groovy-eclipse/wiki/3.4.0-Release-Notes). I had success with https://dist.springsource.org/release/GRECLIPSE/3.4.0/e4.12 (with additional `3.4.0` in path).

**Comment by eric-milles** [comment]
Unversioned release update sites will be fixed once necessary support team is back from holiday.  Versioned site links from release notes page should work properly.

Not sure why eclipse asked you to uninstall Spring IDE and Spring XML namespace support.  My recommendation would be to install Groovy-Eclipse as soon as you have JDT installed.  Then add other plug-ins once Groovy tooling is successful.

**Comment by davidmichaelkarr** [comment]
Installing this e4.12 release (with the correct url) allowed me to move forward.  I installed several plugins before I installed this one.

It seems odd to me that the Marketplace client search finds the snapshot release, and you have to go to extra steps to find the non-snapshot (stable?) release.
