### ISSUE TITLE
Suddenly got CoreException errors with "maven-compiler-plugin", related to groovy eclipse plugin?

### ISSUE THREAD

**Issue by davidmichaelkarr** [groovy/groovy-eclipse#928]
I work on several Java Maven project repos, along with several other developers.  Over time, I've run into problems like "Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin", but we've managed to get through those.  I haven't seen this for quite a while.

A developer called me over to her desk today, and she was getting that error.  I spent quite a while looking at her environment to see what might be different, and I couldn't find anything concrete.  I then saved off all the diagnostics I could think of and went back to my desk.  I did a pull on the same repo, and lo and behold, I'm now getting the same errors.

At one time, we've had the "lifecycle-mapping" plugin specified in our POM to try to resolve these issues.  I thought at one time I was told to remove that.  I may have done that at one point, but I noticed that one of our other developers added it back several months ago.

However, I noticed that the error message I was getting was complaining about "testCompile", but the goals list in the "lifecycle-mapping" plugin only specified the "compile" goal.  I tried adding the "test-compile" goal.  That got rid of the second instance of that error.

However, there are still two remaining errors, which are related to the others, but different from what I've seen before. I now have two of the following error, with a very slight difference, where this one refers to "default-compile", but the other refers to "default-testCompile".

CoreException: Could not get the value for parameter compilerId for plugin execution default-compile: PluginResolutionException: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.0 -> org.codehaus.groovy:groovy-eclipse-compiler:jar:RELEASE: ArtifactDescriptorException: Failed to read artifact descriptor for org.codehaus.groovy:groovy-eclipse-compiler:jar:RELEASE: VersionResolutionException: Failed to resolve version for org.codehaus.groovy:groovy-eclipse-compiler:jar:RELEASE: Could not find metadata org.codehaus.groovy:groovy-eclipse-compiler/maven-metadata.xml in local (C:\Users\dk068x\.m2\repository)

This is my current config for the lifecycle-mapping plugin:

```
	<plugin>
		<groupId>org.eclipse.m2e</groupId>
		<artifactId>lifecycle-mapping</artifactId>
		<version>1.0.0</version>
		<configuration>
			<lifecycleMappingMetadata>
				<pluginExecutions>
					<pluginExecution>
						<pluginExecutionFilter>
							<groupId>
								org.apache.maven.plugins
							</groupId>
							<artifactId>
								maven-compiler-plugin
							</artifactId>
							<versionRange>
								[3.6.1,)
							</versionRange>
							<goals>
								<goal>compile</goal>
								<goal>testCompile</goal>
							</goals>
						</pluginExecutionFilter>
						<action>
							<ignore></ignore>
						</action>
					</pluginExecution>
				</pluginExecutions>
			</lifecycleMappingMetadata>
		</configuration>
	</plugin>
```

**Comment by eric-milles** [comment]
Not sure what your POM(s) look(s) like.  You should not need to specify lifecycle mappings unless you are adding additional goals.  The standard goals "compile" and "testCompile" are mapped within the [metadata](https://github.com/groovy/groovy-eclipse/blob/master/extras/groovy-eclipse-compiler/src/main/resources/META-INF/plexus/components.xml) of the `groovy-eclipse-compiler` adapter.

The maven dependency `org.codehaus.groovy:groovy-eclipse-compiler:jar:RELEASE` will not be found, since the version "RELEASE" does not exist.  The most current version is "3.4.0-01".

**Comment by eric-milles** [comment]
Is this still an issue?  I have not had response to my suggestion in a week.
