### ISSUE TITLE
NPE happens in Java Builder with enabled annotation-based analysis and groovy

### ISSUE THREAD

**Issue by sergebg** [groovy/groovy-eclipse#931]
[error.txt](https://github.com/groovy/groovy-eclipse/files/3464309/error.txt)
NPE happens when Groovy plugin installed and annotation-based null analysis enabled.
Disabling of annotation-based null analysis everything fixes errors. (As well as Groovy plugin removal)

My project is java project with many modules. Main sources include only java. Groovy is used for testing. Tests are based on Spock framework. In these tests we have non-standard naming (from the java point of view), something like this:

def "run scenario and perform checks"() { ... }

Otherwise this project is standard maven-based project. Internal compiler error appearing in "Problems" never relates to groovy code. Usually I can see 2 or 3 errors relating java files. For the same set of modules I get the same errors.

Groovy plugin: Groovy Development Tools 3.5.0.SNAPSHOT (installed from marketplace)
The error was discovered long time ago, and can be reproduced with earlier versions of eclipse and groovy plugin.

**Comment by eric-milles** [comment]
Can you provide the stacktrace of the exception and possibly a small project that demonstrates the problem?  I can enable the feature without issue.

**Comment by eric-milles** [comment]
The one addition GDT makes to BinaryTypeBinding does show up in your stack trace:

```
java.lang.NullPointerException
               at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.getMethods(BinaryTypeBinding.java:1375)
               at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.findMethod(BinaryTypeBinding.java:1171)
               at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:493)
               at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1057)
               at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1038)
               at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:318)
               at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:256)
               at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:114)
               at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.annotateType(LookupEnvironment.java:1914)
               at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromSignature(LookupEnvironment.java:1897)
               at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:810)
               at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:1025) <---
               at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:555)
               at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1057)
               at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1038)
               at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:318)
```

```java
private IBinaryMethod[] createMethods(IBinaryMethod[] iMethods, IBinaryType binaryType, long sourceLevel, char[][][] missingTypeNames) {
	...
		boolean hasRestrictedAccess = hasRestrictedAccess();
		MethodBinding[] methods1 = new MethodBinding[total];
		if (total == initialTotal) {
			...
		} else {
			IBinaryMethod[] mappedBinaryMethods = new IBinaryMethod[total];
			for (int i = 0, index = 0; i < initialTotal; i++) {
				if (iClinit != i && (toSkip == null || toSkip[i] != -1)) {
					MethodBinding method = createMethod(iMethods[i], binaryType, sourceLevel, missingTypeNames);
					if (hasRestrictedAccess)
						method.modifiers |= ExtraCompilerModifiers.AccRestrictedAccess;
					mappedBinaryMethods[index] = iMethods[i];
					methods1[index++] = method;
				}
			}
			this.methods = methods1;
			// GROOVY add -- save the bridge methods; Groovy needs to see them
			if (this.environment.globalOptions.buildGroovyFiles == 2) {
				int skipped = (initialTotal - this.methods.length - (iClinit == -1 ? 0 : 1));
				if (skipped == 0) {
					this.infraMethods = Binding.NO_METHODS;
				} else {
					this.infraMethods = new MethodBinding[skipped];
					for (int i = 0, index = 0; i < initialTotal; i += 1) {
						if (iClinit != i && (toSkip != null && toSkip[i] == -1)) {
							MethodBinding method = createMethod(iMethods[i], binaryType, sourceLevel, missingTypeNames); // this is line 1025
							if (hasRestrictedAccess)
								method.modifiers |= ExtraCompilerModifiers.AccRestrictedAccess;
							this.infraMethods[index++] = method;
						}
					}
				}
			}
			// GROOVY end
```

What's going on here is that Groovy needs to see the bridge methods for covariant checks.  It uses the same call sequence that JDT does to create the method binding.  It's possible this needs to shift up a line si that `this.methods` is not initialized until after the bridge methods are created.

**Comment by sergebg** [comment]
I will try to provide an example. But the error happens on a big project with multiple modules. So that will take some time.

**Comment by eric-milles** [comment]
Does this still happen with the latest snapshot?

If you're looking for something specific, I think the error is happening for an inner class (possibly anonymous).

**Comment by sergebg** [comment]
Updated to 3.5.0.v201908052119-e1906
Still get NPE when enable null analysis

**Comment by sergebg** [comment]
Reproduced NPE using public project spotify/apollo
1. Forked it as https://github.com/sergebg/apollo
2. Imported the project into eclipse (branch 1.x)
3. Then I  added groovy support using gmaveplus plugin. 
(commit 1fd1b43cc85c8bea520ae53342a93b8267cd44df)
4. As result groovy nature was added to projects and...
5. As result I got NPE.

**Comment by eric-milles** [comment]
Does the NPE occur when you open a specific file or just build the project?

The projects built to completion for me:
![image](https://user-images.githubusercontent.com/18193802/62791418-bbc8c780-ba92-11e9-87ce-2fbf828f3324.png)

**Comment by sergebg** [comment]
I just repeated the all steps and reproduced errors. 
1. I have disabled analysis and rebuild the project. Today I have found 1 compilation error specific to eclipse compiler. 
<img width="1523" alt="Screenshot 2019-08-09 at 19 33 02" src="https://user-images.githubusercontent.com/850357/62794800-b0e75480-badd-11e9-8bfd-3c67698cc56f.png">
2. Then I open settings and enable analysis.
<img width="1479" alt="Screenshot 2019-08-09 at 19 34 18" src="https://user-images.githubusercontent.com/850357/62794825-c3618e00-badd-11e9-82b9-5d6972dcc8cd.png">
3. Eclipse suggested full rebuild and instantly after clicking "OK" I got errors
<img width="1479" alt="Screenshot 2019-08-09 at 19 34 33" src="https://user-images.githubusercontent.com/850357/62794893-fc99fe00-badd-11e9-95f3-1bdd3fa3f5bb.png">

**Comment by eric-milles** [comment]
The error can be fixed by replacing `Response::forPayload` with `Response::<R>forPayload`.

I'm not getting the NPE.  Are you running eclipse or building your project with Java 9+?  I'm just trying to find something different about our setups.

**Comment by sergebg** [comment]
I have tried Oracle JDK 1.8.0_171 and 1.8.0_201.  The error happens after any full rebuild. 
By the way, if you use the same settings in null analysis ("Error" for null access and potential null access), then you should get 5 compilation errors. On your screenshot I can't see such errors. So, I believe you have different config.

```
Description	Resource	Path	Location	Type
Null type mismatch: required '@Nonnull ResponseWithDelay' but the provided value is specified as @Nullable	StubClient.java	/apollo-test/src/main/java/com/spotify/apollo/test	line 277	Java Problem
Null type mismatch: required '@Nonnull T' but the provided value is null	PerformanceFixture.java	/apollo-test/src/main/java/com/spotify/apollo/test/experimental	line 88	Java Problem
Null type mismatch: required '@Nonnull Void' but the provided value is null	AsyncRequester.java	/apollo-test/src/main/java/com/spotify/apollo/test/experimental	line 118	Java Problem
Potential null pointer access: The field config is specified as @Nullable	DefaultMetaGatherer.java	/apollo-api-impl/src/main/java/com/spotify/apollo/meta/model	line 101	Java Problem
Potential null pointer access: The field responseWithDelay is specified as @Nullable	StubClient.java	/apollo-test/src/main/java/com/spotify/apollo/test	line 251	Java Problem

```

**Comment by eric-milles** [comment]
I need to know your annotation settings.  I must be missing some of the annotations here:
![image](https://user-images.githubusercontent.com/18193802/62823418-255dda00-bb56-11e9-8a60-01be31da3032.png)

**Comment by sergebg** [comment]
I am using javax.annotation.*:
javax.annotation.Nullable
javax.annotation.Nonnull
javax.annotation.ParametersAreNonnullByDefault

**Comment by eric-milles** [comment]
Can you try again with the latest snapshot?

**Comment by sergebg** [comment]
Now it works fine. Thanks
