### ISSUE TITLE
Compiling script with '(' syntax error makes Eclipse unresponsive

### ISSUE THREAD

**Issue by Cyberdog52** [groovy/groovy-eclipse#932]
**Problem description:**
We found that the compiler takes an unreasonable amount of time to compile a groovy script with a simple syntax error in Eclipse. If you add an opening bracket '(' that is never closed, the compile time will roughly double for each instruction that follows. After 27 instructions the compiler took 3 minutes on our computers. During compile time Eclipse is not responsive.

**Analysis:**
We noticed that the compiler spends an unreasonable amount of time in `org.codehaus.groovy.control.CompilationUnit.compile` using JProfiler.

When we compiled the script with syntax error with groovyc it finished compiling immediately. So we can conclude that it is not an issue with the standard groovy compiler.

We did not test any other syntax errors and their compile time.

**How to reproduce:**
Open Eclipse, create a new groovy project and add an empty groovy script. Copy-paste the code below and save the script. Insert an opening bracket '(' at the beginning of the second line (remove the closing ')' when it automatically pops up) and then try to use Eclipse by clicking somwhere. 
We included the time it took until Eclipse was responsive again as comments. We uncommented some of the lines below to calculate the compile time. After Eclipse is responsive again it will show that there is a missing bracket on the last line of code. 

<pre><code>int a = 0
// insert an opening bracket '(' here instead of this comment and try to select anything below
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0
a = 0 // 20: start noticing delay
a = 0
a = 0 // 22: 3s
a = 0 // 23: 5s
a = 0 // 24: 11s
a = 0 // 25: 22s
a = 0 // 26: 82s
a = 0 // 27: 240s
</code></pre> 

**We experienced the issue with the following settings:**
Eclipse 4.7.3
Groovy: 2.4.13, 2.5.7, 3.0.0-beta-2
Greclipse: 3.2.0, 3.3.0, 3.4.0
Windows 10
32GB RAM
Intel i7-7700 3.6GHz

**Unresponsive Eclipse during compilation:**
<img width="1018" alt="freeze" src="https://user-images.githubusercontent.com/12275319/62458978-8c5a4800-b77e-11e9-99f5-146078e1dea4.png">

**JProfiler call tree when trying to comile the script:**
<img width="732" alt="call%20tree" src="https://user-images.githubusercontent.com/12275319/62458972-88c6c100-b77e-11e9-8256-2276226ebdfc.png">

**Comment by eric-milles** [comment]
Thanks for the extra details.  I was able to reproduce it yesterday and did some initial probing.  I was also able to recreate within Groovy itself and submitted a bug: https://issues.apache.org/jira/browse/GROOVY-9213

**Comment by Cyberdog52** [comment]
Many thanks for further analyzing the problem and submitting it directly to the Groovy issue page.
