### ISSUE TITLE
Outline View not updated after field removal from the Outline View itself

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#943]
Consider this class:

```groovy
package test54

import javax.annotation.Resource

class Test54 {
	String foo
	
	String bar
	
	@Resource
	String foobar
}
```

From the Outline View, select `bar`, press Del key and confirm deletion: the `bar` property gets deleted, but the Outline View is not updated and still shows it.

Please note that in other "real-world" scenarios I get a slightly different behaviour: the view *is* somewhat updated, but it still shows the deleted field with a question mark (instead of the standard property icon) on its left. Please see the following example, where I deleted the `token` field from the Outline View:

![immagine](https://user-images.githubusercontent.com/1742494/63501167-7d3bff80-c4cb-11e9-87e0-b6f3002d5f38.png)

**Comment by eric-milles** [comment]
The editor action ConvertToMethodAction is running between the field removal and the reconcile that builds the delta used to update the outline view.  It is running its own reconcile to determine of the current editor selection is an applicable element.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
If I delete `foo` or `bar` it works correctly now with 3.5.0.v201908222034-e1906.
If I try to delete `foobar` bad things still happen, see #944.

**Comment by mauromol** [comment]
It works fine also in my main project when deleting `AuthenticationToken.token`.
