### ISSUE TITLE
Missing code assist in static method calling another static method

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#946]
Consider this:

```groovy
package test56

class Test56 {
	static Date foo(String foo) {
		new Date()
	}
	
	static Date bar(String bar) {
		foo(bar).|
	}
}
```

Invoke code assist at "|", or otherwise add "cl" and then invoke code assist: no suggestion is given at all.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
Works fine in 3.5.0.v201908251828-e1906, thank you! 👍

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/65536539-3d50a980-dec9-11e9-89dd-4e57f40ab68f.png)
