### ISSUE TITLE
Wrong type inference in map[key] result

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#948]
Consider this:

```groovy
package test58

import groovy.transform.CompileStatic;

@CompileStatic
public class Test58 {

	Map<String, String> m = [
		foo: 'foo' 
		]
		
	void blah() {
		Object c = boh()
		def a = m.get(c)
		uhuh(a)
		def b = m[c]
		uhuh(b)
	}
	
	void uhuh(String a) {
	}
	
	Object boh() {
		'foo'
	}
}
```

The first call to `uhuh(String)` succeeds, the second one gives a compilation error: 
"Groovy:[Static type checking] - Cannot find matching method test58.Test58#uhuh(java.lang.Object). Please check if the declared type is correct and if the method exists."
This is because `b` is resolved as `Object`. But shouldn't both map accesses be equivalent? Since `m` is a `Map<String, String>`, `m[anything]` should be a `String`, even if `anything` is not explicitly a `String`... Or, if the type checker wants to be very strict, the compilation error should be in `b = m[c]` call, not in `uhuh(b)`.

Perhaps a Groovy bug? Using Groovy 2.5 compiler in Greclipse.

**Comment by mauromol** [comment]
Could be... I subscribed to it, thanks for pointing it out.

**Comment by eric-milles** [comment]
This actually comes down to the difference between two declared methods.
```groovy
def map = (Map<String,String>) [:]
def obj = (Object) 'string'
def a = map.get(obj) // V get(Object key) from Map
def b = map[obj] // static <K,V> V getAt(Map<K,V> self, K key) from DefaultGroovyMethods
```

**Comment by mauromol** [comment]
Hi Eric,
I see you closed this, but I don't understand if this problem is indeed confirmed to be due to GROOVY-9097.
Thanks.

**Comment by eric-milles** [comment]
Sorry, thought I explained in the example.  The case of `map.get(key)` and the case of `map[key]` result in two different method calls that have slightly different signatures.  The behavior of static type checking is consistent with the method signatures.

GROOVY-9097 is just a bit different.  It involves direct call to `map.getAt(key)` vs. `map[key]`.

**Comment by mauromol** [comment]
Still, I don't understand. Those methods have different signatures, but the return type is `V` for both, which in my case is `String`. So in the above example both `a` and `b` should be evaluated as `String`s, I would say...

**Comment by eric-milles** [comment]
Let me take a fresh look at it.  I think I got hung up on the key type and the difference between the two styles.

**Comment by eric-milles** [comment]
So, because the key type is Object, "m[c]" does not match the method `getAt(Map<K,V>, K)`.  So it falls back on the general handling for the left-square-bracket operator.  The "[Static Type Checking]" errors come from the groovy compiler.  Any issue with them will require a JIRA ticket against Groovy to resolve.

Sorry for the confusing attempts to explain this.  There are definitely some tricky things in how Groovy actually handles both the type of the map at declaration time and the differences between get, getAt and [].

**Comment by mauromol** [comment]
I opened: https://issues.apache.org/jira/browse/GROOVY-9420
I think there are some relationships with: https://issues.apache.org/jira/browse/GROOVY-9097
