### ISSUE TITLE
How to hang (GR)Eclipse 

### ISSUE THREAD

**Issue by ivoshm** [groovy/groovy-eclipse#952]
## Steps to reproduce:
1. create new Groovy project with default parameters;
1. create in src folder new source file (e.g. a.groovy);
1. write simple script (e.g. ``println 'Hello world'``);
1. save it;
1. put into script as first character symbol '@';
1. now one CPU core jumps to 100% and whole Eclipse is totally slow (response in minutes)
No information found in error log or in console. Memory usage isn't growing.

## SW versions:
- Eclipse 2019-06 (updated)
- Groovy-Eclipse 3.4.0 from https://dist.springsource.org/release/GRECLIPSE/e4.12
- Groovy Compiler 2.4.17 or 2.5.7 (no matter)
- platform Linux64

Thanks for investigating and solving this! I tried to play with ``@Grab`` and even single ``@`` made problem :).

**Comment by eric-milles** [comment]
Can you try with the latest snapshot builds (https://dist.springsource.org/snapshot/GRECLIPSE/e4.12)?  I am not able to recreate for your example.

If you want to try `@Grab`, you will need an import or package statement to annotate.
