### ISSUE TITLE
Make it more obvious that Groovy 2.5 is optional

### ISSUE THREAD

**Issue by digulla** [groovy/groovy-eclipse#958]
When installing the Groovy plugin from the Marketplace, the only available compiler is Groovy 2.5. There is little indication in the UI that the plugin comes with 2.4 and that 2.5 is purely optional which can lead to the InvalidRegistryObjectException issue described in #317 

Please add " (optional; without this, you get 2.4)" or similar to the entry for 2.5 or add 2.4 as a mandatory dependency visible in the Marketplace client.

**Comment by digulla** [comment]
Here is how it looks in the Marketplace Client:

![image](https://user-images.githubusercontent.com/159306/65319335-a968a000-db9f-11e9-9b50-41d1d1c8d366.png)

As you can see, 2.4 and 3.0 are not mentioned at all. This is very confusing.

How about setting the install state for 2.5 to "Optional" (not selected)?

**Comment by eric-milles** [comment]
In your screenshot "Eclipse Groovy Development Tools" is marked "required".  I make Groovy 2.5 optional, but selected because it is the current Groovy release.

**Comment by digulla** [comment]
How about making 2.4 visible and optional + deselected in this screen? That way, it wouldn't like you get nothing if you deselect 2.5 plus you can select 2.4 without 2.5 and avoid the InvalidRegistryObjectException issue when setting up a new workspace.
