### ISSUE TITLE
@CompileStatic  does not work with Date.plus()  

### ISSUE THREAD

**Issue by DariusX** [groovy/groovy-eclipse#965]
This code worked with 
* groovy-eclipse-batch:`2.4.3-01` and groovy-eclipse-compiler:`2.9.2-01` 
But, failed with:
* groovy-eclipse-batch:`2.5.7-01` and groovy-eclipse-compiler: `3.3.0-01`:
```
@CompileStatic
class DateTest {
    @Test
    void dateTest() {
        Date theDate = new Date()
        theDate.plus(5)
    }
}
```

Compiling with `3.3.0-01`, it gives and error:
```
[ERROR] 	theDate.plus(5)
[ERROR] 	^^^^^^^^^^^^^^^
[ERROR] Groovy:[Static type checking] - Cannot find matching method java.util.Date#plus(int). Please check if the declared type is correct and if the method exists.
```

If I remove the `@CompileStatic`, it compiles with the newer version.

**Comment by eric-milles** [comment]
What version of `groovy-eclipse-batch` are you using?  The compiler adapter (aka `groovy-eclipse-compiler`) is merely a bridge between Maven and Eclipse interfaces.  It translates the maven config to command-line arguments.

**Comment by DariusX** [comment]
groovy-eclipse-batch:`2.5.7-01` ... is giving the error, but

`2.4.3-01` worked

**Comment by eric-milles** [comment]
In Groovy 2.5, the date extension methods were moved to a separate module (`groovy-dateutil`) that is not included as part of the `groovy-all` POM.

**Comment by DariusX** [comment]
Do we have to be on Groovy 2.5 to use this version of the compiler? 
Our dependency is `groovy-all:2.4.15`

**Comment by eric-milles** [comment]
It is best to keep the batch compile aligned.  So if you use Groovy 2.4.15, then groovy-eclipse-batch:2.4.17-01 is the most current.

**Comment by DariusX** [comment]
Thank you.
And, given that the other is an adapter... could we use:

- groovy-eclipse-batch: `2.4.17-01`, and
- groovy-eclipse-compiler: `3.3.0-01`

**Comment by eric-milles** [comment]
I would recommend using the most recent adapter for best Maven compat.  `groovy-eclipse-compiler:3.5.0-01` is the most recent.

**Comment by eric-milles** [comment]
There are more details on the Maven components (including latest version badges) here: https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin
