### ISSUE TITLE
Expressions/Display view cannot evaluate groovy code

### ISSUE THREAD

**Issue by mojo2012** [groovy/groovy-eclipse#982]
Hi guys,

I've been playing around with Groovy the last view days and I have trouble to properly debug my own code :-D.

## My setup is:
* Eclipse 2019-09 R (4.13.0)
*  Plugins:
** Groovy Compiler 2.5	3.5.0.v201909291620-e1909-RELEASE
** Groovy Compiler 3.0 (early access)	3.5.0.v201909291620-e1909-RELEASE	
** Groovy Editor for Polyglot Maven .   	0.1.0.201611011520	
** Groovy-Eclipse M2E integration	        3.5.0.v201909291620-e1909-RELEASE	

As you can see on the following screenshot that evaluating groovy code both in the expressions view and the debug/display view doesn't work:
<img width="995" alt="debugging_problem" src="https://user-images.githubusercontent.com/1330361/68067531-60803b80-fd48-11e9-8e8b-a0ab95d93609.png">

Code that is valid java code can be evaluated though!

The project can be checked out at: https://github.com/mojo2012/groovytest
For it to work you also have to build https://github.com/mojo2012/groovier

**Comment by eric-milles** [comment]
Sorry, I interpreted your comment "[IntelliJ] properly supports groovy debugging" to mean you were having trouble with breakpoints or stepping.  This issue is already recorded in #569
