### ISSUE TITLE
Groovy 3/Java 11 syntax not supported correctly

### ISSUE THREAD

**Issue by mojo2012** [groovy/groovy-eclipse#983]
Groovy 3 syntax, like the java 11 method reference using the `::`, doesn't work correctly.
![method_reference](https://user-images.githubusercontent.com/1330361/68070961-5d4f7480-fd75-11e9-9fa9-ece126700393.png)

Also lambdas don't work:
![lambdas](https://user-images.githubusercontent.com/1330361/68070949-401aa600-fd75-11e9-925f-de2354454931.png)

Im using the `groovy-eclipse 3.6.0` with `adoptopenjdk 13` and `groovy 3.0.0-rc-1`.

Check out the sample project: https://github.com/mojo2012/groovytest

**Comment by eric-milles** [comment]
https://github.com/groovy/groovy-eclipse/wiki/3.5.0-Release-Notes#support-for-new-versions-of-groovy

> The new Parrot Parser is disabled by default in Groovy 3. To enable it, add -Dgroovy.antlr4=true to your _eclipse.ini_ file after the `-vmargs` line or add a compiler config script to your project with `configuration.pluginFactory = org.codehaus.groovy.control.ParserPluginFactory.antlr4(configuration)`. Please note that parser recovery is not implemented for the Parrot Parser, so your editing experience may be sub-par in this mode.

**Comment by mojo2012** [comment]
Is there a plan to support "parser recovery" to make the parrot parser fully supported?

**Comment by eric-milles** [comment]
I had been waiting for Groovy 3 to make RC1.  That was finally released on October 25th.  Work on antlr4 parser recovery will begin shortly.
